-- create_assignment_selection_schema
-- App: @iefa/assignment-selection — painel de escolha de vagas (CPAINT).
-- Domínio: seleção de vaga/lotação (billet) por ordem de classificação (OML),
-- com suporte a múltiplas edições (anos). Dados da edição 2025 preservados do
-- projeto Supabase legado (db_cluster dump 2025-08-01).

create schema if not exists assignment_selection;
grant usage on schema assignment_selection to anon, authenticated, service_role;

-- ---- Tabelas ----

-- Edição = uma rodada de escolha (ex.: "2025", "2025/2026"). Apenas uma ativa por vez.
create table assignment_selection.edition (
	id uuid primary key default gen_random_uuid(),
	name text not null unique,
	active boolean not null default false,
	created_at timestamptz not null default now()
);

-- Militar concorrente, ordenado por `classificacao` (OML). `localidade` guarda a OM
-- escolhida; `hide_card = true` marca escolha confirmada (some do painel).
create table assignment_selection.person (
	id bigint generated by default as identity primary key,
	edition_id uuid not null references assignment_selection.edition (id) on delete cascade,
	classificacao bigint not null,
	nome text not null,
	localidade text,
	estado text,
	show_card boolean not null default false,
	show_om boolean not null default false,
	hide_card boolean not null default false,
	created_at timestamptz not null default now()
);
create index person_edition_idx on assignment_selection.person (edition_id);
create index person_edition_classificacao_idx on assignment_selection.person (edition_id, classificacao);

-- Vaga disponível por OM em uma edição.
create table assignment_selection.vacancy (
	id bigint generated by default as identity primary key,
	edition_id uuid not null references assignment_selection.edition (id) on delete cascade,
	om text,
	estado text,
	total_vagas integer,
	created_at timestamptz not null default now()
);
create index vacancy_edition_idx on assignment_selection.vacancy (edition_id);

-- ---- View: status das vagas (vagas x escolhas confirmadas) ----
-- `chosen` = nº de militares que confirmaram (hide_card) aquela OM naquela edição.
-- Espelha a view legada public.vagas_status, agora particionada por edição.
create view assignment_selection.vacancy_status
with (security_invoker = true) as
select
	v.edition_id,
	v.om,
	v.estado,
	v.total_vagas,
	coalesce(count(p.id), 0)::bigint as chosen
from assignment_selection.vacancy v
left join assignment_selection.person p
	on p.edition_id = v.edition_id
	and p.localidade = v.om
	and p.hide_card = true
group by v.edition_id, v.om, v.estado, v.total_vagas;

-- ---- RLS: leitura pública, escrita só service_role (server functions) ----
alter table assignment_selection.edition enable row level security;
alter table assignment_selection.person enable row level security;
alter table assignment_selection.vacancy enable row level security;

create policy "public read edition" on assignment_selection.edition for select to anon, authenticated using (true);
create policy "public read person"  on assignment_selection.person  for select to anon, authenticated using (true);
create policy "public read vacancy" on assignment_selection.vacancy for select to anon, authenticated using (true);

-- ---- Grants (gate a nível de tabela; RLS é o gate a nível de linha) ----
grant select on all tables in schema assignment_selection to anon, authenticated;
grant all    on all tables in schema assignment_selection to service_role;
alter default privileges in schema assignment_selection grant select on tables to anon, authenticated;
alter default privileges in schema assignment_selection grant all    on tables to service_role;

-- ---- Realtime: painel escuta mudanças em person/vacancy ----
-- REPLICA IDENTITY FULL para o payload de DELETE trazer a linha antiga (usada no board).
alter table assignment_selection.person  replica identity full;
alter table assignment_selection.vacancy replica identity full;
alter publication supabase_realtime add table assignment_selection.person;
alter publication supabase_realtime add table assignment_selection.vacancy;

-- ---- Seed: edição 2025 (preservada do legado) ----
insert into assignment_selection.edition (name, active) values ('2025', true);

insert into assignment_selection.vacancy (id, edition_id, om, total_vagas, estado, created_at)
select v.id, (select id from assignment_selection.edition where name = '2025'), v.om, v.total_vagas, v.estado, v.created_at::timestamptz
from (values
		(1, 'GAP AF', 3, 'Rio de Janeiro', '2025-07-22 00:05:12.016423+00'),
		(2, 'GAP BE', 3, 'Pará', '2025-07-22 00:05:12.016423+00'),
		(3, 'GAP BR', 3, 'Distrito Federal', '2025-07-22 00:05:12.016423+00'),
		(4, 'GAP DF', 3, 'Distrito Federal', '2025-07-22 00:05:12.016423+00'),
		(5, 'GAP GL', 2, 'Rio de Janeiro', '2025-07-22 00:05:12.016423+00'),
		(6, 'GAP LS', 2, 'Minas Gerais', '2025-07-22 00:05:12.016423+00'),
		(7, 'GAP MN', 4, 'Amazonas', '2025-07-22 00:05:12.016423+00'),
		(8, 'GAP RJ', 1, 'Rio de Janeiro', '2025-07-22 00:05:12.016423+00'),
		(9, 'GAP SP', 4, 'São Paulo', '2025-07-22 00:05:12.016423+00'),
		(10, 'PAGL', 1, 'Rio de Janeiro', '2025-07-22 00:05:12.016423+00'),
		(11, 'BAPV', 2, 'Rio Grande do Sul', '2025-07-22 00:05:12.016423+00'),
		(12, 'BABV', 2, 'Roraima', '2025-07-22 00:05:12.016423+00'),
		(13, 'BAAN', 2, 'Goiás', '2025-07-22 00:05:12.016423+00'),
		(14, 'BANT', 1, 'Rio Grande do Norte', '2025-07-22 00:05:12.016423+00'),
		(15, 'BACG', 2, 'Mato Grosso do Sul', '2025-07-22 00:05:12.016423+00'),
		(16, 'BASC', 2, 'Rio de Janeiro', '2025-07-22 00:05:12.016423+00'),
		(17, 'BASM', 1, 'Rio Grande do Sul', '2025-07-22 00:05:12.016423+00'),
		(18, 'BAFL', 1, 'Santa Catarina', '2025-07-22 00:05:12.016423+00')
) as v(id, om, total_vagas, estado, created_at);

insert into assignment_selection.person (id, edition_id, classificacao, nome, localidade, estado, show_card, show_om, hide_card, created_at)
select p.id, (select id from assignment_selection.edition where name = '2025'), p.classificacao, p.nome, p.localidade, p.estado, p.show_card, p.show_om, p.hide_card, p.created_at::timestamptz
from (values
		(36, 35, 'Fabian', 'BAPV', 'Rondônia', true, true, true, '2025-07-21 23:07:06.725417+00'),
		(17, 16, 'Pâmella', 'PAGL', 'Rio de Janeiro', true, true, true, '2025-07-21 22:51:25.654234+00'),
		(37, 36, 'Camberlin', 'GAP BE', 'Pará', true, true, true, '2025-07-21 23:07:28.846505+00'),
		(18, 17, 'Macedo', 'GAP SP', 'São Paulo', true, true, true, '2025-07-21 22:52:30.105301+00'),
		(19, 18, 'Peterson', 'GAP RJ', 'Rio de Janeiro', true, true, true, '2025-07-21 22:52:47.352608+00'),
		(38, 37, 'Bruno', 'GAP MN', 'Amazonas', true, true, true, '2025-07-21 23:09:09.136901+00'),
		(20, 19, 'Pedro Soares', 'GAP MN', 'Amazonas', true, true, true, '2025-07-21 22:53:03.214756+00'),
		(39, 38, 'Alencar', 'BABV', 'Roraima', true, true, true, '2025-07-21 23:09:30.871045+00'),
		(21, 20, 'Armando', 'BAPV', 'Rondônia', true, true, true, '2025-07-21 22:54:15.758423+00'),
		(7, 6, 'Spinelli', 'GAP BR', 'Distrito Federal', true, true, false, '2025-07-21 22:46:38.990106+00'),
		(22, 21, 'Lincoln', 'BASC', 'Rio de Janeiro', true, true, true, '2025-07-21 22:54:43.987045+00'),
		(40, 39, 'Patrick', 'BABV', 'Roraima', true, true, true, '2025-07-21 23:10:16.81484+00'),
		(2, 2, 'Maciel', 'GAP BR', 'Distrito Federal', true, true, true, '2025-07-21 13:45:26.641196+00'),
		(23, 22, 'Loureiro', 'GAP DF', 'Distrito Federal', true, true, true, '2025-07-21 22:56:20.158825+00'),
		(3, 3, 'João', 'BAFL', 'Santa Catarina', true, true, true, '2025-07-21 13:45:26.641196+00'),
		(24, 23, 'Marques', 'GAP SP', 'São Paulo', true, true, true, '2025-07-21 22:57:53.664306+00'),
		(1, 1, 'Sabrina', 'BANT', 'Rio Grande do Norte', true, true, true, '2025-07-21 13:45:26.641196+00'),
		(25, 24, 'Roveda', 'BASM', 'Rio Grande do Sul', true, true, true, '2025-07-21 23:02:12.071242+00'),
		(5, 4, 'Victória Lima', 'GAP BE', 'Pará', true, true, true, '2025-07-21 22:46:00.905989+00'),
		(26, 25, 'Linhares', 'GAP DF', 'Distrito Federal', true, true, true, '2025-07-21 23:02:27.554731+00'),
		(27, 26, 'Maria Lima', 'BASC', 'Rio de Janeiro', true, true, true, '2025-07-21 23:02:46.108482+00'),
		(28, 27, 'Freitas', 'GAP MN', 'Amazonas', true, true, true, '2025-07-21 23:03:14.158617+00'),
		(29, 28, 'Tainá', 'GAP SP', 'São Paulo', true, true, true, '2025-07-21 23:03:32.92187+00'),
		(6, 5, 'Joyce Gama', 'GAP AF', 'Rio de Janeiro', true, true, true, '2025-07-21 22:46:19.116513+00'),
		(30, 29, 'Luana', 'GAP BE', 'Pará', true, true, true, '2025-07-21 23:04:13.430841+00'),
		(8, 7, 'Peres', 'GAP GL', 'Rio de Janeiro', true, true, true, '2025-07-21 22:47:03.603996+00'),
		(31, 30, 'Lopo', 'GAP SP', 'São Paulo', true, true, true, '2025-07-21 23:04:36.4123+00'),
		(9, 8, 'Nanni', 'GAP AF', 'Rio de Janeiro', true, true, true, '2025-07-21 22:47:18.397498+00'),
		(32, 31, 'Ana Luiza', 'BAAN', 'Goiás', true, true, true, '2025-07-21 23:05:08.19755+00'),
		(10, 9, 'Vitória', 'GAP AF', 'Rio de Janeiro', true, true, true, '2025-07-21 22:47:38.457125+00'),
		(11, 10, 'Marcos', 'BAAN', 'Goiás', true, true, true, '2025-07-21 22:48:38.724551+00'),
		(12, 11, 'Wandermurem', 'GAP GL', 'Rio de Janeiro', true, true, true, '2025-07-21 22:49:04.121276+00'),
		(33, 32, 'Victoria Araujo', 'BACG', 'Mato Grosso do Sul', true, true, true, '2025-07-21 23:05:51.536462+00'),
		(13, 12, 'Samira', 'GAP DF', 'Distrito Federal', true, true, true, '2025-07-21 22:49:19.088849+00'),
		(34, 33, 'Adriel', 'BACG', 'Mato Grosso do Sul', true, true, true, '2025-07-21 23:06:14.078925+00'),
		(14, 13, 'Jessica Lima', 'GAP BR', 'Distrito Federal', true, true, true, '2025-07-21 22:49:41.15936+00'),
		(15, 14, 'Torres', 'GAP LS', 'Minas Gerais', true, true, true, '2025-07-21 22:50:14.07414+00'),
		(35, 34, 'Thiago', 'GAP MN', 'Amazonas', true, true, true, '2025-07-21 23:06:39.226226+00'),
		(16, 15, 'Gabriel Azevedo', 'GAP LS', 'Minas Gerais', true, true, true, '2025-07-21 22:50:35.838767+00')
) as p(id, classificacao, nome, localidade, estado, show_card, show_om, hide_card, created_at);

-- Reset das sequences de identity após inserts com id explícito.
select setval(pg_get_serial_sequence('assignment_selection.person',  'id'), (select max(id) from assignment_selection.person));
select setval(pg_get_serial_sequence('assignment_selection.vacancy', 'id'), (select max(id) from assignment_selection.vacancy));

-- ---- Expor schema no PostgREST (append à lista existente) ----
alter role authenticator set pgrst.db_schemas to 'public, graphql_public, sisub, iefa, journal, forms, rumaer, core, access_control, kitchen, procurement, finance, compras_gov_integration, inventory, siafi_integration, gs1_integration, nutrition_reference, assignment_selection';
notify pgrst, 'reload config';
notify pgrst, 'reload schema';
