-- Importa catálogo oficial de peças (FAB) — fonte: docs/Situação das Especificações abril 2026.csv
-- Escopo: peças vestíveis ativas (V, AG, CAL, AE, IID, PED, REP, H).
-- Excluídos: MP (tecidos), COR (cores) e itens descontinuados/não-aprovados/EPI/migrados.
-- 269 peças. Upsert por slug → enriquece seed existente com código FAB + tipo.

alter table rumaer.piece add column if not exists codigo text;
comment on column rumaer.piece.codigo is 'Código de especificação oficial FAB (FAB-<seção>-NNN). Não-único: variantes de cor/gênero compartilham código.';
create index if not exists piece_codigo_idx on rumaer.piece (codigo);

insert into rumaer.piece (codigo, nome, slug, tipo) values
  ('FAB-AE-001', 'Botão prateado polido', 'botao-prateado-polido', 'acessorio'),
  ('FAB-AE-003', 'touca preta para frio', 'touca-preta-para-frio', 'cabeca'),
  ('FAB-AE-006', 'bolsa feminina preta', 'bolsa-feminina-preta', 'acessorio'),
  ('FAB-AE-007', 'braçadeira branca ou preta da Polícia da Aeronáutica', 'bracadeira-branca-ou-preta-da-policia-da-aeronautica', 'acessorio'),
  ('FAB-AE-008', 'braçadeira branca ou preto de serviço', 'bracadeira-branca-ou-preto-de-servico', 'acessorio'),
  ('FAB-AE-009', 'cachecol branco', 'cachecol-branco', 'acessorio'),
  ('FAB-AE-010', 'cachecol branco para desfile', 'cachecol-branco-para-desfile', 'acessorio'),
  ('FAB-AE-013', 'capacete azul-aeronáutica', 'capacete-azul-aeronautica', 'cabeca'),
  ('FAB-AE-014', 'capacete branco para motociclista', 'capacete-branco-para-motociclista', 'cabeca'),
  ('FAB-AE-016', 'carteira feminina preta', 'carteira-feminina-preta', 'acessorio'),
  ('FAB-AE-017', 'cinturão branco', 'cinturao-branco', 'acessorio'),
  ('FAB-AE-018', 'cinturão preto', 'cinturao-preto', 'acessorio'),
  ('FAB-AE-019', 'cinturão verde-oliva', 'cinturao-verde-oliva', 'acessorio'),
  ('FAB-AE-020', 'cinturão vermelho', 'cinturao-vermelho', 'acessorio'),
  ('FAB-AE-021', 'colete especial para atividades de foto e filmagem azul-aeronáutica', 'colete-especial-para-atividades-de-foto-e-filmagem-azul-aeronautica', 'torso'),
  ('FAB-AE-021', 'colete especial para atividades de foto e filmagem camuflado', 'colete-especial-para-atividades-de-foto-e-filmagem-camuflado', 'torso'),
  ('FAB-AE-023', 'cordão branco', 'cordao-branco', 'acessorio'),
  ('FAB-AE-023', 'cordão verde', 'cordao-verde', 'acessorio'),
  ('FAB-AE-023', 'cordão vermelho', 'cordao-vermelho', 'acessorio'),
  ('FAB-AE-024', 'fiador para espada', 'fiador-para-espada', 'acessorio'),
  ('FAB-AE-025', 'gorro com pala camuflado com proteção auricular', 'gorro-com-pala-camuflado-com-protecao-auricular', 'cabeca'),
  ('FAB-AE-026', 'guia azul-aeronáutica de seda para espada', 'guia-azul-aeronautica-de-seda-para-espada', 'acessorio'),
  ('FAB-AE-027', 'guia azul-aeronáutica para espadim', 'guia-azul-aeronautica-para-espadim', 'acessorio'),
  ('FAB-AE-028', 'guia branca de couro para espada', 'guia-branca-de-couro-para-espada', 'acessorio'),
  ('FAB-AE-029', 'luva branca de algodão', 'luva-branca-de-algodao', 'acessorio'),
  ('FAB-AE-030', 'luva de couro branca com palma preta e cano longo', 'luva-de-couro-branca-com-palma-preta-e-cano-longo', 'acessorio'),
  ('FAB-AE-031', 'luva preta de couro', 'luva-preta-de-couro', 'acessorio'),
  ('FAB-AE-032', 'luva de couro preta com faixa refletiva para motociclismo', 'luva-de-couro-preta-com-faixa-refletiva-para-motociclismo', 'acessorio'),
  ('FAB-AE-033', 'luva de lã preta', 'luva-de-la-preta', 'acessorio'),
  ('FAB-AE-036', 'porta-algemas branco', 'porta-algemas-branco', 'acessorio'),
  ('FAB-AE-037', 'porta-algemas verde-oliva', 'porta-algemas-verde-oliva', 'acessorio'),
  ('FAB-AE-038', 'porta-cantil verde-oliva', 'porta-cantil-verde-oliva', 'acessorio'),
  ('FAB-AE-039', 'porta-carregador verde-oliva', 'porta-carregador-verde-oliva', 'acessorio'),
  ('FAB-AE-040', 'porta-cassetete branco', 'porta-cassetete-branco', 'acessorio'),
  ('FAB-AE-041', 'porta-cassetete verde-oliva', 'porta-cassetete-verde-oliva', 'acessorio'),
  ('FAB-AE-042', 'porta-pistola branco', 'porta-pistola-branco', 'acessorio'),
  ('FAB-AE-043', 'porta-pistola de peitoral preto', 'porta-pistola-de-peitoral-preto', 'acessorio'),
  ('FAB-AE-044', 'porta-pistola preto', 'porta-pistola-preto', 'acessorio'),
  ('FAB-AE-044', 'porta-pistola verde-oliva', 'porta-pistola-verde-oliva', 'acessorio'),
  ('FAB-AE-045', 'porta-sabre azul-aeronáutica', 'porta-sabre-azul-aeronautica', 'acessorio'),
  ('FAB-AE-045', 'porta-sabre branco', 'porta-sabre-branco', 'acessorio'),
  ('FAB-AE-045', 'porta-sabre preto', 'porta-sabre-preto', 'acessorio'),
  ('FAB-AE-045', 'porta-sabre verde-oliva', 'porta-sabre-verde-oliva', 'acessorio'),
  ('FAB-AE-046', 'suspensórios verde-oliva', 'suspensorios-verde-oliva', 'acessorio'),
  ('FAB-AE-047', 'talabarte branco', 'talabarte-branco', 'acessorio'),
  ('FAB-AE-050', 'talim azul-aeronáutica', 'talim-azul-aeronautica', 'acessorio'),
  ('FAB-AE-051', 'coldre tático', 'coldre-tatico', 'acessorio'),
  ('FAB-AG-001', 'abrigo impermeável amarelo', 'abrigo-impermeavel-amarelo', 'torso'),
  ('FAB-AG-002', 'abrigo camuflado', 'abrigo-camuflado', 'torso'),
  ('FAB-AG-003', 'abrigo polar azul-aeronáutica', 'abrigo-polar-azul-aeronautica', 'torso'),
  ('FAB-AG-004', 'blusão azul-aeronáutica', 'blusao-azul-aeronautica', 'torso'),
  ('FAB-AG-005', 'blusão camuflado', 'blusao-camuflado', 'torso'),
  ('FAB-AG-006', 'jaqueta de competição esportiva', 'jaqueta-de-competicao-esportiva', 'torso'),
  ('FAB-AG-007', 'calça de competição esportiva', 'calca-de-competicao-esportiva', 'pernas'),
  ('FAB-AG-008', 'jaqueta para educação física', 'jaqueta-para-educacao-fisica', 'torso'),
  ('FAB-AG-009', 'macacão camuflado', 'macacao-camuflado', 'torso'),
  ('FAB-AG-010', 'poncho camuflado', 'poncho-camuflado', 'torso'),
  ('FAB-AG-011', 'camisa branca flanelada de mangas compridas (2ª pele)', 'camisa-branca-flanelada-de-mangas-compridas-2-pele', 'torso'),
  ('FAB-AG-012', 'capa de chuva azul-aeronáutica', 'capa-de-chuva-azul-aeronautica', 'torso'),
  ('FAB-AG-013', 'casaco camuflado com forro e capuz', 'casaco-camuflado-com-forro-e-capuz', 'torso'),
  ('FAB-AG-014', 'ceroula feminina branca (2ª pele)', 'ceroula-feminina-branca-2-pele', 'pernas'),
  ('FAB-AG-015', 'ceroula masculina branca (2ª pele)', 'ceroula-masculina-branca-2-pele', 'pernas'),
  ('FAB-AG-016', 'colete azul-aeronáutica com gola em “V”', 'colete-azul-aeronautica-com-gola-em-v', 'torso'),
  ('FAB-AG-017', 'jaleco azul-aeronáutica de mangas curtas', 'jaleco-azul-aeronautica-de-mangas-curtas', 'torso'),
  ('FAB-AG-018', 'jaleco branco', 'jaleco-branco', 'torso'),
  ('FAB-AG-021', 'roupão azul-aeronáutica', 'roupao-azul-aeronautica', 'torso'),
  ('FAB-AG-022', 'jaqueta feminina azul-aeronáutica com forro removível', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel', 'torso'),
  ('FAB-AG-023', 'jaqueta masculina azul-aeronáutica com forro removível', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel', 'torso'),
  ('FAB-AG-024', 'jaqueta feminina branca com forro removível', 'jaqueta-feminina-branca-com-forro-removivel', 'torso'),
  ('FAB-AG-025', 'jaqueta masculina branca com forro removível', 'jaqueta-masculina-branca-com-forro-removivel', 'torso'),
  ('FAB-AG-026', 'jaqueta impermeável azul-aeronáutica', 'jaqueta-impermeavel-azul-aeronautica', 'torso'),
  ('FAB-AG-029', 'sobretudo feminino preto', 'sobretudo-feminino-preto', 'torso'),
  ('FAB-AG-030', 'pulôver azul-aeronáutica', 'pulover-azul-aeronautica', 'torso'),
  ('FAB-AG-031', 'sobretudo masculino preto', 'sobretudo-masculino-preto', 'torso'),
  ('FAB-AG-032', 'jaqueta azul de voo do EDA', 'jaqueta-azul-de-voo-do-eda', 'torso'),
  ('FAB-CAL-001', 'tênis branco multiúso', 'tenis-branco-multiuso', 'calcado'),
  ('FAB-CAL-002', 'Tênis branco prática atividade física', 'tenis-branco-pratica-atividade-fisica', 'calcado'),
  ('FAB-CAL-003', 'sapato masculino preto tipo 2', 'sapato-masculino-preto-tipo-2', 'calcado'),
  ('FAB-CAL-004', 'sapato feminino sem salto', 'sapato-feminino-sem-salto', 'calcado'),
  ('FAB-CAL-006', 'sapato de salto alto', 'sapato-de-salto-alto', 'calcado'),
  ('FAB-CAL-007', 'meia bota de voo', 'meia-bota-de-voo', 'calcado'),
  ('FAB-CAL-008', 'meia bota preta', 'meia-bota-preta', 'calcado'),
  ('FAB-CAL-009', 'borzeguim preto acolchoado', 'borzeguim-preto-acolchoado', 'calcado'),
  ('FAB-CAL-011', 'Calçado para locomoção sobre aeronaves', 'calcado-para-locomocao-sobre-aeronaves', 'calcado'),
  ('FAB-CAL-012', 'meia bota marrom', 'meia-bota-marrom', 'calcado'),
  ('FAB-CAL-013', 'sapato feminino de salto médio tipo 2', 'sapato-feminino-de-salto-medio-tipo-2', 'calcado'),
  ('FAB-CAL-014', 'bota para motociclista e bombeiro', 'bota-para-motociclista-e-bombeiro', 'calcado'),
  ('FAB-CAL-015', 'sapatilha preta', 'sapatilha-preta', 'calcado'),
  ('FAB-CAL-016', 'sapato masculino preto tipo 1', 'sapato-masculino-preto-tipo-1', 'calcado'),
  ('FAB-CAL-017', 'sapato feminino de salto médio tipo 1', 'sapato-feminino-de-salto-medio-tipo-1', 'calcado'),
  ('FAB-CAL-018', 'sapato masculino branco antiderrapante', 'sapato-masculino-branco-antiderrapante', 'calcado'),
  ('FAB-CAL-019', 'sapato feminino preto antiderrapante tipo 1', 'sapato-feminino-preto-antiderrapante-tipo-1', 'calcado'),
  ('FAB-CAL-020', 'bota antiderrapante frigorífica', 'bota-antiderrapante-frigorifica', 'calcado'),
  ('FAB-CAL-021', 'sapato feminino preto antiderrapante tipo 2', 'sapato-feminino-preto-antiderrapante-tipo-2', 'calcado'),
  ('FAB-CAL-022', 'sapato feminino antiderrapante branco para cozinha', 'sapato-feminino-antiderrapante-branco-para-cozinha', 'calcado'),
  ('FAB-CAL-023', 'meia bota para aeronavegante', 'meia-bota-para-aeronavegante', 'calcado'),
  ('FAB-CAL-024', 'sapato feminino branco salto médio', 'sapato-feminino-branco-salto-medio', 'calcado'),
  ('FAB-CAL-025', 'sapato masculino branco', 'sapato-masculino-branco', 'calcado'),
  ('FAB-CAL-026', 'sapato feminino branco sem salto', 'sapato-feminino-branco-sem-salto', 'calcado'),
  ('FAB-CAL-027', 'tênis preto multiuso', 'tenis-preto-multiuso', 'calcado'),
  ('FAB-CAL-028', 'Tênis preto para prática de atividade física', 'tenis-preto-para-pratica-de-atividade-fisica', 'calcado'),
  ('FAB-H-001', 'camisa masculina cáqui de mangas curtas', 'camisa-masculina-caqui-de-mangas-curtas', 'torso'),
  ('FAB-H-002', 'calça cáqui', 'calca-caqui', 'pernas'),
  ('FAB-H-003', 'cinto cáqui', 'cinto-caqui', 'acessorio'),
  ('FAB-H-004', 'gorro cáqui', 'gorro-caqui', 'cabeca'),
  ('FAB-H-006', 'túnica cáqui', 'tunica-caqui', 'torso'),
  ('FAB-H-007', 'botão preto', 'botao-preto', 'acessorio'),
  ('FAB-H-008', 'tecido cáqui', 'tecido-caqui', null),
  ('FAB-H-009', 'insígnia de gorro em tecido cáqui', 'insignia-de-gorro-em-tecido-caqui', 'cabeca'),
  ('FAB-H-010', 'camisa masculina caqui de mangas compridas', 'camisa-masculina-caqui-de-mangas-compridas', 'torso'),
  ('FAB-H-011', 'quepe masculino histórico', 'quepe-masculino-historico', 'cabeca'),
  ('FAB-H-012', 'fivela dourada', 'fivela-dourada', 'acessorio'),
  ('FAB-H-013', 'tecido caqui em sarja pesada', 'tecido-caqui-em-sarja-pesada', null),
  ('FAB-H-014', 'tecido caqui em sarja leve', 'tecido-caqui-em-sarja-leve', null),
  ('FAB-IID-001', 'alamar azul-aeronáutica', 'alamar-azul-aeronautica', 'insignia'),
  ('FAB-IID-002', 'alamar prateado/ dourado', 'alamar-prateado-dourado', 'insignia'),
  ('FAB-IID-003', 'bandeira de nações', 'bandeira-de-nacoes', 'identificacao'),
  ('FAB-IID-004', 'bandeira nacional', 'bandeira-nacional', 'identificacao'),
  ('FAB-IID-005', 'bandeiras e insígnias', 'bandeiras-e-insignias', 'insignia'),
  ('FAB-IID-006', 'crachá para quepe', 'cracha-para-quepe', 'cabeca'),
  ('FAB-IID-007', 'distintivo de curso de formação escudo tipo escudo', 'distintivo-de-curso-de-formacao-escudo-tipo-escudo', 'distintivo'),
  ('FAB-IID-008', 'distintivo de curso de pós-formação para Graduado-Master', 'distintivo-de-curso-de-pos-formacao-para-graduado-master', 'distintivo'),
  ('FAB-IID-009', 'espada', 'espada', 'arma'),
  ('FAB-IID-010', 'insígnias de militares inativos', 'insignias-de-militares-inativos', 'insignia'),
  ('FAB-IID-011', 'identificação da Força Aérea Brasileira em tira de tecido verde', 'identificacao-da-forca-aerea-brasileira-em-tira-de-tecido-verde', 'identificacao'),
  ('FAB-IID-012', 'identificação de nacionalidade em tira de tecido azul-aeronáutica', 'identificacao-de-nacionalidade-em-tira-de-tecido-azul-aeronautica', 'identificacao'),
  ('FAB-IID-013', 'insígnia de gola para uniforme de gala', 'insignia-de-gola-para-uniforme-de-gala', 'insignia'),
  ('FAB-IID-014', 'insignia e distintivo bordado para uso na gola', 'insignia-e-distintivo-bordado-para-uso-na-gola', 'distintivo'),
  ('FAB-IID-015', 'trilho para barretas', 'trilho-para-barretas', 'insignia'),
  ('FAB-IID-016', 'insígnia/distintivo de manga', 'insignia-distintivo-de-manga', 'distintivo'),
  ('FAB-IID-017', 'insígnia/distintivo de bolso e punho', 'insignia-distintivo-de-bolso-e-punho', 'distintivo'),
  ('FAB-IID-018', 'insígnias e distintivos em metal', 'insignias-e-distintivos-em-metal', 'distintivo'),
  ('FAB-IID-019', 'passadeira', 'passadeira', 'insignia'),
  ('FAB-IID-020', 'platina azul-aeronáutica', 'platina-azul-aeronautica', 'insignia'),
  ('FAB-IID-021', 'distintivo de curso de pós-formação para Graduado-Master bordado em tecido verde', 'distintivo-de-curso-de-pos-formacao-para-graduado-master-bordado-em-tecido-verde', 'distintivo'),
  ('FAB-IID-021', 'Platina azul-aeronáutica tipo luva', 'platina-azul-aeronautica-tipo-luva', 'insignia'),
  ('FAB-IID-022', 'platina azul-ferrete', 'platina-azul-ferrete', 'insignia'),
  ('FAB-IID-023', 'tarjeta de acrílico', 'tarjeta-de-acrilico', 'identificacao'),
  ('FAB-IID-024', 'tarjeta de identificação em couro preto', 'tarjeta-de-identificacao-em-couro-preto', 'identificacao'),
  ('FAB-IID-025', 'tarjeta em tira de tecido', 'tarjeta-em-tira-de-tecido', 'identificacao'),
  ('FAB-IID-026', 'Platina bordada em azul-aeronáutica, tipo luva', 'platina-bordada-em-azul-aeronautica-tipo-luva', 'insignia'),
  ('FAB-IID-027', 'Insígnia de ombro para uso no macacão de voo', 'insignia-de-ombro-para-uso-no-macacao-de-voo', 'insignia'),
  ('FAB-IID-028', 'insígnia de aluno taifeiro', 'insignia-de-aluno-taifeiro', 'insignia'),
  ('FAB-IID-029', 'tarjeta de identificação para uso no exterior', 'tarjeta-de-identificacao-para-uso-no-exterior', 'identificacao'),
  ('FAB-IID-030', 'Distintivo de Condição Especial', 'distintivo-de-condicao-especial', 'distintivo'),
  ('FAB-IID-031', 'Suporte em couro para DOM', 'suporte-em-couro-para-dom', 'identificacao'),
  ('FAB-IID-032', 'Distintivo de Organização Militar', 'distintivo-de-organizacao-militar', 'distintivo'),
  ('FAB-IID-033', 'espadim', 'espadim', 'arma'),
  ('FAB-IID-034', 'Distintivos de curso de pós-formação em formato de escudo', 'distintivos-de-curso-de-pos-formacao-em-formato-de-escudo', 'distintivo'),
  ('FAB-IID-035', 'Plaqueta de Identificação do REPOUSAR', 'plaqueta-de-identificacao-do-repousar', 'identificacao'),
  ('FAB-IID-036', 'Plaqueta de Identificação do SISHOTEL', 'plaqueta-de-identificacao-do-sishotel', 'identificacao'),
  ('FAB-IID-037', 'Distintivos CGAEM', 'distintivos-cgaem', 'distintivo'),
  ('FAB-IID-038', 'Trilhos para barretas em policarbonat', 'trilhos-para-barretas-em-policarbonat', 'insignia'),
  ('FAB-IID-039', 'Distintivos de curso de pós-formação para oficiais', 'distintivos-de-curso-de-pos-formacao-para-oficiais', 'distintivo'),
  ('FAB-PED-001', 'macacão verde de voo', 'macacao-verde-de-voo', 'torso'),
  ('FAB-PED-002', 'jaqueta verde de voo', 'jaqueta-verde-de-voo', 'torso'),
  ('FAB-PED-004', 'luva de voo', 'luva-de-voo', 'acessorio'),
  ('FAB-REP-001', 'camisa polo masculina repousar', 'camisa-polo-masculina-repousar', 'torso'),
  ('FAB-REP-002', 'camisa polo feminina repousar', 'camisa-polo-feminina-repousar', 'torso'),
  ('FAB-V-001', 'camisa feminina branca de mangas curtas', 'camisa-feminina-branca-de-mangas-curtas', 'torso'),
  ('FAB-V-002', 'camisa masculina  branca de mangas curtas', 'camisa-masculina-branca-de-mangas-curtas', 'torso'),
  ('FAB-V-006', 'bata branca para gestantes', 'bata-branca-para-gestantes', 'torso'),
  ('FAB-V-007', 'bermuda azul-royal', 'bermuda-azul-royal', 'pernas'),
  ('FAB-V-008', 'bermuda azul-aeronáutica', 'bermuda-azul-aeronautica', 'pernas'),
  ('FAB-V-009', 'bermuda de brim azul-aeronáutica', 'bermuda-de-brim-azul-aeronautica', 'pernas'),
  ('FAB-V-010', 'blazer feminino preto', 'blazer-feminino-preto', 'torso'),
  ('FAB-V-011', 'boina grená', 'boina-grena', 'cabeca'),
  ('FAB-V-012', 'boné para educação física', 'bone-para-educacao-fisica', 'cabeca'),
  ('FAB-V-013', 'calça para educação física', 'calca-para-educacao-fisica', 'pernas'),
  ('FAB-V-014', 'calça azul-aeronáutica para gestante', 'calca-azul-aeronautica-para-gestante', 'pernas'),
  ('FAB-V-015', 'calça branca para trabalhos de copa e cozinha', 'calca-branca-para-trabalhos-de-copa-e-cozinha', 'pernas'),
  ('FAB-V-016', 'calça branca para gestante', 'calca-branca-para-gestante', 'pernas'),
  ('FAB-V-017', 'calça camuflada', 'calca-camuflada', 'pernas'),
  ('FAB-V-018', 'calça de brim azul-aeronáutica', 'calca-de-brim-azul-aeronautica', 'pernas'),
  ('FAB-V-019', 'calça feminina azul-ferrete', 'calca-feminina-azul-ferrete', 'pernas'),
  ('FAB-V-020', 'calça feminina azul-aeronáutica', 'calca-feminina-azul-aeronautica', 'pernas'),
  ('FAB-V-021', 'calça feminina branca', 'calca-feminina-branca', 'pernas'),
  ('FAB-V-022', 'calça feminina preta', 'calca-feminina-preta', 'pernas'),
  ('FAB-V-023', 'calça masculina azul-ferrete', 'calca-masculina-azul-ferrete', 'pernas'),
  ('FAB-V-024', 'calça masculina azul-aeronáutica', 'calca-masculina-azul-aeronautica', 'pernas'),
  ('FAB-V-025', 'calça masculina branca', 'calca-masculina-branca', 'pernas'),
  ('FAB-V-026', 'calça preta', 'calca-preta', 'pernas'),
  ('FAB-V-027', 'calção azul-aeronáutica para ed. Física', 'calcao-azul-aeronautica-para-ed-fisica', 'pernas'),
  ('FAB-V-029', 'calção preto tipo natação', 'calcao-preto-tipo-natacao', 'pernas'),
  ('FAB-V-030', 'camisa masculina branca de mangas compridas', 'camisa-masculina-branca-de-mangas-compridas', 'torso'),
  ('FAB-V-031', 'camisa masculina branca de mangas curtas com colarinho', 'camisa-masculina-branca-de-mangas-curtas-com-colarinho', 'torso'),
  ('FAB-V-032', 'camisa de gala feminina branca', 'camisa-de-gala-feminina-branca', 'torso'),
  ('FAB-V-033', 'camisa de gala masculina branca', 'camisa-de-gala-masculina-branca', 'torso'),
  ('FAB-V-034', 'camisa feminina azul-clara de mangas compridas', 'camisa-feminina-azul-clara-de-mangas-compridas', 'torso'),
  ('FAB-V-037', 'camisa feminina branca de mangas compridas', 'camisa-feminina-branca-de-mangas-compridas', 'torso'),
  ('FAB-V-038', 'camisa feminina branca de mangas curtas com colarinho', 'camisa-feminina-branca-de-mangas-curtas-com-colarinho', 'torso'),
  ('FAB-V-039', 'camisa masculina azul-clara de mangas compridas', 'camisa-masculina-azul-clara-de-mangas-compridas', 'torso'),
  ('FAB-V-042', 'jaqueta masculina azul-ferrete de gala', 'jaqueta-masculina-azul-ferrete-de-gala', 'torso'),
  ('FAB-V-043', 'camiseta branca', 'camiseta-branca', 'torso'),
  ('FAB-V-044', 'camiseta branca com gládio alado para ed. física', 'camiseta-branca-com-gladio-alado-para-ed-fisica', 'torso'),
  ('FAB-V-045', 'camiseta camuflada', 'camiseta-camuflada', 'torso'),
  ('FAB-V-046', 'camiseta branca olímpica com gola em v e debrum', 'camiseta-branca-olimpica-com-gola-em-v-e-debrum', 'torso'),
  ('FAB-V-047', 'cinto azul-aeronáutica, branco ou preto', 'cinto-azul-aeronautica-branco-ou-preto', 'acessorio'),
  ('FAB-V-048', 'dolmã branco', 'dolma-branco', 'torso'),
  ('FAB-V-049', 'faixa preta de cetim', 'faixa-preta-de-cetim', 'acessorio'),
  ('FAB-V-050', 'fivela prateada ou preta', 'fivela-prateada-ou-preta', 'acessorio'),
  ('FAB-V-051', 'gandola camuflada', 'gandola-camuflada', 'torso'),
  ('FAB-V-053', 'gorro branco para chefe de cozinha', 'gorro-branco-para-chefe-de-cozinha', 'cabeca'),
  ('FAB-V-054', 'gorro camuflado com pala', 'gorro-camuflado-com-pala', 'cabeca'),
  ('FAB-V-055', 'gorro feminino azul-aeronáutica', 'gorro-feminino-azul-aeronautica', 'cabeca'),
  ('FAB-V-056', 'gorro laranja', 'gorro-laranja', 'cabeca'),
  ('FAB-V-057', 'gorro masculino azul-aeronáutica', 'gorro-masculino-azul-aeronautica', 'cabeca'),
  ('FAB-V-058', 'gravata feminina preta', 'gravata-feminina-preta', 'acessorio'),
  ('FAB-V-060', 'gravata vertical preta', 'gravata-vertical-preta', 'acessorio'),
  ('FAB-V-061', 'camisa de combate', 'camisa-de-combate', 'torso'),
  ('FAB-V-062', 'jaleco para barbeiro', 'jaleco-para-barbeiro', 'torso'),
  ('FAB-V-063', 'camisa branca para comissária de bordo', 'camisa-branca-para-comissaria-de-bordo', 'torso'),
  ('FAB-V-064', 'bermuda cargo azul-aeronáutica', 'bermuda-cargo-azul-aeronautica', 'pernas'),
  ('FAB-V-065', 'jaqueta feminina azul-ferrete', 'jaqueta-feminina-azul-ferrete', 'torso'),
  ('FAB-V-066', 'jaqueta preta de couro', 'jaqueta-preta-de-couro', 'torso'),
  ('FAB-V-067', 'jaqueta rigor feminina azul-aeronáutica', 'jaqueta-rigor-feminina-azul-aeronautica', 'torso'),
  ('FAB-V-068', 'jaqueta rigor feminina branca', 'jaqueta-rigor-feminina-branca', 'torso'),
  ('FAB-V-070', 'colete preto', 'colete-preto', 'torso'),
  ('FAB-V-071', 'macacao de voo do EDA', 'macacao-de-voo-do-eda', 'torso'),
  ('FAB-V-073', 'maiô preto de tecido sintético com elastômero', 'maio-preto-de-tecido-sintetico-com-elastomero', 'torso'),
  ('FAB-V-074', 'macacão azul-aeronáutica', 'macacao-azul-aeronautica', 'torso'),
  ('FAB-V-075', 'meia branca de cano curto para esporte', 'meia-branca-de-cano-curto-para-esporte', 'acessorio'),
  ('FAB-V-076', 'meia calça social lisa', 'meia-calca-social-lisa', 'acessorio'),
  ('FAB-V-077', 'meia preta/branca de cano longo', 'meia-preta-branca-de-cano-longo', 'acessorio'),
  ('FAB-V-078', 'meia preta/branca de nylon', 'meia-preta-branca-de-nylon', 'acessorio'),
  ('FAB-V-079', 'Meio avental branco', 'meio-avental-branco', 'acessorio'),
  ('FAB-V-080', 'prendedor para gravata masculina vertical preta', 'prendedor-para-gravata-masculina-vertical-preta', 'acessorio'),
  ('FAB-V-081', 'quepe feminino', 'quepe-feminino', 'cabeca'),
  ('FAB-V-082', 'quepe masculino', 'quepe-masculino', 'cabeca'),
  ('FAB-V-083', 'saia azul-aeronáutica', 'saia-azul-aeronautica', 'pernas'),
  ('FAB-V-084', 'saia longa azul-ferrete', 'saia-longa-azul-ferrete', 'pernas'),
  ('FAB-V-085', 'saia longa azul-aeronáutica', 'saia-longa-azul-aeronautica', 'pernas'),
  ('FAB-V-086', 'saia preta', 'saia-preta', 'pernas'),
  ('FAB-V-087', 'paletó preto', 'paleto-preto', 'torso'),
  ('FAB-V-088', 'top azul azul-aeronáutica', 'top-azul-azul-aeronautica', 'torso'),
  ('FAB-V-089', 'touca preta para natação', 'touca-preta-para-natacao', 'cabeca'),
  ('FAB-V-090', 'túnica masculina branca', 'tunica-masculina-branca', 'torso'),
  ('FAB-V-091', 'túnica de desfile feminina', 'tunica-de-desfile-feminina', 'torso'),
  ('FAB-V-092', 'tunica de desfile masculina', 'tunica-de-desfile-masculina', 'torso'),
  ('FAB-V-093', 'túnica feminina azul-aeronáutica', 'tunica-feminina-azul-aeronautica', 'torso'),
  ('FAB-V-094', 'túnica feminina branca', 'tunica-feminina-branca', 'torso'),
  ('FAB-V-095', 'túnica masculina azul-aeronáutica', 'tunica-masculina-azul-aeronautica', 'torso'),
  ('FAB-V-096', 'Vestido preto para comissária de bordo', 'vestido-preto-para-comissaria-de-bordo', 'torso'),
  ('FAB-V-097', 'vestido azul-aeronáutica para gestante', 'vestido-azul-aeronautica-para-gestante', 'torso'),
  ('FAB-V-098', 'vestido branco para o serviço de saúde', 'vestido-branco-para-o-servico-de-saude', 'torso'),
  ('FAB-V-099', 'vestido branco para gestante', 'vestido-branco-para-gestante', 'torso'),
  ('FAB-V-101', 'colete feminino preto', 'colete-feminino-preto', 'torso'),
  ('FAB-V-102', 'cinto feminino preto de couro', 'cinto-feminino-preto-de-couro', 'acessorio'),
  ('FAB-V-103', 'jaqueta masculina branca para orquestra', 'jaqueta-masculina-branca-para-orquestra', 'torso'),
  ('FAB-V-104', 'calça masculina azul-aeronáutica para orquestra', 'calca-masculina-azul-aeronautica-para-orquestra', 'pernas'),
  ('FAB-V-105', 'jaqueta feminina branca para orquestra', 'jaqueta-feminina-branca-para-orquestra', 'torso'),
  ('FAB-V-106', 'calça feminina azul-aeronáutica para orquestra', 'calca-feminina-azul-aeronautica-para-orquestra', 'pernas'),
  ('FAB-V-107', 'saia azul-aeronáutica para orquestra', 'saia-azul-aeronautica-para-orquestra', 'pernas'),
  ('FAB-V-108', 'faixa azul de cetim', 'faixa-azul-de-cetim', 'acessorio'),
  ('FAB-V-109', 'gravata feminina com laço', 'gravata-feminina-com-laco', 'acessorio'),
  ('FAB-V-111', 'casaca para maestro', 'casaca-para-maestro', 'torso'),
  ('FAB-V-112', 'colete para maestro', 'colete-para-maestro', 'torso'),
  ('FAB-V-113', 'gravata horizontal azul-aeronáutica ou preta', 'gravata-horizontal-azul-aeronautica-ou-preta', 'acessorio'),
  ('FAB-V-114', 'CAMISAS FEMININAS AZUIS-CLARAS DE MANGAS CURTAS', 'camisas-femininas-azuis-claras-de-mangas-curtas', 'torso'),
  ('FAB-V-115', 'CAMISAS MASCULINAS AZUIS-CLARAS DE MANGAS CURTAS', 'camisas-masculinas-azuis-claras-de-mangas-curtas', 'torso'),
  ('FAB-V-116', 'camiseta camuflada em poliamida', 'camiseta-camuflada-em-poliamida', 'torso'),
  ('FAB-V-117', 'paletó para conselheiros INCAER', 'paleto-para-conselheiros-incaer', 'torso'),
  ('FAB-V-118', 'colete para conselheiros INCAER', 'colete-para-conselheiros-incaer', 'torso'),
  ('FAB-V-119', 'calça para conselheiros INCAER', 'calca-para-conselheiros-incaer', 'pernas'),
  ('FAB-V-120', 'túnica transpassada feminina azul-aeronáutica', 'tunica-transpassada-feminina-azul-aeronautica', 'torso'),
  ('FAB-V-121', 'batas azuis-claras de mangas curtas', 'batas-azuis-claras-de-mangas-curtas', 'torso'),
  ('FAB-V-124', 'Meio avental preto', 'meio-avental-preto', 'acessorio'),
  ('FAB-V-125', 'túnica transpassada masculina azul-aeronáutica', 'tunica-transpassada-masculina-azul-aeronautica', 'torso'),
  ('FAB-V-126', 'cinto masculino preto de couro', 'cinto-masculino-preto-de-couro', 'acessorio')
on conflict (slug) do update set
  codigo = excluded.codigo,
  nome = excluded.nome,
  tipo = coalesce(excluded.tipo, rumaer.piece.tipo),
  deleted_at = null,
  updated_at = now();
