-- Reconstrói o "7º Uniforme A" (Art. 26 do RUMAER), traje de passeio — grupo servicos.
-- O 7A do seed tinha variantes/peças DEMO (platina/tarjeta, só oficiais+sargentos) que não batem com o
-- Art. 26 → as variantes demo são removidas (cascade nas peças) e o uniforme é repreenchido conforme o artigo.
-- Variantes: feminino (oficiais, suboficiais, cadetes, sargentos, alunos), gestante (oficiais, suboficiais,
-- sargentos), masculino (mesmos círculos do feminino).
-- Camisa azul-clara de mangas curtas: PASSANTES para oficiais/suboficiais/cadetes/alunos; OMBREIRAS para
-- sargentos (e alunos da EEAR) — registrado na observação (peça única por gênero).
-- Idempotente; casa variante por (círculo, gênero, sub_variação) e peça por slug.

do $$
declare
	u_id uuid;
begin
	select id into u_id from rumaer.uniform where numero = 7 and letra = 'A' and deleted_at is null limit 1;

	if u_id is null then
		insert into rumaer.uniform (numero, letra, nome, grupo, subgrupo, traje, art_referencia, ordem, descricao_md)
		values (7, 'A', '7º Uniforme A', 'servicos', 'passeio', 'passeio', 'Art. 26', 70,
			'7º Uniforme "A", correspondente ao traje de passeio.')
		returning id into u_id;
	else
		-- remove a composição/variantes demo do seed para repreencher conforme o Art. 26
		delete from rumaer.uniform_variant where uniform_id = u_id;
	end if;

	insert into rumaer.uniform_category (uniform_id, categoria) values
		(u_id, 'oficiais'), (u_id, 'cadetes'), (u_id, 'suboficiais'),
		(u_id, 'sargentos'), (u_id, 'alunos_formacao')
	on conflict (uniform_id, categoria) do nothing;

	insert into rumaer.uniform_variant (uniform_id, circulo, genero, sub_variacao, ordem) values
		(u_id, 'oficiais',    'feminino',  null,       0),
		(u_id, 'cadetes',     'feminino',  null,       1),
		(u_id, 'suboficiais', 'feminino',  null,       2),
		(u_id, 'sargentos',   'feminino',  null,       3),
		(u_id, 'alunos',      'feminino',  null,       4),
		(u_id, 'oficiais',    'feminino',  'gestante', 5),
		(u_id, 'suboficiais', 'feminino',  'gestante', 6),
		(u_id, 'sargentos',   'feminino',  'gestante', 7),
		(u_id, 'oficiais',    'masculino', null,       8),
		(u_id, 'cadetes',     'masculino', null,       9),
		(u_id, 'suboficiais', 'masculino', null,       10),
		(u_id, 'sargentos',   'masculino', null,       11),
		(u_id, 'alunos',      'masculino', null,       12)
	on conflict (uniform_id, circulo, genero, sub_variacao) do nothing;
end $$;

with comp(genero, subvar, circulo, slug, nivel, ordem, obs) as (
	values
		-- ===================== FEMININO =====================
		('feminino', null, 'oficiais', 'quepe-feminino',                               'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunas dos centros de formação ou de adaptação de oficiais)'),
		('feminino', null, 'oficiais', 'camiseta-branca',                              'obrigatorio', 2,  'branca'),
		('feminino', null, 'oficiais', 'saia-azul-aeronautica',                        'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'oficiais', 'calca-feminina-azul-aeronautica',              'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'oficiais', 'cinto-azul-aeronautica-branco-ou-preto',       'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'oficiais', 'sapato-feminino-de-salto-medio-tipo-2',        'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'oficiais', 'meia-calca-social-lisa',                       'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'oficiais', 'meia-preta-branca-de-nylon',                   'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'oficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'oficiais', 'colete-azul-aeronautica-com-gola-em-v',        'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'oficiais', 'pulover-azul-aeronautica',                     'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'capa-de-chuva-azul-aeronautica',               'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'japona-azul-aeronautica',                      'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'sobretudo-feminino-azul-aeronautica',          'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'cachecol-branco',                              'facultativo', 17, null),
		('feminino', null, 'oficiais', 'luva-de-la-preta',                             'facultativo', 18, 'preta'),
		('feminino', null, 'oficiais', 'jaleco-branco',                                'eventual',    20, 'branco'),
		('feminino', null, 'oficiais', 'cinturao-preto',                               'eventual',    21, 'preto'),
		('feminino', null, 'oficiais', 'porta-pistola-preto',                          'eventual',    22, 'preto'),
		('feminino', null, 'oficiais', 'colete-especial-para-atividades-de-foto-e-filmagem-azul-aeronautica','eventual', 23, 'azul-aeronáutica (oficiais, suboficiais e sargentos)'),
		('feminino', null, 'cadetes', 'quepe-feminino',                                'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunas dos centros de formação ou de adaptação de oficiais)'),
		('feminino', null, 'cadetes', 'camiseta-branca',                               'obrigatorio', 2,  'branca'),
		('feminino', null, 'cadetes', 'saia-azul-aeronautica',                         'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'cadetes', 'calca-feminina-azul-aeronautica',               'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'cadetes', 'cinto-azul-aeronautica-branco-ou-preto',        'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'cadetes', 'sapato-feminino-de-salto-medio-tipo-2',         'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'cadetes', 'meia-calca-social-lisa',                        'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'cadetes', 'meia-preta-branca-de-nylon',                    'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'cadetes', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'cadetes', 'colete-azul-aeronautica-com-gola-em-v',         'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'cadetes', 'pulover-azul-aeronautica',                      'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'capa-de-chuva-azul-aeronautica',                'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'japona-azul-aeronautica',                       'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'sobretudo-feminino-azul-aeronautica',           'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'cachecol-branco',                               'facultativo', 17, null),
		('feminino', null, 'cadetes', 'luva-de-la-preta',                              'facultativo', 18, 'preta'),
		('feminino', null, 'cadetes', 'jaleco-branco',                                 'eventual',    20, 'branco'),
		('feminino', null, 'cadetes', 'cinturao-preto',                                'eventual',    21, 'preto'),
		('feminino', null, 'cadetes', 'porta-pistola-preto',                           'eventual',    22, 'preto'),
		('feminino', null, 'suboficiais', 'quepe-feminino',                            'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunas dos centros de formação ou de adaptação de oficiais)'),
		('feminino', null, 'suboficiais', 'camiseta-branca',                           'obrigatorio', 2,  'branca'),
		('feminino', null, 'suboficiais', 'saia-azul-aeronautica',                     'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'calca-feminina-azul-aeronautica',           'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'cinto-azul-aeronautica-branco-ou-preto',    'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'suboficiais', 'sapato-feminino-de-salto-medio-tipo-2',     'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'suboficiais', 'meia-calca-social-lisa',                    'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'suboficiais', 'meia-preta-branca-de-nylon',                'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'suboficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'suboficiais', 'colete-azul-aeronautica-com-gola-em-v',     'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'suboficiais', 'pulover-azul-aeronautica',                  'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'capa-de-chuva-azul-aeronautica',            'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'japona-azul-aeronautica',                   'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'sobretudo-feminino-azul-aeronautica',       'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'cachecol-branco',                           'facultativo', 17, null),
		('feminino', null, 'suboficiais', 'luva-de-la-preta',                          'facultativo', 18, 'preta'),
		('feminino', null, 'suboficiais', 'jaleco-branco',                             'eventual',    20, 'branco'),
		('feminino', null, 'suboficiais', 'cinturao-preto',                            'eventual',    21, 'preto'),
		('feminino', null, 'suboficiais', 'porta-pistola-preto',                       'eventual',    22, 'preto'),
		('feminino', null, 'suboficiais', 'colete-especial-para-atividades-de-foto-e-filmagem-azul-aeronautica','eventual', 23, 'azul-aeronáutica (oficiais, suboficiais e sargentos)'),
		('feminino', null, 'sargentos', 'quepe-feminino',                              'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com ombreiras (sargentos e alunas da EEAR)'),
		('feminino', null, 'sargentos', 'camiseta-branca',                             'obrigatorio', 2,  'branca'),
		('feminino', null, 'sargentos', 'saia-azul-aeronautica',                       'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'sargentos', 'calca-feminina-azul-aeronautica',             'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'sargentos', 'cinto-azul-aeronautica-branco-ou-preto',      'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'sargentos', 'sapato-feminino-de-salto-medio-tipo-2',       'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'sargentos', 'meia-calca-social-lisa',                      'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'sargentos', 'meia-preta-branca-de-nylon',                  'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'sargentos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'sargentos', 'colete-azul-aeronautica-com-gola-em-v',       'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'sargentos', 'pulover-azul-aeronautica',                    'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'capa-de-chuva-azul-aeronautica',              'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'japona-azul-aeronautica',                     'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'sobretudo-feminino-azul-aeronautica',         'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'cachecol-branco',                             'facultativo', 17, null),
		('feminino', null, 'sargentos', 'luva-de-la-preta',                            'facultativo', 18, 'preta'),
		('feminino', null, 'sargentos', 'jaleco-branco',                               'eventual',    20, 'branco'),
		('feminino', null, 'sargentos', 'cinturao-preto',                              'eventual',    21, 'preto'),
		('feminino', null, 'sargentos', 'porta-pistola-preto',                         'eventual',    22, 'preto'),
		('feminino', null, 'sargentos', 'colete-especial-para-atividades-de-foto-e-filmagem-azul-aeronautica','eventual', 23, 'azul-aeronáutica (oficiais, suboficiais e sargentos)'),
		('feminino', null, 'alunos', 'quepe-feminino',                                 'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'alunos', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunas dos centros de formação ou de adaptação de oficiais)'),
		('feminino', null, 'alunos', 'camiseta-branca',                                'obrigatorio', 2,  'branca'),
		('feminino', null, 'alunos', 'saia-azul-aeronautica',                          'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'alunos', 'calca-feminina-azul-aeronautica',                'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'alunos', 'cinto-azul-aeronautica-branco-ou-preto',         'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'alunos', 'sapato-feminino-de-salto-medio-tipo-2',          'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'alunos', 'meia-calca-social-lisa',                         'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'alunos', 'meia-preta-branca-de-nylon',                     'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'alunos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'alunos', 'colete-azul-aeronautica-com-gola-em-v',          'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'alunos', 'pulover-azul-aeronautica',                       'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'capa-de-chuva-azul-aeronautica',                 'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'japona-azul-aeronautica',                        'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'sobretudo-feminino-azul-aeronautica',            'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'cachecol-branco',                                'facultativo', 17, null),
		('feminino', null, 'alunos', 'luva-de-la-preta',                               'facultativo', 18, 'preta'),
		('feminino', null, 'alunos', 'jaleco-branco',                                  'eventual',    20, 'branco'),
		('feminino', null, 'alunos', 'cinturao-preto',                                 'eventual',    21, 'preto'),
		('feminino', null, 'alunos', 'porta-pistola-preto',                            'eventual',    22, 'preto'),

		-- ===================== GESTANTE =====================
		('feminino', 'gestante', 'oficiais', 'quepe-feminino',                         'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'vestido-azul-aeronautica-para-gestante', 'obrigatorio', 1,  'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 2,  'ou bata azul-clara de mangas curtas, com passantes (oficiais e suboficiais)'),
		('feminino', 'gestante', 'oficiais', 'camiseta-branca',                        'obrigatorio', 3,  'branca'),
		('feminino', 'gestante', 'oficiais', 'calca-azul-aeronautica-para-gestante',   'obrigatorio', 4,  'azul-aeronáutica (utilizada em conjunto com a bata)'),
		('feminino', 'gestante', 'oficiais', 'sapato-feminino-de-salto-medio-tipo-2',  'obrigatorio', 5,  'preto (salto médio, baixo ou sem salto)'),
		('feminino', 'gestante', 'oficiais', 'meia-calca-social-lisa',                 'obrigatorio', 6,  'cor da pele (autorizado meia especial; ou meia preta quando usando calça)'),
		('feminino', 'gestante', 'oficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', 'gestante', 'oficiais', 'colete-azul-aeronautica-com-gola-em-v',  'facultativo', 11, 'gola em "V"'),
		('feminino', 'gestante', 'oficiais', 'pulover-azul-aeronautica',               'facultativo', 12, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'capa-de-chuva-azul-aeronautica',         'facultativo', 14, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'japona-azul-aeronautica',                'facultativo', 15, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'sobretudo-feminino-azul-aeronautica',    'facultativo', 16, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'cachecol-branco',                        'facultativo', 17, null),
		('feminino', 'gestante', 'oficiais', 'luva-de-la-preta',                       'facultativo', 18, 'preta'),
		('feminino', 'gestante', 'oficiais', 'jaleco-branco',                          'eventual',    20, 'branco'),
		('feminino', 'gestante', 'suboficiais', 'quepe-feminino',                      'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'vestido-azul-aeronautica-para-gestante','obrigatorio', 1,  'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 2,  'ou bata azul-clara de mangas curtas, com passantes (oficiais e suboficiais)'),
		('feminino', 'gestante', 'suboficiais', 'camiseta-branca',                     'obrigatorio', 3,  'branca'),
		('feminino', 'gestante', 'suboficiais', 'calca-azul-aeronautica-para-gestante','obrigatorio', 4,  'azul-aeronáutica (utilizada em conjunto com a bata)'),
		('feminino', 'gestante', 'suboficiais', 'sapato-feminino-de-salto-medio-tipo-2','obrigatorio', 5,  'preto (salto médio, baixo ou sem salto)'),
		('feminino', 'gestante', 'suboficiais', 'meia-calca-social-lisa',              'obrigatorio', 6,  'cor da pele (autorizado meia especial; ou meia preta quando usando calça)'),
		('feminino', 'gestante', 'suboficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', 'gestante', 'suboficiais', 'colete-azul-aeronautica-com-gola-em-v','facultativo', 11, 'gola em "V"'),
		('feminino', 'gestante', 'suboficiais', 'pulover-azul-aeronautica',            'facultativo', 12, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'capa-de-chuva-azul-aeronautica',      'facultativo', 14, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'japona-azul-aeronautica',             'facultativo', 15, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'sobretudo-feminino-azul-aeronautica', 'facultativo', 16, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'cachecol-branco',                     'facultativo', 17, null),
		('feminino', 'gestante', 'suboficiais', 'luva-de-la-preta',                    'facultativo', 18, 'preta'),
		('feminino', 'gestante', 'suboficiais', 'jaleco-branco',                       'eventual',    20, 'branco'),
		('feminino', 'gestante', 'sargentos', 'quepe-feminino',                        'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'vestido-azul-aeronautica-para-gestante','obrigatorio', 1,  'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'camisas-femininas-azuis-claras-de-mangas-curtas','obrigatorio', 2,  'ou bata azul-clara de mangas curtas, com ombreiras (sargentos)'),
		('feminino', 'gestante', 'sargentos', 'camiseta-branca',                       'obrigatorio', 3,  'branca'),
		('feminino', 'gestante', 'sargentos', 'calca-azul-aeronautica-para-gestante',  'obrigatorio', 4,  'azul-aeronáutica (utilizada em conjunto com a bata)'),
		('feminino', 'gestante', 'sargentos', 'sapato-feminino-de-salto-medio-tipo-2', 'obrigatorio', 5,  'preto (salto médio, baixo ou sem salto)'),
		('feminino', 'gestante', 'sargentos', 'meia-calca-social-lisa',                'obrigatorio', 6,  'cor da pele (autorizado meia especial; ou meia preta quando usando calça)'),
		('feminino', 'gestante', 'sargentos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', 'gestante', 'sargentos', 'colete-azul-aeronautica-com-gola-em-v', 'facultativo', 11, 'gola em "V"'),
		('feminino', 'gestante', 'sargentos', 'pulover-azul-aeronautica',              'facultativo', 12, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'capa-de-chuva-azul-aeronautica',        'facultativo', 14, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'japona-azul-aeronautica',               'facultativo', 15, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'sobretudo-feminino-azul-aeronautica',   'facultativo', 16, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'cachecol-branco',                       'facultativo', 17, null),
		('feminino', 'gestante', 'sargentos', 'luva-de-la-preta',                      'facultativo', 18, 'preta'),
		('feminino', 'gestante', 'sargentos', 'jaleco-branco',                         'eventual',    20, 'branco'),

		-- ===================== MASCULINO =====================
		('masculino', null, 'oficiais', 'quepe-masculino',                             'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'camisas-masculinas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunos dos centros de formação ou de adaptação de oficiais)'),
		('masculino', null, 'oficiais', 'camiseta-branca',                             'obrigatorio', 2,  'branca'),
		('masculino', null, 'oficiais', 'calca-masculina-azul-aeronautica',            'obrigatorio', 3,  null),
		('masculino', null, 'oficiais', 'cinto-azul-aeronautica-branco-ou-preto',      'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'oficiais', 'sapato-masculino-preto-tipo-2',               'obrigatorio', 5,  'preto'),
		('masculino', null, 'oficiais', 'meia-preta-branca-de-nylon',                  'obrigatorio', 6,  'preta'),
		('masculino', null, 'oficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'oficiais', 'colete-azul-aeronautica-com-gola-em-v',       'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'oficiais', 'pulover-azul-aeronautica',                    'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'capa-de-chuva-azul-aeronautica',              'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'japona-azul-aeronautica',                     'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'sobretudo-masculino-azul-aeronautica',        'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'cachecol-branco',                             'facultativo', 17, null),
		('masculino', null, 'oficiais', 'luva-de-la-preta',                            'facultativo', 18, 'preta'),
		('masculino', null, 'oficiais', 'jaleco-branco',                               'eventual',    20, 'branco'),
		('masculino', null, 'oficiais', 'cinturao-preto',                              'eventual',    21, 'preto'),
		('masculino', null, 'oficiais', 'porta-pistola-preto',                         'eventual',    22, 'preto'),
		('masculino', null, 'oficiais', 'colete-especial-para-atividades-de-foto-e-filmagem-azul-aeronautica','eventual', 23, 'azul-aeronáutica (oficiais, suboficiais e sargentos)'),
		('masculino', null, 'cadetes', 'quepe-masculino',                              'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'camisas-masculinas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunos dos centros de formação ou de adaptação de oficiais)'),
		('masculino', null, 'cadetes', 'camiseta-branca',                              'obrigatorio', 2,  'branca'),
		('masculino', null, 'cadetes', 'calca-masculina-azul-aeronautica',             'obrigatorio', 3,  null),
		('masculino', null, 'cadetes', 'cinto-azul-aeronautica-branco-ou-preto',       'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'cadetes', 'sapato-masculino-preto-tipo-2',                'obrigatorio', 5,  'preto'),
		('masculino', null, 'cadetes', 'meia-preta-branca-de-nylon',                   'obrigatorio', 6,  'preta'),
		('masculino', null, 'cadetes', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'cadetes', 'colete-azul-aeronautica-com-gola-em-v',        'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'cadetes', 'pulover-azul-aeronautica',                     'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'capa-de-chuva-azul-aeronautica',               'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'japona-azul-aeronautica',                      'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'sobretudo-masculino-azul-aeronautica',         'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'cachecol-branco',                              'facultativo', 17, null),
		('masculino', null, 'cadetes', 'luva-de-la-preta',                             'facultativo', 18, 'preta'),
		('masculino', null, 'cadetes', 'jaleco-branco',                                'eventual',    20, 'branco'),
		('masculino', null, 'cadetes', 'cinturao-preto',                               'eventual',    21, 'preto'),
		('masculino', null, 'cadetes', 'porta-pistola-preto',                          'eventual',    22, 'preto'),
		('masculino', null, 'suboficiais', 'quepe-masculino',                          'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'camisas-masculinas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunos dos centros de formação ou de adaptação de oficiais)'),
		('masculino', null, 'suboficiais', 'camiseta-branca',                          'obrigatorio', 2,  'branca'),
		('masculino', null, 'suboficiais', 'calca-masculina-azul-aeronautica',         'obrigatorio', 3,  null),
		('masculino', null, 'suboficiais', 'cinto-azul-aeronautica-branco-ou-preto',   'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'suboficiais', 'sapato-masculino-preto-tipo-2',            'obrigatorio', 5,  'preto'),
		('masculino', null, 'suboficiais', 'meia-preta-branca-de-nylon',               'obrigatorio', 6,  'preta'),
		('masculino', null, 'suboficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'suboficiais', 'colete-azul-aeronautica-com-gola-em-v',    'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'suboficiais', 'pulover-azul-aeronautica',                 'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'capa-de-chuva-azul-aeronautica',           'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'japona-azul-aeronautica',                  'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'sobretudo-masculino-azul-aeronautica',     'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'cachecol-branco',                          'facultativo', 17, null),
		('masculino', null, 'suboficiais', 'luva-de-la-preta',                         'facultativo', 18, 'preta'),
		('masculino', null, 'suboficiais', 'jaleco-branco',                            'eventual',    20, 'branco'),
		('masculino', null, 'suboficiais', 'cinturao-preto',                           'eventual',    21, 'preto'),
		('masculino', null, 'suboficiais', 'porta-pistola-preto',                      'eventual',    22, 'preto'),
		('masculino', null, 'suboficiais', 'colete-especial-para-atividades-de-foto-e-filmagem-azul-aeronautica','eventual', 23, 'azul-aeronáutica (oficiais, suboficiais e sargentos)'),
		('masculino', null, 'sargentos', 'quepe-masculino',                            'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'camisas-masculinas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com ombreiras (sargentos e alunos da EEAR)'),
		('masculino', null, 'sargentos', 'camiseta-branca',                            'obrigatorio', 2,  'branca'),
		('masculino', null, 'sargentos', 'calca-masculina-azul-aeronautica',           'obrigatorio', 3,  null),
		('masculino', null, 'sargentos', 'cinto-azul-aeronautica-branco-ou-preto',     'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'sargentos', 'sapato-masculino-preto-tipo-2',              'obrigatorio', 5,  'preto'),
		('masculino', null, 'sargentos', 'meia-preta-branca-de-nylon',                 'obrigatorio', 6,  'preta'),
		('masculino', null, 'sargentos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'sargentos', 'colete-azul-aeronautica-com-gola-em-v',      'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'sargentos', 'pulover-azul-aeronautica',                   'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'capa-de-chuva-azul-aeronautica',             'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'japona-azul-aeronautica',                    'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'sobretudo-masculino-azul-aeronautica',       'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'cachecol-branco',                            'facultativo', 17, null),
		('masculino', null, 'sargentos', 'luva-de-la-preta',                           'facultativo', 18, 'preta'),
		('masculino', null, 'sargentos', 'jaleco-branco',                              'eventual',    20, 'branco'),
		('masculino', null, 'sargentos', 'cinturao-preto',                             'eventual',    21, 'preto'),
		('masculino', null, 'sargentos', 'porta-pistola-preto',                        'eventual',    22, 'preto'),
		('masculino', null, 'sargentos', 'colete-especial-para-atividades-de-foto-e-filmagem-azul-aeronautica','eventual', 23, 'azul-aeronáutica (oficiais, suboficiais e sargentos)'),
		('masculino', null, 'alunos', 'quepe-masculino',                               'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'alunos', 'camisas-masculinas-azuis-claras-de-mangas-curtas','obrigatorio', 1,  'azul-clara, de mangas curtas, com passantes (oficiais, suboficiais, cadetes e alunos dos centros de formação ou de adaptação de oficiais)'),
		('masculino', null, 'alunos', 'camiseta-branca',                               'obrigatorio', 2,  'branca'),
		('masculino', null, 'alunos', 'calca-masculina-azul-aeronautica',              'obrigatorio', 3,  null),
		('masculino', null, 'alunos', 'cinto-azul-aeronautica-branco-ou-preto',        'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'alunos', 'sapato-masculino-preto-tipo-2',                 'obrigatorio', 5,  'preto'),
		('masculino', null, 'alunos', 'meia-preta-branca-de-nylon',                    'obrigatorio', 6,  'preta'),
		('masculino', null, 'alunos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'alunos', 'colete-azul-aeronautica-com-gola-em-v',         'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'alunos', 'pulover-azul-aeronautica',                      'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'capa-de-chuva-azul-aeronautica',                'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'japona-azul-aeronautica',                       'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'sobretudo-masculino-azul-aeronautica',          'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'cachecol-branco',                               'facultativo', 17, null),
		('masculino', null, 'alunos', 'luva-de-la-preta',                              'facultativo', 18, 'preta'),
		('masculino', null, 'alunos', 'jaleco-branco',                                 'eventual',    20, 'branco'),
		('masculino', null, 'alunos', 'cinturao-preto',                                'eventual',    21, 'preto'),
		('masculino', null, 'alunos', 'porta-pistola-preto',                           'eventual',    22, 'preto')
)
insert into rumaer.uniform_variant_piece (variant_id, piece_id, obrigatoriedade, observacao, ordem)
select uv.id, p.id, c.nivel::rumaer.obrigatoriedade, c.obs, c.ordem
from comp c
join rumaer.uniform u on u.numero = 7 and u.letra = 'A' and u.deleted_at is null
join rumaer.uniform_variant uv
	on uv.uniform_id = u.id
	and uv.circulo = c.circulo::rumaer.circulo_hierarquico
	and uv.genero = c.genero::rumaer.genero
	and uv.sub_variacao is not distinct from c.subvar
join rumaer.piece p on p.slug = c.slug and p.deleted_at is null
where not exists (
	select 1 from rumaer.uniform_variant_piece x where x.variant_id = uv.id and x.piece_id = p.id
);
