-- Cria e preenche o "6º Uniforme A" (Art. 25 do RUMAER), traje de passeio — grupo representacao.
-- Variantes: feminino (oficiais, cadetes, suboficiais, sargentos, alunos), gestante (oficiais, suboficiais,
-- sargentos), masculino (mesmos círculos do feminino).
-- Nota: aqui os PASSANTES da camisa azul-clara vão para CADETES e ALUNOS dos centros de formação/adaptação
-- (oficiais, suboficiais, sargentos e alunos da EEAR usam camisa sem passantes) — registrado na observação.
-- Peça nova: japona azul-aeronáutica.
-- Idempotente; casa variante por (círculo, gênero, sub_variação) e peça por slug.

insert into rumaer.piece (codigo, nome, slug, tipo) values
	(null, 'japona azul-aeronáutica', 'japona-azul-aeronautica', 'torso')
on conflict (slug) do update set
	nome = excluded.nome, tipo = coalesce(excluded.tipo, rumaer.piece.tipo), deleted_at = null, updated_at = now();

do $$
declare
	u_id uuid;
begin
	select id into u_id from rumaer.uniform where numero = 6 and letra = 'A' and deleted_at is null limit 1;

	if u_id is null then
		insert into rumaer.uniform (numero, letra, nome, grupo, subgrupo, traje, art_referencia, ordem, descricao_md)
		values (6, 'A', '6º Uniforme A', 'representacao', 'passeio', 'passeio', 'Art. 25', 110,
			'6º Uniforme "A", correspondente ao traje de passeio.')
		returning id into u_id;

		insert into rumaer.uniform_category (uniform_id, categoria) values
			(u_id, 'oficiais'), (u_id, 'cadetes'), (u_id, 'suboficiais'),
			(u_id, 'sargentos'), (u_id, 'alunos_formacao')
		on conflict (uniform_id, categoria) do nothing;

		insert into rumaer.uniform_variant (uniform_id, circulo, genero, sub_variacao, ordem) values
			(u_id, 'oficiais',    'feminino',  null,       0),
			(u_id, 'cadetes',     'feminino',  null,       1),
			(u_id, 'suboficiais', 'feminino',  null,       2),
			(u_id, 'sargentos',   'feminino',  null,       3),
			(u_id, 'alunos',      'feminino',  null,       4),
			(u_id, 'oficiais',    'feminino',  'gestante', 5),
			(u_id, 'suboficiais', 'feminino',  'gestante', 6),
			(u_id, 'sargentos',   'feminino',  'gestante', 7),
			(u_id, 'oficiais',    'masculino', null,       8),
			(u_id, 'cadetes',     'masculino', null,       9),
			(u_id, 'suboficiais', 'masculino', null,       10),
			(u_id, 'sargentos',   'masculino', null,       11),
			(u_id, 'alunos',      'masculino', null,       12)
		on conflict (uniform_id, circulo, genero, sub_variacao) do nothing;
	end if;
end $$;

with comp(genero, subvar, circulo, slug, nivel, ordem, obs) as (
	values
		-- ===================== FEMININO ===================== (passantes na camisa: cadetes e alunos)
		('feminino', null, 'oficiais', 'quepe-feminino',                               'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'camisa-feminina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas'),
		('feminino', null, 'oficiais', 'gravata-feminina-preta',                       'obrigatorio', 2,  null),
		('feminino', null, 'oficiais', 'saia-azul-aeronautica',                        'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'oficiais', 'calca-feminina-azul-aeronautica',              'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'oficiais', 'cinto-azul-aeronautica-branco-ou-preto',       'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'oficiais', 'sapato-feminino-de-salto-medio-tipo-2',        'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'oficiais', 'meia-calca-social-lisa',                       'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'oficiais', 'meia-preta-branca-de-nylon',                   'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'oficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'oficiais', 'colete-azul-aeronautica-com-gola-em-v',        'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'oficiais', 'pulover-azul-aeronautica',                     'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'capa-de-chuva-azul-aeronautica',               'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'japona-azul-aeronautica',                      'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'sobretudo-feminino-azul-aeronautica',          'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'oficiais', 'cachecol-branco',                              'facultativo', 17, null),
		('feminino', null, 'oficiais', 'luva-de-la-preta',                             'facultativo', 18, 'preta'),
		('feminino', null, 'oficiais', 'jaleco-branco',                                'eventual',    20, 'branco'),
		('feminino', null, 'oficiais', 'cinturao-preto',                               'eventual',    21, 'preto'),
		('feminino', null, 'oficiais', 'porta-pistola-preto',                          'eventual',    22, 'preto'),
		('feminino', null, 'cadetes', 'quepe-feminino',                                'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'camisa-feminina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas, com passantes (cadetes e alunas dos centros de formação ou de adaptação de oficiais)'),
		('feminino', null, 'cadetes', 'gravata-feminina-preta',                        'obrigatorio', 2,  null),
		('feminino', null, 'cadetes', 'saia-azul-aeronautica',                         'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'cadetes', 'calca-feminina-azul-aeronautica',               'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'cadetes', 'cinto-azul-aeronautica-branco-ou-preto',        'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'cadetes', 'sapato-feminino-de-salto-medio-tipo-2',         'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'cadetes', 'meia-calca-social-lisa',                        'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'cadetes', 'meia-preta-branca-de-nylon',                    'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'cadetes', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'cadetes', 'colete-azul-aeronautica-com-gola-em-v',         'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'cadetes', 'pulover-azul-aeronautica',                      'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'capa-de-chuva-azul-aeronautica',                'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'japona-azul-aeronautica',                       'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'sobretudo-feminino-azul-aeronautica',           'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'cadetes', 'cachecol-branco',                               'facultativo', 17, null),
		('feminino', null, 'cadetes', 'luva-de-la-preta',                              'facultativo', 18, 'preta'),
		('feminino', null, 'cadetes', 'jaleco-branco',                                 'eventual',    20, 'branco'),
		('feminino', null, 'cadetes', 'cinturao-preto',                                'eventual',    21, 'preto'),
		('feminino', null, 'cadetes', 'porta-pistola-preto',                           'eventual',    22, 'preto'),
		('feminino', null, 'suboficiais', 'quepe-feminino',                            'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'camisa-feminina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas'),
		('feminino', null, 'suboficiais', 'gravata-feminina-preta',                    'obrigatorio', 2,  null),
		('feminino', null, 'suboficiais', 'saia-azul-aeronautica',                     'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'calca-feminina-azul-aeronautica',           'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'cinto-azul-aeronautica-branco-ou-preto',    'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'suboficiais', 'sapato-feminino-de-salto-medio-tipo-2',     'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'suboficiais', 'meia-calca-social-lisa',                    'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'suboficiais', 'meia-preta-branca-de-nylon',                'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'suboficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'suboficiais', 'colete-azul-aeronautica-com-gola-em-v',     'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'suboficiais', 'pulover-azul-aeronautica',                  'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'capa-de-chuva-azul-aeronautica',            'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'japona-azul-aeronautica',                   'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'sobretudo-feminino-azul-aeronautica',       'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'suboficiais', 'cachecol-branco',                           'facultativo', 17, null),
		('feminino', null, 'suboficiais', 'luva-de-la-preta',                          'facultativo', 18, 'preta'),
		('feminino', null, 'suboficiais', 'jaleco-branco',                             'eventual',    20, 'branco'),
		('feminino', null, 'suboficiais', 'cinturao-preto',                            'eventual',    21, 'preto'),
		('feminino', null, 'suboficiais', 'porta-pistola-preto',                       'eventual',    22, 'preto'),
		('feminino', null, 'sargentos', 'quepe-feminino',                              'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'camisa-feminina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas'),
		('feminino', null, 'sargentos', 'gravata-feminina-preta',                      'obrigatorio', 2,  null),
		('feminino', null, 'sargentos', 'saia-azul-aeronautica',                       'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'sargentos', 'calca-feminina-azul-aeronautica',             'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'sargentos', 'cinto-azul-aeronautica-branco-ou-preto',      'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'sargentos', 'sapato-feminino-de-salto-medio-tipo-2',       'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'sargentos', 'meia-calca-social-lisa',                      'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'sargentos', 'meia-preta-branca-de-nylon',                  'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'sargentos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'sargentos', 'colete-azul-aeronautica-com-gola-em-v',       'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'sargentos', 'pulover-azul-aeronautica',                    'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'capa-de-chuva-azul-aeronautica',              'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'japona-azul-aeronautica',                     'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'sobretudo-feminino-azul-aeronautica',         'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'sargentos', 'cachecol-branco',                             'facultativo', 17, null),
		('feminino', null, 'sargentos', 'luva-de-la-preta',                            'facultativo', 18, 'preta'),
		('feminino', null, 'sargentos', 'jaleco-branco',                               'eventual',    20, 'branco'),
		('feminino', null, 'sargentos', 'cinturao-preto',                              'eventual',    21, 'preto'),
		('feminino', null, 'sargentos', 'porta-pistola-preto',                         'eventual',    22, 'preto'),
		('feminino', null, 'alunos', 'quepe-feminino',                                 'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', null, 'alunos', 'camisa-feminina-azul-clara-de-mangas-compridas', 'obrigatorio', 1,  'azul-clara, de mangas compridas, com passantes (cadetes e alunas dos centros de formação ou de adaptação de oficiais)'),
		('feminino', null, 'alunos', 'gravata-feminina-preta',                         'obrigatorio', 2,  null),
		('feminino', null, 'alunos', 'saia-azul-aeronautica',                          'obrigatorio', 3,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'alunos', 'calca-feminina-azul-aeronautica',                'obrigatorio', 4,  'saia ou calça, azul-aeronáutica'),
		('feminino', null, 'alunos', 'cinto-azul-aeronautica-branco-ou-preto',         'obrigatorio', 5,  'azul-aeronáutica, com fivela prateada'),
		('feminino', null, 'alunos', 'sapato-feminino-de-salto-medio-tipo-2',          'obrigatorio', 6,  'preto, salto médio'),
		('feminino', null, 'alunos', 'meia-calca-social-lisa',                         'obrigatorio', 7,  'cor da pele (quando usando saia)'),
		('feminino', null, 'alunos', 'meia-preta-branca-de-nylon',                     'obrigatorio', 8,  'preta (quando usando calça)'),
		('feminino', null, 'alunos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', null, 'alunos', 'colete-azul-aeronautica-com-gola-em-v',          'facultativo', 11, 'gola em "V"'),
		('feminino', null, 'alunos', 'pulover-azul-aeronautica',                       'facultativo', 12, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'capa-de-chuva-azul-aeronautica',                 'facultativo', 14, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'japona-azul-aeronautica',                        'facultativo', 15, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'sobretudo-feminino-azul-aeronautica',            'facultativo', 16, 'azul-aeronáutica'),
		('feminino', null, 'alunos', 'cachecol-branco',                                'facultativo', 17, null),
		('feminino', null, 'alunos', 'luva-de-la-preta',                               'facultativo', 18, 'preta'),
		('feminino', null, 'alunos', 'jaleco-branco',                                  'eventual',    20, 'branco'),
		('feminino', null, 'alunos', 'cinturao-preto',                                 'eventual',    21, 'preto'),
		('feminino', null, 'alunos', 'porta-pistola-preto',                            'eventual',    22, 'preto'),

		-- ===================== GESTANTE =====================
		('feminino', 'gestante', 'oficiais', 'quepe-feminino',                         'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'vestido-azul-aeronautica-para-gestante', 'obrigatorio', 1,  'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'camisa-feminina-azul-clara-de-mangas-compridas','obrigatorio', 2,  'ou bata azul-clara'),
		('feminino', 'gestante', 'oficiais', 'gravata-feminina-preta',                 'obrigatorio', 3,  null),
		('feminino', 'gestante', 'oficiais', 'calca-azul-aeronautica-para-gestante',   'obrigatorio', 4,  'azul-aeronáutica (utilizada em conjunto com a bata)'),
		('feminino', 'gestante', 'oficiais', 'sapato-feminino-de-salto-medio-tipo-2',  'obrigatorio', 5,  'preto (salto médio, baixo ou sem salto)'),
		('feminino', 'gestante', 'oficiais', 'meia-calca-social-lisa',                 'obrigatorio', 6,  'cor da pele (autorizado meia especial; ou meia preta quando usando calça)'),
		('feminino', 'gestante', 'oficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', 'gestante', 'oficiais', 'colete-azul-aeronautica-com-gola-em-v',  'facultativo', 11, 'gola em "V"'),
		('feminino', 'gestante', 'oficiais', 'pulover-azul-aeronautica',               'facultativo', 12, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'capa-de-chuva-azul-aeronautica',         'facultativo', 14, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'japona-azul-aeronautica',                'facultativo', 15, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'sobretudo-feminino-azul-aeronautica',    'facultativo', 16, 'azul-aeronáutica'),
		('feminino', 'gestante', 'oficiais', 'cachecol-branco',                        'facultativo', 17, null),
		('feminino', 'gestante', 'oficiais', 'luva-de-la-preta',                       'facultativo', 18, 'preta'),
		('feminino', 'gestante', 'oficiais', 'jaleco-branco',                          'eventual',    20, 'branco'),
		('feminino', 'gestante', 'suboficiais', 'quepe-feminino',                      'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'vestido-azul-aeronautica-para-gestante','obrigatorio', 1,  'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'camisa-feminina-azul-clara-de-mangas-compridas','obrigatorio', 2,  'ou bata azul-clara'),
		('feminino', 'gestante', 'suboficiais', 'gravata-feminina-preta',              'obrigatorio', 3,  null),
		('feminino', 'gestante', 'suboficiais', 'calca-azul-aeronautica-para-gestante','obrigatorio', 4,  'azul-aeronáutica (utilizada em conjunto com a bata)'),
		('feminino', 'gestante', 'suboficiais', 'sapato-feminino-de-salto-medio-tipo-2','obrigatorio', 5,  'preto (salto médio, baixo ou sem salto)'),
		('feminino', 'gestante', 'suboficiais', 'meia-calca-social-lisa',              'obrigatorio', 6,  'cor da pele (autorizado meia especial; ou meia preta quando usando calça)'),
		('feminino', 'gestante', 'suboficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', 'gestante', 'suboficiais', 'colete-azul-aeronautica-com-gola-em-v','facultativo', 11, 'gola em "V"'),
		('feminino', 'gestante', 'suboficiais', 'pulover-azul-aeronautica',            'facultativo', 12, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'capa-de-chuva-azul-aeronautica',      'facultativo', 14, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'japona-azul-aeronautica',             'facultativo', 15, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'sobretudo-feminino-azul-aeronautica', 'facultativo', 16, 'azul-aeronáutica'),
		('feminino', 'gestante', 'suboficiais', 'cachecol-branco',                     'facultativo', 17, null),
		('feminino', 'gestante', 'suboficiais', 'luva-de-la-preta',                    'facultativo', 18, 'preta'),
		('feminino', 'gestante', 'suboficiais', 'jaleco-branco',                       'eventual',    20, 'branco'),
		('feminino', 'gestante', 'sargentos', 'quepe-feminino',                        'obrigatorio', 0,  'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'vestido-azul-aeronautica-para-gestante','obrigatorio', 1,  'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'camisa-feminina-azul-clara-de-mangas-compridas','obrigatorio', 2,  'ou bata azul-clara'),
		('feminino', 'gestante', 'sargentos', 'gravata-feminina-preta',                'obrigatorio', 3,  null),
		('feminino', 'gestante', 'sargentos', 'calca-azul-aeronautica-para-gestante',  'obrigatorio', 4,  'azul-aeronáutica (utilizada em conjunto com a bata)'),
		('feminino', 'gestante', 'sargentos', 'sapato-feminino-de-salto-medio-tipo-2', 'obrigatorio', 5,  'preto (salto médio, baixo ou sem salto)'),
		('feminino', 'gestante', 'sargentos', 'meia-calca-social-lisa',                'obrigatorio', 6,  'cor da pele (autorizado meia especial; ou meia preta quando usando calça)'),
		('feminino', 'gestante', 'sargentos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('feminino', 'gestante', 'sargentos', 'colete-azul-aeronautica-com-gola-em-v', 'facultativo', 11, 'gola em "V"'),
		('feminino', 'gestante', 'sargentos', 'pulover-azul-aeronautica',              'facultativo', 12, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'jaqueta-feminina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'capa-de-chuva-azul-aeronautica',        'facultativo', 14, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'japona-azul-aeronautica',               'facultativo', 15, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'sobretudo-feminino-azul-aeronautica',   'facultativo', 16, 'azul-aeronáutica'),
		('feminino', 'gestante', 'sargentos', 'cachecol-branco',                       'facultativo', 17, null),
		('feminino', 'gestante', 'sargentos', 'luva-de-la-preta',                      'facultativo', 18, 'preta'),
		('feminino', 'gestante', 'sargentos', 'jaleco-branco',                         'eventual',    20, 'branco'),

		-- ===================== MASCULINO ===================== (passantes na camisa: cadetes e alunos)
		('masculino', null, 'oficiais', 'quepe-masculino',                             'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'camisa-masculina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas'),
		('masculino', null, 'oficiais', 'gravata-vertical-preta',                      'obrigatorio', 2,  'vertical'),
		('masculino', null, 'oficiais', 'calca-masculina-azul-aeronautica',            'obrigatorio', 3,  null),
		('masculino', null, 'oficiais', 'cinto-azul-aeronautica-branco-ou-preto',      'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'oficiais', 'sapato-masculino-preto-tipo-2',               'obrigatorio', 5,  'preto'),
		('masculino', null, 'oficiais', 'meia-preta-branca-de-nylon',                  'obrigatorio', 6,  'preta'),
		('masculino', null, 'oficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'oficiais', 'colete-azul-aeronautica-com-gola-em-v',       'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'oficiais', 'pulover-azul-aeronautica',                    'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'capa-de-chuva-azul-aeronautica',              'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'japona-azul-aeronautica',                     'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'sobretudo-masculino-azul-aeronautica',        'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'oficiais', 'cachecol-branco',                             'facultativo', 17, null),
		('masculino', null, 'oficiais', 'luva-de-la-preta',                            'facultativo', 18, 'preta'),
		('masculino', null, 'oficiais', 'jaleco-branco',                               'eventual',    20, 'branco'),
		('masculino', null, 'oficiais', 'cinturao-preto',                              'eventual',    21, 'preto'),
		('masculino', null, 'oficiais', 'porta-pistola-preto',                         'eventual',    22, 'preto'),
		('masculino', null, 'cadetes', 'quepe-masculino',                              'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'camisa-masculina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas, com passantes (cadetes e alunos dos centros de formação ou de adaptação de oficiais)'),
		('masculino', null, 'cadetes', 'gravata-vertical-preta',                       'obrigatorio', 2,  'vertical'),
		('masculino', null, 'cadetes', 'calca-masculina-azul-aeronautica',             'obrigatorio', 3,  null),
		('masculino', null, 'cadetes', 'cinto-azul-aeronautica-branco-ou-preto',       'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'cadetes', 'sapato-masculino-preto-tipo-2',                'obrigatorio', 5,  'preto'),
		('masculino', null, 'cadetes', 'meia-preta-branca-de-nylon',                   'obrigatorio', 6,  'preta'),
		('masculino', null, 'cadetes', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'cadetes', 'colete-azul-aeronautica-com-gola-em-v',        'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'cadetes', 'pulover-azul-aeronautica',                     'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'capa-de-chuva-azul-aeronautica',               'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'japona-azul-aeronautica',                      'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'sobretudo-masculino-azul-aeronautica',         'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'cadetes', 'cachecol-branco',                              'facultativo', 17, null),
		('masculino', null, 'cadetes', 'luva-de-la-preta',                             'facultativo', 18, 'preta'),
		('masculino', null, 'cadetes', 'jaleco-branco',                                'eventual',    20, 'branco'),
		('masculino', null, 'cadetes', 'cinturao-preto',                               'eventual',    21, 'preto'),
		('masculino', null, 'cadetes', 'porta-pistola-preto',                          'eventual',    22, 'preto'),
		('masculino', null, 'suboficiais', 'quepe-masculino',                          'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'camisa-masculina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas'),
		('masculino', null, 'suboficiais', 'gravata-vertical-preta',                   'obrigatorio', 2,  'vertical'),
		('masculino', null, 'suboficiais', 'calca-masculina-azul-aeronautica',         'obrigatorio', 3,  null),
		('masculino', null, 'suboficiais', 'cinto-azul-aeronautica-branco-ou-preto',   'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'suboficiais', 'sapato-masculino-preto-tipo-2',            'obrigatorio', 5,  'preto'),
		('masculino', null, 'suboficiais', 'meia-preta-branca-de-nylon',               'obrigatorio', 6,  'preta'),
		('masculino', null, 'suboficiais', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'suboficiais', 'colete-azul-aeronautica-com-gola-em-v',    'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'suboficiais', 'pulover-azul-aeronautica',                 'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'capa-de-chuva-azul-aeronautica',           'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'japona-azul-aeronautica',                  'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'sobretudo-masculino-azul-aeronautica',     'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'suboficiais', 'cachecol-branco',                          'facultativo', 17, null),
		('masculino', null, 'suboficiais', 'luva-de-la-preta',                         'facultativo', 18, 'preta'),
		('masculino', null, 'suboficiais', 'jaleco-branco',                            'eventual',    20, 'branco'),
		('masculino', null, 'suboficiais', 'cinturao-preto',                           'eventual',    21, 'preto'),
		('masculino', null, 'suboficiais', 'porta-pistola-preto',                      'eventual',    22, 'preto'),
		('masculino', null, 'sargentos', 'quepe-masculino',                            'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'camisa-masculina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas'),
		('masculino', null, 'sargentos', 'gravata-vertical-preta',                     'obrigatorio', 2,  'vertical'),
		('masculino', null, 'sargentos', 'calca-masculina-azul-aeronautica',           'obrigatorio', 3,  null),
		('masculino', null, 'sargentos', 'cinto-azul-aeronautica-branco-ou-preto',     'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'sargentos', 'sapato-masculino-preto-tipo-2',              'obrigatorio', 5,  'preto'),
		('masculino', null, 'sargentos', 'meia-preta-branca-de-nylon',                 'obrigatorio', 6,  'preta'),
		('masculino', null, 'sargentos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'sargentos', 'colete-azul-aeronautica-com-gola-em-v',      'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'sargentos', 'pulover-azul-aeronautica',                   'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'capa-de-chuva-azul-aeronautica',             'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'japona-azul-aeronautica',                    'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'sobretudo-masculino-azul-aeronautica',       'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'sargentos', 'cachecol-branco',                            'facultativo', 17, null),
		('masculino', null, 'sargentos', 'luva-de-la-preta',                           'facultativo', 18, 'preta'),
		('masculino', null, 'sargentos', 'jaleco-branco',                              'eventual',    20, 'branco'),
		('masculino', null, 'sargentos', 'cinturao-preto',                             'eventual',    21, 'preto'),
		('masculino', null, 'sargentos', 'porta-pistola-preto',                        'eventual',    22, 'preto'),
		('masculino', null, 'alunos', 'quepe-masculino',                               'obrigatorio', 0,  'azul-aeronáutica'),
		('masculino', null, 'alunos', 'camisa-masculina-azul-clara-de-mangas-compridas','obrigatorio', 1,  'azul-clara, de mangas compridas, com passantes (cadetes e alunos dos centros de formação ou de adaptação de oficiais)'),
		('masculino', null, 'alunos', 'gravata-vertical-preta',                        'obrigatorio', 2,  'vertical'),
		('masculino', null, 'alunos', 'calca-masculina-azul-aeronautica',              'obrigatorio', 3,  null),
		('masculino', null, 'alunos', 'cinto-azul-aeronautica-branco-ou-preto',        'obrigatorio', 4,  'azul-aeronáutica, com fivela prateada'),
		('masculino', null, 'alunos', 'sapato-masculino-preto-tipo-2',                 'obrigatorio', 5,  'preto'),
		('masculino', null, 'alunos', 'meia-preta-branca-de-nylon',                    'obrigatorio', 6,  'preta'),
		('masculino', null, 'alunos', 'camisa-branca-flanelada-de-mangas-compridas-2-pele','facultativo', 10, '2ª pele branca'),
		('masculino', null, 'alunos', 'colete-azul-aeronautica-com-gola-em-v',         'facultativo', 11, 'gola em "V"'),
		('masculino', null, 'alunos', 'pulover-azul-aeronautica',                      'facultativo', 12, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'jaqueta-masculina-azul-aeronautica-com-forro-removivel','facultativo', 13, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'capa-de-chuva-azul-aeronautica',                'facultativo', 14, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'japona-azul-aeronautica',                       'facultativo', 15, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'sobretudo-masculino-azul-aeronautica',          'facultativo', 16, 'azul-aeronáutica'),
		('masculino', null, 'alunos', 'cachecol-branco',                               'facultativo', 17, null),
		('masculino', null, 'alunos', 'luva-de-la-preta',                              'facultativo', 18, 'preta'),
		('masculino', null, 'alunos', 'jaleco-branco',                                 'eventual',    20, 'branco'),
		('masculino', null, 'alunos', 'cinturao-preto',                                'eventual',    21, 'preto'),
		('masculino', null, 'alunos', 'porta-pistola-preto',                           'eventual',    22, 'preto')
)
insert into rumaer.uniform_variant_piece (variant_id, piece_id, obrigatoriedade, observacao, ordem)
select uv.id, p.id, c.nivel::rumaer.obrigatoriedade, c.obs, c.ordem
from comp c
join rumaer.uniform u on u.numero = 6 and u.letra = 'A' and u.deleted_at is null
join rumaer.uniform_variant uv
	on uv.uniform_id = u.id
	and uv.circulo = c.circulo::rumaer.circulo_hierarquico
	and uv.genero = c.genero::rumaer.genero
	and uv.sub_variacao is not distinct from c.subvar
join rumaer.piece p on p.slug = c.slug and p.deleted_at is null
where not exists (
	select 1 from rumaer.uniform_variant_piece x where x.variant_id = uv.id and x.piece_id = p.id
);
