export const modulesData = {
	"3.1": {
		title: "SUCONT-3.1 — Seção de Acompanhamento Contábil",
		items: [
			{
				id: "q43",
				name: "Cruzamento de Contas Correntes de Cobrança (Q43)",
				purpose: "Analisar e cruzar dados de contas correntes de cobrança para identificar divergências.",
				examples: ["Analisar Q43", "Verificar divergências de cobrança", "Gerar relatório de contas correntes"],
				url: "https://cruzamentoscontas.sucont3-2sau.workers.dev/",
				group: "Analistas SUCONT - Análises automatizadas do RAC",
			},
			{
				id: "q26_36",
				name: "Monitoramento de Contas de Saldo Transitório (Q26, Q27, Q28, Q31, Q32, Q36)",
				purpose: "Acompanhar contas com saldos transitórios e identificar pendências de regularização.",
				examples: ["Listar contas transitórias", "Verificar Q26", "Analisar pendências Q31"],
				url: "https://analistasaldosimproprios.sucont3-2sau.workers.dev/",
				group: "Analistas SUCONT - Análises automatizadas do RAC",
			},
			{
				id: "q05_25",
				name: "Monitoramento de Saldos Alongados (Q05 a Q25)",
				purpose: "Monitorar saldos que permanecem alongados e exigem providências das Unidades Gestoras.",
				examples: ["Analisar saldos alongados", "Consultar Q05", "Relatório de envelhecimento de saldos"],
				url: "https://analistasaldoalongado.sucont3-2sau.workers.dev/",
				group: "Analistas SUCONT - Análises automatizadas do RAC",
			},
			{
				id: "q34",
				name: "Uso de Subitens Genéricos (Q34)",
				purpose: "Identificar o uso de subitens genéricos nas apropriações contábeis.",
				examples: ["Verificar Q34", "Listar subitens genéricos", "Analisar apropriações indevidas"],
				url: "https://ai.studio/apps/ae41b970-96e8-47ea-ae35-827fa1eb96dd",
				group: "Analistas SUCONT - Análises automatizadas do RAC",
			},
			{
				id: "q40_42",
				name: "Compatibilidade entre Contas (Q40, Q41, Q42)",
				purpose: "Verificar a compatibilidade entre contas contábeis e identificar lançamentos atípicos.",
				examples: ["Analisar compatibilidade", "Consultar Q40", "Verificar lançamentos atípicos"],
				url: "https://analistacompatibilidade.sucont3-2sau.workers.dev/",
				group: "Analistas SUCONT - Análises automatizadas do RAC",
			},
			{
				id: "q35",
				name: "Uso de Contas Contábeis Genéricas (Q35)",
				purpose: "Identificar e analisar o uso indevido de contas contábeis genéricas no COMAER, com base no RAC.",
				examples: ["Mostrar inconsistências", "Mostrar minhas UGs", "Cobrar apenas a questão RAC", "Gerar análise gerencial"],
				url: "https://analistacontagenerica.sucont3-2sau.workers.dev/",
				group: "Analistas SUCONT - Análises automatizadas do RAC",
			},
			{
				id: "tesouro_gerencial_folder",
				name: "Pasta do Tesouro Gerencial (Bases de Dados)",
				purpose: "Acesso às planilhas e bases de dados do Tesouro Gerencial que alimentam as análises automatizadas.",
				examples: ["Acessar bases de dados", "Abrir Tesouro Gerencial", "Consultar planilhas fonte"],
				url: "http://tesourogerencial.tesouro.gov.br:80/tg/servlet/mstrWeb?evt=2001&src=mstrWeb.my.fbb.fb.2001&folderID=D160BEED25417B4E30D137B91E98FFA6&Server=161.148.236.206&Project=TESOURO%20GERENCIAL&Port=0&share=1",
				group: "Analistas SUCONT - Análises automatizadas do RAC",
				highlighted: true,
			},
			{
				id: "num_msg_siafi",
				name: "Numerador de Mensagens SIAFI",
				purpose: "Controle de numeração das mensagens SIAFI enviadas pela SUCONT-3.",
				examples: ["Acessar numerador", "Ver mensagens enviadas"],
				url: "https://docs.google.com/spreadsheets/d/1Da90YGWy-zh9gQ4mkS-5fWMv9ERLfNI0FwIlNYshoRI/edit?gid=2086084205#gid=2086084205",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
			{
				id: "lista_ug",
				name: "Lista de UGs e Conferentes",
				purpose: "Relação de Unidades Gestoras do COMAER e seus respectivos conferentes.",
				examples: ["Consultar conferente", "Ver lista de UGs"],
				url: "https://docs.google.com/spreadsheets/d/1FyugNRl3qnhIUBuYSx0ZzvMPyvcSnnxS/edit?gid=1729024649#gid=1729024649",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
			{
				id: "conf_diaria",
				name: "Conferência Diária SUCONT-3.1",
				purpose: "Documento de registro da conferência diária realizada no âmbito da SUCONT-3.1.",
				examples: ["Acessar conferência diária", "Verificar pendências do dia"],
				url: "https://docs.google.com/document/d/1UBJX2s08dVZDiAupNvJ3715rzw2Fuuqrkg1Enp9SaNU/edit?tab=t.0",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
			{
				id: "planilha_rac",
				name: "Planilha de Registros RAC",
				purpose: "Registro mensal do Roteiro de Acompanhamento Contábil (RAC) pelos operadores.",
				examples: ["Acessar RAC", "Registrar acompanhamento"],
				url: "https://docs.google.com/spreadsheets/d/1kiZx2qO9GvhU8WaFk4FnBQynD4Z9Ik-Aekms2DWaWx0/edit?gid=450899566#gid=450899566",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
			{
				id: "form_rac",
				name: "Formulário RAC (Referencial Teórico)",
				purpose: "Referencial teórico para o RAC mensal e apuração do Grau de Performance Contábil.",
				examples: ["Consultar referencial RAC", "Verificar critérios de performance"],
				url: "https://docs.google.com/spreadsheets/d/15piwHeQwwxApQy79HSL53osBwqiYy0usDeYcJVWtXEM/edit?gid=1946125470#gid=1946125470",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
			{
				id: "restricoes_contabeis",
				name: "Planilha de Restrições Contábeis",
				purpose: "Registro mensal das restrições a nível UG do COMAER pelos conferentes.",
				examples: ["Acessar restrições", "Registrar restrição UG"],
				url: "https://docs.google.com/spreadsheets/d/1sZpDIwZFJfa1vMmgdrjhrJ3FdxLQxY4RIw53Y_sus8M/edit?gid=239324724#gid=239324724",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
			{
				id: "conciliacao_spiunet",
				name: "Conciliação SPIUNET x SIAFI",
				purpose: "Conciliação entre a Gestão Analítica (SPIUNET) e Sintética (SIAFI) dos Imóveis.",
				examples: ["Acessar conciliação de imóveis", "Verificar divergências SPIUNET"],
				url: "https://docs.google.com/spreadsheets/d/1kMUsy4wCC2fnB9Rt-P2pRAQ23ITqNXah/edit?gid=1809425722#gid=1809425722",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
			{
				id: "acomp_mensal",
				name: "Acompanhamento Mensal SUCONT-3",
				purpose: "Planilha geral de acompanhamento mensal das atividades da SUCONT-3.",
				examples: ["Acessar acompanhamento mensal", "Verificar status mensal"],
				url: "https://docs.google.com/spreadsheets/d/1RwSaV5ue_YkLdSTZIuV9iSiMsmPzBONKKpXxzelLhIU/edit?gid=2046313248#gid=2046313248",
				group: "Documentos de Trabalho da SUCONT-3.1",
			},
		],
	},
	"3.2": {
		title: "SUCONT-3.2 — Seção de Suporte ao Usuário",
		items: [
			{
				id: "restos",
				name: "Gestão de Restos a Pagar no COMAER",
				purpose: "Dar suporte na inscrição, bloqueio, desbloqueio e cancelamento de Restos a Pagar.",
				examples: ["Problema de restos a pagar", "Como cancelar RP?", "Dúvida sobre bloqueio de RP"],
				url: "https://notebooklm.google.com/notebook/f898cbe7-2f0d-42de-9deb-0798b8a4d97d?authuser=5",
				group: "Oráculos SUCONT - Chatbots para Suporte aos Militares da SUCONT-3",
			},
			{
				id: "sucont4",
				name: "Execução Patrimonial (SUCONT-4 — Módulo 7)",
				purpose: "Integração para direcionamento de demandas patrimoniais, depreciação, reavaliação e alienação.",
				examples: ["Problema patrimonial", "Dúvida sobre depreciação", "Como registrar baixa de bem?"],
				url: "https://notebooklm.google.com/notebook/69f8cb5d-7656-42b2-91f1-36d998b02a37?addSource=true&authuser=5",
				group: "Oráculos SUCONT - Chatbots para Suporte aos Militares da SUCONT-3",
			},
			{
				id: "siafi",
				name: "Cadastro SIAFI (Usuários e Cadastradores)",
				purpose: "Prestar suporte relacionado ao cadastro de usuários, perfis de acesso e cadastradores no SIAFI.",
				examples: ["Como cadastrar usuário?", "Problema de acesso SIAFI", "Solicitar perfil de acesso"],
				url: "https://notebooklm.google.com/notebook/ccc390f3-9820-46e3-a975-ebe00b109a67?authuser=5",
				group: "Oráculos SUCONT - Chatbots para Suporte aos Militares da SUCONT-3",
			},
			{
				id: "despesa",
				name: "Execução Orçamentária e Financeira da Despesa",
				purpose: "Auxiliar nas dúvidas e problemas durante a execução orçamentária e financeira (empenho, liquidação, pagamento).",
				examples: ["Dúvida sobre empenho", "Erro na liquidação", "Como anular pagamento?"],
				url: "https://notebooklm.google.com/notebook/06d2e4e9-f09a-4ab3-8ab1-6f874cde5f40?authuser=5",
				group: "Oráculos SUCONT - Chatbots para Suporte aos Militares da SUCONT-3",
			},
			{
				id: "pessoal",
				name: "Folha de Pagamento e Despesas com Pessoal",
				purpose: "Prestar suporte para questões contábeis envolvendo a folha de pagamento e despesas com pessoal.",
				examples: ["Inconsistência na folha", "Dúvida sobre rubrica", "Analisar apropriação da folha"],
				url: "https://notebooklm.google.com/notebook/9b1f1cf6-820b-4777-8472-386dc64e7bbc?authuser=5",
				group: "Oráculos SUCONT - Chatbots para Suporte aos Militares da SUCONT-3",
			},
			{
				id: "suprimento",
				name: "Suprimento de Fundos",
				purpose: "Orientar e solucionar problemas relacionados à concessão, aplicação e prestação de contas de suprimento de fundos.",
				examples: ["Como conceder suprimento?", "Dúvida na prestação de contas", "Erro na devolução de saldo"],
				url: "https://notebooklm.google.com/notebook/d13390c4-93a6-48b6-9ebd-82a5047cbc3e?authuser=5",
				group: "Oráculos SUCONT - Chatbots para Suporte aos Militares da SUCONT-3",
			},
			{
				id: "sau_atendimento",
				name: "Sistema de Atendimento de Usuários do COMAER - SAU",
				purpose: "Acessar o Sistema de Atendimento ao Usuário (SAU) para relatar problemas ou solicitar suporte técnico.",
				examples: ["Acessar SAU", "Abrir chamado de suporte"],
				url: "https://is.producao.ccarj.intraer/authenticationendpoint/login.do?RelayState=null&commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=29775690-597d-4ae4-a3d5-213c7cf851d8&relyingParty=loginunico&type=samlsso&sp=loginunico&isSaaSApp=false&authenticators=BasicAuthenticator:LOCAL",
				group: "Sistema de Atendimento",
			},
		],
	},
	geral: {
		title: "Âmbito Geral — Sistemas, Guias e Trilhas",
		items: [
			{
				id: "trilha_acomp",
				name: "Trilha de Acompanhamento Contábil",
				purpose: "Trilha de estudos para os novos membros que estão chegando à SUCONT-3.",
				examples: ["Acessar trilha de estudos", "Material para novatos"],
				url: "https://docs.google.com/document/d/1fiB883OpAKh4uWxYpPeDAiJ9VNKhPonz/edit",
				group: "Guias e Trilhas",
			},
			{
				id: "guia_iniciais",
				name: "Guia de Informações Iniciais",
				purpose: "Guia prático com informações iniciais para novos membros da SUCONT-3.",
				examples: ["Acessar guia de novatos", "Informações iniciais"],
				url: "https://docs.google.com/document/d/1Af-0W4rBb0sN6P9jAQBTylO4i2Xqwb1q/edit",
				group: "Guias e Trilhas",
			},
			{
				id: "sigadaer",
				name: "SIGADAER",
				purpose: "Sistema Informatizado de Gestão Arquivística do COMAER.",
				examples: ["Acessar SIGADAER", "Gestão de documentos"],
				url: "https://app.sigadaer.intraer/",
				group: "Sistemas",
			},
			{
				id: "siscontaer",
				name: "SISCONTAER",
				purpose: "Sistema de Contabilidade do COMAER.",
				examples: ["Acessar SISCONTAER", "Sistema contábil"],
				url: "http://www.siscontaer.intraer/",
				group: "Sistemas",
			},
			{
				id: "sau",
				name: "SAU (Sistema de Atendimento)",
				purpose: "Sistema de Atendimento de Usuários do COMAER.",
				examples: ["Acessar SAU", "Abrir chamado"],
				url: "https://is.producao.ccarj.intraer/authenticationendpoint/login.do?RelayState=null&commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=29775690-597d-4ae4-a3d5-213c7cf851d8&relyingParty=loginunico&type=samlsso&sp=loginunico&isSaaSApp=false&authenticators=BasicAuthenticator:LOCAL",
				group: "Sistemas",
			},
			{
				id: "siafi_site",
				name: "SIAFI (Site Oficial)",
				purpose: "Sistema Integrado de Administração Financeira do Governo Federal.",
				examples: ["Acessar SIAFI web", "Login SIAFI"],
				url: "https://siafi.tesouro.gov.br/",
				group: "Sistemas",
			},
			{
				id: "serpro",
				name: "Rede SERPRO - Cadastro",
				purpose: "Acesso ao cadastro e serviços da Rede SERPRO (HOD).",
				examples: ["Acessar HOD", "Cadastro SERPRO"],
				url: "https://hod.serpro.gov.br/a83016cv/",
				group: "Sistemas",
			},
			{
				id: "tesouro_gerencial",
				name: "Tesouro Gerencial",
				purpose: "Sistema de consultas e relatórios do Tesouro Nacional.",
				examples: ["Acessar TG", "Relatórios do Tesouro"],
				url: "https://tesourogerencial.tesouro.gov.br/",
				group: "Sistemas",
			},
			{
				id: "aec_sefa",
				name: "AEC-SEFA",
				purpose: "Sistema AEC da Secretaria de Economia, Finanças e Administração da Aeronáutica.",
				examples: ["Acessar AEC", "Sistema SEFA"],
				url: "http://aec.sefa.intraer/login.phtml",
				group: "Sistemas",
			},
			{
				id: "zimbra",
				name: "Zimbra (E-mail FAB)",
				purpose: "Correio eletrônico oficial da Força Aérea Brasileira.",
				examples: ["Acessar webmail", "Ler e-mails FAB"],
				url: "https://mail.fab.mil.br/modern/",
				group: "Sistemas",
			},
			{
				id: "sisgru",
				name: "SISGRU (Consulta e Retificações)",
				purpose: "Site do SISGRU para Consulta de RA e Retificações de GRU.",
				examples: ["Acessar SISGRU", "Consultar RA", "Retificar GRU"],
				url: "https://www.sisgru.tesouro.gov.br/sisgru/public/pages/login.jsf",
				group: "Sistemas",
			},
			{
				id: "manuais_siafi",
				name: "Manuais e Macrofunções SIAFI",
				purpose: "Manuais SIAFI e Consulta às Macrofunções SIAFI.",
				examples: ["Consultar manual SIAFI", "Ver macrofunção", "Regras contábeis SIAFI"],
				url: "https://sisweb.tesouro.gov.br/apex/cosis/manuais/siafi",
				group: "Sistemas",
			},
			{
				id: "siafi_homologacao",
				name: "SIAFI Homologação (Testes)",
				purpose: "Site do SIAFI Homologação utilizado para fins de teste.",
				examples: ["Acessar SIAFI Homologação", "Testar no SIAFI", "Ambiente de teste SIAFI"],
				url: "https://homext-siafi.tesouro.gov.br/senha/public/pages/security/login.jsf",
				group: "Sistemas",
			},
			{
				id: "drive_sucont3",
				name: "Pasta da SUCONT-3 (Google Drive)",
				purpose: "Acesso à pasta compartilhada da SUCONT-3 no Google Drive.",
				examples: ["Acessar Drive", "Pasta da SUCONT-3", "Documentos SUCONT-3"],
				url: "https://drive.google.com/drive/u/0/folders/1Yv6q5q62wya2ok3A17IrON1fL2KNsi9i",
				group: "Documentos de Trabalho",
			},
			{
				id: "chatgpt",
				name: "ChatGPT",
				purpose: "Assistente virtual de inteligência artificial da OpenAI.",
				examples: ["Acessar ChatGPT", "IA OpenAI"],
				url: "https://chatgpt.com/",
				group: "Inteligência Artificial (IAs)",
			},
			{
				id: "manus",
				name: "Manus AI",
				purpose: "Plataforma de inteligência artificial Manus.",
				examples: ["Acessar Manus", "IA Manus"],
				url: "https://manus.im/app",
				group: "Inteligência Artificial (IAs)",
			},
			{
				id: "gemini",
				name: "Google Gemini",
				purpose: "Assistente virtual de inteligência artificial do Google.",
				examples: ["Acessar Gemini", "IA Google"],
				url: "https://gemini.google.com/?hl=pt-BR",
				group: "Inteligência Artificial (IAs)",
			},
			{
				id: "grok",
				name: "Grok",
				purpose: "Assistente virtual de inteligência artificial da xAI.",
				examples: ["Acessar Grok", "IA xAI"],
				url: "https://grok.com/",
				group: "Inteligência Artificial (IAs)",
			},
		],
	},
}

export const routingKeywords = [
	{ keywords: ["q43", "cobrança", "contas correntes", "cobranca"], moduleId: "q43", section: "3.1" },
	{ keywords: ["q26", "q27", "q28", "q31", "q32", "q36", "transitório", "transitórias", "transitorio", "transitorias"], moduleId: "q26_36", section: "3.1" },
	{ keywords: ["q05", "q25", "alongados", "alongado"], moduleId: "q05_25", section: "3.1" },
	{ keywords: ["q34", "subitens genéricos", "subitem genérico", "generico", "genericos"], moduleId: "q34", section: "3.1" },
	{ keywords: ["q40", "q41", "q42", "compatibilidade"], moduleId: "q40_42", section: "3.1" },
	{ keywords: ["q35", "contas genéricas", "conta genérica", "genericas", "generica"], moduleId: "q35", section: "3.1" },
	{ keywords: ["siafi", "cadastro", "cadastrador", "usuário", "usuario", "senha"], moduleId: "siafi", section: "3.2" },
	{
		keywords: ["despesa", "orçamentária", "orcamentaria", "financeira", "empenho", "liquidação", "liquidacao", "pagamento"],
		moduleId: "despesa",
		section: "3.2",
	},
	{ keywords: ["folha", "pessoal", "rubrica", "pagamento de pessoal"], moduleId: "pessoal", section: "3.2" },
	{ keywords: ["suprimento", "fundos", "prestação de contas", "prestacao"], moduleId: "suprimento", section: "3.2" },
	{ keywords: ["restos a pagar", "rp", "restos"], moduleId: "restos", section: "3.2" },
	{
		keywords: ["patrimonial", "patrimônio", "patrimonio", "sucont-4", "sucont 4", "módulo 7", "modulo 7", "depreciação", "depreciacao"],
		moduleId: "sucont4",
		section: "3.2",
	},
	{ keywords: ["numerador", "mensagens", "siafi"], moduleId: "num_msg_siafi", section: "3.1" },
	{ keywords: ["lista", "ug", "ugs", "conferentes", "conferente"], moduleId: "lista_ug", section: "3.1" },
	{ keywords: ["conferência", "conferencia", "diária", "diaria"], moduleId: "conf_diaria", section: "3.1" },
	{ keywords: ["planilha", "rac", "registros"], moduleId: "planilha_rac", section: "3.1" },
	{ keywords: ["formulário", "formulario", "rac", "referencial", "teórico", "teorico"], moduleId: "form_rac", section: "3.1" },
	{ keywords: ["restrições", "restricoes", "contábeis", "contabeis"], moduleId: "restricoes_contabeis", section: "3.1" },
	{ keywords: ["conciliação", "conciliacao", "spiunet", "imóveis", "imoveis"], moduleId: "conciliacao_spiunet", section: "3.1" },
	{ keywords: ["acompanhamento", "mensal"], moduleId: "acomp_mensal", section: "3.1" },
	{ keywords: ["trilha", "estudos", "novatos"], moduleId: "trilha_acomp", section: "geral" },
	{ keywords: ["guia", "informações", "iniciais"], moduleId: "guia_iniciais", section: "geral" },
	{ keywords: ["sigadaer", "arquivística", "arquivistica"], moduleId: "sigadaer", section: "geral" },
	{ keywords: ["siscontaer", "contabilidade"], moduleId: "siscontaer", section: "geral" },
	{ keywords: ["sau", "atendimento", "chamado"], moduleId: "sau", section: "geral" },
	{ keywords: ["siafi", "tesouro"], moduleId: "siafi_site", section: "geral" },
	{ keywords: ["serpro", "hod", "cadastro"], moduleId: "serpro", section: "geral" },
	{ keywords: ["tesouro", "gerencial", "tg"], moduleId: "tesouro_gerencial", section: "geral" },
	{ keywords: ["aec", "sefa"], moduleId: "aec_sefa", section: "geral" },
	{ keywords: ["zimbra", "email", "e-mail", "correio"], moduleId: "zimbra", section: "geral" },
	{ keywords: ["sisgru", "ra", "retificação", "retificacao", "gru"], moduleId: "sisgru", section: "geral" },
	{ keywords: ["manuais", "manual", "macrofunção", "macrofuncao", "macrofunções", "macrofuncoes", "siafi"], moduleId: "manuais_siafi", section: "geral" },
	{ keywords: ["siafi", "homologação", "homologacao", "teste", "testes"], moduleId: "siafi_homologacao", section: "geral" },
	{ keywords: ["drive", "pasta", "documentos", "sucont-3", "sucont 3"], moduleId: "drive_sucont3", section: "geral" },
	{ keywords: ["chatgpt", "chat gpt", "openai", "ia", "inteligência artificial"], moduleId: "chatgpt", section: "geral" },
	{ keywords: ["manus", "ia", "inteligência artificial"], moduleId: "manus", section: "geral" },
	{ keywords: ["gemini", "google", "ia", "inteligência artificial"], moduleId: "gemini", section: "geral" },
	{ keywords: ["grok", "xai", "ia", "inteligência artificial"], moduleId: "grok", section: "geral" },
]

export const returnCommands = ["menu", "início", "inicio", "voltar", "hub", "sair"]
