/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as RespondIdRouteImport } from './routes/respond/$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResponsesIndexRouteImport } from './routes/_authenticated/responses/index'
import { Route as AuthenticatedResponsesQuestionnaireIdRouteImport } from './routes/_authenticated/responses/$questionnaireId'
import { Route as AuthenticatedQuestionnairesNewRouteImport } from './routes/_authenticated/questionnaires/new'
import { Route as AuthenticatedQuestionnairesIdRouteImport } from './routes/_authenticated/questionnaires/$id'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const RespondIdRoute = RespondIdRouteImport.update({
  id: '/respond/$id',
  path: '/respond/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponsesIndexRoute =
  AuthenticatedResponsesIndexRouteImport.update({
    id: '/responses/',
    path: '/responses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResponsesQuestionnaireIdRoute =
  AuthenticatedResponsesQuestionnaireIdRouteImport.update({
    id: '/responses/$questionnaireId',
    path: '/responses/$questionnaireId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionnairesNewRoute =
  AuthenticatedQuestionnairesNewRouteImport.update({
    id: '/questionnaires/new',
    path: '/questionnaires/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionnairesIdRoute =
  AuthenticatedQuestionnairesIdRouteImport.update({
    id: '/questionnaires/$id',
    path: '/questionnaires/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/respond/$id': typeof RespondIdRoute
  '/auth/': typeof AuthIndexRoute
  '/questionnaires/$id': typeof AuthenticatedQuestionnairesIdRoute
  '/questionnaires/new': typeof AuthenticatedQuestionnairesNewRoute
  '/responses/$questionnaireId': typeof AuthenticatedResponsesQuestionnaireIdRoute
  '/responses/': typeof AuthenticatedResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/respond/$id': typeof RespondIdRoute
  '/auth': typeof AuthIndexRoute
  '/questionnaires/$id': typeof AuthenticatedQuestionnairesIdRoute
  '/questionnaires/new': typeof AuthenticatedQuestionnairesNewRoute
  '/responses/$questionnaireId': typeof AuthenticatedResponsesQuestionnaireIdRoute
  '/responses': typeof AuthenticatedResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/respond/$id': typeof RespondIdRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/questionnaires/$id': typeof AuthenticatedQuestionnairesIdRoute
  '/_authenticated/questionnaires/new': typeof AuthenticatedQuestionnairesNewRoute
  '/_authenticated/responses/$questionnaireId': typeof AuthenticatedResponsesQuestionnaireIdRoute
  '/_authenticated/responses/': typeof AuthenticatedResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/health'
    | '/dashboard'
    | '/respond/$id'
    | '/auth/'
    | '/questionnaires/$id'
    | '/questionnaires/new'
    | '/responses/$questionnaireId'
    | '/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/dashboard'
    | '/respond/$id'
    | '/auth'
    | '/questionnaires/$id'
    | '/questionnaires/new'
    | '/responses/$questionnaireId'
    | '/responses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/health'
    | '/_authenticated/dashboard'
    | '/respond/$id'
    | '/auth/'
    | '/_authenticated/questionnaires/$id'
    | '/_authenticated/questionnaires/new'
    | '/_authenticated/responses/$questionnaireId'
    | '/_authenticated/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  RespondIdRoute: typeof RespondIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/respond/$id': {
      id: '/respond/$id'
      path: '/respond/$id'
      fullPath: '/respond/$id'
      preLoaderRoute: typeof RespondIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responses/': {
      id: '/_authenticated/responses/'
      path: '/responses'
      fullPath: '/responses/'
      preLoaderRoute: typeof AuthenticatedResponsesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responses/$questionnaireId': {
      id: '/_authenticated/responses/$questionnaireId'
      path: '/responses/$questionnaireId'
      fullPath: '/responses/$questionnaireId'
      preLoaderRoute: typeof AuthenticatedResponsesQuestionnaireIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaires/new': {
      id: '/_authenticated/questionnaires/new'
      path: '/questionnaires/new'
      fullPath: '/questionnaires/new'
      preLoaderRoute: typeof AuthenticatedQuestionnairesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaires/$id': {
      id: '/_authenticated/questionnaires/$id'
      path: '/questionnaires/$id'
      fullPath: '/questionnaires/$id'
      preLoaderRoute: typeof AuthenticatedQuestionnairesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQuestionnairesIdRoute: typeof AuthenticatedQuestionnairesIdRoute
  AuthenticatedQuestionnairesNewRoute: typeof AuthenticatedQuestionnairesNewRoute
  AuthenticatedResponsesQuestionnaireIdRoute: typeof AuthenticatedResponsesQuestionnaireIdRoute
  AuthenticatedResponsesIndexRoute: typeof AuthenticatedResponsesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQuestionnairesIdRoute: AuthenticatedQuestionnairesIdRoute,
  AuthenticatedQuestionnairesNewRoute: AuthenticatedQuestionnairesNewRoute,
  AuthenticatedResponsesQuestionnaireIdRoute:
    AuthenticatedResponsesQuestionnaireIdRoute,
  AuthenticatedResponsesIndexRoute: AuthenticatedResponsesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  RespondIdRoute: RespondIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
