/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AciRouteRouteImport } from './routes/aci/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AlphaRouteRouteImport } from './routes/alpha/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PregoeiroRouteRouteImport } from './routes/pregoeiro/route'
import { Route as RequisitanteRouteRouteImport } from './routes/requisitante/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AciIndexRouteImport } from './routes/aci/index'
import { Route as AciUnitIdRouteRouteImport } from './routes/aci/$unitId/route'
import { Route as AciNovaRouteImport } from './routes/aci/nova'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUnitIdRouteRouteImport } from './routes/admin/$unitId/route'
import { Route as AdminAcessosRouteImport } from './routes/admin/acessos'
import { Route as AlphaBancadaRouteImport } from './routes/alpha/bancada'
import { Route as AlphaFontesRouteImport } from './routes/alpha/fontes'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PregoeiroIndexRouteImport } from './routes/pregoeiro/index'
import { Route as RequisitanteIndexRouteImport } from './routes/requisitante/index'
import { Route as RequisitanteUnitIdRouteRouteImport } from './routes/requisitante/$unitId/route'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known.agent-skills.index[.]json'
import { Route as AciUnitIdIndexRouteImport } from './routes/aci/$unitId/index'
import { Route as AciProcessosSubmissionIdRouteImport } from './routes/aci/processos.$submissionId'
import { Route as AciRelatorioRunIdRouteImport } from './routes/aci/relatorio.$runId'
import { Route as AdminUnitIdIndexRouteImport } from './routes/admin/$unitId/index'
import { Route as AdminUnitIdAcessosRouteImport } from './routes/admin/$unitId/acessos'
import { Route as AlphaAnaliseRunIdRouteImport } from './routes/alpha/analise.$runId'
import { Route as AlphaAnaliseNovaRouteImport } from './routes/alpha/analise.nova'
import { Route as AlphaModelosIdRouteImport } from './routes/alpha/modelos.$id'
import { Route as RequisitanteUnitIdIndexRouteImport } from './routes/requisitante/$unitId/index'
import { Route as RequisitanteUnitIdNovaRouteImport } from './routes/requisitante/$unitId/nova'
import { Route as DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport } from './routes/[.]well-known.agent-skills.$skill.SKILL[.]md'
import { Route as AciUnitIdProcessosSubmissionIdRouteImport } from './routes/aci/$unitId/processos.$submissionId'
import { Route as AciUnitIdRelatorioRunIdRouteImport } from './routes/aci/$unitId/relatorio.$runId'
import { Route as RequisitanteUnitIdProcessosSubmissionIdRouteImport } from './routes/requisitante/$unitId/processos.$submissionId'
import { Route as RequisitanteUnitIdRelatorioRunIdRouteImport } from './routes/requisitante/$unitId/relatorio.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AciRouteRoute = AciRouteRouteImport.update({
  id: '/aci',
  path: '/aci',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaRouteRoute = AlphaRouteRouteImport.update({
  id: '/alpha',
  path: '/alpha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PregoeiroRouteRoute = PregoeiroRouteRouteImport.update({
  id: '/pregoeiro',
  path: '/pregoeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitanteRouteRoute = RequisitanteRouteRouteImport.update({
  id: '/requisitante',
  path: '/requisitante',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AciIndexRoute = AciIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AciRouteRoute,
} as any)
const AciUnitIdRouteRoute = AciUnitIdRouteRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => AciRouteRoute,
} as any)
const AciNovaRoute = AciNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AciRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUnitIdRouteRoute = AdminUnitIdRouteRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAcessosRoute = AdminAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AlphaBancadaRoute = AlphaBancadaRouteImport.update({
  id: '/bancada',
  path: '/bancada',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AlphaFontesRoute = AlphaFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PregoeiroIndexRoute = PregoeiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PregoeiroRouteRoute,
} as any)
const RequisitanteIndexRoute = RequisitanteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequisitanteRouteRoute,
} as any)
const RequisitanteUnitIdRouteRoute = RequisitanteUnitIdRouteRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => RequisitanteRouteRoute,
} as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AciUnitIdIndexRoute = AciUnitIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AciUnitIdRouteRoute,
} as any)
const AciProcessosSubmissionIdRoute =
  AciProcessosSubmissionIdRouteImport.update({
    id: '/processos/$submissionId',
    path: '/processos/$submissionId',
    getParentRoute: () => AciRouteRoute,
  } as any)
const AciRelatorioRunIdRoute = AciRelatorioRunIdRouteImport.update({
  id: '/relatorio/$runId',
  path: '/relatorio/$runId',
  getParentRoute: () => AciRouteRoute,
} as any)
const AdminUnitIdIndexRoute = AdminUnitIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUnitIdRouteRoute,
} as any)
const AdminUnitIdAcessosRoute = AdminUnitIdAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AdminUnitIdRouteRoute,
} as any)
const AlphaAnaliseRunIdRoute = AlphaAnaliseRunIdRouteImport.update({
  id: '/analise/$runId',
  path: '/analise/$runId',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AlphaAnaliseNovaRoute = AlphaAnaliseNovaRouteImport.update({
  id: '/analise/nova',
  path: '/analise/nova',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AlphaModelosIdRoute = AlphaModelosIdRouteImport.update({
  id: '/modelos/$id',
  path: '/modelos/$id',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const RequisitanteUnitIdIndexRoute = RequisitanteUnitIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequisitanteUnitIdRouteRoute,
} as any)
const RequisitanteUnitIdNovaRoute = RequisitanteUnitIdNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => RequisitanteUnitIdRouteRoute,
} as any)
const DotwellKnownAgentSkillsSkillSKILLDotmdRoute =
  DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport.update({
    id: '/.well-known/agent-skills/$skill/SKILL.md',
    path: '/.well-known/agent-skills/$skill/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const AciUnitIdProcessosSubmissionIdRoute =
  AciUnitIdProcessosSubmissionIdRouteImport.update({
    id: '/processos/$submissionId',
    path: '/processos/$submissionId',
    getParentRoute: () => AciUnitIdRouteRoute,
  } as any)
const AciUnitIdRelatorioRunIdRoute = AciUnitIdRelatorioRunIdRouteImport.update({
  id: '/relatorio/$runId',
  path: '/relatorio/$runId',
  getParentRoute: () => AciUnitIdRouteRoute,
} as any)
const RequisitanteUnitIdProcessosSubmissionIdRoute =
  RequisitanteUnitIdProcessosSubmissionIdRouteImport.update({
    id: '/processos/$submissionId',
    path: '/processos/$submissionId',
    getParentRoute: () => RequisitanteUnitIdRouteRoute,
  } as any)
const RequisitanteUnitIdRelatorioRunIdRoute =
  RequisitanteUnitIdRelatorioRunIdRouteImport.update({
    id: '/relatorio/$runId',
    path: '/relatorio/$runId',
    getParentRoute: () => RequisitanteUnitIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aci': typeof AciRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/alpha': typeof AlphaRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/pregoeiro': typeof PregoeiroRouteRouteWithChildren
  '/requisitante': typeof RequisitanteRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/aci/$unitId': typeof AciUnitIdRouteRouteWithChildren
  '/admin/$unitId': typeof AdminUnitIdRouteRouteWithChildren
  '/requisitante/$unitId': typeof RequisitanteUnitIdRouteRouteWithChildren
  '/aci/nova': typeof AciNovaRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/alpha/bancada': typeof AlphaBancadaRoute
  '/alpha/fontes': typeof AlphaFontesRoute
  '/aci/': typeof AciIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/pregoeiro/': typeof PregoeiroIndexRoute
  '/requisitante/': typeof RequisitanteIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/aci/processos/$submissionId': typeof AciProcessosSubmissionIdRoute
  '/aci/relatorio/$runId': typeof AciRelatorioRunIdRoute
  '/admin/$unitId/acessos': typeof AdminUnitIdAcessosRoute
  '/alpha/analise/$runId': typeof AlphaAnaliseRunIdRoute
  '/alpha/analise/nova': typeof AlphaAnaliseNovaRoute
  '/alpha/modelos/$id': typeof AlphaModelosIdRoute
  '/requisitante/$unitId/nova': typeof RequisitanteUnitIdNovaRoute
  '/aci/$unitId/': typeof AciUnitIdIndexRoute
  '/admin/$unitId/': typeof AdminUnitIdIndexRoute
  '/requisitante/$unitId/': typeof RequisitanteUnitIdIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/aci/$unitId/processos/$submissionId': typeof AciUnitIdProcessosSubmissionIdRoute
  '/aci/$unitId/relatorio/$runId': typeof AciUnitIdRelatorioRunIdRoute
  '/requisitante/$unitId/processos/$submissionId': typeof RequisitanteUnitIdProcessosSubmissionIdRoute
  '/requisitante/$unitId/relatorio/$runId': typeof RequisitanteUnitIdRelatorioRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alpha': typeof AlphaRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/aci/nova': typeof AciNovaRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/alpha/bancada': typeof AlphaBancadaRoute
  '/alpha/fontes': typeof AlphaFontesRoute
  '/aci': typeof AciIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/pregoeiro': typeof PregoeiroIndexRoute
  '/requisitante': typeof RequisitanteIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/aci/processos/$submissionId': typeof AciProcessosSubmissionIdRoute
  '/aci/relatorio/$runId': typeof AciRelatorioRunIdRoute
  '/admin/$unitId/acessos': typeof AdminUnitIdAcessosRoute
  '/alpha/analise/$runId': typeof AlphaAnaliseRunIdRoute
  '/alpha/analise/nova': typeof AlphaAnaliseNovaRoute
  '/alpha/modelos/$id': typeof AlphaModelosIdRoute
  '/requisitante/$unitId/nova': typeof RequisitanteUnitIdNovaRoute
  '/aci/$unitId': typeof AciUnitIdIndexRoute
  '/admin/$unitId': typeof AdminUnitIdIndexRoute
  '/requisitante/$unitId': typeof RequisitanteUnitIdIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/aci/$unitId/processos/$submissionId': typeof AciUnitIdProcessosSubmissionIdRoute
  '/aci/$unitId/relatorio/$runId': typeof AciUnitIdRelatorioRunIdRoute
  '/requisitante/$unitId/processos/$submissionId': typeof RequisitanteUnitIdProcessosSubmissionIdRoute
  '/requisitante/$unitId/relatorio/$runId': typeof RequisitanteUnitIdRelatorioRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aci': typeof AciRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/alpha': typeof AlphaRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/pregoeiro': typeof PregoeiroRouteRouteWithChildren
  '/requisitante': typeof RequisitanteRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/aci/$unitId': typeof AciUnitIdRouteRouteWithChildren
  '/admin/$unitId': typeof AdminUnitIdRouteRouteWithChildren
  '/requisitante/$unitId': typeof RequisitanteUnitIdRouteRouteWithChildren
  '/aci/nova': typeof AciNovaRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/alpha/bancada': typeof AlphaBancadaRoute
  '/alpha/fontes': typeof AlphaFontesRoute
  '/aci/': typeof AciIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/pregoeiro/': typeof PregoeiroIndexRoute
  '/requisitante/': typeof RequisitanteIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/aci/processos/$submissionId': typeof AciProcessosSubmissionIdRoute
  '/aci/relatorio/$runId': typeof AciRelatorioRunIdRoute
  '/admin/$unitId/acessos': typeof AdminUnitIdAcessosRoute
  '/alpha/analise/$runId': typeof AlphaAnaliseRunIdRoute
  '/alpha/analise/nova': typeof AlphaAnaliseNovaRoute
  '/alpha/modelos/$id': typeof AlphaModelosIdRoute
  '/requisitante/$unitId/nova': typeof RequisitanteUnitIdNovaRoute
  '/aci/$unitId/': typeof AciUnitIdIndexRoute
  '/admin/$unitId/': typeof AdminUnitIdIndexRoute
  '/requisitante/$unitId/': typeof RequisitanteUnitIdIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/aci/$unitId/processos/$submissionId': typeof AciUnitIdProcessosSubmissionIdRoute
  '/aci/$unitId/relatorio/$runId': typeof AciUnitIdRelatorioRunIdRoute
  '/requisitante/$unitId/processos/$submissionId': typeof RequisitanteUnitIdProcessosSubmissionIdRoute
  '/requisitante/$unitId/relatorio/$runId': typeof RequisitanteUnitIdRelatorioRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aci'
    | '/admin'
    | '/alpha'
    | '/auth'
    | '/pregoeiro'
    | '/requisitante'
    | '/health'
    | '/llms.txt'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/aci/$unitId'
    | '/admin/$unitId'
    | '/requisitante/$unitId'
    | '/aci/nova'
    | '/admin/acessos'
    | '/alpha/bancada'
    | '/alpha/fontes'
    | '/aci/'
    | '/admin/'
    | '/auth/'
    | '/pregoeiro/'
    | '/requisitante/'
    | '/.well-known/agent-skills/index.json'
    | '/aci/processos/$submissionId'
    | '/aci/relatorio/$runId'
    | '/admin/$unitId/acessos'
    | '/alpha/analise/$runId'
    | '/alpha/analise/nova'
    | '/alpha/modelos/$id'
    | '/requisitante/$unitId/nova'
    | '/aci/$unitId/'
    | '/admin/$unitId/'
    | '/requisitante/$unitId/'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/aci/$unitId/processos/$submissionId'
    | '/aci/$unitId/relatorio/$runId'
    | '/requisitante/$unitId/processos/$submissionId'
    | '/requisitante/$unitId/relatorio/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alpha'
    | '/health'
    | '/llms.txt'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/aci/nova'
    | '/admin/acessos'
    | '/alpha/bancada'
    | '/alpha/fontes'
    | '/aci'
    | '/admin'
    | '/auth'
    | '/pregoeiro'
    | '/requisitante'
    | '/.well-known/agent-skills/index.json'
    | '/aci/processos/$submissionId'
    | '/aci/relatorio/$runId'
    | '/admin/$unitId/acessos'
    | '/alpha/analise/$runId'
    | '/alpha/analise/nova'
    | '/alpha/modelos/$id'
    | '/requisitante/$unitId/nova'
    | '/aci/$unitId'
    | '/admin/$unitId'
    | '/requisitante/$unitId'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/aci/$unitId/processos/$submissionId'
    | '/aci/$unitId/relatorio/$runId'
    | '/requisitante/$unitId/processos/$submissionId'
    | '/requisitante/$unitId/relatorio/$runId'
  id:
    | '__root__'
    | '/'
    | '/aci'
    | '/admin'
    | '/alpha'
    | '/auth'
    | '/pregoeiro'
    | '/requisitante'
    | '/health'
    | '/llms.txt'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/aci/$unitId'
    | '/admin/$unitId'
    | '/requisitante/$unitId'
    | '/aci/nova'
    | '/admin/acessos'
    | '/alpha/bancada'
    | '/alpha/fontes'
    | '/aci/'
    | '/admin/'
    | '/auth/'
    | '/pregoeiro/'
    | '/requisitante/'
    | '/.well-known/agent-skills/index.json'
    | '/aci/processos/$submissionId'
    | '/aci/relatorio/$runId'
    | '/admin/$unitId/acessos'
    | '/alpha/analise/$runId'
    | '/alpha/analise/nova'
    | '/alpha/modelos/$id'
    | '/requisitante/$unitId/nova'
    | '/aci/$unitId/'
    | '/admin/$unitId/'
    | '/requisitante/$unitId/'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/aci/$unitId/processos/$submissionId'
    | '/aci/$unitId/relatorio/$runId'
    | '/requisitante/$unitId/processos/$submissionId'
    | '/requisitante/$unitId/relatorio/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AciRouteRoute: typeof AciRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AlphaRouteRoute: typeof AlphaRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PregoeiroRouteRoute: typeof PregoeiroRouteRouteWithChildren
  RequisitanteRouteRoute: typeof RequisitanteRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aci': {
      id: '/aci'
      path: '/aci'
      fullPath: '/aci'
      preLoaderRoute: typeof AciRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha': {
      id: '/alpha'
      path: '/alpha'
      fullPath: '/alpha'
      preLoaderRoute: typeof AlphaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregoeiro': {
      id: '/pregoeiro'
      path: '/pregoeiro'
      fullPath: '/pregoeiro'
      preLoaderRoute: typeof PregoeiroRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitante': {
      id: '/requisitante'
      path: '/requisitante'
      fullPath: '/requisitante'
      preLoaderRoute: typeof RequisitanteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aci/': {
      id: '/aci/'
      path: '/'
      fullPath: '/aci/'
      preLoaderRoute: typeof AciIndexRouteImport
      parentRoute: typeof AciRouteRoute
    }
    '/aci/$unitId': {
      id: '/aci/$unitId'
      path: '/$unitId'
      fullPath: '/aci/$unitId'
      preLoaderRoute: typeof AciUnitIdRouteRouteImport
      parentRoute: typeof AciRouteRoute
    }
    '/aci/nova': {
      id: '/aci/nova'
      path: '/nova'
      fullPath: '/aci/nova'
      preLoaderRoute: typeof AciNovaRouteImport
      parentRoute: typeof AciRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$unitId': {
      id: '/admin/$unitId'
      path: '/$unitId'
      fullPath: '/admin/$unitId'
      preLoaderRoute: typeof AdminUnitIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/acessos': {
      id: '/admin/acessos'
      path: '/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AdminAcessosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/alpha/bancada': {
      id: '/alpha/bancada'
      path: '/bancada'
      fullPath: '/alpha/bancada'
      preLoaderRoute: typeof AlphaBancadaRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/alpha/fontes': {
      id: '/alpha/fontes'
      path: '/fontes'
      fullPath: '/alpha/fontes'
      preLoaderRoute: typeof AlphaFontesRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/pregoeiro/': {
      id: '/pregoeiro/'
      path: '/'
      fullPath: '/pregoeiro/'
      preLoaderRoute: typeof PregoeiroIndexRouteImport
      parentRoute: typeof PregoeiroRouteRoute
    }
    '/requisitante/': {
      id: '/requisitante/'
      path: '/'
      fullPath: '/requisitante/'
      preLoaderRoute: typeof RequisitanteIndexRouteImport
      parentRoute: typeof RequisitanteRouteRoute
    }
    '/requisitante/$unitId': {
      id: '/requisitante/$unitId'
      path: '/$unitId'
      fullPath: '/requisitante/$unitId'
      preLoaderRoute: typeof RequisitanteUnitIdRouteRouteImport
      parentRoute: typeof RequisitanteRouteRoute
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aci/$unitId/': {
      id: '/aci/$unitId/'
      path: '/'
      fullPath: '/aci/$unitId/'
      preLoaderRoute: typeof AciUnitIdIndexRouteImport
      parentRoute: typeof AciUnitIdRouteRoute
    }
    '/aci/processos/$submissionId': {
      id: '/aci/processos/$submissionId'
      path: '/processos/$submissionId'
      fullPath: '/aci/processos/$submissionId'
      preLoaderRoute: typeof AciProcessosSubmissionIdRouteImport
      parentRoute: typeof AciRouteRoute
    }
    '/aci/relatorio/$runId': {
      id: '/aci/relatorio/$runId'
      path: '/relatorio/$runId'
      fullPath: '/aci/relatorio/$runId'
      preLoaderRoute: typeof AciRelatorioRunIdRouteImport
      parentRoute: typeof AciRouteRoute
    }
    '/admin/$unitId/': {
      id: '/admin/$unitId/'
      path: '/'
      fullPath: '/admin/$unitId/'
      preLoaderRoute: typeof AdminUnitIdIndexRouteImport
      parentRoute: typeof AdminUnitIdRouteRoute
    }
    '/admin/$unitId/acessos': {
      id: '/admin/$unitId/acessos'
      path: '/acessos'
      fullPath: '/admin/$unitId/acessos'
      preLoaderRoute: typeof AdminUnitIdAcessosRouteImport
      parentRoute: typeof AdminUnitIdRouteRoute
    }
    '/alpha/analise/$runId': {
      id: '/alpha/analise/$runId'
      path: '/analise/$runId'
      fullPath: '/alpha/analise/$runId'
      preLoaderRoute: typeof AlphaAnaliseRunIdRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/alpha/analise/nova': {
      id: '/alpha/analise/nova'
      path: '/analise/nova'
      fullPath: '/alpha/analise/nova'
      preLoaderRoute: typeof AlphaAnaliseNovaRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/alpha/modelos/$id': {
      id: '/alpha/modelos/$id'
      path: '/modelos/$id'
      fullPath: '/alpha/modelos/$id'
      preLoaderRoute: typeof AlphaModelosIdRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/requisitante/$unitId/': {
      id: '/requisitante/$unitId/'
      path: '/'
      fullPath: '/requisitante/$unitId/'
      preLoaderRoute: typeof RequisitanteUnitIdIndexRouteImport
      parentRoute: typeof RequisitanteUnitIdRouteRoute
    }
    '/requisitante/$unitId/nova': {
      id: '/requisitante/$unitId/nova'
      path: '/nova'
      fullPath: '/requisitante/$unitId/nova'
      preLoaderRoute: typeof RequisitanteUnitIdNovaRouteImport
      parentRoute: typeof RequisitanteUnitIdRouteRoute
    }
    '/.well-known/agent-skills/$skill/SKILL.md': {
      id: '/.well-known/agent-skills/$skill/SKILL.md'
      path: '/.well-known/agent-skills/$skill/SKILL.md'
      fullPath: '/.well-known/agent-skills/$skill/SKILL.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aci/$unitId/processos/$submissionId': {
      id: '/aci/$unitId/processos/$submissionId'
      path: '/processos/$submissionId'
      fullPath: '/aci/$unitId/processos/$submissionId'
      preLoaderRoute: typeof AciUnitIdProcessosSubmissionIdRouteImport
      parentRoute: typeof AciUnitIdRouteRoute
    }
    '/aci/$unitId/relatorio/$runId': {
      id: '/aci/$unitId/relatorio/$runId'
      path: '/relatorio/$runId'
      fullPath: '/aci/$unitId/relatorio/$runId'
      preLoaderRoute: typeof AciUnitIdRelatorioRunIdRouteImport
      parentRoute: typeof AciUnitIdRouteRoute
    }
    '/requisitante/$unitId/processos/$submissionId': {
      id: '/requisitante/$unitId/processos/$submissionId'
      path: '/processos/$submissionId'
      fullPath: '/requisitante/$unitId/processos/$submissionId'
      preLoaderRoute: typeof RequisitanteUnitIdProcessosSubmissionIdRouteImport
      parentRoute: typeof RequisitanteUnitIdRouteRoute
    }
    '/requisitante/$unitId/relatorio/$runId': {
      id: '/requisitante/$unitId/relatorio/$runId'
      path: '/relatorio/$runId'
      fullPath: '/requisitante/$unitId/relatorio/$runId'
      preLoaderRoute: typeof RequisitanteUnitIdRelatorioRunIdRouteImport
      parentRoute: typeof RequisitanteUnitIdRouteRoute
    }
  }
}

interface AciUnitIdRouteRouteChildren {
  AciUnitIdIndexRoute: typeof AciUnitIdIndexRoute
  AciUnitIdProcessosSubmissionIdRoute: typeof AciUnitIdProcessosSubmissionIdRoute
  AciUnitIdRelatorioRunIdRoute: typeof AciUnitIdRelatorioRunIdRoute
}

const AciUnitIdRouteRouteChildren: AciUnitIdRouteRouteChildren = {
  AciUnitIdIndexRoute: AciUnitIdIndexRoute,
  AciUnitIdProcessosSubmissionIdRoute: AciUnitIdProcessosSubmissionIdRoute,
  AciUnitIdRelatorioRunIdRoute: AciUnitIdRelatorioRunIdRoute,
}

const AciUnitIdRouteRouteWithChildren = AciUnitIdRouteRoute._addFileChildren(
  AciUnitIdRouteRouteChildren,
)

interface AciRouteRouteChildren {
  AciUnitIdRouteRoute: typeof AciUnitIdRouteRouteWithChildren
  AciNovaRoute: typeof AciNovaRoute
  AciIndexRoute: typeof AciIndexRoute
  AciProcessosSubmissionIdRoute: typeof AciProcessosSubmissionIdRoute
  AciRelatorioRunIdRoute: typeof AciRelatorioRunIdRoute
}

const AciRouteRouteChildren: AciRouteRouteChildren = {
  AciUnitIdRouteRoute: AciUnitIdRouteRouteWithChildren,
  AciNovaRoute: AciNovaRoute,
  AciIndexRoute: AciIndexRoute,
  AciProcessosSubmissionIdRoute: AciProcessosSubmissionIdRoute,
  AciRelatorioRunIdRoute: AciRelatorioRunIdRoute,
}

const AciRouteRouteWithChildren = AciRouteRoute._addFileChildren(
  AciRouteRouteChildren,
)

interface AdminUnitIdRouteRouteChildren {
  AdminUnitIdAcessosRoute: typeof AdminUnitIdAcessosRoute
  AdminUnitIdIndexRoute: typeof AdminUnitIdIndexRoute
}

const AdminUnitIdRouteRouteChildren: AdminUnitIdRouteRouteChildren = {
  AdminUnitIdAcessosRoute: AdminUnitIdAcessosRoute,
  AdminUnitIdIndexRoute: AdminUnitIdIndexRoute,
}

const AdminUnitIdRouteRouteWithChildren =
  AdminUnitIdRouteRoute._addFileChildren(AdminUnitIdRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminUnitIdRouteRoute: typeof AdminUnitIdRouteRouteWithChildren
  AdminAcessosRoute: typeof AdminAcessosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUnitIdRouteRoute: AdminUnitIdRouteRouteWithChildren,
  AdminAcessosRoute: AdminAcessosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AlphaRouteRouteChildren {
  AlphaBancadaRoute: typeof AlphaBancadaRoute
  AlphaFontesRoute: typeof AlphaFontesRoute
  AlphaAnaliseRunIdRoute: typeof AlphaAnaliseRunIdRoute
  AlphaAnaliseNovaRoute: typeof AlphaAnaliseNovaRoute
  AlphaModelosIdRoute: typeof AlphaModelosIdRoute
}

const AlphaRouteRouteChildren: AlphaRouteRouteChildren = {
  AlphaBancadaRoute: AlphaBancadaRoute,
  AlphaFontesRoute: AlphaFontesRoute,
  AlphaAnaliseRunIdRoute: AlphaAnaliseRunIdRoute,
  AlphaAnaliseNovaRoute: AlphaAnaliseNovaRoute,
  AlphaModelosIdRoute: AlphaModelosIdRoute,
}

const AlphaRouteRouteWithChildren = AlphaRouteRoute._addFileChildren(
  AlphaRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PregoeiroRouteRouteChildren {
  PregoeiroIndexRoute: typeof PregoeiroIndexRoute
}

const PregoeiroRouteRouteChildren: PregoeiroRouteRouteChildren = {
  PregoeiroIndexRoute: PregoeiroIndexRoute,
}

const PregoeiroRouteRouteWithChildren = PregoeiroRouteRoute._addFileChildren(
  PregoeiroRouteRouteChildren,
)

interface RequisitanteUnitIdRouteRouteChildren {
  RequisitanteUnitIdNovaRoute: typeof RequisitanteUnitIdNovaRoute
  RequisitanteUnitIdIndexRoute: typeof RequisitanteUnitIdIndexRoute
  RequisitanteUnitIdProcessosSubmissionIdRoute: typeof RequisitanteUnitIdProcessosSubmissionIdRoute
  RequisitanteUnitIdRelatorioRunIdRoute: typeof RequisitanteUnitIdRelatorioRunIdRoute
}

const RequisitanteUnitIdRouteRouteChildren: RequisitanteUnitIdRouteRouteChildren =
  {
    RequisitanteUnitIdNovaRoute: RequisitanteUnitIdNovaRoute,
    RequisitanteUnitIdIndexRoute: RequisitanteUnitIdIndexRoute,
    RequisitanteUnitIdProcessosSubmissionIdRoute:
      RequisitanteUnitIdProcessosSubmissionIdRoute,
    RequisitanteUnitIdRelatorioRunIdRoute:
      RequisitanteUnitIdRelatorioRunIdRoute,
  }

const RequisitanteUnitIdRouteRouteWithChildren =
  RequisitanteUnitIdRouteRoute._addFileChildren(
    RequisitanteUnitIdRouteRouteChildren,
  )

interface RequisitanteRouteRouteChildren {
  RequisitanteUnitIdRouteRoute: typeof RequisitanteUnitIdRouteRouteWithChildren
  RequisitanteIndexRoute: typeof RequisitanteIndexRoute
}

const RequisitanteRouteRouteChildren: RequisitanteRouteRouteChildren = {
  RequisitanteUnitIdRouteRoute: RequisitanteUnitIdRouteRouteWithChildren,
  RequisitanteIndexRoute: RequisitanteIndexRoute,
}

const RequisitanteRouteRouteWithChildren =
  RequisitanteRouteRoute._addFileChildren(RequisitanteRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AciRouteRoute: AciRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AlphaRouteRoute: AlphaRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PregoeiroRouteRoute: PregoeiroRouteRouteWithChildren,
  RequisitanteRouteRoute: RequisitanteRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute:
    DotwellKnownAgentSkillsSkillSKILLDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
