/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as JournalRouteRouteImport } from './routes/journal/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as JournalSubmitRouteImport } from './routes/journal/submit'
import { Route as JournalProfileRouteImport } from './routes/journal/profile'
import { Route as JournalAboutRouteImport } from './routes/journal/about'
import { Route as JournalEditorialRouteRouteImport } from './routes/journal/editorial/route'
import { Route as JournalSubmissionsIndexRouteImport } from './routes/journal/submissions/index'
import { Route as JournalReviewIndexRouteImport } from './routes/journal/review/index'
import { Route as JournalArticlesIndexRouteImport } from './routes/journal/articles/index'
import { Route as JournalSubmissionsIdRouteImport } from './routes/journal/submissions/$id'
import { Route as JournalReviewTokenRouteImport } from './routes/journal/review/$token'
import { Route as JournalReviewAssignmentIdRouteImport } from './routes/journal/review/$assignmentId'
import { Route as JournalEditorialVolumesRouteImport } from './routes/journal/editorial/volumes'
import { Route as JournalEditorialSettingsRouteImport } from './routes/journal/editorial/settings'
import { Route as JournalEditorialPublicationRouteImport } from './routes/journal/editorial/publication'
import { Route as JournalEditorialMetadataExportRouteImport } from './routes/journal/editorial/metadata-export'
import { Route as JournalEditorialDashboardRouteImport } from './routes/journal/editorial/dashboard'
import { Route as JournalArticlesIdRouteImport } from './routes/journal/articles/$id'
import { Route as PublicPtSobreRouteImport } from './routes/_public/_pt/sobre'
import { Route as PublicPtRoteiroRouteImport } from './routes/_public/_pt/roteiro'
import { Route as PublicPtPoliticaDeInovacaoRouteImport } from './routes/_public/_pt/politica-de-inovacao'
import { Route as PublicPtPesquisaRouteImport } from './routes/_public/_pt/pesquisa'
import { Route as PublicPtPainelFiscalRouteImport } from './routes/_public/_pt/painel-fiscal'
import { Route as PublicEnRoadmapRouteImport } from './routes/_public/_en/roadmap'
import { Route as PublicEnResearchRouteImport } from './routes/_public/_en/research'
import { Route as PublicEnOverseerDashboardRouteImport } from './routes/_public/_en/overseerDashboard'
import { Route as PublicEnInnovationPolicyRouteImport } from './routes/_public/_en/innovation-policy'
import { Route as PublicEnChatRadaRouteImport } from './routes/_public/_en/chatRada'
import { Route as PublicEnAboutRouteImport } from './routes/_public/_en/about'
import { Route as PublicPtPublicacoesIndexRouteImport } from './routes/_public/_pt/publicacoes/index'
import { Route as PublicPtInstalacoesIndexRouteImport } from './routes/_public/_pt/instalacoes/index'
import { Route as PublicEnPostsIndexRouteImport } from './routes/_public/_en/posts/index'
import { Route as PublicEnFacilitiesIndexRouteImport } from './routes/_public/_en/facilities/index'
import { Route as JournalEditorialArticlesArticleIdRouteImport } from './routes/journal/editorial/articles/$articleId'
import { Route as PublicPtPublicacoesSlugRouteImport } from './routes/_public/_pt/publicacoes/$slug'
import { Route as PublicPtInstalacoesPregoeiroRouteImport } from './routes/_public/_pt/instalacoes/pregoeiro'
import { Route as PublicEnPostsSlugRouteImport } from './routes/_public/_en/posts/$slug'
import { Route as PublicEnFacilitiesPregoeiroRouteImport } from './routes/_public/_en/facilities/pregoeiro'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRouteRoute = JournalRouteRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const JournalSubmitRoute = JournalSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalProfileRoute = JournalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalAboutRoute = JournalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalEditorialRouteRoute = JournalEditorialRouteRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalSubmissionsIndexRoute = JournalSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalReviewIndexRoute = JournalReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalArticlesIndexRoute = JournalArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalSubmissionsIdRoute = JournalSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalReviewTokenRoute = JournalReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalReviewAssignmentIdRoute =
  JournalReviewAssignmentIdRouteImport.update({
    id: '/review/$assignmentId',
    path: '/review/$assignmentId',
    getParentRoute: () => JournalRouteRoute,
  } as any)
const JournalEditorialVolumesRoute = JournalEditorialVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => JournalEditorialRouteRoute,
} as any)
const JournalEditorialSettingsRoute =
  JournalEditorialSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalEditorialPublicationRoute =
  JournalEditorialPublicationRouteImport.update({
    id: '/publication',
    path: '/publication',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalEditorialMetadataExportRoute =
  JournalEditorialMetadataExportRouteImport.update({
    id: '/metadata-export',
    path: '/metadata-export',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalEditorialDashboardRoute =
  JournalEditorialDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalArticlesIdRoute = JournalArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => JournalRouteRoute,
} as any)
const PublicPtSobreRoute = PublicPtSobreRouteImport.update({
  id: '/_pt/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtRoteiroRoute = PublicPtRoteiroRouteImport.update({
  id: '/_pt/roteiro',
  path: '/roteiro',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtPoliticaDeInovacaoRoute =
  PublicPtPoliticaDeInovacaoRouteImport.update({
    id: '/_pt/politica-de-inovacao',
    path: '/politica-de-inovacao',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtPesquisaRoute = PublicPtPesquisaRouteImport.update({
  id: '/_pt/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtPainelFiscalRoute = PublicPtPainelFiscalRouteImport.update({
  id: '/_pt/painel-fiscal',
  path: '/painel-fiscal',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnRoadmapRoute = PublicEnRoadmapRouteImport.update({
  id: '/_en/roadmap',
  path: '/roadmap',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnResearchRoute = PublicEnResearchRouteImport.update({
  id: '/_en/research',
  path: '/research',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnOverseerDashboardRoute =
  PublicEnOverseerDashboardRouteImport.update({
    id: '/_en/overseerDashboard',
    path: '/overseerDashboard',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicEnInnovationPolicyRoute =
  PublicEnInnovationPolicyRouteImport.update({
    id: '/_en/innovation-policy',
    path: '/innovation-policy',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicEnChatRadaRoute = PublicEnChatRadaRouteImport.update({
  id: '/_en/chatRada',
  path: '/chatRada',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnAboutRoute = PublicEnAboutRouteImport.update({
  id: '/_en/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtPublicacoesIndexRoute =
  PublicPtPublicacoesIndexRouteImport.update({
    id: '/_pt/publicacoes/',
    path: '/publicacoes/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtInstalacoesIndexRoute =
  PublicPtInstalacoesIndexRouteImport.update({
    id: '/_pt/instalacoes/',
    path: '/instalacoes/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicEnPostsIndexRoute = PublicEnPostsIndexRouteImport.update({
  id: '/_en/posts/',
  path: '/posts/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnFacilitiesIndexRoute = PublicEnFacilitiesIndexRouteImport.update({
  id: '/_en/facilities/',
  path: '/facilities/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const JournalEditorialArticlesArticleIdRoute =
  JournalEditorialArticlesArticleIdRouteImport.update({
    id: '/articles/$articleId',
    path: '/articles/$articleId',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const PublicPtPublicacoesSlugRoute = PublicPtPublicacoesSlugRouteImport.update({
  id: '/_pt/publicacoes/$slug',
  path: '/publicacoes/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtInstalacoesPregoeiroRoute =
  PublicPtInstalacoesPregoeiroRouteImport.update({
    id: '/_pt/instalacoes/pregoeiro',
    path: '/instalacoes/pregoeiro',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicEnPostsSlugRoute = PublicEnPostsSlugRouteImport.update({
  id: '/_en/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnFacilitiesPregoeiroRoute =
  PublicEnFacilitiesPregoeiroRouteImport.update({
    id: '/_en/facilities/pregoeiro',
    path: '/facilities/pregoeiro',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/journal': typeof JournalRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/journal/editorial': typeof JournalEditorialRouteRouteWithChildren
  '/journal/about': typeof JournalAboutRoute
  '/journal/profile': typeof JournalProfileRoute
  '/journal/submit': typeof JournalSubmitRoute
  '/auth/': typeof AuthIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/about': typeof PublicEnAboutRoute
  '/chatRada': typeof PublicEnChatRadaRoute
  '/innovation-policy': typeof PublicEnInnovationPolicyRoute
  '/overseerDashboard': typeof PublicEnOverseerDashboardRoute
  '/research': typeof PublicEnResearchRoute
  '/roadmap': typeof PublicEnRoadmapRoute
  '/painel-fiscal': typeof PublicPtPainelFiscalRoute
  '/pesquisa': typeof PublicPtPesquisaRoute
  '/politica-de-inovacao': typeof PublicPtPoliticaDeInovacaoRoute
  '/roteiro': typeof PublicPtRoteiroRoute
  '/sobre': typeof PublicPtSobreRoute
  '/journal/articles/$id': typeof JournalArticlesIdRoute
  '/journal/editorial/dashboard': typeof JournalEditorialDashboardRoute
  '/journal/editorial/metadata-export': typeof JournalEditorialMetadataExportRoute
  '/journal/editorial/publication': typeof JournalEditorialPublicationRoute
  '/journal/editorial/settings': typeof JournalEditorialSettingsRoute
  '/journal/editorial/volumes': typeof JournalEditorialVolumesRoute
  '/journal/review/$assignmentId': typeof JournalReviewAssignmentIdRoute
  '/journal/review/$token': typeof JournalReviewTokenRoute
  '/journal/submissions/$id': typeof JournalSubmissionsIdRoute
  '/journal/articles/': typeof JournalArticlesIndexRoute
  '/journal/review/': typeof JournalReviewIndexRoute
  '/journal/submissions/': typeof JournalSubmissionsIndexRoute
  '/facilities/pregoeiro': typeof PublicEnFacilitiesPregoeiroRoute
  '/posts/$slug': typeof PublicEnPostsSlugRoute
  '/instalacoes/pregoeiro': typeof PublicPtInstalacoesPregoeiroRoute
  '/publicacoes/$slug': typeof PublicPtPublicacoesSlugRoute
  '/journal/editorial/articles/$articleId': typeof JournalEditorialArticlesArticleIdRoute
  '/facilities/': typeof PublicEnFacilitiesIndexRoute
  '/posts/': typeof PublicEnPostsIndexRoute
  '/instalacoes/': typeof PublicPtInstalacoesIndexRoute
  '/publicacoes/': typeof PublicPtPublicacoesIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/journal/editorial': typeof JournalEditorialRouteRouteWithChildren
  '/journal/about': typeof JournalAboutRoute
  '/journal/profile': typeof JournalProfileRoute
  '/journal/submit': typeof JournalSubmitRoute
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthIndexRoute
  '/journal': typeof JournalIndexRoute
  '/about': typeof PublicEnAboutRoute
  '/chatRada': typeof PublicEnChatRadaRoute
  '/innovation-policy': typeof PublicEnInnovationPolicyRoute
  '/overseerDashboard': typeof PublicEnOverseerDashboardRoute
  '/research': typeof PublicEnResearchRoute
  '/roadmap': typeof PublicEnRoadmapRoute
  '/painel-fiscal': typeof PublicPtPainelFiscalRoute
  '/pesquisa': typeof PublicPtPesquisaRoute
  '/politica-de-inovacao': typeof PublicPtPoliticaDeInovacaoRoute
  '/roteiro': typeof PublicPtRoteiroRoute
  '/sobre': typeof PublicPtSobreRoute
  '/journal/articles/$id': typeof JournalArticlesIdRoute
  '/journal/editorial/dashboard': typeof JournalEditorialDashboardRoute
  '/journal/editorial/metadata-export': typeof JournalEditorialMetadataExportRoute
  '/journal/editorial/publication': typeof JournalEditorialPublicationRoute
  '/journal/editorial/settings': typeof JournalEditorialSettingsRoute
  '/journal/editorial/volumes': typeof JournalEditorialVolumesRoute
  '/journal/review/$assignmentId': typeof JournalReviewAssignmentIdRoute
  '/journal/review/$token': typeof JournalReviewTokenRoute
  '/journal/submissions/$id': typeof JournalSubmissionsIdRoute
  '/journal/articles': typeof JournalArticlesIndexRoute
  '/journal/review': typeof JournalReviewIndexRoute
  '/journal/submissions': typeof JournalSubmissionsIndexRoute
  '/facilities/pregoeiro': typeof PublicEnFacilitiesPregoeiroRoute
  '/posts/$slug': typeof PublicEnPostsSlugRoute
  '/instalacoes/pregoeiro': typeof PublicPtInstalacoesPregoeiroRoute
  '/publicacoes/$slug': typeof PublicPtPublicacoesSlugRoute
  '/journal/editorial/articles/$articleId': typeof JournalEditorialArticlesArticleIdRoute
  '/facilities': typeof PublicEnFacilitiesIndexRoute
  '/posts': typeof PublicEnPostsIndexRoute
  '/instalacoes': typeof PublicPtInstalacoesIndexRoute
  '/publicacoes': typeof PublicPtPublicacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/journal': typeof JournalRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/journal/editorial': typeof JournalEditorialRouteRouteWithChildren
  '/journal/about': typeof JournalAboutRoute
  '/journal/profile': typeof JournalProfileRoute
  '/journal/submit': typeof JournalSubmitRoute
  '/_public/': typeof PublicIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/_public/_en/about': typeof PublicEnAboutRoute
  '/_public/_en/chatRada': typeof PublicEnChatRadaRoute
  '/_public/_en/innovation-policy': typeof PublicEnInnovationPolicyRoute
  '/_public/_en/overseerDashboard': typeof PublicEnOverseerDashboardRoute
  '/_public/_en/research': typeof PublicEnResearchRoute
  '/_public/_en/roadmap': typeof PublicEnRoadmapRoute
  '/_public/_pt/painel-fiscal': typeof PublicPtPainelFiscalRoute
  '/_public/_pt/pesquisa': typeof PublicPtPesquisaRoute
  '/_public/_pt/politica-de-inovacao': typeof PublicPtPoliticaDeInovacaoRoute
  '/_public/_pt/roteiro': typeof PublicPtRoteiroRoute
  '/_public/_pt/sobre': typeof PublicPtSobreRoute
  '/journal/articles/$id': typeof JournalArticlesIdRoute
  '/journal/editorial/dashboard': typeof JournalEditorialDashboardRoute
  '/journal/editorial/metadata-export': typeof JournalEditorialMetadataExportRoute
  '/journal/editorial/publication': typeof JournalEditorialPublicationRoute
  '/journal/editorial/settings': typeof JournalEditorialSettingsRoute
  '/journal/editorial/volumes': typeof JournalEditorialVolumesRoute
  '/journal/review/$assignmentId': typeof JournalReviewAssignmentIdRoute
  '/journal/review/$token': typeof JournalReviewTokenRoute
  '/journal/submissions/$id': typeof JournalSubmissionsIdRoute
  '/journal/articles/': typeof JournalArticlesIndexRoute
  '/journal/review/': typeof JournalReviewIndexRoute
  '/journal/submissions/': typeof JournalSubmissionsIndexRoute
  '/_public/_en/facilities/pregoeiro': typeof PublicEnFacilitiesPregoeiroRoute
  '/_public/_en/posts/$slug': typeof PublicEnPostsSlugRoute
  '/_public/_pt/instalacoes/pregoeiro': typeof PublicPtInstalacoesPregoeiroRoute
  '/_public/_pt/publicacoes/$slug': typeof PublicPtPublicacoesSlugRoute
  '/journal/editorial/articles/$articleId': typeof JournalEditorialArticlesArticleIdRoute
  '/_public/_en/facilities/': typeof PublicEnFacilitiesIndexRoute
  '/_public/_en/posts/': typeof PublicEnPostsIndexRoute
  '/_public/_pt/instalacoes/': typeof PublicPtInstalacoesIndexRoute
  '/_public/_pt/publicacoes/': typeof PublicPtPublicacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/journal'
    | '/health'
    | '/journal/editorial'
    | '/journal/about'
    | '/journal/profile'
    | '/journal/submit'
    | '/auth/'
    | '/journal/'
    | '/about'
    | '/chatRada'
    | '/innovation-policy'
    | '/overseerDashboard'
    | '/research'
    | '/roadmap'
    | '/painel-fiscal'
    | '/pesquisa'
    | '/politica-de-inovacao'
    | '/roteiro'
    | '/sobre'
    | '/journal/articles/$id'
    | '/journal/editorial/dashboard'
    | '/journal/editorial/metadata-export'
    | '/journal/editorial/publication'
    | '/journal/editorial/settings'
    | '/journal/editorial/volumes'
    | '/journal/review/$assignmentId'
    | '/journal/review/$token'
    | '/journal/submissions/$id'
    | '/journal/articles/'
    | '/journal/review/'
    | '/journal/submissions/'
    | '/facilities/pregoeiro'
    | '/posts/$slug'
    | '/instalacoes/pregoeiro'
    | '/publicacoes/$slug'
    | '/journal/editorial/articles/$articleId'
    | '/facilities/'
    | '/posts/'
    | '/instalacoes/'
    | '/publicacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/journal/editorial'
    | '/journal/about'
    | '/journal/profile'
    | '/journal/submit'
    | '/'
    | '/auth'
    | '/journal'
    | '/about'
    | '/chatRada'
    | '/innovation-policy'
    | '/overseerDashboard'
    | '/research'
    | '/roadmap'
    | '/painel-fiscal'
    | '/pesquisa'
    | '/politica-de-inovacao'
    | '/roteiro'
    | '/sobre'
    | '/journal/articles/$id'
    | '/journal/editorial/dashboard'
    | '/journal/editorial/metadata-export'
    | '/journal/editorial/publication'
    | '/journal/editorial/settings'
    | '/journal/editorial/volumes'
    | '/journal/review/$assignmentId'
    | '/journal/review/$token'
    | '/journal/submissions/$id'
    | '/journal/articles'
    | '/journal/review'
    | '/journal/submissions'
    | '/facilities/pregoeiro'
    | '/posts/$slug'
    | '/instalacoes/pregoeiro'
    | '/publicacoes/$slug'
    | '/journal/editorial/articles/$articleId'
    | '/facilities'
    | '/posts'
    | '/instalacoes'
    | '/publicacoes'
  id:
    | '__root__'
    | '/_public'
    | '/auth'
    | '/journal'
    | '/health'
    | '/journal/editorial'
    | '/journal/about'
    | '/journal/profile'
    | '/journal/submit'
    | '/_public/'
    | '/auth/'
    | '/journal/'
    | '/_public/_en/about'
    | '/_public/_en/chatRada'
    | '/_public/_en/innovation-policy'
    | '/_public/_en/overseerDashboard'
    | '/_public/_en/research'
    | '/_public/_en/roadmap'
    | '/_public/_pt/painel-fiscal'
    | '/_public/_pt/pesquisa'
    | '/_public/_pt/politica-de-inovacao'
    | '/_public/_pt/roteiro'
    | '/_public/_pt/sobre'
    | '/journal/articles/$id'
    | '/journal/editorial/dashboard'
    | '/journal/editorial/metadata-export'
    | '/journal/editorial/publication'
    | '/journal/editorial/settings'
    | '/journal/editorial/volumes'
    | '/journal/review/$assignmentId'
    | '/journal/review/$token'
    | '/journal/submissions/$id'
    | '/journal/articles/'
    | '/journal/review/'
    | '/journal/submissions/'
    | '/_public/_en/facilities/pregoeiro'
    | '/_public/_en/posts/$slug'
    | '/_public/_pt/instalacoes/pregoeiro'
    | '/_public/_pt/publicacoes/$slug'
    | '/journal/editorial/articles/$articleId'
    | '/_public/_en/facilities/'
    | '/_public/_en/posts/'
    | '/_public/_pt/instalacoes/'
    | '/_public/_pt/publicacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  JournalRouteRoute: typeof JournalRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/journal/submit': {
      id: '/journal/submit'
      path: '/submit'
      fullPath: '/journal/submit'
      preLoaderRoute: typeof JournalSubmitRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/profile': {
      id: '/journal/profile'
      path: '/profile'
      fullPath: '/journal/profile'
      preLoaderRoute: typeof JournalProfileRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/about': {
      id: '/journal/about'
      path: '/about'
      fullPath: '/journal/about'
      preLoaderRoute: typeof JournalAboutRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/editorial': {
      id: '/journal/editorial'
      path: '/editorial'
      fullPath: '/journal/editorial'
      preLoaderRoute: typeof JournalEditorialRouteRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/submissions/': {
      id: '/journal/submissions/'
      path: '/submissions'
      fullPath: '/journal/submissions/'
      preLoaderRoute: typeof JournalSubmissionsIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/review/': {
      id: '/journal/review/'
      path: '/review'
      fullPath: '/journal/review/'
      preLoaderRoute: typeof JournalReviewIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/articles/': {
      id: '/journal/articles/'
      path: '/articles'
      fullPath: '/journal/articles/'
      preLoaderRoute: typeof JournalArticlesIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/submissions/$id': {
      id: '/journal/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/journal/submissions/$id'
      preLoaderRoute: typeof JournalSubmissionsIdRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/review/$token': {
      id: '/journal/review/$token'
      path: '/review/$token'
      fullPath: '/journal/review/$token'
      preLoaderRoute: typeof JournalReviewTokenRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/review/$assignmentId': {
      id: '/journal/review/$assignmentId'
      path: '/review/$assignmentId'
      fullPath: '/journal/review/$assignmentId'
      preLoaderRoute: typeof JournalReviewAssignmentIdRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/editorial/volumes': {
      id: '/journal/editorial/volumes'
      path: '/volumes'
      fullPath: '/journal/editorial/volumes'
      preLoaderRoute: typeof JournalEditorialVolumesRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/settings': {
      id: '/journal/editorial/settings'
      path: '/settings'
      fullPath: '/journal/editorial/settings'
      preLoaderRoute: typeof JournalEditorialSettingsRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/publication': {
      id: '/journal/editorial/publication'
      path: '/publication'
      fullPath: '/journal/editorial/publication'
      preLoaderRoute: typeof JournalEditorialPublicationRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/metadata-export': {
      id: '/journal/editorial/metadata-export'
      path: '/metadata-export'
      fullPath: '/journal/editorial/metadata-export'
      preLoaderRoute: typeof JournalEditorialMetadataExportRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/dashboard': {
      id: '/journal/editorial/dashboard'
      path: '/dashboard'
      fullPath: '/journal/editorial/dashboard'
      preLoaderRoute: typeof JournalEditorialDashboardRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/articles/$id': {
      id: '/journal/articles/$id'
      path: '/articles/$id'
      fullPath: '/journal/articles/$id'
      preLoaderRoute: typeof JournalArticlesIdRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/_public/_pt/sobre': {
      id: '/_public/_pt/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicPtSobreRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/roteiro': {
      id: '/_public/_pt/roteiro'
      path: '/roteiro'
      fullPath: '/roteiro'
      preLoaderRoute: typeof PublicPtRoteiroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/politica-de-inovacao': {
      id: '/_public/_pt/politica-de-inovacao'
      path: '/politica-de-inovacao'
      fullPath: '/politica-de-inovacao'
      preLoaderRoute: typeof PublicPtPoliticaDeInovacaoRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/pesquisa': {
      id: '/_public/_pt/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PublicPtPesquisaRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/painel-fiscal': {
      id: '/_public/_pt/painel-fiscal'
      path: '/painel-fiscal'
      fullPath: '/painel-fiscal'
      preLoaderRoute: typeof PublicPtPainelFiscalRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/roadmap': {
      id: '/_public/_en/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof PublicEnRoadmapRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/research': {
      id: '/_public/_en/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof PublicEnResearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/overseerDashboard': {
      id: '/_public/_en/overseerDashboard'
      path: '/overseerDashboard'
      fullPath: '/overseerDashboard'
      preLoaderRoute: typeof PublicEnOverseerDashboardRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/innovation-policy': {
      id: '/_public/_en/innovation-policy'
      path: '/innovation-policy'
      fullPath: '/innovation-policy'
      preLoaderRoute: typeof PublicEnInnovationPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/chatRada': {
      id: '/_public/_en/chatRada'
      path: '/chatRada'
      fullPath: '/chatRada'
      preLoaderRoute: typeof PublicEnChatRadaRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/about': {
      id: '/_public/_en/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicEnAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/publicacoes/': {
      id: '/_public/_pt/publicacoes/'
      path: '/publicacoes'
      fullPath: '/publicacoes/'
      preLoaderRoute: typeof PublicPtPublicacoesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/instalacoes/': {
      id: '/_public/_pt/instalacoes/'
      path: '/instalacoes'
      fullPath: '/instalacoes/'
      preLoaderRoute: typeof PublicPtInstalacoesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/posts/': {
      id: '/_public/_en/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PublicEnPostsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/facilities/': {
      id: '/_public/_en/facilities/'
      path: '/facilities'
      fullPath: '/facilities/'
      preLoaderRoute: typeof PublicEnFacilitiesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/journal/editorial/articles/$articleId': {
      id: '/journal/editorial/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/journal/editorial/articles/$articleId'
      preLoaderRoute: typeof JournalEditorialArticlesArticleIdRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/_public/_pt/publicacoes/$slug': {
      id: '/_public/_pt/publicacoes/$slug'
      path: '/publicacoes/$slug'
      fullPath: '/publicacoes/$slug'
      preLoaderRoute: typeof PublicPtPublicacoesSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/instalacoes/pregoeiro': {
      id: '/_public/_pt/instalacoes/pregoeiro'
      path: '/instalacoes/pregoeiro'
      fullPath: '/instalacoes/pregoeiro'
      preLoaderRoute: typeof PublicPtInstalacoesPregoeiroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/posts/$slug': {
      id: '/_public/_en/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PublicEnPostsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/facilities/pregoeiro': {
      id: '/_public/_en/facilities/pregoeiro'
      path: '/facilities/pregoeiro'
      fullPath: '/facilities/pregoeiro'
      preLoaderRoute: typeof PublicEnFacilitiesPregoeiroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEnAboutRoute: typeof PublicEnAboutRoute
  PublicEnChatRadaRoute: typeof PublicEnChatRadaRoute
  PublicEnInnovationPolicyRoute: typeof PublicEnInnovationPolicyRoute
  PublicEnOverseerDashboardRoute: typeof PublicEnOverseerDashboardRoute
  PublicEnResearchRoute: typeof PublicEnResearchRoute
  PublicEnRoadmapRoute: typeof PublicEnRoadmapRoute
  PublicPtPainelFiscalRoute: typeof PublicPtPainelFiscalRoute
  PublicPtPesquisaRoute: typeof PublicPtPesquisaRoute
  PublicPtPoliticaDeInovacaoRoute: typeof PublicPtPoliticaDeInovacaoRoute
  PublicPtRoteiroRoute: typeof PublicPtRoteiroRoute
  PublicPtSobreRoute: typeof PublicPtSobreRoute
  PublicEnFacilitiesPregoeiroRoute: typeof PublicEnFacilitiesPregoeiroRoute
  PublicEnPostsSlugRoute: typeof PublicEnPostsSlugRoute
  PublicPtInstalacoesPregoeiroRoute: typeof PublicPtInstalacoesPregoeiroRoute
  PublicPtPublicacoesSlugRoute: typeof PublicPtPublicacoesSlugRoute
  PublicEnFacilitiesIndexRoute: typeof PublicEnFacilitiesIndexRoute
  PublicEnPostsIndexRoute: typeof PublicEnPostsIndexRoute
  PublicPtInstalacoesIndexRoute: typeof PublicPtInstalacoesIndexRoute
  PublicPtPublicacoesIndexRoute: typeof PublicPtPublicacoesIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicEnAboutRoute: PublicEnAboutRoute,
  PublicEnChatRadaRoute: PublicEnChatRadaRoute,
  PublicEnInnovationPolicyRoute: PublicEnInnovationPolicyRoute,
  PublicEnOverseerDashboardRoute: PublicEnOverseerDashboardRoute,
  PublicEnResearchRoute: PublicEnResearchRoute,
  PublicEnRoadmapRoute: PublicEnRoadmapRoute,
  PublicPtPainelFiscalRoute: PublicPtPainelFiscalRoute,
  PublicPtPesquisaRoute: PublicPtPesquisaRoute,
  PublicPtPoliticaDeInovacaoRoute: PublicPtPoliticaDeInovacaoRoute,
  PublicPtRoteiroRoute: PublicPtRoteiroRoute,
  PublicPtSobreRoute: PublicPtSobreRoute,
  PublicEnFacilitiesPregoeiroRoute: PublicEnFacilitiesPregoeiroRoute,
  PublicEnPostsSlugRoute: PublicEnPostsSlugRoute,
  PublicPtInstalacoesPregoeiroRoute: PublicPtInstalacoesPregoeiroRoute,
  PublicPtPublicacoesSlugRoute: PublicPtPublicacoesSlugRoute,
  PublicEnFacilitiesIndexRoute: PublicEnFacilitiesIndexRoute,
  PublicEnPostsIndexRoute: PublicEnPostsIndexRoute,
  PublicPtInstalacoesIndexRoute: PublicPtInstalacoesIndexRoute,
  PublicPtPublicacoesIndexRoute: PublicPtPublicacoesIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface JournalEditorialRouteRouteChildren {
  JournalEditorialDashboardRoute: typeof JournalEditorialDashboardRoute
  JournalEditorialMetadataExportRoute: typeof JournalEditorialMetadataExportRoute
  JournalEditorialPublicationRoute: typeof JournalEditorialPublicationRoute
  JournalEditorialSettingsRoute: typeof JournalEditorialSettingsRoute
  JournalEditorialVolumesRoute: typeof JournalEditorialVolumesRoute
  JournalEditorialArticlesArticleIdRoute: typeof JournalEditorialArticlesArticleIdRoute
}

const JournalEditorialRouteRouteChildren: JournalEditorialRouteRouteChildren = {
  JournalEditorialDashboardRoute: JournalEditorialDashboardRoute,
  JournalEditorialMetadataExportRoute: JournalEditorialMetadataExportRoute,
  JournalEditorialPublicationRoute: JournalEditorialPublicationRoute,
  JournalEditorialSettingsRoute: JournalEditorialSettingsRoute,
  JournalEditorialVolumesRoute: JournalEditorialVolumesRoute,
  JournalEditorialArticlesArticleIdRoute:
    JournalEditorialArticlesArticleIdRoute,
}

const JournalEditorialRouteRouteWithChildren =
  JournalEditorialRouteRoute._addFileChildren(
    JournalEditorialRouteRouteChildren,
  )

interface JournalRouteRouteChildren {
  JournalEditorialRouteRoute: typeof JournalEditorialRouteRouteWithChildren
  JournalAboutRoute: typeof JournalAboutRoute
  JournalProfileRoute: typeof JournalProfileRoute
  JournalSubmitRoute: typeof JournalSubmitRoute
  JournalIndexRoute: typeof JournalIndexRoute
  JournalArticlesIdRoute: typeof JournalArticlesIdRoute
  JournalReviewAssignmentIdRoute: typeof JournalReviewAssignmentIdRoute
  JournalReviewTokenRoute: typeof JournalReviewTokenRoute
  JournalSubmissionsIdRoute: typeof JournalSubmissionsIdRoute
  JournalArticlesIndexRoute: typeof JournalArticlesIndexRoute
  JournalReviewIndexRoute: typeof JournalReviewIndexRoute
  JournalSubmissionsIndexRoute: typeof JournalSubmissionsIndexRoute
}

const JournalRouteRouteChildren: JournalRouteRouteChildren = {
  JournalEditorialRouteRoute: JournalEditorialRouteRouteWithChildren,
  JournalAboutRoute: JournalAboutRoute,
  JournalProfileRoute: JournalProfileRoute,
  JournalSubmitRoute: JournalSubmitRoute,
  JournalIndexRoute: JournalIndexRoute,
  JournalArticlesIdRoute: JournalArticlesIdRoute,
  JournalReviewAssignmentIdRoute: JournalReviewAssignmentIdRoute,
  JournalReviewTokenRoute: JournalReviewTokenRoute,
  JournalSubmissionsIdRoute: JournalSubmissionsIdRoute,
  JournalArticlesIndexRoute: JournalArticlesIndexRoute,
  JournalReviewIndexRoute: JournalReviewIndexRoute,
  JournalSubmissionsIndexRoute: JournalSubmissionsIndexRoute,
}

const JournalRouteRouteWithChildren = JournalRouteRoute._addFileChildren(
  JournalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  JournalRouteRoute: JournalRouteRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
