/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AlphaRouteRouteImport } from './routes/alpha/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthDotmdRouteImport } from './routes/auth[.]md'
import { Route as HealthRouteImport } from './routes/health'
import { Route as JournalRouteRouteImport } from './routes/journal/route'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AlphaBancadaRouteImport } from './routes/alpha/bancada'
import { Route as AlphaFontesRouteImport } from './routes/alpha/fontes'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalAboutRouteImport } from './routes/journal/about'
import { Route as JournalEditorialRouteRouteImport } from './routes/journal/editorial/route'
import { Route as JournalProfileRouteImport } from './routes/journal/profile'
import { Route as JournalSubmitRouteImport } from './routes/journal/submit'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known.agent-skills.index[.]json'
import { Route as PublicEnAboutRouteImport } from './routes/_public/_en/about'
import { Route as PublicEnChatRadaRouteImport } from './routes/_public/_en/chatRada'
import { Route as PublicEnCookiePolicyRouteImport } from './routes/_public/_en/cookie-policy'
import { Route as PublicEnInnovationPolicyRouteImport } from './routes/_public/_en/innovation-policy'
import { Route as PublicEnOverseerDashboardRouteImport } from './routes/_public/_en/overseerDashboard'
import { Route as PublicEnPrivacyPolicyRouteImport } from './routes/_public/_en/privacy-policy'
import { Route as PublicEnResearchRouteImport } from './routes/_public/_en/research'
import { Route as PublicEnRoadmapRouteImport } from './routes/_public/_en/roadmap'
import { Route as PublicEnTermsOfUseRouteImport } from './routes/_public/_en/terms-of-use'
import { Route as PublicPtPainelFiscalRouteImport } from './routes/_public/_pt/painel-fiscal'
import { Route as PublicPtPesquisaRouteImport } from './routes/_public/_pt/pesquisa'
import { Route as PublicPtPoliticaDeCookiesRouteImport } from './routes/_public/_pt/politica-de-cookies'
import { Route as PublicPtPoliticaDeInovacaoRouteImport } from './routes/_public/_pt/politica-de-inovacao'
import { Route as PublicPtPoliticaDePrivacidadeRouteImport } from './routes/_public/_pt/politica-de-privacidade'
import { Route as PublicPtRoteiroRouteImport } from './routes/_public/_pt/roteiro'
import { Route as PublicPtSobreRouteImport } from './routes/_public/_pt/sobre'
import { Route as PublicPtTermosDeUsoRouteImport } from './routes/_public/_pt/termos-de-uso'
import { Route as AlphaAnaliseRunIdRouteImport } from './routes/alpha/analise.$runId'
import { Route as AlphaAnaliseNovaRouteImport } from './routes/alpha/analise.nova'
import { Route as AlphaModelosIdRouteImport } from './routes/alpha/modelos.$id'
import { Route as JournalArticlesIndexRouteImport } from './routes/journal/articles/index'
import { Route as JournalArticlesIdRouteImport } from './routes/journal/articles/$id'
import { Route as JournalEditorialDashboardRouteImport } from './routes/journal/editorial/dashboard'
import { Route as JournalEditorialMetadataExportRouteImport } from './routes/journal/editorial/metadata-export'
import { Route as JournalEditorialPublicationRouteImport } from './routes/journal/editorial/publication'
import { Route as JournalEditorialSettingsRouteImport } from './routes/journal/editorial/settings'
import { Route as JournalEditorialVolumesRouteImport } from './routes/journal/editorial/volumes'
import { Route as JournalReviewIndexRouteImport } from './routes/journal/review/index'
import { Route as JournalReviewTokenRouteImport } from './routes/journal/review/$token'
import { Route as JournalSubmissionsIndexRouteImport } from './routes/journal/submissions/index'
import { Route as JournalSubmissionsIdRouteImport } from './routes/journal/submissions/$id'
import { Route as DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport } from './routes/[.]well-known.agent-skills.$skill.SKILL[.]md'
import { Route as PublicEnFacilitiesIndexRouteImport } from './routes/_public/_en/facilities/index'
import { Route as PublicEnFacilitiesPregoeiroRouteImport } from './routes/_public/_en/facilities/pregoeiro'
import { Route as PublicEnPostsIndexRouteImport } from './routes/_public/_en/posts/index'
import { Route as PublicEnPostsSlugRouteImport } from './routes/_public/_en/posts/$slug'
import { Route as PublicPtInstalacoesIndexRouteImport } from './routes/_public/_pt/instalacoes/index'
import { Route as PublicPtInstalacoesPregoeiroRouteImport } from './routes/_public/_pt/instalacoes/pregoeiro'
import { Route as PublicPtPublicacoesIndexRouteImport } from './routes/_public/_pt/publicacoes/index'
import { Route as PublicPtPublicacoesSlugRouteImport } from './routes/_public/_pt/publicacoes/$slug'
import { Route as JournalEditorialArticlesArticleIdRouteImport } from './routes/journal/editorial/articles/$articleId'
import { Route as JournalReviewAssignmentAssignmentIdRouteImport } from './routes/journal/review/assignment/$assignmentId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaRouteRoute = AlphaRouteRouteImport.update({
  id: '/alpha',
  path: '/alpha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDotmdRoute = AuthDotmdRouteImport.update({
  id: '/auth.md',
  path: '/auth.md',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRouteRoute = JournalRouteRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AlphaBancadaRoute = AlphaBancadaRouteImport.update({
  id: '/bancada',
  path: '/bancada',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AlphaFontesRoute = AlphaFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalAboutRoute = JournalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalEditorialRouteRoute = JournalEditorialRouteRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalProfileRoute = JournalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalSubmitRoute = JournalSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => JournalRouteRoute,
} as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicEnAboutRoute = PublicEnAboutRouteImport.update({
  id: '/_en/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnChatRadaRoute = PublicEnChatRadaRouteImport.update({
  id: '/_en/chatRada',
  path: '/chatRada',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnCookiePolicyRoute = PublicEnCookiePolicyRouteImport.update({
  id: '/_en/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnInnovationPolicyRoute =
  PublicEnInnovationPolicyRouteImport.update({
    id: '/_en/innovation-policy',
    path: '/innovation-policy',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicEnOverseerDashboardRoute =
  PublicEnOverseerDashboardRouteImport.update({
    id: '/_en/overseerDashboard',
    path: '/overseerDashboard',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicEnPrivacyPolicyRoute = PublicEnPrivacyPolicyRouteImport.update({
  id: '/_en/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnResearchRoute = PublicEnResearchRouteImport.update({
  id: '/_en/research',
  path: '/research',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnRoadmapRoute = PublicEnRoadmapRouteImport.update({
  id: '/_en/roadmap',
  path: '/roadmap',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnTermsOfUseRoute = PublicEnTermsOfUseRouteImport.update({
  id: '/_en/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtPainelFiscalRoute = PublicPtPainelFiscalRouteImport.update({
  id: '/_pt/painel-fiscal',
  path: '/painel-fiscal',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtPesquisaRoute = PublicPtPesquisaRouteImport.update({
  id: '/_pt/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtPoliticaDeCookiesRoute =
  PublicPtPoliticaDeCookiesRouteImport.update({
    id: '/_pt/politica-de-cookies',
    path: '/politica-de-cookies',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtPoliticaDeInovacaoRoute =
  PublicPtPoliticaDeInovacaoRouteImport.update({
    id: '/_pt/politica-de-inovacao',
    path: '/politica-de-inovacao',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtPoliticaDePrivacidadeRoute =
  PublicPtPoliticaDePrivacidadeRouteImport.update({
    id: '/_pt/politica-de-privacidade',
    path: '/politica-de-privacidade',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtRoteiroRoute = PublicPtRoteiroRouteImport.update({
  id: '/_pt/roteiro',
  path: '/roteiro',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtSobreRoute = PublicPtSobreRouteImport.update({
  id: '/_pt/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtTermosDeUsoRoute = PublicPtTermosDeUsoRouteImport.update({
  id: '/_pt/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AlphaAnaliseRunIdRoute = AlphaAnaliseRunIdRouteImport.update({
  id: '/analise/$runId',
  path: '/analise/$runId',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AlphaAnaliseNovaRoute = AlphaAnaliseNovaRouteImport.update({
  id: '/analise/nova',
  path: '/analise/nova',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const AlphaModelosIdRoute = AlphaModelosIdRouteImport.update({
  id: '/modelos/$id',
  path: '/modelos/$id',
  getParentRoute: () => AlphaRouteRoute,
} as any)
const JournalArticlesIndexRoute = JournalArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalArticlesIdRoute = JournalArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalEditorialDashboardRoute =
  JournalEditorialDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalEditorialMetadataExportRoute =
  JournalEditorialMetadataExportRouteImport.update({
    id: '/metadata-export',
    path: '/metadata-export',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalEditorialPublicationRoute =
  JournalEditorialPublicationRouteImport.update({
    id: '/publication',
    path: '/publication',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalEditorialSettingsRoute =
  JournalEditorialSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalEditorialVolumesRoute = JournalEditorialVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => JournalEditorialRouteRoute,
} as any)
const JournalReviewIndexRoute = JournalReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalReviewTokenRoute = JournalReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalSubmissionsIndexRoute = JournalSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => JournalRouteRoute,
} as any)
const JournalSubmissionsIdRoute = JournalSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => JournalRouteRoute,
} as any)
const DotwellKnownAgentSkillsSkillSKILLDotmdRoute =
  DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport.update({
    id: '/.well-known/agent-skills/$skill/SKILL.md',
    path: '/.well-known/agent-skills/$skill/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicEnFacilitiesIndexRoute = PublicEnFacilitiesIndexRouteImport.update({
  id: '/_en/facilities/',
  path: '/facilities/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnFacilitiesPregoeiroRoute =
  PublicEnFacilitiesPregoeiroRouteImport.update({
    id: '/_en/facilities/pregoeiro',
    path: '/facilities/pregoeiro',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicEnPostsIndexRoute = PublicEnPostsIndexRouteImport.update({
  id: '/_en/posts/',
  path: '/posts/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnPostsSlugRoute = PublicEnPostsSlugRouteImport.update({
  id: '/_en/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPtInstalacoesIndexRoute =
  PublicPtInstalacoesIndexRouteImport.update({
    id: '/_pt/instalacoes/',
    path: '/instalacoes/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtInstalacoesPregoeiroRoute =
  PublicPtInstalacoesPregoeiroRouteImport.update({
    id: '/_pt/instalacoes/pregoeiro',
    path: '/instalacoes/pregoeiro',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtPublicacoesIndexRoute =
  PublicPtPublicacoesIndexRouteImport.update({
    id: '/_pt/publicacoes/',
    path: '/publicacoes/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPtPublicacoesSlugRoute = PublicPtPublicacoesSlugRouteImport.update({
  id: '/_pt/publicacoes/$slug',
  path: '/publicacoes/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const JournalEditorialArticlesArticleIdRoute =
  JournalEditorialArticlesArticleIdRouteImport.update({
    id: '/articles/$articleId',
    path: '/articles/$articleId',
    getParentRoute: () => JournalEditorialRouteRoute,
  } as any)
const JournalReviewAssignmentAssignmentIdRoute =
  JournalReviewAssignmentAssignmentIdRouteImport.update({
    id: '/review/assignment/$assignmentId',
    path: '/review/assignment/$assignmentId',
    getParentRoute: () => JournalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/alpha': typeof AlphaRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/journal': typeof JournalRouteRouteWithChildren
  '/auth.md': typeof AuthDotmdRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/journal/editorial': typeof JournalEditorialRouteRouteWithChildren
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/alpha/bancada': typeof AlphaBancadaRoute
  '/alpha/fontes': typeof AlphaFontesRoute
  '/journal/about': typeof JournalAboutRoute
  '/journal/profile': typeof JournalProfileRoute
  '/journal/submit': typeof JournalSubmitRoute
  '/auth/': typeof AuthIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/about': typeof PublicEnAboutRoute
  '/chatRada': typeof PublicEnChatRadaRoute
  '/cookie-policy': typeof PublicEnCookiePolicyRoute
  '/innovation-policy': typeof PublicEnInnovationPolicyRoute
  '/overseerDashboard': typeof PublicEnOverseerDashboardRoute
  '/privacy-policy': typeof PublicEnPrivacyPolicyRoute
  '/research': typeof PublicEnResearchRoute
  '/roadmap': typeof PublicEnRoadmapRoute
  '/terms-of-use': typeof PublicEnTermsOfUseRoute
  '/painel-fiscal': typeof PublicPtPainelFiscalRoute
  '/pesquisa': typeof PublicPtPesquisaRoute
  '/politica-de-cookies': typeof PublicPtPoliticaDeCookiesRoute
  '/politica-de-inovacao': typeof PublicPtPoliticaDeInovacaoRoute
  '/politica-de-privacidade': typeof PublicPtPoliticaDePrivacidadeRoute
  '/roteiro': typeof PublicPtRoteiroRoute
  '/sobre': typeof PublicPtSobreRoute
  '/termos-de-uso': typeof PublicPtTermosDeUsoRoute
  '/alpha/analise/$runId': typeof AlphaAnaliseRunIdRoute
  '/alpha/analise/nova': typeof AlphaAnaliseNovaRoute
  '/alpha/modelos/$id': typeof AlphaModelosIdRoute
  '/journal/articles/$id': typeof JournalArticlesIdRoute
  '/journal/editorial/dashboard': typeof JournalEditorialDashboardRoute
  '/journal/editorial/metadata-export': typeof JournalEditorialMetadataExportRoute
  '/journal/editorial/publication': typeof JournalEditorialPublicationRoute
  '/journal/editorial/settings': typeof JournalEditorialSettingsRoute
  '/journal/editorial/volumes': typeof JournalEditorialVolumesRoute
  '/journal/review/$token': typeof JournalReviewTokenRoute
  '/journal/submissions/$id': typeof JournalSubmissionsIdRoute
  '/journal/articles/': typeof JournalArticlesIndexRoute
  '/journal/review/': typeof JournalReviewIndexRoute
  '/journal/submissions/': typeof JournalSubmissionsIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/facilities/pregoeiro': typeof PublicEnFacilitiesPregoeiroRoute
  '/posts/$slug': typeof PublicEnPostsSlugRoute
  '/instalacoes/pregoeiro': typeof PublicPtInstalacoesPregoeiroRoute
  '/publicacoes/$slug': typeof PublicPtPublicacoesSlugRoute
  '/journal/editorial/articles/$articleId': typeof JournalEditorialArticlesArticleIdRoute
  '/journal/review/assignment/$assignmentId': typeof JournalReviewAssignmentAssignmentIdRoute
  '/facilities/': typeof PublicEnFacilitiesIndexRoute
  '/posts/': typeof PublicEnPostsIndexRoute
  '/instalacoes/': typeof PublicPtInstalacoesIndexRoute
  '/publicacoes/': typeof PublicPtPublicacoesIndexRoute
}
export interface FileRoutesByTo {
  '/alpha': typeof AlphaRouteRouteWithChildren
  '/auth.md': typeof AuthDotmdRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/journal/editorial': typeof JournalEditorialRouteRouteWithChildren
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/alpha/bancada': typeof AlphaBancadaRoute
  '/alpha/fontes': typeof AlphaFontesRoute
  '/journal/about': typeof JournalAboutRoute
  '/journal/profile': typeof JournalProfileRoute
  '/journal/submit': typeof JournalSubmitRoute
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthIndexRoute
  '/journal': typeof JournalIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/about': typeof PublicEnAboutRoute
  '/chatRada': typeof PublicEnChatRadaRoute
  '/cookie-policy': typeof PublicEnCookiePolicyRoute
  '/innovation-policy': typeof PublicEnInnovationPolicyRoute
  '/overseerDashboard': typeof PublicEnOverseerDashboardRoute
  '/privacy-policy': typeof PublicEnPrivacyPolicyRoute
  '/research': typeof PublicEnResearchRoute
  '/roadmap': typeof PublicEnRoadmapRoute
  '/terms-of-use': typeof PublicEnTermsOfUseRoute
  '/painel-fiscal': typeof PublicPtPainelFiscalRoute
  '/pesquisa': typeof PublicPtPesquisaRoute
  '/politica-de-cookies': typeof PublicPtPoliticaDeCookiesRoute
  '/politica-de-inovacao': typeof PublicPtPoliticaDeInovacaoRoute
  '/politica-de-privacidade': typeof PublicPtPoliticaDePrivacidadeRoute
  '/roteiro': typeof PublicPtRoteiroRoute
  '/sobre': typeof PublicPtSobreRoute
  '/termos-de-uso': typeof PublicPtTermosDeUsoRoute
  '/alpha/analise/$runId': typeof AlphaAnaliseRunIdRoute
  '/alpha/analise/nova': typeof AlphaAnaliseNovaRoute
  '/alpha/modelos/$id': typeof AlphaModelosIdRoute
  '/journal/articles/$id': typeof JournalArticlesIdRoute
  '/journal/editorial/dashboard': typeof JournalEditorialDashboardRoute
  '/journal/editorial/metadata-export': typeof JournalEditorialMetadataExportRoute
  '/journal/editorial/publication': typeof JournalEditorialPublicationRoute
  '/journal/editorial/settings': typeof JournalEditorialSettingsRoute
  '/journal/editorial/volumes': typeof JournalEditorialVolumesRoute
  '/journal/review/$token': typeof JournalReviewTokenRoute
  '/journal/submissions/$id': typeof JournalSubmissionsIdRoute
  '/journal/articles': typeof JournalArticlesIndexRoute
  '/journal/review': typeof JournalReviewIndexRoute
  '/journal/submissions': typeof JournalSubmissionsIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/facilities/pregoeiro': typeof PublicEnFacilitiesPregoeiroRoute
  '/posts/$slug': typeof PublicEnPostsSlugRoute
  '/instalacoes/pregoeiro': typeof PublicPtInstalacoesPregoeiroRoute
  '/publicacoes/$slug': typeof PublicPtPublicacoesSlugRoute
  '/journal/editorial/articles/$articleId': typeof JournalEditorialArticlesArticleIdRoute
  '/journal/review/assignment/$assignmentId': typeof JournalReviewAssignmentAssignmentIdRoute
  '/facilities': typeof PublicEnFacilitiesIndexRoute
  '/posts': typeof PublicEnPostsIndexRoute
  '/instalacoes': typeof PublicPtInstalacoesIndexRoute
  '/publicacoes': typeof PublicPtPublicacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/alpha': typeof AlphaRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/journal': typeof JournalRouteRouteWithChildren
  '/auth.md': typeof AuthDotmdRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/journal/editorial': typeof JournalEditorialRouteRouteWithChildren
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/alpha/bancada': typeof AlphaBancadaRoute
  '/alpha/fontes': typeof AlphaFontesRoute
  '/journal/about': typeof JournalAboutRoute
  '/journal/profile': typeof JournalProfileRoute
  '/journal/submit': typeof JournalSubmitRoute
  '/_public/': typeof PublicIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/_public/_en/about': typeof PublicEnAboutRoute
  '/_public/_en/chatRada': typeof PublicEnChatRadaRoute
  '/_public/_en/cookie-policy': typeof PublicEnCookiePolicyRoute
  '/_public/_en/innovation-policy': typeof PublicEnInnovationPolicyRoute
  '/_public/_en/overseerDashboard': typeof PublicEnOverseerDashboardRoute
  '/_public/_en/privacy-policy': typeof PublicEnPrivacyPolicyRoute
  '/_public/_en/research': typeof PublicEnResearchRoute
  '/_public/_en/roadmap': typeof PublicEnRoadmapRoute
  '/_public/_en/terms-of-use': typeof PublicEnTermsOfUseRoute
  '/_public/_pt/painel-fiscal': typeof PublicPtPainelFiscalRoute
  '/_public/_pt/pesquisa': typeof PublicPtPesquisaRoute
  '/_public/_pt/politica-de-cookies': typeof PublicPtPoliticaDeCookiesRoute
  '/_public/_pt/politica-de-inovacao': typeof PublicPtPoliticaDeInovacaoRoute
  '/_public/_pt/politica-de-privacidade': typeof PublicPtPoliticaDePrivacidadeRoute
  '/_public/_pt/roteiro': typeof PublicPtRoteiroRoute
  '/_public/_pt/sobre': typeof PublicPtSobreRoute
  '/_public/_pt/termos-de-uso': typeof PublicPtTermosDeUsoRoute
  '/alpha/analise/$runId': typeof AlphaAnaliseRunIdRoute
  '/alpha/analise/nova': typeof AlphaAnaliseNovaRoute
  '/alpha/modelos/$id': typeof AlphaModelosIdRoute
  '/journal/articles/$id': typeof JournalArticlesIdRoute
  '/journal/editorial/dashboard': typeof JournalEditorialDashboardRoute
  '/journal/editorial/metadata-export': typeof JournalEditorialMetadataExportRoute
  '/journal/editorial/publication': typeof JournalEditorialPublicationRoute
  '/journal/editorial/settings': typeof JournalEditorialSettingsRoute
  '/journal/editorial/volumes': typeof JournalEditorialVolumesRoute
  '/journal/review/$token': typeof JournalReviewTokenRoute
  '/journal/submissions/$id': typeof JournalSubmissionsIdRoute
  '/journal/articles/': typeof JournalArticlesIndexRoute
  '/journal/review/': typeof JournalReviewIndexRoute
  '/journal/submissions/': typeof JournalSubmissionsIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/_public/_en/facilities/pregoeiro': typeof PublicEnFacilitiesPregoeiroRoute
  '/_public/_en/posts/$slug': typeof PublicEnPostsSlugRoute
  '/_public/_pt/instalacoes/pregoeiro': typeof PublicPtInstalacoesPregoeiroRoute
  '/_public/_pt/publicacoes/$slug': typeof PublicPtPublicacoesSlugRoute
  '/journal/editorial/articles/$articleId': typeof JournalEditorialArticlesArticleIdRoute
  '/journal/review/assignment/$assignmentId': typeof JournalReviewAssignmentAssignmentIdRoute
  '/_public/_en/facilities/': typeof PublicEnFacilitiesIndexRoute
  '/_public/_en/posts/': typeof PublicEnPostsIndexRoute
  '/_public/_pt/instalacoes/': typeof PublicPtInstalacoesIndexRoute
  '/_public/_pt/publicacoes/': typeof PublicPtPublicacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alpha'
    | '/auth'
    | '/journal'
    | '/auth.md'
    | '/health'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/journal/editorial'
    | '/.well-known/api-catalog'
    | '/alpha/bancada'
    | '/alpha/fontes'
    | '/journal/about'
    | '/journal/profile'
    | '/journal/submit'
    | '/auth/'
    | '/journal/'
    | '/.well-known/agent-skills/index.json'
    | '/about'
    | '/chatRada'
    | '/cookie-policy'
    | '/innovation-policy'
    | '/overseerDashboard'
    | '/privacy-policy'
    | '/research'
    | '/roadmap'
    | '/terms-of-use'
    | '/painel-fiscal'
    | '/pesquisa'
    | '/politica-de-cookies'
    | '/politica-de-inovacao'
    | '/politica-de-privacidade'
    | '/roteiro'
    | '/sobre'
    | '/termos-de-uso'
    | '/alpha/analise/$runId'
    | '/alpha/analise/nova'
    | '/alpha/modelos/$id'
    | '/journal/articles/$id'
    | '/journal/editorial/dashboard'
    | '/journal/editorial/metadata-export'
    | '/journal/editorial/publication'
    | '/journal/editorial/settings'
    | '/journal/editorial/volumes'
    | '/journal/review/$token'
    | '/journal/submissions/$id'
    | '/journal/articles/'
    | '/journal/review/'
    | '/journal/submissions/'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/facilities/pregoeiro'
    | '/posts/$slug'
    | '/instalacoes/pregoeiro'
    | '/publicacoes/$slug'
    | '/journal/editorial/articles/$articleId'
    | '/journal/review/assignment/$assignmentId'
    | '/facilities/'
    | '/posts/'
    | '/instalacoes/'
    | '/publicacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alpha'
    | '/auth.md'
    | '/health'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/journal/editorial'
    | '/.well-known/api-catalog'
    | '/alpha/bancada'
    | '/alpha/fontes'
    | '/journal/about'
    | '/journal/profile'
    | '/journal/submit'
    | '/'
    | '/auth'
    | '/journal'
    | '/.well-known/agent-skills/index.json'
    | '/about'
    | '/chatRada'
    | '/cookie-policy'
    | '/innovation-policy'
    | '/overseerDashboard'
    | '/privacy-policy'
    | '/research'
    | '/roadmap'
    | '/terms-of-use'
    | '/painel-fiscal'
    | '/pesquisa'
    | '/politica-de-cookies'
    | '/politica-de-inovacao'
    | '/politica-de-privacidade'
    | '/roteiro'
    | '/sobre'
    | '/termos-de-uso'
    | '/alpha/analise/$runId'
    | '/alpha/analise/nova'
    | '/alpha/modelos/$id'
    | '/journal/articles/$id'
    | '/journal/editorial/dashboard'
    | '/journal/editorial/metadata-export'
    | '/journal/editorial/publication'
    | '/journal/editorial/settings'
    | '/journal/editorial/volumes'
    | '/journal/review/$token'
    | '/journal/submissions/$id'
    | '/journal/articles'
    | '/journal/review'
    | '/journal/submissions'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/facilities/pregoeiro'
    | '/posts/$slug'
    | '/instalacoes/pregoeiro'
    | '/publicacoes/$slug'
    | '/journal/editorial/articles/$articleId'
    | '/journal/review/assignment/$assignmentId'
    | '/facilities'
    | '/posts'
    | '/instalacoes'
    | '/publicacoes'
  id:
    | '__root__'
    | '/_public'
    | '/alpha'
    | '/auth'
    | '/journal'
    | '/auth.md'
    | '/health'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/journal/editorial'
    | '/.well-known/api-catalog'
    | '/alpha/bancada'
    | '/alpha/fontes'
    | '/journal/about'
    | '/journal/profile'
    | '/journal/submit'
    | '/_public/'
    | '/auth/'
    | '/journal/'
    | '/.well-known/agent-skills/index.json'
    | '/_public/_en/about'
    | '/_public/_en/chatRada'
    | '/_public/_en/cookie-policy'
    | '/_public/_en/innovation-policy'
    | '/_public/_en/overseerDashboard'
    | '/_public/_en/privacy-policy'
    | '/_public/_en/research'
    | '/_public/_en/roadmap'
    | '/_public/_en/terms-of-use'
    | '/_public/_pt/painel-fiscal'
    | '/_public/_pt/pesquisa'
    | '/_public/_pt/politica-de-cookies'
    | '/_public/_pt/politica-de-inovacao'
    | '/_public/_pt/politica-de-privacidade'
    | '/_public/_pt/roteiro'
    | '/_public/_pt/sobre'
    | '/_public/_pt/termos-de-uso'
    | '/alpha/analise/$runId'
    | '/alpha/analise/nova'
    | '/alpha/modelos/$id'
    | '/journal/articles/$id'
    | '/journal/editorial/dashboard'
    | '/journal/editorial/metadata-export'
    | '/journal/editorial/publication'
    | '/journal/editorial/settings'
    | '/journal/editorial/volumes'
    | '/journal/review/$token'
    | '/journal/submissions/$id'
    | '/journal/articles/'
    | '/journal/review/'
    | '/journal/submissions/'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/_public/_en/facilities/pregoeiro'
    | '/_public/_en/posts/$slug'
    | '/_public/_pt/instalacoes/pregoeiro'
    | '/_public/_pt/publicacoes/$slug'
    | '/journal/editorial/articles/$articleId'
    | '/journal/review/assignment/$assignmentId'
    | '/_public/_en/facilities/'
    | '/_public/_en/posts/'
    | '/_public/_pt/instalacoes/'
    | '/_public/_pt/publicacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AlphaRouteRoute: typeof AlphaRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  JournalRouteRoute: typeof JournalRouteRouteWithChildren
  AuthDotmdRoute: typeof AuthDotmdRoute
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha': {
      id: '/alpha'
      path: '/alpha'
      fullPath: '/alpha'
      preLoaderRoute: typeof AlphaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth.md': {
      id: '/auth.md'
      path: '/auth.md'
      fullPath: '/auth.md'
      preLoaderRoute: typeof AuthDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/alpha/bancada': {
      id: '/alpha/bancada'
      path: '/bancada'
      fullPath: '/alpha/bancada'
      preLoaderRoute: typeof AlphaBancadaRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/alpha/fontes': {
      id: '/alpha/fontes'
      path: '/fontes'
      fullPath: '/alpha/fontes'
      preLoaderRoute: typeof AlphaFontesRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/about': {
      id: '/journal/about'
      path: '/about'
      fullPath: '/journal/about'
      preLoaderRoute: typeof JournalAboutRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/editorial': {
      id: '/journal/editorial'
      path: '/editorial'
      fullPath: '/journal/editorial'
      preLoaderRoute: typeof JournalEditorialRouteRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/profile': {
      id: '/journal/profile'
      path: '/profile'
      fullPath: '/journal/profile'
      preLoaderRoute: typeof JournalProfileRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/submit': {
      id: '/journal/submit'
      path: '/submit'
      fullPath: '/journal/submit'
      preLoaderRoute: typeof JournalSubmitRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_en/about': {
      id: '/_public/_en/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicEnAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/chatRada': {
      id: '/_public/_en/chatRada'
      path: '/chatRada'
      fullPath: '/chatRada'
      preLoaderRoute: typeof PublicEnChatRadaRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/cookie-policy': {
      id: '/_public/_en/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof PublicEnCookiePolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/innovation-policy': {
      id: '/_public/_en/innovation-policy'
      path: '/innovation-policy'
      fullPath: '/innovation-policy'
      preLoaderRoute: typeof PublicEnInnovationPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/overseerDashboard': {
      id: '/_public/_en/overseerDashboard'
      path: '/overseerDashboard'
      fullPath: '/overseerDashboard'
      preLoaderRoute: typeof PublicEnOverseerDashboardRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/privacy-policy': {
      id: '/_public/_en/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicEnPrivacyPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/research': {
      id: '/_public/_en/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof PublicEnResearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/roadmap': {
      id: '/_public/_en/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof PublicEnRoadmapRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/terms-of-use': {
      id: '/_public/_en/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof PublicEnTermsOfUseRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/painel-fiscal': {
      id: '/_public/_pt/painel-fiscal'
      path: '/painel-fiscal'
      fullPath: '/painel-fiscal'
      preLoaderRoute: typeof PublicPtPainelFiscalRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/pesquisa': {
      id: '/_public/_pt/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PublicPtPesquisaRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/politica-de-cookies': {
      id: '/_public/_pt/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PublicPtPoliticaDeCookiesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/politica-de-inovacao': {
      id: '/_public/_pt/politica-de-inovacao'
      path: '/politica-de-inovacao'
      fullPath: '/politica-de-inovacao'
      preLoaderRoute: typeof PublicPtPoliticaDeInovacaoRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/politica-de-privacidade': {
      id: '/_public/_pt/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PublicPtPoliticaDePrivacidadeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/roteiro': {
      id: '/_public/_pt/roteiro'
      path: '/roteiro'
      fullPath: '/roteiro'
      preLoaderRoute: typeof PublicPtRoteiroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/sobre': {
      id: '/_public/_pt/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicPtSobreRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/termos-de-uso': {
      id: '/_public/_pt/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof PublicPtTermosDeUsoRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/alpha/analise/$runId': {
      id: '/alpha/analise/$runId'
      path: '/analise/$runId'
      fullPath: '/alpha/analise/$runId'
      preLoaderRoute: typeof AlphaAnaliseRunIdRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/alpha/analise/nova': {
      id: '/alpha/analise/nova'
      path: '/analise/nova'
      fullPath: '/alpha/analise/nova'
      preLoaderRoute: typeof AlphaAnaliseNovaRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/alpha/modelos/$id': {
      id: '/alpha/modelos/$id'
      path: '/modelos/$id'
      fullPath: '/alpha/modelos/$id'
      preLoaderRoute: typeof AlphaModelosIdRouteImport
      parentRoute: typeof AlphaRouteRoute
    }
    '/journal/articles/': {
      id: '/journal/articles/'
      path: '/articles'
      fullPath: '/journal/articles/'
      preLoaderRoute: typeof JournalArticlesIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/articles/$id': {
      id: '/journal/articles/$id'
      path: '/articles/$id'
      fullPath: '/journal/articles/$id'
      preLoaderRoute: typeof JournalArticlesIdRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/editorial/dashboard': {
      id: '/journal/editorial/dashboard'
      path: '/dashboard'
      fullPath: '/journal/editorial/dashboard'
      preLoaderRoute: typeof JournalEditorialDashboardRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/metadata-export': {
      id: '/journal/editorial/metadata-export'
      path: '/metadata-export'
      fullPath: '/journal/editorial/metadata-export'
      preLoaderRoute: typeof JournalEditorialMetadataExportRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/publication': {
      id: '/journal/editorial/publication'
      path: '/publication'
      fullPath: '/journal/editorial/publication'
      preLoaderRoute: typeof JournalEditorialPublicationRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/settings': {
      id: '/journal/editorial/settings'
      path: '/settings'
      fullPath: '/journal/editorial/settings'
      preLoaderRoute: typeof JournalEditorialSettingsRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/editorial/volumes': {
      id: '/journal/editorial/volumes'
      path: '/volumes'
      fullPath: '/journal/editorial/volumes'
      preLoaderRoute: typeof JournalEditorialVolumesRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/review/': {
      id: '/journal/review/'
      path: '/review'
      fullPath: '/journal/review/'
      preLoaderRoute: typeof JournalReviewIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/review/$token': {
      id: '/journal/review/$token'
      path: '/review/$token'
      fullPath: '/journal/review/$token'
      preLoaderRoute: typeof JournalReviewTokenRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/submissions/': {
      id: '/journal/submissions/'
      path: '/submissions'
      fullPath: '/journal/submissions/'
      preLoaderRoute: typeof JournalSubmissionsIndexRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/journal/submissions/$id': {
      id: '/journal/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/journal/submissions/$id'
      preLoaderRoute: typeof JournalSubmissionsIdRouteImport
      parentRoute: typeof JournalRouteRoute
    }
    '/.well-known/agent-skills/$skill/SKILL.md': {
      id: '/.well-known/agent-skills/$skill/SKILL.md'
      path: '/.well-known/agent-skills/$skill/SKILL.md'
      fullPath: '/.well-known/agent-skills/$skill/SKILL.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_en/facilities/': {
      id: '/_public/_en/facilities/'
      path: '/facilities'
      fullPath: '/facilities/'
      preLoaderRoute: typeof PublicEnFacilitiesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/facilities/pregoeiro': {
      id: '/_public/_en/facilities/pregoeiro'
      path: '/facilities/pregoeiro'
      fullPath: '/facilities/pregoeiro'
      preLoaderRoute: typeof PublicEnFacilitiesPregoeiroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/posts/': {
      id: '/_public/_en/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PublicEnPostsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_en/posts/$slug': {
      id: '/_public/_en/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PublicEnPostsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/instalacoes/': {
      id: '/_public/_pt/instalacoes/'
      path: '/instalacoes'
      fullPath: '/instalacoes/'
      preLoaderRoute: typeof PublicPtInstalacoesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/instalacoes/pregoeiro': {
      id: '/_public/_pt/instalacoes/pregoeiro'
      path: '/instalacoes/pregoeiro'
      fullPath: '/instalacoes/pregoeiro'
      preLoaderRoute: typeof PublicPtInstalacoesPregoeiroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/publicacoes/': {
      id: '/_public/_pt/publicacoes/'
      path: '/publicacoes'
      fullPath: '/publicacoes/'
      preLoaderRoute: typeof PublicPtPublicacoesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_pt/publicacoes/$slug': {
      id: '/_public/_pt/publicacoes/$slug'
      path: '/publicacoes/$slug'
      fullPath: '/publicacoes/$slug'
      preLoaderRoute: typeof PublicPtPublicacoesSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/journal/editorial/articles/$articleId': {
      id: '/journal/editorial/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/journal/editorial/articles/$articleId'
      preLoaderRoute: typeof JournalEditorialArticlesArticleIdRouteImport
      parentRoute: typeof JournalEditorialRouteRoute
    }
    '/journal/review/assignment/$assignmentId': {
      id: '/journal/review/assignment/$assignmentId'
      path: '/review/assignment/$assignmentId'
      fullPath: '/journal/review/assignment/$assignmentId'
      preLoaderRoute: typeof JournalReviewAssignmentAssignmentIdRouteImport
      parentRoute: typeof JournalRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEnAboutRoute: typeof PublicEnAboutRoute
  PublicEnChatRadaRoute: typeof PublicEnChatRadaRoute
  PublicEnCookiePolicyRoute: typeof PublicEnCookiePolicyRoute
  PublicEnInnovationPolicyRoute: typeof PublicEnInnovationPolicyRoute
  PublicEnOverseerDashboardRoute: typeof PublicEnOverseerDashboardRoute
  PublicEnPrivacyPolicyRoute: typeof PublicEnPrivacyPolicyRoute
  PublicEnResearchRoute: typeof PublicEnResearchRoute
  PublicEnRoadmapRoute: typeof PublicEnRoadmapRoute
  PublicEnTermsOfUseRoute: typeof PublicEnTermsOfUseRoute
  PublicPtPainelFiscalRoute: typeof PublicPtPainelFiscalRoute
  PublicPtPesquisaRoute: typeof PublicPtPesquisaRoute
  PublicPtPoliticaDeCookiesRoute: typeof PublicPtPoliticaDeCookiesRoute
  PublicPtPoliticaDeInovacaoRoute: typeof PublicPtPoliticaDeInovacaoRoute
  PublicPtPoliticaDePrivacidadeRoute: typeof PublicPtPoliticaDePrivacidadeRoute
  PublicPtRoteiroRoute: typeof PublicPtRoteiroRoute
  PublicPtSobreRoute: typeof PublicPtSobreRoute
  PublicPtTermosDeUsoRoute: typeof PublicPtTermosDeUsoRoute
  PublicEnFacilitiesPregoeiroRoute: typeof PublicEnFacilitiesPregoeiroRoute
  PublicEnPostsSlugRoute: typeof PublicEnPostsSlugRoute
  PublicPtInstalacoesPregoeiroRoute: typeof PublicPtInstalacoesPregoeiroRoute
  PublicPtPublicacoesSlugRoute: typeof PublicPtPublicacoesSlugRoute
  PublicEnFacilitiesIndexRoute: typeof PublicEnFacilitiesIndexRoute
  PublicEnPostsIndexRoute: typeof PublicEnPostsIndexRoute
  PublicPtInstalacoesIndexRoute: typeof PublicPtInstalacoesIndexRoute
  PublicPtPublicacoesIndexRoute: typeof PublicPtPublicacoesIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicEnAboutRoute: PublicEnAboutRoute,
  PublicEnChatRadaRoute: PublicEnChatRadaRoute,
  PublicEnCookiePolicyRoute: PublicEnCookiePolicyRoute,
  PublicEnInnovationPolicyRoute: PublicEnInnovationPolicyRoute,
  PublicEnOverseerDashboardRoute: PublicEnOverseerDashboardRoute,
  PublicEnPrivacyPolicyRoute: PublicEnPrivacyPolicyRoute,
  PublicEnResearchRoute: PublicEnResearchRoute,
  PublicEnRoadmapRoute: PublicEnRoadmapRoute,
  PublicEnTermsOfUseRoute: PublicEnTermsOfUseRoute,
  PublicPtPainelFiscalRoute: PublicPtPainelFiscalRoute,
  PublicPtPesquisaRoute: PublicPtPesquisaRoute,
  PublicPtPoliticaDeCookiesRoute: PublicPtPoliticaDeCookiesRoute,
  PublicPtPoliticaDeInovacaoRoute: PublicPtPoliticaDeInovacaoRoute,
  PublicPtPoliticaDePrivacidadeRoute: PublicPtPoliticaDePrivacidadeRoute,
  PublicPtRoteiroRoute: PublicPtRoteiroRoute,
  PublicPtSobreRoute: PublicPtSobreRoute,
  PublicPtTermosDeUsoRoute: PublicPtTermosDeUsoRoute,
  PublicEnFacilitiesPregoeiroRoute: PublicEnFacilitiesPregoeiroRoute,
  PublicEnPostsSlugRoute: PublicEnPostsSlugRoute,
  PublicPtInstalacoesPregoeiroRoute: PublicPtInstalacoesPregoeiroRoute,
  PublicPtPublicacoesSlugRoute: PublicPtPublicacoesSlugRoute,
  PublicEnFacilitiesIndexRoute: PublicEnFacilitiesIndexRoute,
  PublicEnPostsIndexRoute: PublicEnPostsIndexRoute,
  PublicPtInstalacoesIndexRoute: PublicPtInstalacoesIndexRoute,
  PublicPtPublicacoesIndexRoute: PublicPtPublicacoesIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AlphaRouteRouteChildren {
  AlphaBancadaRoute: typeof AlphaBancadaRoute
  AlphaFontesRoute: typeof AlphaFontesRoute
  AlphaAnaliseRunIdRoute: typeof AlphaAnaliseRunIdRoute
  AlphaAnaliseNovaRoute: typeof AlphaAnaliseNovaRoute
  AlphaModelosIdRoute: typeof AlphaModelosIdRoute
}

const AlphaRouteRouteChildren: AlphaRouteRouteChildren = {
  AlphaBancadaRoute: AlphaBancadaRoute,
  AlphaFontesRoute: AlphaFontesRoute,
  AlphaAnaliseRunIdRoute: AlphaAnaliseRunIdRoute,
  AlphaAnaliseNovaRoute: AlphaAnaliseNovaRoute,
  AlphaModelosIdRoute: AlphaModelosIdRoute,
}

const AlphaRouteRouteWithChildren = AlphaRouteRoute._addFileChildren(
  AlphaRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface JournalEditorialRouteRouteChildren {
  JournalEditorialDashboardRoute: typeof JournalEditorialDashboardRoute
  JournalEditorialMetadataExportRoute: typeof JournalEditorialMetadataExportRoute
  JournalEditorialPublicationRoute: typeof JournalEditorialPublicationRoute
  JournalEditorialSettingsRoute: typeof JournalEditorialSettingsRoute
  JournalEditorialVolumesRoute: typeof JournalEditorialVolumesRoute
  JournalEditorialArticlesArticleIdRoute: typeof JournalEditorialArticlesArticleIdRoute
}

const JournalEditorialRouteRouteChildren: JournalEditorialRouteRouteChildren = {
  JournalEditorialDashboardRoute: JournalEditorialDashboardRoute,
  JournalEditorialMetadataExportRoute: JournalEditorialMetadataExportRoute,
  JournalEditorialPublicationRoute: JournalEditorialPublicationRoute,
  JournalEditorialSettingsRoute: JournalEditorialSettingsRoute,
  JournalEditorialVolumesRoute: JournalEditorialVolumesRoute,
  JournalEditorialArticlesArticleIdRoute:
    JournalEditorialArticlesArticleIdRoute,
}

const JournalEditorialRouteRouteWithChildren =
  JournalEditorialRouteRoute._addFileChildren(
    JournalEditorialRouteRouteChildren,
  )

interface JournalRouteRouteChildren {
  JournalEditorialRouteRoute: typeof JournalEditorialRouteRouteWithChildren
  JournalAboutRoute: typeof JournalAboutRoute
  JournalProfileRoute: typeof JournalProfileRoute
  JournalSubmitRoute: typeof JournalSubmitRoute
  JournalIndexRoute: typeof JournalIndexRoute
  JournalArticlesIdRoute: typeof JournalArticlesIdRoute
  JournalReviewTokenRoute: typeof JournalReviewTokenRoute
  JournalSubmissionsIdRoute: typeof JournalSubmissionsIdRoute
  JournalArticlesIndexRoute: typeof JournalArticlesIndexRoute
  JournalReviewIndexRoute: typeof JournalReviewIndexRoute
  JournalSubmissionsIndexRoute: typeof JournalSubmissionsIndexRoute
  JournalReviewAssignmentAssignmentIdRoute: typeof JournalReviewAssignmentAssignmentIdRoute
}

const JournalRouteRouteChildren: JournalRouteRouteChildren = {
  JournalEditorialRouteRoute: JournalEditorialRouteRouteWithChildren,
  JournalAboutRoute: JournalAboutRoute,
  JournalProfileRoute: JournalProfileRoute,
  JournalSubmitRoute: JournalSubmitRoute,
  JournalIndexRoute: JournalIndexRoute,
  JournalArticlesIdRoute: JournalArticlesIdRoute,
  JournalReviewTokenRoute: JournalReviewTokenRoute,
  JournalSubmissionsIdRoute: JournalSubmissionsIdRoute,
  JournalArticlesIndexRoute: JournalArticlesIndexRoute,
  JournalReviewIndexRoute: JournalReviewIndexRoute,
  JournalSubmissionsIndexRoute: JournalSubmissionsIndexRoute,
  JournalReviewAssignmentAssignmentIdRoute:
    JournalReviewAssignmentAssignmentIdRoute,
}

const JournalRouteRouteWithChildren = JournalRouteRoute._addFileChildren(
  JournalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AlphaRouteRoute: AlphaRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  JournalRouteRoute: JournalRouteRouteWithChildren,
  AuthDotmdRoute: AuthDotmdRoute,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute:
    DotwellKnownAgentSkillsSkillSKILLDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
