import type { ChecklistItem, Notice, Tool, UnitResponsibility } from "#/lib/types"

// Utility: N-th business day of current month → formatted date string
export function getNthBusinessDay(n: string): string {
	const match = n.match(/(\d+)/)
	if (!match) return n
	const target = parseInt(match[1], 10)
	const now = new Date()
	const year = now.getFullYear()
	const month = now.getMonth()
	let count = 0
	let day = 1
	while (day <= 31) {
		const date = new Date(year, month, day)
		if (date.getMonth() !== month) break
		const dow = date.getDay()
		if (dow !== 0 && dow !== 6) {
			count++
			if (count === target) return date.toLocaleDateString("pt-BR")
		}
		day++
	}
	return n
}

export const sucontTools: Tool[] = [
	{
		id: "auditor",
		title: "Auditor SUCONT-4",
		description: "Ferramenta principal de auditoria e análise de dados.",
		internalPath: "/auditor",
		stage: "analisar",
		icon: "ShieldCheck",
		iconColor: "bg-tech-blue",
	},
	{
		id: "monitoramento",
		title: "Monitoramento Patrimonial",
		description: "Acompanhamento em tempo real de conformidade patrimonial.",
		internalPath: "/monitoramento",
		stage: "acompanhar",
		icon: "Activity",
		iconColor: "bg-tech-cyan",
	},
	{
		id: "plataforma-doc",
		title: "Plataforma de Automação de Documentação",
		description: "Sistema centralizado para geração e gestão automatizada de documentos.",
		url: "/documentacao",
		internalPath: "/documentacao",
		stage: "comunicar",
		icon: "Zap",
		iconColor: "bg-success",
	},
	{
		id: "sau-chatbot",
		title: "Chatbot SAU",
		description: "Assistente inteligente para suporte administrativo unificado.",
		url: "https://notebooklm.google.com/notebook/69f8cb5d-7656-42b2-91f1-36d998b02a37?authuser=1",
		stage: "consultar",
		icon: "MessageSquare",
		iconColor: "bg-tech-blue",
	},
	{
		id: "siafi-automate",
		title: "MSG SIAFI Automate",
		description: "Automação de mensagens e processos do sistema SIAFI.",
		url: "https://notebooklm.google.com/notebook/f3995b07-12af-45bf-89b6-451723cfefb4?authuser=1",
		stage: "comunicar",
		icon: "Terminal",
		iconColor: "bg-tech-blue",
	},
	{
		id: "oficios-automate",
		title: "Automação de Ofícios",
		description: "Sistema de auxílio na geração e padronização de ofícios.",
		url: "https://notebooklm.google.com/notebook/2f39d31e-a0c6-435c-9c6f-00ae19039138?authuser=1",
		stage: "comunicar",
		icon: "FileText",
		iconColor: "bg-success",
	},
	{
		id: "manual-interno",
		title: "Manual Interno SUCONT-4",
		description: "Diretrizes e procedimentos internos da seção.",
		url: "https://docs.google.com/document/d/1E0rUh29RAmq7mEbJl50xKfA63szBv7kDwXLmTfocOWg/edit?tab=t.n2lgxw4p7bn1#heading=h.vlw5v11g3kkn",
		stage: "consultar",
		icon: "FileText",
		iconColor: "bg-muted-foreground",
	},
	{
		id: "radae-manuais",
		title: "Manuais Eletrônicos do RADA-e",
		description: "Repositório oficial de manuais eletrônicos da DIREF.",
		url: "http://www.diref.intraer/index.php/servicos/manuais/manuais",
		stage: "consultar",
		icon: "BookOpen",
		iconColor: "bg-tech-blue",
	},
	{
		id: "chatbot-oficio-cabw",
		title: "Chatbot Ofício CABW",
		description: "Assistente para elaboração de ofícios da CABW.",
		url: "https://notebooklm.google.com/notebook/23333c8a-aa7a-4405-8156-fb893398a1da",
		stage: "comunicar",
		icon: "MessageSquare",
		iconColor: "bg-tech-blue",
	},
	{
		id: "chatbot-aut-oficios",
		title: "Chatbot Automação de Ofícios",
		description: "IA para auxílio na gestão e criação de ofícios.",
		url: "https://notebooklm.google.com/notebook/2f39d31e-a0c6-435c-9c6f-00ae19039138",
		stage: "comunicar",
		icon: "Cpu",
		iconColor: "bg-success",
	},
	{
		id: "chatbot-tcu",
		title: "Chatbot Auditoria TCU",
		description: "Assistente especializado em normas e auditorias do TCU.",
		url: "https://notebooklm.google.com/notebook/e3ad873a-f9fd-44e0-8f50-1d7f39c06c46",
		stage: "consultar",
		icon: "ShieldCheck",
		iconColor: "bg-tech-blue",
	},
	{
		id: "fab-sucont-chatbot",
		title: "Chatbot FAB/SUCONT-4",
		description: "Assistente especializado em normas da FAB e SUCONT-4.",
		url: "https://notebooklm.google.com/notebook/2ea19b26-e16b-45b8-9aad-22f58d3b457a?authuser=1",
		stage: "consultar",
		icon: "Cpu",
		iconColor: "bg-tech-cyan",
	},
	{
		id: "subitens-genericos",
		title: "Subitens Genéricos (Q34)",
		description:
			"Análise automatizada de subitens genéricos (99/999) no Tesouro Gerencial — Questão 34 do Roteiro de Acompanhamento Contábil. Geração de mensagens institucionais e Oráculo IA.",
		internalPath: "/subitens-genericos",
		stage: "analisar",
		racQuestions: [34],
		icon: "FileBarChart",
		iconColor: "bg-fab-blue",
	},
	{
		id: "cruzamento-contas",
		title: "Cruzamento de Contas (Q43)",
		description: "Análise automatizada de espelhamento entre as contas 897210300 e 897110300 — Questão 43 do Roteiro SUCONT-3.",
		internalPath: "/cruzamento-contas",
		stage: "analisar",
		racQuestions: [43],
		icon: "BarChart3",
		iconColor: "bg-tech-blue",
	},
	{
		id: "analista-compatibilidade",
		title: "Analista de Compatibilidade (Q40–Q42)",
		description:
			"Análise automatizada de incompatibilidade de saldos entre contas contábeis — Questões 40, 41 e 42 do Roteiro SUCONT-3. Geração de mensagens institucionais.",
		internalPath: "/analista-compatibilidade",
		stage: "analisar",
		racQuestions: [40, 41, 42],
		icon: "Scale",
		iconColor: "bg-tech-blue",
	},
	{
		id: "conta-generica",
		title: "Analista Conta Genérica (Q35)",
		description:
			"Identificação de uso indevido de contas contábeis genéricas pelas UGs — Questão 35 do Roteiro SUCONT-3. Geração de mensagens institucionais e Oráculo IA.",
		internalPath: "/conta-generica",
		stage: "analisar",
		racQuestions: [35],
		icon: "Search",
		iconColor: "bg-action",
	},
	{
		id: "analistasaldoalongado",
		title: "Analista Saldo Alongado",
		description:
			"Análise de contas com saldo sem movimentação superior a 3 meses — Questões Q05 a Q25 do Roteiro de Acompanhamento Contábil (RAC). Geração de mensagens institucionais.",
		internalPath: "/analistasaldoalongado",
		stage: "analisar",
		racQuestions: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
		icon: "Activity",
		iconColor: "bg-fab-600",
	},
	{
		id: "sac-dgc",
		title: "SAC-DGC — Análise Crítica do DGC",
		description:
			"Análise crítica do Demonstrativo Gerencial de Custos por Unidade Gestora, sobre os quatro painéis do Tesouro Gerencial. Alertas de criticidade e Checklist AEC gerados por IA à luz dos Módulos 19 e 22.",
		internalPath: "/sac-dgc",
		stage: "analisar",
		icon: "FileSearch",
		iconColor: "bg-tech-cyan",
	},
	{
		id: "sau-system",
		title: "SAU's",
		description: "Sistema de Atendimento Unificado.",
		url: "http://sau.servicos.ccarj.intraer/sau/consumer",
		stage: "consultar",
		icon: "Ticket",
	},
	{
		id: "sigadaer",
		title: "Sigadaer",
		description: "Informações Gerenciais.",
		url: "https://app.sigadaer.intraer/",
		stage: "comunicar",
		icon: "Globe",
	},
	{
		id: "siafi-web",
		title: "Siafi Web",
		description: "Portal do Tesouro.",
		url: "https://siafi.tesouro.gov.br/senha/public/pages/security/login.jsf",
		stage: "consultar",
		icon: "Banknote",
	},
	{
		id: "siloms-contabil",
		title: "Siloms Contábil",
		description: "Prestação de contas.",
		url: "http://siloms.servicos.ccarj.intraer/siloms-prestacao/faces/index.xhtml",
		stage: "consultar",
		icon: "Calculator",
	},
	{
		id: "siloms-mac",
		title: "SILOMS MAC",
		description: "Sistema Integrado de Logística.",
		url: "https://mac1.siloms.intraer/siloms_mac/servlet/aqs01001w",
		stage: "consultar",
		icon: "Plane",
	},
	{
		id: "tesouro-gerencial",
		title: "Tesouro Gerencial",
		description: "Relatórios gerenciais.",
		url: "https://tesourogerencial.tesouro.gov.br/tg/servlet/mstrWeb?pg=login&v=1772494208370",
		stage: "consultar",
		icon: "Monitor",
	},
	{
		id: "saldos-siloms",
		title: "Saldos Patrimoniais SILOMS",
		description: "Consulta de saldos executivos no SILOMS.",
		url: "http://siloms.servicos.ccarj.intraer/siloms-prestacao/faces/patSaldosComaerExec.xhtml",
		stage: "acompanhar",
		icon: "Database",
	},
	{
		id: "saldos-siafi",
		title: "Saldos Patrimoniais SIAFI",
		description: "Consulta de saldos no Tesouro Gerencial/SIAFI.",
		url: "https://tesourogerencial.tesouro.gov.br/tg/servlet/mstrWeb",
		stage: "acompanhar",
		icon: "FileBarChart",
	},
]

export const initialChecklist: ChecklistItem[] = [
	{
		id: "xml-deprec",
		task: "Verificação de Carga de XML de Depreciação",
		deadline: "2º dia útil do mês",
		description: "Confirmar se cada UG realizou a carga do arquivo XML de depreciação e baixa de bens. Cobrar as UGs que não cumpriram o prazo.",
		responsible: "Cada Responsável",
		path: "Tesouro Gerencial: Sucont-4.1 > Monitoramento das UG > Acomp. registro da depreciação e amortização mensal por UG",
	},
	{
		id: "relat-deprec",
		task: "Relatório Depreciação > Bem",
		deadline: "4° dia útil do mês",
		description:
			"Comparar o saldo de depreciação acumulada com o saldo do bem no SIAFI. Identificar e reportar UGs com saldo de depreciação superior ao valor contábil do bem.",
		responsible: "Cada Responsável",
		path: "Tesouro Gerencial: Sucont-4.1 > Monitoramento das UG > CONSOLIDADA - COMP BENS MÓVEIS E DEP ACUM",
	},
	{
		id: "prest-contas",
		task: "Prestação de Contas",
		deadline: "4° dia útil do mês",
		description: "Acompanhamento do fechamento SIAFI.",
		responsible: "Vanessa",
	},
	{
		id: "restr-contabil",
		task: "Relatório Restrição Contábil",
		deadline: "4° dia útil do mês",
		description: "Pós fechamento SIAFI e Relatório de Depreciação.",
		responsible: "Klebson",
	},
	{
		id: "conc-transito",
		task: "Conciliação Mensal de Contas de Trânsito",
		deadline: "Mensal",
		description: "Verificar discrepâncias entre Conta de trânsito (1.2.3.1.1.99.05) e Conta de controle (899920202).",
		responsible: "Cada Responsável",
		path: "Tesouro Gerencial: Sucont-4 > Relatórios para Consultas por UG EXEC Parciais > Auditor de documento - compatibilidade controle x transito de BMP",
	},
	{
		id: "pos-prest",
		task: "Acompanhamento Pós-Prestação de Contas",
		deadline: "1x por semana",
		description: "Priorizar análise das UGs com maiores diferenças contábeis e solicitar ajustes formais.",
		responsible: "Cada Responsável",
	},
	{
		id: "contas-conc",
		task: "Monitoramento de Contas Conciliadas (TCU)",
		deadline: "1x por semana",
		description: "Verificar mensalmente as contas 1.2.3.1.1.01.15, 1.2.3.1.1.02.01, 1.2.3.1.1.05.03, 1.2.3.1.1.05.05, 1.2.3.1.1.05.06.",
		responsible: "SGT KLEBSON, 3S VANESSA, SGT IARA",
	},
]

export const initialNotices: Notice[] = [
	{
		id: "notice-1",
		content: "Reunião de alinhamento mensal agendada para o 1º dia útil.",
		date: "01/03/2026",
		type: "info",
	},
	{
		id: "notice-2",
		content: "Lembrete: Prazo final para carga de XML de depreciação se aproxima.",
		date: "02/03/2026",
		type: "alert",
	},
]

export const unitResponsibilities: UnitResponsibility[] = [
	{ code: "120005", name: "PABR", operator: "3S VANESSA" },
	{ code: "120007", name: "PARF", operator: "3S VANESSA" },
	{ code: "120013", name: "CLA", operator: "3S VANESSA" },
	{ code: "120014", name: "BAFZ", operator: "3S VANESSA" },
	{ code: "120019", name: "HARF", operator: "3S VANESSA" },
	{ code: "120029", name: "BAAF", operator: "3S VANESSA" },
	{ code: "120030", name: "BAGL", operator: "3S VANESSA" },
	{ code: "120049", name: "PAMA GL", operator: "3S VANESSA" },
	{ code: "120062", name: "BASP", operator: "3S VANESSA" },
	{ code: "120065", name: "FAYS", operator: "3S VANESSA" },
	{ code: "120069", name: "CRCEA-SE", operator: "3S VANESSA" },
	{ code: "120071", name: "CELOG", operator: "3S VANESSA" },
	{ code: "120075", name: "BACO", operator: "3S VANESSA" },
	{ code: "120077", name: "HACO", operator: "3S VANESSA" },
	{ code: "120087", name: "BABE", operator: "3S VANESSA" },
	{ code: "120091", name: "CABE", operator: "3S VANESSA" },
	{ code: "120094", name: "CINDACTA IV", operator: "3S VANESSA" },
	{ code: "120096", name: "HFAB", operator: "3S VANESSA" },
	{ code: "120108", name: "COPAC", operator: "3S VANESSA" },
	{ code: "120195", name: "CAE", operator: "3S VANESSA" },
	{ code: "120260", name: "SERINFRA BR", operator: "3S VANESSA" },
	{ code: "120623", name: "GAP AF", operator: "3S VANESSA" },
	{ code: "120624", name: "BAAN", operator: "3S VANESSA" },
	{ code: "120630", name: "GAP MN", operator: "3S VANESSA" },
	{ code: "120636", name: "GAP LS", operator: "3S VANESSA" },
	{ code: "120637", name: "BABV", operator: "3S VANESSA" },
	{ code: "120641", name: "BAPV", operator: "3S VANESSA" },
	{ code: "120645", name: "GAP GL", operator: "3S VANESSA" },
	{ code: "120001", name: "GABAER", operator: "SGT KLEBSON" },
	{ code: "120006", name: "GAP BR", operator: "SGT KLEBSON" },
	{ code: "120008", name: "CINDACTA I", operator: "SGT KLEBSON" },
	{ code: "120015", name: "CLBI", operator: "SGT KLEBSON" },
	{ code: "120039", name: "GAP RJ", operator: "SGT KLEBSON" },
	{ code: "120040", name: "HCA", operator: "SGT KLEBSON" },
	{ code: "120045", name: "PAGL", operator: "SGT KLEBSON" },
	{ code: "120047", name: "PAMB RJ", operator: "SGT KLEBSON" },
	{ code: "120048", name: "PAME RJ", operator: "SGT KLEBSON" },
	{ code: "120066", name: "HFASP", operator: "SGT KLEBSON" },
	{ code: "120068", name: "PAMA SP", operator: "SGT KLEBSON" },
	{ code: "120072", name: "CINDACTA II", operator: "SGT KLEBSON" },
	{ code: "120073", name: "BAFL", operator: "SGT KLEBSON" },
	{ code: "120082", name: "BAMN", operator: "SGT KLEBSON" },
	{ code: "120154", name: "HAMN", operator: "SGT KLEBSON" },
	{ code: "120225", name: "SERINFRA SJ", operator: "SGT KLEBSON" },
	{ code: "120255", name: "SERINFRA BE", operator: "SGT KLEBSON" },
	{ code: "120259", name: "SERINFRA CO", operator: "SGT KLEBSON" },
	{ code: "120261", name: "SERINFRA MN", operator: "SGT KLEBSON" },
	{ code: "120512", name: "PASJ", operator: "SGT KLEBSON" },
	{ code: "120628", name: "GAP BE", operator: "SGT KLEBSON" },
	{ code: "120631", name: "BANT", operator: "SGT KLEBSON" },
	{ code: "120638", name: "BACG", operator: "SGT KLEBSON" },
	{ code: "120643", name: "BASM", operator: "SGT KLEBSON" },
	{ code: "120004", name: "BABR", operator: "3S TALITA" },
	{ code: "120016", name: "GAP SJ", operator: "3S TALITA" },
	{ code: "120021", name: "CINDACTA III", operator: "3S TALITA" },
	{ code: "120023", name: "BASV", operator: "3S TALITA" },
	{ code: "120025", name: "EPCAR", operator: "3S TALITA" },
	{ code: "120026", name: "PAMA LS", operator: "3S TALITA" },
	{ code: "120041", name: "HAAF", operator: "3S TALITA" },
	{ code: "120042", name: "HFAG", operator: "3S TALITA" },
	{ code: "120053", name: "PAAF", operator: "3S TALITA" },
	{ code: "120060", name: "AFA", operator: "3S TALITA" },
	{ code: "120061", name: "BAST", operator: "3S TALITA" },
	{ code: "120064", name: "EEAR", operator: "3S TALITA" },
	{ code: "120088", name: "COMARA", operator: "3S TALITA" },
	{ code: "120089", name: "HABE", operator: "3S TALITA" },
	{ code: "120090", name: "CABW", operator: "3S TALITA" },
	{ code: "120097", name: "PASP", operator: "3S TALITA" },
	{ code: "120099", name: "DIRINFRA", operator: "3S TALITA" },
	{ code: "120100", name: "SDAB", operator: "3S TALITA" },
	{ code: "120127", name: "CISCEA", operator: "3S TALITA" },
	{ code: "120152", name: "CPBV", operator: "3S TALITA" },
	{ code: "120257", name: "SERINFRA RJ", operator: "3S TALITA" },
	{ code: "120265", name: "SERINFRA NT", operator: "3S TALITA" },
	{ code: "120625", name: "GAP DF", operator: "3S TALITA" },
	{ code: "120629", name: "GAP CO", operator: "3S TALITA" },
	{ code: "120632", name: "GAP RF", operator: "3S TALITA" },
	{ code: "120633", name: "GAP SP", operator: "3S TALITA" },
	{ code: "120669", name: "BASC", operator: "3S TALITA" },
]
