/**
 * SQL safety layer for analytics queries.
 *
 * All queries generated by the LLM are validated here before execution:
 * - Only SELECT / WITH ... SELECT allowed
 * - DML / DDL keywords blocked
 * - Table whitelist enforced on EVERY relation reference (FROM/JOIN and comma lists)
 * - Function calls restricted to an allow-list; schema-qualified calls rejected
 * - An outer LIMIT 500 is always applied at execution
 *
 * Esta camada NÃO é a fronteira de segurança. Quem segura é o banco: a RPC roda como
 * `analytics_reader` (SELECT só nestas tabelas, sem EXECUTE em função de aplicação, em
 * transação somente leitura — migration 20260921130000). A validação aqui existe para
 * devolver ao modelo um erro legível, antes do `permission denied`.
 */

const MAX_QUERY_LENGTH = 4000
const MAX_LIMIT = 500

const ALLOWED_TABLES = new Set([
	"meal_forecasts",
	"meal_presences",
	"units",
	"mess_halls",
	"kitchen",
	"daily_menu",
	"menu_items",
	"recipes",
	"procurement_list",
	"procurement_list_item",
	"procurement_arp_item",
	"empenho",
	"ingredient",
	"production_task",
	"meal_type",
	"recipe_ingredients",
	"v_meal_presences_with_user",
	"v_user_identity",
])

/** Schemas em que as tabelas liberadas moram — o `search_path` da RPC. */
const ALLOWED_SCHEMAS = new Set(["core", "kitchen", "procurement", "finance"])

/** Funções que o assistente usa para agregar e formatar. Chamada fora daqui é recusada. */
const ALLOWED_FUNCTIONS = new Set([
	"count",
	"sum",
	"avg",
	"min",
	"max",
	"coalesce",
	"nullif",
	"greatest",
	"least",
	"round",
	"floor",
	"ceil",
	"ceiling",
	"abs",
	"trunc",
	"date_trunc",
	"date_part",
	"extract",
	"to_char",
	"to_date",
	"make_date",
	"age",
	"lower",
	"upper",
	"trim",
	"length",
	"concat",
	"substring",
	"left",
	"right",
	"replace",
	"split_part",
	"initcap",
	"string_agg",
	"array_agg",
	"row_number",
	"rank",
	"dense_rank",
	"ntile",
	"lag",
	"lead",
	"first_value",
	"last_value",
	"percentile_cont",
	"percentile_disc",
	"stddev",
	"variance",
	"bool_and",
	"bool_or",
	"generate_series",
	"cast",
])

/** Palavras-chave que legitimamente vêm antes de "(" sem serem chamada de função. */
const KEYWORDS_BEFORE_PAREN = new Set([
	"select",
	"from",
	"join",
	"where",
	"in",
	"exists",
	"any",
	"all",
	"some",
	"as",
	"over",
	"filter",
	"group",
	"values",
	"and",
	"or",
	"not",
	"on",
	"using",
	"when",
	"then",
	"else",
	"distinct",
	"union",
	"intersect",
	"except",
	"row",
	"array",
	"limit",
	"offset",
	"having",
	"by",
	"between",
	"like",
	"ilike",
	"is",
	"case",
	"end",
	"with",
])

/**
 * Palavras que encerram a lista de relações de um FROM (no mesmo nível de parênteses).
 * `ON`/`USING`/`JOIN` NÃO encerram: `FROM a JOIN b ON a.x = b.x, core.user_data d` continua
 * sendo lista de relações depois da condição — vírgula no nível do FROM só pode abrir outra
 * relação (dentro de expressão ela fica num nível de parênteses mais fundo).
 */
const FROM_LIST_TERMINATORS = new Set(["where", "group", "order", "limit", "having", "union", "intersect", "except", "offset", "fetch"])

const BLOCKED_KEYWORDS = [
	"INSERT",
	"UPDATE",
	"DELETE",
	"DROP",
	"TRUNCATE",
	"ALTER",
	"COPY",
	"$$",
	"EXECUTE",
	"CALL",
	"GRANT",
	"REVOKE",
	"INTO",
	"LATERAL",
	"MERGE",
	"LOCK",
	"SET",
	// `TABLE x` é relação sem FROM; `WINDOW nome AS (...)` se confundia com nome de CTE.
	"TABLE",
	"WINDOW",
]

type Token = { kind: "ident" | "string" | "number" | "punct"; value: string }

/**
 * Tokenizador mínimo. Recusa (retorna string de erro) o que abriria ambiguidade entre o que
 * o validador lê e o que o Postgres executa: comentário, dollar-quoting, string com escape
 * (E'…', U&'…') e identificador entre aspas com caractere fora de [A-Za-z0-9_].
 */
function tokenize(sql: string): Token[] | string {
	const tokens: Token[] = []
	let i = 0
	while (i < sql.length) {
		const ch = sql[i]
		if (/\s/.test(ch)) {
			i++
			continue
		}
		if (sql.startsWith("--", i) || sql.startsWith("/*", i)) return "Comentários não são permitidos"
		if (ch === "$" || ch === "\\" || ch === "`") return `Caractere não permitido: ${ch}`
		if (ch === "'") {
			const prev = tokens.at(-1)
			if (prev?.kind === "ident" && /^(e|u&|b|x|n)$/i.test(prev.value)) return "Strings com prefixo não são permitidas"
			let j = i + 1
			let value = ""
			while (j < sql.length) {
				if (sql[j] === "'") {
					if (sql[j + 1] === "'") {
						value += "'"
						j += 2
						continue
					}
					break
				}
				value += sql[j]
				j++
			}
			if (j >= sql.length) return "String não terminada"
			tokens.push({ kind: "string", value })
			i = j + 1
			continue
		}
		if (ch === '"') {
			const close = sql.indexOf('"', i + 1)
			if (close === -1) return "Identificador não terminado"
			const value = sql.slice(i + 1, close)
			if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)) return "Identificador entre aspas inválido"
			tokens.push({ kind: "ident", value: value.toLowerCase() })
			i = close + 1
			continue
		}
		const ident = /^[A-Za-z_][A-Za-z0-9_]*/.exec(sql.slice(i))
		if (ident) {
			tokens.push({ kind: "ident", value: ident[0].toLowerCase() })
			i += ident[0].length
			continue
		}
		const num = /^[0-9]+(\.[0-9]+)?/.exec(sql.slice(i))
		if (num) {
			tokens.push({ kind: "number", value: num[0] })
			i += num[0].length
			continue
		}
		if (sql.startsWith("::", i)) {
			tokens.push({ kind: "punct", value: "::" })
			i += 2
			continue
		}
		tokens.push({ kind: "punct", value: ch })
		i++
	}
	return tokens
}

/** Nome de CTE declarado em `WITH nome AS (` ou `, nome AS (`. */
function collectCteNames(tokens: Token[]): Set<string> {
	const names = new Set<string>()
	for (let i = 0; i + 2 < tokens.length; i++) {
		const [a, b, c] = [tokens[i], tokens[i + 1], tokens[i + 2]]
		if (a.kind === "ident" && b.kind === "ident" && b.value === "as" && c.value === "(") {
			const prev = tokens[i - 1]
			if (prev && (prev.value === "with" || prev.value === ",")) names.add(a.value)
		}
	}
	return names
}

/** Lê uma referência de relação a partir de `i`; devolve o erro, se houver. */
function checkRelationAt(tokens: Token[], i: number, cteNames: Set<string>): string | null {
	const first = tokens[i]
	if (!first) return "Relação ausente"
	if (first.value === "(") return null // subquery — validada pelo resto da varredura
	if (first.kind !== "ident") return `Relação inválida: ${first.value}`
	let schema: string | null = null
	let table = first.value
	if (tokens[i + 1]?.value === "." && tokens[i + 2]?.kind === "ident") {
		schema = first.value
		table = tokens[i + 2].value
	}
	if (tokens[schema ? i + 3 : i + 1]?.value === "(") return `Função como relação não permitida: ${table}`
	if (schema && !ALLOWED_SCHEMAS.has(schema)) return `Tabela não permitida: ${table}`
	if (!schema && cteNames.has(table)) return null
	if (!ALLOWED_TABLES.has(table)) return `Tabela não permitida: ${table}`
	return null
}

export function validateSql(sql: string): { valid: boolean; error?: string } {
	if (!sql?.trim()) return { valid: false, error: "SQL vazio" }

	const normalized = sql.trim().replace(/;$/, "")
	const up = normalized.toUpperCase()

	if (normalized.length > MAX_QUERY_LENGTH) return { valid: false, error: "SQL muito longa" }

	// Only SELECT or WITH … SELECT (CTEs)
	if (!up.startsWith("SELECT") && !up.startsWith("WITH")) {
		return { valid: false, error: "Apenas SELECT permitido" }
	}

	if (normalized.includes(";")) {
		return { valid: false, error: "Múltiplas instruções não são permitidas" }
	}

	// Block DML / DDL — no texto cru, de propósito conservador (inclusive dentro de string).
	for (const kw of BLOCKED_KEYWORDS) {
		if (kw === "$$" ? up.includes(kw) : new RegExp(`\\b${kw}\\b`, "i").test(normalized)) {
			return { valid: false, error: `Keyword proibida: ${kw}` }
		}
	}

	const tokens = tokenize(normalized)
	if (typeof tokens === "string") return { valid: false, error: tokens }

	const cteNames = collectCteNames(tokens)

	// Contexto por nível de parênteses: dentro da lista de relações de um FROM?
	const inFromList: boolean[] = [false]
	let depth = 0

	for (let i = 0; i < tokens.length; i++) {
		const token = tokens[i]
		const prev = tokens[i - 1]

		if (token.value === "(") {
			depth++
			inFromList[depth] = false
			continue
		}
		if (token.value === ")") {
			inFromList[depth] = false
			depth = Math.max(0, depth - 1)
			continue
		}

		if (token.kind === "ident") {
			// Catálogo e funções de sistema: nada de pg_* nem information_schema.
			if (token.value.startsWith("pg_") || token.value === "information_schema") {
				return { valid: false, error: `Identificador não permitido: ${token.value}` }
			}

			if (token.value === "from" || token.value === "join") {
				// `EXTRACT(x FROM y)` e `SUBSTRING(a FROM b)` usam FROM sem ser relação.
				const opener = findOpenerFunction(tokens, i)
				if (token.value === "from" && opener && (opener === "extract" || opener === "substring" || opener === "trim")) continue
				const err = checkRelationAt(tokens, i + 1, cteNames)
				if (err) return { valid: false, error: err }
				inFromList[depth] = true
				continue
			}

			if (FROM_LIST_TERMINATORS.has(token.value)) inFromList[depth] = false

			if (tokens[i + 1]?.value === "(") {
				if (prev?.value === ".") return { valid: false, error: `Função qualificada não permitida: ${token.value}` }
				const isType = prev?.value === "::" || prev?.value === "as"
				if (!isType && !ALLOWED_FUNCTIONS.has(token.value) && !KEYWORDS_BEFORE_PAREN.has(token.value)) {
					return { valid: false, error: `Função não permitida: ${token.value}` }
				}
			}
			continue
		}

		if (token.value === "," && inFromList[depth]) {
			const err = checkRelationAt(tokens, i + 1, cteNames)
			if (err) return { valid: false, error: err }
		}
	}

	const limitMatches = [...normalized.matchAll(/\bLIMIT\s+(\d+)\b/gi)]
	for (const [, rawLimit] of limitMatches) {
		if (Number(rawLimit) > MAX_LIMIT) {
			return { valid: false, error: `LIMIT máximo permitido: ${MAX_LIMIT}` }
		}
	}

	return { valid: true }
}

/** Nome da função cujo "(" envolve a posição `i` no mesmo nível, se houver. */
function findOpenerFunction(tokens: Token[], i: number): string | null {
	let depth = 0
	for (let j = i - 1; j >= 0; j--) {
		const v = tokens[j].value
		if (v === ")") depth++
		else if (v === "(") {
			if (depth === 0) return tokens[j - 1]?.kind === "ident" ? tokens[j - 1].value : null
			depth--
		}
	}
	return null
}

export async function executeSql(sql: string): Promise<Record<string, unknown>[]> {
	const { getSupabaseServerClient } = await import("@/lib/supabase.server")

	// LIMIT externo SEMPRE: `LIMIT ALL` ou `FETCH FIRST n` dentro da query não furam o teto,
	// porque a RPC agrega o resultado inteiro num jsonb só.
	const trimmedSql = sql.trim().replace(/;$/, "")
	const safeSql = `SELECT * FROM (${trimmedSql}) AS analytics_q LIMIT ${MAX_LIMIT}`

	const { data, error } = await getSupabaseServerClient().rpc("execute_analytics_query", {
		query: safeSql,
	})
	if (error) throw new Error(error.message)

	return Array.isArray(data) ? (data as Record<string, unknown>[]) : []
}
