export const UG_INFO: Record<string, { sigla: string; ods: string; orgaoSuperior: string }> = {
	// SEFA
	"120002": { sigla: "DIREF", ods: "SEFA", orgaoSuperior: "SEFA" },
	"120005": { sigla: "PABR", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120006": { sigla: "GAP-BR", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120007": { sigla: "PARF", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120039": { sigla: "GAP-RJ", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120044": { sigla: "BREVET", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120045": { sigla: "PAGL", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120052": { sigla: "SDPP/PAÍS", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120053": { sigla: "PAAF", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120065": { sigla: "FAYS", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120093": { sigla: "SDPP/EXTERIOR", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120097": { sigla: "PASP", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120100": { sigla: "SDAB", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120195": { sigla: "CAE", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120279": { sigla: "RANCHO-DIRAD", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120623": { sigla: "GAP-AF", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120625": { sigla: "GAP-DF", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120628": { sigla: "GAP-BE", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120629": { sigla: "GAP-CO", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120630": { sigla: "GAP-MN", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120632": { sigla: "GAP-RF", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120633": { sigla: "GAP-SP", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120636": { sigla: "GAP-LS", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120639": { sigla: "GAP-FL", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120640": { sigla: "GAP-FZ", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120642": { sigla: "GAP-SV", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120644": { sigla: "GAP-CT", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120645": { sigla: "GAP-GL", ods: "SEFA", orgaoSuperior: "DIRAD" },
	"120701": { sigla: "DIREF/SUCONT", ods: "SEFA", orgaoSuperior: "SEFA" },
	"120702": { sigla: "DIREF/SUCONV", ods: "SEFA", orgaoSuperior: "SEFA" },

	// COMPREP
	"120004": { sigla: "BABR", ods: "COMPREP", orgaoSuperior: "VI COMAR" },
	"120014": { sigla: "BAFZ", ods: "COMPREP", orgaoSuperior: "II COMAR" },
	"120017": { sigla: "II COMAR", ods: "COMPREP", orgaoSuperior: "COMPREP" },
	"120018": { sigla: "BARF", ods: "COMPREP", orgaoSuperior: "II COMAR" },
	"120023": { sigla: "BASV", ods: "COMPREP", orgaoSuperior: "II COMAR" },
	"120029": { sigla: "BAAF", ods: "COMPREP", orgaoSuperior: "III COMAR" },
	"120030": { sigla: "BAGL", ods: "COMPREP", orgaoSuperior: "III COMAR" },
	"120061": { sigla: "BAST", ods: "COMPREP", orgaoSuperior: "IV COMAR" },
	"120062": { sigla: "BASP", ods: "COMPREP", orgaoSuperior: "IV COMAR" },
	"120073": { sigla: "BAFL", ods: "COMPREP", orgaoSuperior: "V COMAR" },
	"120075": { sigla: "BACO", ods: "COMPREP", orgaoSuperior: "V COMAR" },
	"120082": { sigla: "BAMN", ods: "COMPREP", orgaoSuperior: "VII COMAR" },
	"120087": { sigla: "BABE", ods: "COMPREP", orgaoSuperior: "I COMAR" },
	"120152": { sigla: "CPBV", ods: "COMPREP", orgaoSuperior: "VI COMAR" },
	"120624": { sigla: "BAAN", ods: "COMPREP", orgaoSuperior: "VI COMAR" },
	"120631": { sigla: "BANT", ods: "COMPREP", orgaoSuperior: "II COMAR" },
	"120637": { sigla: "BABV", ods: "COMPREP", orgaoSuperior: "VII COMAR" },
	"120638": { sigla: "BACG", ods: "COMPREP", orgaoSuperior: "IV COMAR" },
	"120641": { sigla: "BAPV", ods: "COMPREP", orgaoSuperior: "VII COMAR" },
	"120643": { sigla: "BASM", ods: "COMPREP", orgaoSuperior: "V COMAR" },
	"120669": { sigla: "BASC", ods: "COMPREP", orgaoSuperior: "III COMAR" },

	// COMGAP
	"120026": { sigla: "PAMA-LS", ods: "COMGAP", orgaoSuperior: "DIRMAB" },
	"120035": { sigla: "CTLA", ods: "COMGAP", orgaoSuperior: "CELOG" },
	"120047": { sigla: "PAMB", ods: "COMGAP", orgaoSuperior: "DIRMAB" },
	"120049": { sigla: "PAMA-GL", ods: "COMGAP", orgaoSuperior: "DIRMAB" },
	"120068": { sigla: "PAMA-SP", ods: "COMGAP", orgaoSuperior: "DIRMAB" },
	"120071": { sigla: "CELOG", ods: "COMGAP", orgaoSuperior: "COMGAP" },
	"120088": { sigla: "COMARA", ods: "COMGAP", orgaoSuperior: "COMGAP" },
	"120090": { sigla: "CABW", ods: "COMGAP", orgaoSuperior: "CELOG" },
	"120091": { sigla: "CABE", ods: "COMGAP", orgaoSuperior: "CELOG" },
	"120099": { sigla: "DIRINFRA", ods: "COMGAP", orgaoSuperior: "COMGAP" },
	"120225": { sigla: "SERINFRA-SJ", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"120255": { sigla: "SERINFRA-BE", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"120257": { sigla: "SERINFRA-RJ", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"120258": { sigla: "SERINFRA-SP", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"120259": { sigla: "SERINFRA-CO", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"120260": { sigla: "SERINFRA-BR", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"120261": { sigla: "SERINFRA-MN", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"120265": { sigla: "SERINFRA-NT", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },

	// COMGEP
	"120019": { sigla: "HARF", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120025": { sigla: "EPCAR", ods: "COMGEP", orgaoSuperior: "DIRENS" },
	"120040": { sigla: "HCA", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120041": { sigla: "HAAF", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120042": { sigla: "HFAG", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120060": { sigla: "AFA", ods: "COMGEP", orgaoSuperior: "DIRENS" },
	"120064": { sigla: "EEAR", ods: "COMGEP", orgaoSuperior: "DIRENS" },
	"120066": { sigla: "HFASP", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120077": { sigla: "HACO", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120089": { sigla: "HABE", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120096": { sigla: "HFAB", ods: "COMGEP", orgaoSuperior: "DIRSA" },
	"120154": { sigla: "HAMN", ods: "COMGEP", orgaoSuperior: "DIRSA" },

	// DECEA
	"120008": { sigla: "CINDACTA I", ods: "DECEA", orgaoSuperior: "DECEA" },
	"120021": { sigla: "CINDACTA III", ods: "DECEA", orgaoSuperior: "DECEA" },
	"120036": { sigla: "DECEA", ods: "DECEA", orgaoSuperior: "DECEA" },
	"120048": { sigla: "PAME", ods: "DECEA", orgaoSuperior: "DECEA" },
	"120069": { sigla: "CRCEA-SE", ods: "DECEA", orgaoSuperior: "DECEA" },
	"120072": { sigla: "CINDACTA II", ods: "DECEA", orgaoSuperior: "DECEA" },
	"120094": { sigla: "CINDACTA IV", ods: "DECEA", orgaoSuperior: "DECEA" },
	"120127": { sigla: "CISCEA", ods: "DECEA", orgaoSuperior: "DECEA" },

	// DCTA
	"120013": { sigla: "CLA", ods: "DCTA", orgaoSuperior: "DCTA" },
	"120015": { sigla: "CLBI", ods: "DCTA", orgaoSuperior: "DCTA" },
	"120016": { sigla: "GAP-SJ", ods: "DCTA", orgaoSuperior: "DCTA" },
	"120108": { sigla: "COPAC", ods: "DCTA", orgaoSuperior: "DCTA" },
	"120512": { sigla: "PASJ", ods: "DCTA", orgaoSuperior: "DCTA" },

	// GABAER
	"120001": { sigla: "GABAER", ods: "GABAER", orgaoSuperior: "GABAER" },

	// STN
	"120999": { sigla: "MAER - DIF. CAMBIAL", ods: "STN", orgaoSuperior: "STN" },
	"120283": { sigla: "SERINFRA-RF", ods: "COMGAP", orgaoSuperior: "DIRINFRA" },
	"121002": { sigla: "DIREF - FAer", ods: "SEFA", orgaoSuperior: "SEFA" },
}
