/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SubitensGenericosRouteImport } from './routes/subitens-genericos'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as CruzamentoContasRouteImport } from './routes/cruzamento-contas'
import { Route as ContaGenericaRouteImport } from './routes/conta-generica'
import { Route as CentroMonitoramentoRouteImport } from './routes/centro-monitoramento'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as AnalistasaldoalongadoRouteImport } from './routes/analistasaldoalongado'
import { Route as AnalistaCompatibilidadeRouteImport } from './routes/analista-compatibilidade'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SubitensGenericosRoute = SubitensGenericosRouteImport.update({
  id: '/subitens-genericos',
  path: '/subitens-genericos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CruzamentoContasRoute = CruzamentoContasRouteImport.update({
  id: '/cruzamento-contas',
  path: '/cruzamento-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaGenericaRoute = ContaGenericaRouteImport.update({
  id: '/conta-generica',
  path: '/conta-generica',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroMonitoramentoRoute = CentroMonitoramentoRouteImport.update({
  id: '/centro-monitoramento',
  path: '/centro-monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistasaldoalongadoRoute = AnalistasaldoalongadoRouteImport.update({
  id: '/analistasaldoalongado',
  path: '/analistasaldoalongado',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaCompatibilidadeRoute = AnalistaCompatibilidadeRouteImport.update({
  id: '/analista-compatibilidade',
  path: '/analista-compatibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analista-compatibilidade': typeof AnalistaCompatibilidadeRoute
  '/analistasaldoalongado': typeof AnalistasaldoalongadoRoute
  '/auditor': typeof AuditorRoute
  '/centro-monitoramento': typeof CentroMonitoramentoRoute
  '/conta-generica': typeof ContaGenericaRoute
  '/cruzamento-contas': typeof CruzamentoContasRoute
  '/documentacao': typeof DocumentacaoRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/reports': typeof ReportsRoute
  '/subitens-genericos': typeof SubitensGenericosRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analista-compatibilidade': typeof AnalistaCompatibilidadeRoute
  '/analistasaldoalongado': typeof AnalistasaldoalongadoRoute
  '/auditor': typeof AuditorRoute
  '/centro-monitoramento': typeof CentroMonitoramentoRoute
  '/conta-generica': typeof ContaGenericaRoute
  '/cruzamento-contas': typeof CruzamentoContasRoute
  '/documentacao': typeof DocumentacaoRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/reports': typeof ReportsRoute
  '/subitens-genericos': typeof SubitensGenericosRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analista-compatibilidade': typeof AnalistaCompatibilidadeRoute
  '/analistasaldoalongado': typeof AnalistasaldoalongadoRoute
  '/auditor': typeof AuditorRoute
  '/centro-monitoramento': typeof CentroMonitoramentoRoute
  '/conta-generica': typeof ContaGenericaRoute
  '/cruzamento-contas': typeof CruzamentoContasRoute
  '/documentacao': typeof DocumentacaoRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/reports': typeof ReportsRoute
  '/subitens-genericos': typeof SubitensGenericosRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analista-compatibilidade'
    | '/analistasaldoalongado'
    | '/auditor'
    | '/centro-monitoramento'
    | '/conta-generica'
    | '/cruzamento-contas'
    | '/documentacao'
    | '/monitoramento'
    | '/reports'
    | '/subitens-genericos'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analista-compatibilidade'
    | '/analistasaldoalongado'
    | '/auditor'
    | '/centro-monitoramento'
    | '/conta-generica'
    | '/cruzamento-contas'
    | '/documentacao'
    | '/monitoramento'
    | '/reports'
    | '/subitens-genericos'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/analista-compatibilidade'
    | '/analistasaldoalongado'
    | '/auditor'
    | '/centro-monitoramento'
    | '/conta-generica'
    | '/cruzamento-contas'
    | '/documentacao'
    | '/monitoramento'
    | '/reports'
    | '/subitens-genericos'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalistaCompatibilidadeRoute: typeof AnalistaCompatibilidadeRoute
  AnalistasaldoalongadoRoute: typeof AnalistasaldoalongadoRoute
  AuditorRoute: typeof AuditorRoute
  CentroMonitoramentoRoute: typeof CentroMonitoramentoRoute
  ContaGenericaRoute: typeof ContaGenericaRoute
  CruzamentoContasRoute: typeof CruzamentoContasRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  ReportsRoute: typeof ReportsRoute
  SubitensGenericosRoute: typeof SubitensGenericosRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subitens-genericos': {
      id: '/subitens-genericos'
      path: '/subitens-genericos'
      fullPath: '/subitens-genericos'
      preLoaderRoute: typeof SubitensGenericosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruzamento-contas': {
      id: '/cruzamento-contas'
      path: '/cruzamento-contas'
      fullPath: '/cruzamento-contas'
      preLoaderRoute: typeof CruzamentoContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-generica': {
      id: '/conta-generica'
      path: '/conta-generica'
      fullPath: '/conta-generica'
      preLoaderRoute: typeof ContaGenericaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro-monitoramento': {
      id: '/centro-monitoramento'
      path: '/centro-monitoramento'
      fullPath: '/centro-monitoramento'
      preLoaderRoute: typeof CentroMonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analistasaldoalongado': {
      id: '/analistasaldoalongado'
      path: '/analistasaldoalongado'
      fullPath: '/analistasaldoalongado'
      preLoaderRoute: typeof AnalistasaldoalongadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista-compatibilidade': {
      id: '/analista-compatibilidade'
      path: '/analista-compatibilidade'
      fullPath: '/analista-compatibilidade'
      preLoaderRoute: typeof AnalistaCompatibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalistaCompatibilidadeRoute: AnalistaCompatibilidadeRoute,
  AnalistasaldoalongadoRoute: AnalistasaldoalongadoRoute,
  AuditorRoute: AuditorRoute,
  CentroMonitoramentoRoute: CentroMonitoramentoRoute,
  ContaGenericaRoute: ContaGenericaRoute,
  CruzamentoContasRoute: CruzamentoContasRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  ReportsRoute: ReportsRoute,
  SubitensGenericosRoute: SubitensGenericosRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
