/**
 * Drizzle entrypoint for the `sisub` schema.
 *
 * `schema.ts` (tables + enums) and `relations.ts` (relational-query metadata) are
 * generated by `bun run db:drizzle:pull` — do not edit them by hand. This barrel
 * re-exports both and exposes the combined schema object + the canonical `SisubDb`
 * type consumed by `getDb()` (apps/sisub) and every operation in `@iefa/sisub-domain`.
 *
 * `SisubDb` replaces the ~23 local `AnyClient = SupabaseClient<any,any,any>` aliases:
 * one source of truth for the query-layer client type.
 */
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js"
import * as relations from "./relations"
import * as schema from "./schema"

export * from "./relations"
export * from "./schema"

/** Tables + enums + relations — pass to `drizzle(client, { schema: sisubSchema })`. */
export const sisubSchema = { ...schema, ...relations }

/** Canonical Drizzle client type for the sisub query layer (enables `db.query.*`). */
export type SisubDb = PostgresJsDatabase<typeof sisubSchema>
