-- 20261003100000 (saram_verified_link). Roda no fim de run.sh, depois de signup-allowlist.test.sql
-- (que criou o esqueleto de core.user_data) e de audit-hardening.test.sql (log append-only).
-- Aplica a migration DUAS vezes (idempotência) e prova:
--
--   * a chave: acento, preposições, `tp.`, dígito de homônimo, domínio exato;
--   * o backfill email/legacy, com SARAM repetido;
--   * a guarda de core.user_data (SARAM gravado por fora fica sem verificação);
--   * estado, sugestão, homônimos (sufixo do CPF), CPF com bloqueio, pedido, contestação,
--     transferência de legacy com log, formulário antigo (claim), conta institucional;
--   * as decisões do administrador, auditadas e com conferência de versão.

\set ON_ERROR_STOP 1
set client_min_messages = warning;

create or replace function pg_temp.expect_error(p_sql text, p_msg text) returns void language plpgsql as $$
begin
	begin
		execute p_sql;
	exception when others then
		if sqlerrm is distinct from p_msg then
			raise exception 'esperava %, veio % (%) em: %', p_msg, sqlerrm, sqlstate, p_sql;
		end if;
		return;
	end;
	raise exception 'esperava %, mas passou: %', p_msg, p_sql;
end;
$$;

-- ── Esqueleto: espelho, view, arranchamento, presença ───────────────────────
-- Sem `unaccent` de propósito: a chave usa `translate` e não depende de extensão.
create schema if not exists sisub;
create schema if not exists analytics;
create or replace function sisub.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;

drop table if exists core.military_identity;
create table core.user_military_data (
	"nrOrdem" text, "nrCpf" text not null unique, "nmGuerra" text, "nmPessoa" text, "sgPosto" text, "sgOrg" text,
	"dataAtualizacao" timestamptz, id bigint generated by default as identity primary key
);
create view core.military_identity with (security_invoker = true) as
	select m."nrOrdem" as saram, m."sgPosto" as posto, m."nmGuerra" as nome_guerra, m."sgOrg" as sg_org, m."dataAtualizacao" as data_atualizacao
	from core.user_military_data m;
create table kitchen.arranchamento (
	id uuid primary key default gen_random_uuid(), date date not null, user_id uuid not null references auth.users(id),
	meal text not null, will_eat boolean not null, mess_hall_id bigint not null references kitchen.mess_halls(id),
	created_at timestamptz default now(), updated_at timestamptz default now(), unique (user_id, date, meal)
);
create table kitchen.meal_presences (
	id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), date date not null,
	meal text not null, mess_hall_id bigint not null references kitchen.mess_halls(id), created_at timestamptz not null default now(),
	unique (user_id, date, meal)
);
insert into kitchen.mess_halls (id) values (9201) on conflict do nothing;

insert into core.user_military_data ("nrOrdem", "nrCpf", "nmGuerra", "nmPessoa", "sgPosto", "sgOrg") values
	('1000001', '111.222.333-44', 'ANDRÉ', 'André Luís da Costa', '3S', 'IEFA'),
	('2000002', '22233344455', 'SOUZA', 'Paulo Roberto Souza', '1S', 'GAP-SJ'),
	('2000003', '33344455566', 'Souza', 'Pedro Rafael de Souza', '2S', 'DIRAD'),
	('4000004', '44455566677', 'CARVALHO', 'Bruno Carvalho', 'SO', 'IEFA'),
	('5000005', '55566677788', 'LIMA', 'Ana Lima', 'CB', 'IEFA'),
	('6000006', '66677788899', 'MELO', 'Caio Melo', 'S1', 'IEFA'),
	('7000007', '77788899900', 'JOÃO', 'João dos Santos e Silva', 'S2', 'IEFA'),
	('8000008', '88899900011', 'ROCHA', 'Davi Rocha', '3S', 'IEFA');

-- Contas de antes da migration (backfill).
insert into auth.users (id, email) values
	('00000000-0000-0000-0000-000000000061', 'carvalhobc@fab.mil.br'),
	('00000000-0000-0000-0000-000000000062', 'outro.carvalho@fab.mil.br'),
	('00000000-0000-0000-0000-000000000063', 'tp.joaojss3@fab.mil.br'),
	('00000000-0000-0000-0000-000000000064', 'qualquer@fab.mil.br'),
	('00000000-0000-0000-0000-000000000071', 'andrealc@fab.mil.br'),
	('00000000-0000-0000-0000-000000000072', 'souzaprs@fab.mil.br'),
	('00000000-0000-0000-0000-000000000073', 'tp.limaal2@fab.mil.br'),
	('00000000-0000-0000-0000-000000000074', 'semcadastro@fab.mil.br'),
	('00000000-0000-0000-0000-000000000076', 'verificador@fab.mil.br'),
	('00000000-0000-0000-0000-000000000077', 'contestador@fab.mil.br'),
	('00000000-0000-0000-0000-000000000078', 'forcabruta@fab.mil.br'),
	('00000000-0000-0000-0000-000000000079', 'secao-gapsj@fab.mil.br'),
	('00000000-0000-0000-0000-000000000080', 'admin.saram@fab.mil.br'),
	('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br'),
	('00000000-0000-0000-0000-000000000082', 'rochadr@fab.mil.br'),
	('00000000-0000-0000-0000-000000000083', 'digitouerrado@fab.mil.br');
insert into core.user_data (id, email, saram) values
	('00000000-0000-0000-0000-000000000083', 'digitouerrado@fab.mil.br', '1111110'),
	('00000000-0000-0000-0000-000000000061', 'carvalhobc@fab.mil.br', '4000004'),
	('00000000-0000-0000-0000-000000000062', 'outro.carvalho@fab.mil.br', '4000004'),
	('00000000-0000-0000-0000-000000000063', 'tp.joaojss3@fab.mil.br', '7000007'),
	('00000000-0000-0000-0000-000000000064', 'qualquer@fab.mil.br', '6000006');

\ir ../../supabase/migrations/20261003100000_saram_verified_link.sql
\ir ../../supabase/migrations/20261003100000_saram_verified_link.sql

-- ── Chave ───────────────────────────────────────────────────────────────────
do $$
begin
	assert core.military_name_key('ANDRÉ', 'André Luís da Costa') = 'andrealc', 'acento e preposição';
	assert core.military_name_key('JOÃO', 'João dos Santos e Silva') = 'joaojss', 'dos/e fora das iniciais';
	assert core.military_name_key('D''ÁVILA', 'Maria D''Ávila das Neves') = 'davilamdn', 'apóstrofo some';
	assert core.military_name_key(null, null) is null;
	assert core.email_name_key('andrealc@fab.mil.br') = 'andrealc';
	assert core.email_name_key(' AndreALC@FAB.mil.br ') = 'andrealc', 'caixa e espaço';
	assert core.email_name_key('tp.limaal2@fab.mil.br') = 'limaal', 'tp. e dígito';
	assert core.email_name_key('andrealc12@fab.mil.br') = 'andrealc', 'dígitos finais';
	assert core.email_name_key('andrealc@evil.fab.mil.br') is null, 'domínio exato';
	assert core.email_name_key('andrealc@fab.mil.br.evil.com') is null, 'domínio exato (sufixo)';
	assert core.email_name_key('andre.lc@fab.mil.br') is null, 'só letras';
	assert core.email_name_key('secao-gapsj@fab.mil.br') is null, 'hífen não tem chave';
	assert core.email_has_homonym_suffix('tp.limaal2@fab.mil.br') and not core.email_has_homonym_suffix('andrealc@fab.mil.br');
	assert (select count(*) from core.saram_email_candidates('souzaprs@fab.mil.br')) = 2, 'homônimos';
	assert (select count(*) from core.saram_email_candidates('andrealc@gmail.com')) = 0, 'fora da FAB não tem candidato';
	-- O índice existe e é o da chave.
	assert to_regclass('core.user_military_data_name_key_idx') is not null;
end $$;

-- ── Backfill ────────────────────────────────────────────────────────────────
do $$
begin
	assert (select saram_verified_by from core.user_data where id = '00000000-0000-0000-0000-000000000061') = 'email', 'bate → email';
	assert (select saram_verified_by from core.user_data where id = '00000000-0000-0000-0000-000000000062') = 'legacy', 'repetido que não bate → legacy';
	assert (select saram_verified_by from core.user_data where id = '00000000-0000-0000-0000-000000000063') = 'email', 'tp. + dígito → email';
	assert (select saram_verified_by from core.user_data where id = '00000000-0000-0000-0000-000000000064') = 'legacy', 'não bate → legacy';
	assert (select saram_verified_by from core.user_data where id = '00000000-0000-0000-0000-000000000051') = 'legacy', 'fora do espelho → legacy';
	assert not exists (select 1 from core.user_data where saram is not null and saram_verified_by is null);
	assert (select account_kind from core.user_data where id = '00000000-0000-0000-0000-000000000061') = 'pessoal';
	-- Visibilidade: legacy repetido com verificado concorrente não vê; legacy sozinho vê.
	assert core.visible_saram('00000000-0000-0000-0000-000000000061') = '4000004';
	assert core.visible_saram('00000000-0000-0000-0000-000000000062') is null, 'legacy em conflito não vê';
	assert core.visible_saram('00000000-0000-0000-0000-000000000064') = '6000006', 'legacy sozinho vê';
	-- Nome de exibição pelas mesmas regras: o legacy em conflito não aparece com o nome do dono.
	assert (select display_name from core.v_user_identity where id = '00000000-0000-0000-0000-000000000061') = 'SO Carvalho';
	assert (select display_name from core.v_user_identity where id = '00000000-0000-0000-0000-000000000062') = 'outro.carvalho@fab.mil.br';
	assert (select display_name from analytics.v_user_identity where id = '00000000-0000-0000-0000-000000000062') like 'Usuário %';
	assert (select display_name from analytics.v_user_identity where id = '00000000-0000-0000-0000-000000000064') = 'S1 Melo';
end $$;

-- ── Guarda de core.user_data ────────────────────────────────────────────────
do $$
begin
	update core.user_data set saram = '9999999' where id = '00000000-0000-0000-0000-000000000051';
	assert (select saram_verified_by is null from core.user_data where id = '00000000-0000-0000-0000-000000000051'), 'SARAM gravado por fora fica sem verificação';
	assert core.visible_saram('00000000-0000-0000-0000-000000000051') is null, 'sem verificação não vê';
	assert (select display_name from core.v_user_identity where id = '00000000-0000-0000-0000-000000000051') = 'um@fab.mil.br';
	perform pg_temp.expect_error($q$ update core.user_data set saram_verified_by = 'admin' where id = '00000000-0000-0000-0000-000000000051' $q$, 'SARAM_LINK_OUTSIDE_FUNCTION');
	perform pg_temp.expect_error($q$ update core.user_data set account_kind = 'institucional', saram = null where id = '00000000-0000-0000-0000-000000000052' $q$, 'SARAM_LINK_OUTSIDE_FUNCTION');
	perform pg_temp.expect_error($q$ select core.assign_saram('00000000-0000-0000-0000-000000000052', null, '8000008', 'admin') $q$, 'SARAM_LINK_OUTSIDE_FUNCTION');
	perform pg_temp.expect_error($q$ select core.apply_saram_link('00000000-0000-0000-0000-000000000052', null, '8000008', 'email') $q$, 'SARAM_LINK_OUTSIDE_FUNCTION');
	-- E-mail e refeitório padrão continuam livres.
	update core.user_data set default_mess_hall_id = 9201 where id = '00000000-0000-0000-0000-000000000061';
end $$;

-- ── Estado e sugestão por e-mail ────────────────────────────────────────────
do $$
declare s jsonb; r jsonb;
begin
	s := core.saram_link_status('00000000-0000-0000-0000-000000000071', 'andrealc@fab.mil.br', true);
	assert s ->> 'status' = 'suggestion', s::text;
	assert jsonb_array_length(s -> 'candidates') = 1;
	assert s -> 'candidates' -> 0 ->> 'nome_guerra' = 'ANDRÉ';
	assert not (s -> 'candidates' -> 0 ? 'saram'), 'candidato sem SARAM';
	assert s::text !~ '1000001' and s::text !~ '11122233344' and s::text !~ 'Costa', 'nem SARAM, nem CPF, nem nome completo';
	assert (s -> 'actions') ? 'confirm_candidate';

	-- e-mail não confirmado, ou de fora: sem sugestão
	assert core.saram_link_status('00000000-0000-0000-0000-000000000071', 'andrealc@fab.mil.br', false) ->> 'email_eligibility' = 'unconfirmed';
	assert core.saram_link_status('00000000-0000-0000-0000-000000000071', 'andrealc@gmail.com', true) ->> 'status' = 'no_match';
	assert core.saram_link_status('00000000-0000-0000-0000-000000000074', 'semcadastro@fab.mil.br', true) ->> 'status' = 'no_match';

	-- candidato de outra chave é recusado
	perform pg_temp.expect_error(format($q$ select core.confirm_saram_candidate('00000000-0000-0000-0000-000000000071', 'andrealc@fab.mil.br', true, %s, null) $q$,
		(select id from core.user_military_data where "nrOrdem" = '8000008')), 'CANDIDATE_NOT_FOUND');
	perform pg_temp.expect_error(format($q$ select core.confirm_saram_candidate('00000000-0000-0000-0000-000000000071', 'andrealc@fab.mil.br', false, %s, null) $q$,
		(s -> 'candidates' -> 0 ->> 'ref')), 'EMAIL_NOT_ELIGIBLE');

	r := core.confirm_saram_candidate('00000000-0000-0000-0000-000000000071', 'andrealc@fab.mil.br', true, (s -> 'candidates' -> 0 ->> 'ref')::bigint, null);
	assert r ->> 'outcome' = 'linked', r::text;
	assert r -> 'status' ->> 'status' = 'verified';
	assert (select saram = '1000001' and saram_verified_by = 'email' and saram_verified_at is not null from core.user_data where id = '00000000-0000-0000-0000-000000000071');
	assert r -> 'status' -> 'identity' ->> 'posto' = '3S';
	perform pg_temp.expect_error(format($q$ select core.confirm_saram_candidate('00000000-0000-0000-0000-000000000071', 'andrealc@fab.mil.br', true, %s, null) $q$,
		(s -> 'candidates' -> 0 ->> 'ref')), 'SARAM_ALREADY_LINKED');
end $$;

-- ── Homônimos e sufixo do CPF ───────────────────────────────────────────────
do $$
declare s jsonb; r jsonb; v_ref bigint; n int;
begin
	s := core.saram_link_status('00000000-0000-0000-0000-000000000072', 'souzaprs@fab.mil.br', true);
	assert s ->> 'status' = 'homonyms', s::text;
	assert (s ->> 'requires_cpf_suffix')::boolean;
	assert jsonb_array_length(s -> 'candidates') = 2;
	select (c ->> 'ref')::bigint into v_ref from jsonb_array_elements(s -> 'candidates') c where c ->> 'sg_org' = 'DIRAD';

	perform pg_temp.expect_error(format($q$ select core.confirm_saram_candidate('00000000-0000-0000-0000-000000000072', 'souzaprs@fab.mil.br', true, %s, null) $q$, v_ref), 'CPF_SUFFIX_INVALID');
	n := (select count(*) from core.saram_verification_attempt);
	r := core.confirm_saram_candidate('00000000-0000-0000-0000-000000000072', 'souzaprs@fab.mil.br', true, v_ref, '4455');
	assert r ->> 'outcome' = 'mismatch', r::text;
	assert (r ->> 'attempts_left')::int = 4;
	assert (select count(*) from core.saram_verification_attempt) = n + 1, 'a falha fica registrada';
	assert not exists (select 1 from core.user_data where id = '00000000-0000-0000-0000-000000000072' and saram is not null);
	r := core.confirm_saram_candidate('00000000-0000-0000-0000-000000000072', 'souzaprs@fab.mil.br', true, v_ref, '5566');
	assert r ->> 'outcome' = 'linked', r::text;
	assert (select saram from core.user_data where id = '00000000-0000-0000-0000-000000000072') = '2000003';

	-- e-mail com dígito: um candidato só, e ainda assim pede o sufixo
	s := core.saram_link_status('00000000-0000-0000-0000-000000000073', 'tp.limaal2@fab.mil.br', true);
	assert s ->> 'status' = 'homonyms' and jsonb_array_length(s -> 'candidates') = 1 and (s ->> 'requires_cpf_suffix')::boolean, s::text;
end $$;

-- ── CPF: bloqueio, transferência de legacy, contestação ─────────────────────
do $$
declare r jsonb; i int; v_log bigint;
begin
	perform pg_temp.expect_error($q$ select core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000078', 'forcabruta@fab.mil.br', true, '12a', '12345678901') $q$, 'SARAM_INVALID');
	perform pg_temp.expect_error($q$ select core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000078', 'forcabruta@fab.mil.br', true, '8000008', '123') $q$, 'CPF_INVALID');

	-- SARAM inexistente e CPF errado: mesma resposta
	r := core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000078', 'forcabruta@fab.mil.br', true, '3333333', '88899900011');
	assert r ->> 'outcome' = 'mismatch';
	for i in 1..4 loop
		r := core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000078', 'forcabruta@fab.mil.br', true, '8000008', '00000000000');
	end loop;
	assert r ->> 'outcome' = 'mismatch' and (r ->> 'attempts_left')::int = 0, r::text;
	-- bloqueada: nem o CPF certo passa
	r := core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000078', 'forcabruta@fab.mil.br', true, '8000008', '88899900011');
	assert r ->> 'outcome' = 'locked' and r ->> 'locked_until' is not null, r::text;
	assert core.saram_link_status('00000000-0000-0000-0000-000000000078', 'forcabruta@fab.mil.br', true) ->> 'status' = 'locked_out';
	assert not exists (select 1 from core.user_data where id = '00000000-0000-0000-0000-000000000078');

	-- titular legacy: verificado prevalece, com log
	v_log := (select count(*) from access_control.sensitive_operation_log);
	r := core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000076', 'verificador@fab.mil.br', true, '6000006', '666.777.888-99');
	assert r ->> 'outcome' = 'linked', r::text;
	assert (select saram = '6000006' and saram_verified_by = 'cpf' from core.user_data where id = '00000000-0000-0000-0000-000000000076');
	assert (select saram is null and saram_verified_by is null from core.user_data where id = '00000000-0000-0000-0000-000000000064'), 'legacy perdeu o SARAM';
	assert (select count(*) from access_control.sensitive_operation_log) = v_log + 1;
	assert exists (select 1 from access_control.sensitive_operation_log
		where operation = 'claimSaramFromUnverifiedHolder' and actor_id = '00000000-0000-0000-0000-000000000076'
			and target ->> 'action' = 'saram_transfer' and target -> 'removed_from' -> 0 ->> 'user_id' = '00000000-0000-0000-0000-000000000064');

	-- titular verificado: contestação, nada muda
	r := core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000077', 'contestador@fab.mil.br', true, '4000004', '44455566677');
	assert r ->> 'outcome' = 'disputed', r::text;
	assert r -> 'status' ->> 'status' = 'contested';
	assert (select saram from core.user_data where id = '00000000-0000-0000-0000-000000000061') = '4000004';
	assert exists (select 1 from core.saram_link_request where user_id = '00000000-0000-0000-0000-000000000077' and kind = 'dispute' and claim_verified_by = 'cpf'
		and holder_user_id = '00000000-0000-0000-0000-000000000061' and status = 'pending');
end $$;

-- ── Pedido, desistência, limite; formulário antigo ──────────────────────────
do $$
declare r jsonb; v_req uuid; i int;
begin
	perform pg_temp.expect_error($q$ select core.request_saram_link('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, '9100001', 'curta') $q$, 'JUSTIFICATION_INVALID');
	r := core.request_saram_link('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, '9100001', 'Cheguei depois da última carga do cadastro.');
	assert r ->> 'kind' = 'link' and r -> 'status' ->> 'status' = 'pending_request', r::text;
	assert core.visible_saram('00000000-0000-0000-0000-000000000081') is null, 'pedido pendente não vê dado militar';
	perform pg_temp.expect_error($q$ select core.request_saram_link('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, '9100002', 'Outro pedido enquanto o primeiro está pendente.') $q$, 'REQUEST_PENDING');
	v_req := (r ->> 'request_id')::uuid;
	r := core.withdraw_saram_request('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, v_req);
	assert r -> 'status' ->> 'status' = 'no_match';
	perform pg_temp.expect_error(format($q$ select core.withdraw_saram_request('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, '%s') $q$, v_req), 'REQUEST_NOT_FOUND');
	-- teto: 5 pedidos em 24 h
	for i in 1..4 loop
		r := core.request_saram_link('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, '91000' || (10 + i), 'Pedido repetido para provar o teto diário.');
		perform core.withdraw_saram_request('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, (r ->> 'request_id')::uuid);
	end loop;
	perform pg_temp.expect_error($q$ select core.request_saram_link('00000000-0000-0000-0000-000000000081', 'pedinte@fab.mil.br', true, '9100020', 'Sexto pedido em menos de um dia.') $q$, 'REQUEST_LIMIT');

	-- SARAM com titular → contestação
	r := core.request_saram_link('00000000-0000-0000-0000-000000000074', 'semcadastro@fab.mil.br', true, '1000001', 'Este SARAM é meu; troquei de nome de guerra.');
	assert r ->> 'kind' = 'dispute' and r -> 'status' ->> 'status' = 'contested', r::text;

	-- formulário antigo: candidato único do e-mail vincula por e-mail; outro número vira pedido
	r := core.claim_saram('00000000-0000-0000-0000-000000000082', 'rochadr@fab.mil.br', true, '8000008');
	assert r ->> 'outcome' = 'linked' and r ->> 'verified_by' = 'email', r::text;
	r := core.claim_saram('00000000-0000-0000-0000-000000000082', 'rochadr@fab.mil.br', true, '8000008');
	assert r ->> 'outcome' = 'unchanged';
	perform pg_temp.expect_error($q$ select core.claim_saram('00000000-0000-0000-0000-000000000082', 'rochadr@fab.mil.br', true, '1000001') $q$, 'SARAM_LOCKED');
	-- legacy que localiza cadastro: só o administrador troca; sem prova, nada passa
	perform pg_temp.expect_error($q$ select core.claim_saram('00000000-0000-0000-0000-000000000062', 'outro.carvalho@fab.mil.br', true, '8100001') $q$, 'SARAM_LOCKED');
	perform pg_temp.expect_error($q$ select core.request_saram_link('00000000-0000-0000-0000-000000000062', 'outro.carvalho@fab.mil.br', true, '8100001', 'Quero trocar o meu SARAM antigo.') $q$, 'SARAM_ALREADY_LINKED');
	-- ...e ao conferir o PRÓPRIO número contra titular verificado, abre contestação visível no estado
	r := core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000062', 'outro.carvalho@fab.mil.br', true, '4000004', '44455566677');
	assert r ->> 'outcome' = 'disputed' and not (r ->> 'upgraded')::boolean, r::text;
	assert r -> 'status' ->> 'status' = 'contested' and (r -> 'status' -> 'actions') ? 'withdraw_request', r::text;
	perform core.withdraw_saram_request('00000000-0000-0000-0000-000000000062', 'outro.carvalho@fab.mil.br', true,
		(select id from core.saram_link_request where user_id = '00000000-0000-0000-0000-000000000062' and status = 'pending'));
	-- legacy que não localiza ninguém (digitado errado) segue corrigível: pede, ou prova outro
	assert core.saram_link_status('00000000-0000-0000-0000-000000000083', 'digitouerrado@fab.mil.br', true) -> 'actions' ? 'request_link';
	r := core.verify_saram_by_cpf('00000000-0000-0000-0000-000000000083', 'digitouerrado@fab.mil.br', true, '5000005', '55566677788');
	assert r ->> 'outcome' = 'linked' and not (r ->> 'upgraded')::boolean, r::text;
	assert (select saram = '5000005' and saram_verified_by = 'cpf' from core.user_data where id = '00000000-0000-0000-0000-000000000083');

	r := core.claim_saram('00000000-0000-0000-0000-000000000073', 'tp.limaal2@fab.mil.br', true, '5000005');
	assert r ->> 'outcome' = 'requested', 'e-mail com dígito não vincula pelo formulário: ' || r::text;
	r := core.claim_saram('00000000-0000-0000-0000-000000000073', 'tp.limaal2@fab.mil.br', true, '5000005');
	assert r ->> 'outcome' = 'pending';
end $$;

-- ── Conta institucional ─────────────────────────────────────────────────────
do $$
declare r jsonb; v_today date := (now() at time zone 'America/Sao_Paulo')::date;
begin
	insert into core.user_data (id, email) values ('00000000-0000-0000-0000-000000000079', 'secao-gapsj@fab.mil.br');
	insert into kitchen.arranchamento (date, user_id, meal, will_eat, mess_hall_id) values
		(v_today + 1, '00000000-0000-0000-0000-000000000079', 'almoco', true, 9201),
		(v_today - 1, '00000000-0000-0000-0000-000000000079', 'almoco', true, 9201);
	r := core.set_own_account_kind('00000000-0000-0000-0000-000000000079', 'secao-gapsj@fab.mil.br', true, 'institucional');
	assert r ->> 'outcome' = 'changed' and (r -> 'effects' ->> 'cancelled_arranchamentos')::int = 1, r::text;
	assert r -> 'status' ->> 'status' = 'institutional';
	assert (select will_eat from kitchen.arranchamento where user_id = '00000000-0000-0000-0000-000000000079' and date = v_today - 1), 'passado não muda';
	perform pg_temp.expect_error(format($q$ insert into kitchen.arranchamento (date, user_id, meal, will_eat, mess_hall_id) values ('%s', '00000000-0000-0000-0000-000000000079', 'janta', true, 9201) $q$, v_today + 2), 'ACCOUNT_INSTITUTIONAL_NO_MEALS');
	perform pg_temp.expect_error(format($q$ update kitchen.arranchamento set will_eat = true where user_id = '00000000-0000-0000-0000-000000000079' and date = '%s' $q$, v_today + 1), 'ACCOUNT_INSTITUTIONAL_NO_MEALS');
	perform pg_temp.expect_error(format($q$ insert into kitchen.meal_presences (user_id, date, meal, mess_hall_id) values ('00000000-0000-0000-0000-000000000079', '%s', 'almoco', 9201) $q$, v_today), 'ACCOUNT_INSTITUTIONAL_NO_MEALS');
	-- desmarcar continua livre
	insert into kitchen.arranchamento (date, user_id, meal, will_eat, mess_hall_id) values (v_today + 3, '00000000-0000-0000-0000-000000000079', 'cafe', false, 9201);
	perform pg_temp.expect_error($q$ select core.claim_saram('00000000-0000-0000-0000-000000000079', 'secao-gapsj@fab.mil.br', true, '8000008') $q$, 'ACCOUNT_INSTITUTIONAL');
	perform pg_temp.expect_error($q$ update core.user_data set saram = '8000008' where id = '00000000-0000-0000-0000-000000000079' $q$,
		'new row for relation "user_data" violates check constraint "user_data_institutional_without_saram"');
	-- pessoa comum continua arranchando
	insert into kitchen.arranchamento (date, user_id, meal, will_eat, mess_hall_id) values (v_today + 1, '00000000-0000-0000-0000-000000000074', 'almoco', true, 9201);

	-- conta verificada que se declara institucional perde o vínculo
	r := core.set_own_account_kind('00000000-0000-0000-0000-000000000082', 'rochadr@fab.mil.br', true, 'institucional');
	assert (select saram is null and account_kind = 'institucional' from core.user_data where id = '00000000-0000-0000-0000-000000000082');
	r := core.set_own_account_kind('00000000-0000-0000-0000-000000000082', 'rochadr@fab.mil.br', true, 'pessoal');
	assert r -> 'status' ->> 'status' = 'suggestion', 'volta a pessoal e verifica de novo: ' || r::text;
	assert core.set_own_account_kind('00000000-0000-0000-0000-000000000082', 'rochadr@fab.mil.br', true, 'pessoal') ->> 'outcome' = 'unchanged';
end $$;

-- ── Administrador ───────────────────────────────────────────────────────────
do $$
declare r jsonb; q jsonb; v_req uuid; v_log bigint := (select count(*) from access_control.sensitive_operation_log);
begin
	q := core.saram_review_queue();
	assert jsonb_array_length(q -> 'requests') >= 2, q::text;
	assert exists (select 1 from jsonb_array_elements(q -> 'legacy') l where l ->> 'user_id' = '00000000-0000-0000-0000-000000000062' and (l ->> 'verified_elsewhere')::boolean);
	assert exists (select 1 from jsonb_array_elements(q -> 'unverified') l where l ->> 'user_id' = '00000000-0000-0000-0000-000000000051');
	assert exists (select 1 from jsonb_array_elements(q -> 'institutional') l where l ->> 'user_id' = '00000000-0000-0000-0000-000000000079');
	assert q::text !~ '44455566677', 'CPF não sai na fila';

	-- contestação aprovada: sai do titular, vai para quem contestou, com log
	select id into v_req from core.saram_link_request where user_id = '00000000-0000-0000-0000-000000000077' and status = 'pending';
	perform pg_temp.expect_error(format($q$ select core.decide_saram_request('00000000-0000-0000-0000-000000000080', 'decideSaramRequestFn', '%s', 'reject', 'não', 'fresh') $q$, v_req), 'NOTE_REQUIRED');
	r := core.decide_saram_request('00000000-0000-0000-0000-000000000080', 'decideSaramRequestFn', v_req, 'approve', null, 'fresh');
	assert r ->> 'outcome' = 'approved', r::text;
	assert (select saram = '4000004' and saram_verified_by = 'admin' from core.user_data where id = '00000000-0000-0000-0000-000000000077');
	assert (select saram is null from core.user_data where id = '00000000-0000-0000-0000-000000000061');
	-- o legacy repetido também saiu
	assert (select saram is null from core.user_data where id = '00000000-0000-0000-0000-000000000062');
	assert exists (select 1 from access_control.sensitive_operation_log where id = (r ->> 'log_id')::uuid and operation = 'decideSaramRequestFn'
		and actor_id = '00000000-0000-0000-0000-000000000080' and assurance = 'fresh' and target ->> 'target_user_id' = '00000000-0000-0000-0000-000000000077');
	perform pg_temp.expect_error(format($q$ select core.decide_saram_request('00000000-0000-0000-0000-000000000080', 'decideSaramRequestFn', '%s', 'approve', null, 'fresh') $q$, v_req), 'REQUEST_NOT_PENDING');

	-- recusa
	select id into v_req from core.saram_link_request where user_id = '00000000-0000-0000-0000-000000000074' and status = 'pending';
	r := core.decide_saram_request('00000000-0000-0000-0000-000000000080', 'decideSaramRequestFn', v_req, 'reject', 'O SARAM é de outra pessoa, conferido.', 'fresh');
	assert r ->> 'outcome' = 'rejected' and (select status from core.saram_link_request where id = v_req) = 'rejected';

	-- vínculo manual confere o que a tela viu
	perform pg_temp.expect_error($q$ select core.admin_link_saram('00000000-0000-0000-0000-000000000080', 'linkUserSaramFn', '00000000-0000-0000-0000-000000000074', '7000007', '1111111', 'Conferido pessoalmente na seção.', 'fresh') $q$, 'SARAM_LINK_CHANGED');
	perform pg_temp.expect_error($q$ select core.admin_link_saram('00000000-0000-0000-0000-000000000080', 'linkUserSaramFn', '00000000-0000-0000-0000-000000000074', '7000007', null, 'Conferido pessoalmente na seção.', 'fresh') $q$, 'SARAM_TAKEN');
	r := core.admin_link_saram('00000000-0000-0000-0000-000000000080', 'linkUserSaramFn', '00000000-0000-0000-0000-000000000074', '9100001', null, 'Conferido pessoalmente na seção.', 'fresh');
	assert (select saram = '9100001' and saram_verified_by = 'admin' from core.user_data where id = '00000000-0000-0000-0000-000000000074');
	-- confirmar legacy: mesmo SARAM
	r := core.admin_link_saram('00000000-0000-0000-0000-000000000080', 'linkUserSaramFn', '00000000-0000-0000-0000-000000000052', '555555', '555555', 'Legacy revisado e confirmado.', 'fresh');
	assert (select saram_verified_by from core.user_data where id = '00000000-0000-0000-0000-000000000052') = 'admin';

	-- desvincular
	perform pg_temp.expect_error($q$ select core.admin_unlink_saram('00000000-0000-0000-0000-000000000080', 'unlinkUserSaramFn', '00000000-0000-0000-0000-000000000074', '0000000', 'SARAM digitado errado.', 'fresh') $q$, 'SARAM_LINK_CHANGED');
	r := core.admin_unlink_saram('00000000-0000-0000-0000-000000000080', 'unlinkUserSaramFn', '00000000-0000-0000-0000-000000000074', '9100001', 'SARAM digitado errado.', 'fresh');
	assert (select saram is null from core.user_data where id = '00000000-0000-0000-0000-000000000074');

	-- tipo de conta
	perform pg_temp.expect_error($q$ select core.admin_set_account_kind('00000000-0000-0000-0000-000000000080', 'setUserAccountKindFn', '00000000-0000-0000-0000-000000000079', 'pessoal', 'pessoal', 'Conta de pessoa, marcada por engano.', 'fresh') $q$, 'ACCOUNT_KIND_CHANGED');
	r := core.admin_set_account_kind('00000000-0000-0000-0000-000000000080', 'setUserAccountKindFn', '00000000-0000-0000-0000-000000000079', 'pessoal', 'institucional', 'Conta de pessoa, marcada por engano.', 'fresh');
	assert r ->> 'outcome' = 'changed' and (select account_kind from core.user_data where id = '00000000-0000-0000-0000-000000000079') = 'pessoal';
	-- conta sem linha em core.user_data: a linha nasce do e-mail do Auth
	r := core.admin_set_account_kind('00000000-0000-0000-0000-000000000080', 'setUserAccountKindFn', '00000000-0000-0000-0000-000000000078', 'institucional', 'pessoal', 'Conta da seção de subsistência.', 'fresh');
	assert (select account_kind = 'institucional' and email = 'forcabruta@fab.mil.br' from core.user_data where id = '00000000-0000-0000-0000-000000000078');

	-- recusa não grava log; cada mudança grava uma
	assert (select count(*) from access_control.sensitive_operation_log) = v_log + 7, (select count(*) from access_control.sensitive_operation_log) - v_log;
	perform pg_temp.expect_error($q$ select core.admin_unlink_saram('00000000-0000-0000-0000-000000000080', 'unlinkUserSaramFn', '00000000-0000-0000-0000-000000000074', '9100001', 'curto', 'fresh') $q$, 'NOTE_REQUIRED');
end $$;

-- ── Privilégios ─────────────────────────────────────────────────────────────
do $$
declare f text;
begin
	foreach f in array array[
		'core.saram_link_status(uuid, text, boolean)', 'core.visible_saram(uuid)', 'core.confirm_saram_candidate(uuid, text, boolean, bigint, text)',
		'core.verify_saram_by_cpf(uuid, text, boolean, text, text)', 'core.request_saram_link(uuid, text, boolean, text, text)',
		'core.claim_saram(uuid, text, boolean, text)', 'core.set_own_account_kind(uuid, text, boolean, text)', 'core.saram_review_queue()',
		'core.decide_saram_request(uuid, text, uuid, text, text, text)', 'core.admin_link_saram(uuid, text, uuid, text, text, text, text)',
		'core.saram_email_candidates(text)', 'core.assign_saram(uuid, text, text, text)'
	] loop
		assert has_function_privilege('service_role', f, 'execute'), f;
		assert not has_function_privilege('anon', f, 'execute'), f;
		assert not has_function_privilege('authenticated', f, 'execute'), f;
	end loop;
	assert not has_table_privilege('authenticated', 'core.saram_verification_attempt', 'select');
	assert coalesce((select proconfig from pg_proc where oid = 'core.claim_saram(uuid, text, boolean, text)'::regprocedure), '{}') @> array['search_path=""'];
end $$;

select 'saram-link: OK' as resultado;
