/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as PublicTutorialRouteImport } from './routes/_public/tutorial'
import { Route as PublicChangelogRouteImport } from './routes/_public/changelog'
import { Route as ProtectedHubRouteImport } from './routes/_protected/hub'
import { Route as ProtectedModulesRouteRouteImport } from './routes/_protected/_modules/route'
import { Route as ProtectedModulesAnalyticsRouteRouteImport } from './routes/_protected/_modules/analytics/route'
import { Route as ProtectedModulesUnitIndexRouteImport } from './routes/_protected/_modules/unit/index'
import { Route as ProtectedModulesMesshallIndexRouteImport } from './routes/_protected/_modules/messhall/index'
import { Route as ProtectedModulesLocalAnalyticsIndexRouteImport } from './routes/_protected/_modules/local-analytics/index'
import { Route as ProtectedModulesKitchenIndexRouteImport } from './routes/_protected/_modules/kitchen/index'
import { Route as ProtectedModulesKitchenProductionIndexRouteImport } from './routes/_protected/_modules/kitchen-production/index'
import { Route as ProtectedModulesGlobalIndexRouteImport } from './routes/_protected/_modules/global/index'
import { Route as ProtectedModulesDinerIndexRouteImport } from './routes/_protected/_modules/diner/index'
import { Route as ProtectedModulesAnalyticsIndexRouteImport } from './routes/_protected/_modules/analytics/index'
import { Route as ProtectedModulesGlobalPolicyRouteImport } from './routes/_protected/_modules/global/policy'
import { Route as ProtectedModulesGlobalPlacesManagerRouteImport } from './routes/_protected/_modules/global/places-manager'
import { Route as ProtectedModulesGlobalPermissionsRouteImport } from './routes/_protected/_modules/global/permissions'
import { Route as ProtectedModulesGlobalEvaluationRouteImport } from './routes/_protected/_modules/global/evaluation'
import { Route as ProtectedModulesGlobalComprasSyncRouteImport } from './routes/_protected/_modules/global/compras-sync'
import { Route as ProtectedModulesGlobalChatRouteImport } from './routes/_protected/_modules/global/chat'
import { Route as ProtectedModulesDinerSelfCheckInRouteImport } from './routes/_protected/_modules/diner/self-check-in'
import { Route as ProtectedModulesDinerQrCodeRouteImport } from './routes/_protected/_modules/diner/qr-code'
import { Route as ProtectedModulesDinerProfileRouteImport } from './routes/_protected/_modules/diner/profile'
import { Route as ProtectedModulesDinerMenuRouteImport } from './routes/_protected/_modules/diner/menu'
import { Route as ProtectedModulesDinerMcpKeysRouteImport } from './routes/_protected/_modules/diner/mcp-keys'
import { Route as ProtectedModulesDinerForecastRouteImport } from './routes/_protected/_modules/diner/forecast'
import { Route as ProtectedModulesAnalyticsGlobalRouteImport } from './routes/_protected/_modules/analytics/global'
import { Route as ProtectedModulesAnalyticsChatRouteImport } from './routes/_protected/_modules/analytics/chat'
import { Route as ProtectedModulesUnitUnitIdRouteRouteImport } from './routes/_protected/_modules/unit/$unitId/route'
import { Route as ProtectedModulesMesshallMessHallIdRouteRouteImport } from './routes/_protected/_modules/messhall/$messHallId/route'
import { Route as ProtectedModulesLocalAnalyticsUnitIdRouteRouteImport } from './routes/_protected/_modules/local-analytics/$unitId/route'
import { Route as ProtectedModulesKitchenKitchenIdRouteRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/route'
import { Route as ProtectedModulesKitchenProductionKitchenIdRouteRouteImport } from './routes/_protected/_modules/kitchen-production/$kitchenId/route'
import { Route as ProtectedModulesUnitUnitIdIndexRouteImport } from './routes/_protected/_modules/unit/$unitId/index'
import { Route as ProtectedModulesMesshallMessHallIdIndexRouteImport } from './routes/_protected/_modules/messhall/$messHallId/index'
import { Route as ProtectedModulesKitchenKitchenIdIndexRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/index'
import { Route as ProtectedModulesKitchenProductionKitchenIdIndexRouteImport } from './routes/_protected/_modules/kitchen-production/$kitchenId/index'
import { Route as ProtectedModulesGlobalWeeklyPlansIndexRouteImport } from './routes/_protected/_modules/global/weekly-plans/index'
import { Route as ProtectedModulesGlobalRecipesIndexRouteImport } from './routes/_protected/_modules/global/recipes/index'
import { Route as ProtectedModulesGlobalIngredientsIndexRouteImport } from './routes/_protected/_modules/global/ingredients/index'
import { Route as ProtectedModulesUnitUnitIdSettingsRouteImport } from './routes/_protected/_modules/unit/$unitId/settings'
import { Route as ProtectedModulesUnitUnitIdProcurementRouteImport } from './routes/_protected/_modules/unit/$unitId/procurement'
import { Route as ProtectedModulesUnitUnitIdDashboardRouteImport } from './routes/_protected/_modules/unit/$unitId/dashboard'
import { Route as ProtectedModulesUnitUnitIdChatRouteImport } from './routes/_protected/_modules/unit/$unitId/chat'
import { Route as ProtectedModulesLocalAnalyticsUnitIdIndicatorsRouteImport } from './routes/_protected/_modules/local-analytics/$unitId/indicators'
import { Route as ProtectedModulesLocalAnalyticsUnitIdDashboardRouteImport } from './routes/_protected/_modules/local-analytics/$unitId/dashboard'
import { Route as ProtectedModulesKitchenKitchenIdSettingsRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/settings'
import { Route as ProtectedModulesKitchenKitchenIdQrCodeRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/qr-code'
import { Route as ProtectedModulesKitchenKitchenIdPlanningRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/planning'
import { Route as ProtectedModulesKitchenKitchenIdChatRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/chat'
import { Route as ProtectedModulesGlobalWeeklyPlansNewRouteImport } from './routes/_protected/_modules/global/weekly-plans/new'
import { Route as ProtectedModulesGlobalWeeklyPlansPlanIdRouteImport } from './routes/_protected/_modules/global/weekly-plans/$planId'
import { Route as ProtectedModulesGlobalRecipesNewRouteImport } from './routes/_protected/_modules/global/recipes/new'
import { Route as ProtectedModulesGlobalIngredientsIngredientIdRouteImport } from './routes/_protected/_modules/global/ingredients/$ingredientId'
import { Route as ProtectedModulesUnitUnitIdProcurementIndexRouteImport } from './routes/_protected/_modules/unit/$unitId/procurement/index'
import { Route as ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/weekly-menus/index'
import { Route as ProtectedModulesKitchenKitchenIdSuprimentosIndexRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/suprimentos/index'
import { Route as ProtectedModulesKitchenKitchenIdRecipesIndexRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/recipes/index'
import { Route as ProtectedModulesKitchenKitchenIdEventsIndexRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/events/index'
import { Route as ProtectedModulesGlobalRecipesRecipeIdIndexRouteImport } from './routes/_protected/_modules/global/recipes/$recipeId/index'
import { Route as ProtectedModulesUnitUnitIdProcurementNewRouteImport } from './routes/_protected/_modules/unit/$unitId/procurement/new'
import { Route as ProtectedModulesUnitUnitIdProcurementAtaIdRouteImport } from './routes/_protected/_modules/unit/$unitId/procurement/$ataId'
import { Route as ProtectedModulesKitchenKitchenIdWeeklyMenusNewRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/weekly-menus/new'
import { Route as ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/weekly-menus/$weeklyMenuId'
import { Route as ProtectedModulesKitchenKitchenIdSuprimentosNewRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/suprimentos/new'
import { Route as ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/suprimentos/$draftId'
import { Route as ProtectedModulesKitchenKitchenIdRecipesNewRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/recipes/new'
import { Route as ProtectedModulesKitchenKitchenIdEventsNewRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/events/new'
import { Route as ProtectedModulesKitchenKitchenIdEventsEventIdRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/events/$eventId'
import { Route as ProtectedModulesGlobalRecipesRecipeIdVersionsRouteImport } from './routes/_protected/_modules/global/recipes/$recipeId/versions'
import { Route as ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/route'
import { Route as ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/index'
import { Route as ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/versions'
import { Route as ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRouteImport } from './routes/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/fork'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicTutorialRoute = PublicTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicChangelogRoute = PublicChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedHubRoute = ProtectedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedModulesRouteRoute = ProtectedModulesRouteRouteImport.update({
  id: '/_modules',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedModulesAnalyticsRouteRoute =
  ProtectedModulesAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesUnitIndexRoute =
  ProtectedModulesUnitIndexRouteImport.update({
    id: '/unit/',
    path: '/unit/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesMesshallIndexRoute =
  ProtectedModulesMesshallIndexRouteImport.update({
    id: '/messhall/',
    path: '/messhall/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesLocalAnalyticsIndexRoute =
  ProtectedModulesLocalAnalyticsIndexRouteImport.update({
    id: '/local-analytics/',
    path: '/local-analytics/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesKitchenIndexRoute =
  ProtectedModulesKitchenIndexRouteImport.update({
    id: '/kitchen/',
    path: '/kitchen/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesKitchenProductionIndexRoute =
  ProtectedModulesKitchenProductionIndexRouteImport.update({
    id: '/kitchen-production/',
    path: '/kitchen-production/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalIndexRoute =
  ProtectedModulesGlobalIndexRouteImport.update({
    id: '/global/',
    path: '/global/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesDinerIndexRoute =
  ProtectedModulesDinerIndexRouteImport.update({
    id: '/diner/',
    path: '/diner/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesAnalyticsIndexRoute =
  ProtectedModulesAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedModulesAnalyticsRouteRoute,
  } as any)
const ProtectedModulesGlobalPolicyRoute =
  ProtectedModulesGlobalPolicyRouteImport.update({
    id: '/global/policy',
    path: '/global/policy',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalPlacesManagerRoute =
  ProtectedModulesGlobalPlacesManagerRouteImport.update({
    id: '/global/places-manager',
    path: '/global/places-manager',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalPermissionsRoute =
  ProtectedModulesGlobalPermissionsRouteImport.update({
    id: '/global/permissions',
    path: '/global/permissions',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalEvaluationRoute =
  ProtectedModulesGlobalEvaluationRouteImport.update({
    id: '/global/evaluation',
    path: '/global/evaluation',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalComprasSyncRoute =
  ProtectedModulesGlobalComprasSyncRouteImport.update({
    id: '/global/compras-sync',
    path: '/global/compras-sync',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalChatRoute =
  ProtectedModulesGlobalChatRouteImport.update({
    id: '/global/chat',
    path: '/global/chat',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesDinerSelfCheckInRoute =
  ProtectedModulesDinerSelfCheckInRouteImport.update({
    id: '/diner/self-check-in',
    path: '/diner/self-check-in',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesDinerQrCodeRoute =
  ProtectedModulesDinerQrCodeRouteImport.update({
    id: '/diner/qr-code',
    path: '/diner/qr-code',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesDinerProfileRoute =
  ProtectedModulesDinerProfileRouteImport.update({
    id: '/diner/profile',
    path: '/diner/profile',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesDinerMenuRoute =
  ProtectedModulesDinerMenuRouteImport.update({
    id: '/diner/menu',
    path: '/diner/menu',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesDinerMcpKeysRoute =
  ProtectedModulesDinerMcpKeysRouteImport.update({
    id: '/diner/mcp-keys',
    path: '/diner/mcp-keys',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesDinerForecastRoute =
  ProtectedModulesDinerForecastRouteImport.update({
    id: '/diner/forecast',
    path: '/diner/forecast',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesAnalyticsGlobalRoute =
  ProtectedModulesAnalyticsGlobalRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => ProtectedModulesAnalyticsRouteRoute,
  } as any)
const ProtectedModulesAnalyticsChatRoute =
  ProtectedModulesAnalyticsChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => ProtectedModulesAnalyticsRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdRouteRoute =
  ProtectedModulesUnitUnitIdRouteRouteImport.update({
    id: '/unit/$unitId',
    path: '/unit/$unitId',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesMesshallMessHallIdRouteRoute =
  ProtectedModulesMesshallMessHallIdRouteRouteImport.update({
    id: '/messhall/$messHallId',
    path: '/messhall/$messHallId',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesLocalAnalyticsUnitIdRouteRoute =
  ProtectedModulesLocalAnalyticsUnitIdRouteRouteImport.update({
    id: '/local-analytics/$unitId',
    path: '/local-analytics/$unitId',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdRouteRoute =
  ProtectedModulesKitchenKitchenIdRouteRouteImport.update({
    id: '/kitchen/$kitchenId',
    path: '/kitchen/$kitchenId',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesKitchenProductionKitchenIdRouteRoute =
  ProtectedModulesKitchenProductionKitchenIdRouteRouteImport.update({
    id: '/kitchen-production/$kitchenId',
    path: '/kitchen-production/$kitchenId',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdIndexRoute =
  ProtectedModulesUnitUnitIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedModulesUnitUnitIdRouteRoute,
  } as any)
const ProtectedModulesMesshallMessHallIdIndexRoute =
  ProtectedModulesMesshallMessHallIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedModulesMesshallMessHallIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdIndexRoute =
  ProtectedModulesKitchenKitchenIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenProductionKitchenIdIndexRoute =
  ProtectedModulesKitchenProductionKitchenIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedModulesKitchenProductionKitchenIdRouteRoute,
  } as any)
const ProtectedModulesGlobalWeeklyPlansIndexRoute =
  ProtectedModulesGlobalWeeklyPlansIndexRouteImport.update({
    id: '/global/weekly-plans/',
    path: '/global/weekly-plans/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalRecipesIndexRoute =
  ProtectedModulesGlobalRecipesIndexRouteImport.update({
    id: '/global/recipes/',
    path: '/global/recipes/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalIngredientsIndexRoute =
  ProtectedModulesGlobalIngredientsIndexRouteImport.update({
    id: '/global/ingredients/',
    path: '/global/ingredients/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdSettingsRoute =
  ProtectedModulesUnitUnitIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedModulesUnitUnitIdRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdProcurementRoute =
  ProtectedModulesUnitUnitIdProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => ProtectedModulesUnitUnitIdRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdDashboardRoute =
  ProtectedModulesUnitUnitIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedModulesUnitUnitIdRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdChatRoute =
  ProtectedModulesUnitUnitIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => ProtectedModulesUnitUnitIdRouteRoute,
  } as any)
const ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute =
  ProtectedModulesLocalAnalyticsUnitIdIndicatorsRouteImport.update({
    id: '/indicators',
    path: '/indicators',
    getParentRoute: () => ProtectedModulesLocalAnalyticsUnitIdRouteRoute,
  } as any)
const ProtectedModulesLocalAnalyticsUnitIdDashboardRoute =
  ProtectedModulesLocalAnalyticsUnitIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedModulesLocalAnalyticsUnitIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdSettingsRoute =
  ProtectedModulesKitchenKitchenIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdQrCodeRoute =
  ProtectedModulesKitchenKitchenIdQrCodeRouteImport.update({
    id: '/qr-code',
    path: '/qr-code',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdPlanningRoute =
  ProtectedModulesKitchenKitchenIdPlanningRouteImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdChatRoute =
  ProtectedModulesKitchenKitchenIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesGlobalWeeklyPlansNewRoute =
  ProtectedModulesGlobalWeeklyPlansNewRouteImport.update({
    id: '/global/weekly-plans/new',
    path: '/global/weekly-plans/new',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalWeeklyPlansPlanIdRoute =
  ProtectedModulesGlobalWeeklyPlansPlanIdRouteImport.update({
    id: '/global/weekly-plans/$planId',
    path: '/global/weekly-plans/$planId',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalRecipesNewRoute =
  ProtectedModulesGlobalRecipesNewRouteImport.update({
    id: '/global/recipes/new',
    path: '/global/recipes/new',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesGlobalIngredientsIngredientIdRoute =
  ProtectedModulesGlobalIngredientsIngredientIdRouteImport.update({
    id: '/global/ingredients/$ingredientId',
    path: '/global/ingredients/$ingredientId',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdProcurementIndexRoute =
  ProtectedModulesUnitUnitIdProcurementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedModulesUnitUnitIdProcurementRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute =
  ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRouteImport.update({
    id: '/weekly-menus/',
    path: '/weekly-menus/',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute =
  ProtectedModulesKitchenKitchenIdSuprimentosIndexRouteImport.update({
    id: '/suprimentos/',
    path: '/suprimentos/',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdRecipesIndexRoute =
  ProtectedModulesKitchenKitchenIdRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdEventsIndexRoute =
  ProtectedModulesKitchenKitchenIdEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesGlobalRecipesRecipeIdIndexRoute =
  ProtectedModulesGlobalRecipesRecipeIdIndexRouteImport.update({
    id: '/global/recipes/$recipeId/',
    path: '/global/recipes/$recipeId/',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesUnitUnitIdProcurementNewRoute =
  ProtectedModulesUnitUnitIdProcurementNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedModulesUnitUnitIdProcurementRoute,
  } as any)
const ProtectedModulesUnitUnitIdProcurementAtaIdRoute =
  ProtectedModulesUnitUnitIdProcurementAtaIdRouteImport.update({
    id: '/$ataId',
    path: '/$ataId',
    getParentRoute: () => ProtectedModulesUnitUnitIdProcurementRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute =
  ProtectedModulesKitchenKitchenIdWeeklyMenusNewRouteImport.update({
    id: '/weekly-menus/new',
    path: '/weekly-menus/new',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute =
  ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRouteImport.update({
    id: '/weekly-menus/$weeklyMenuId',
    path: '/weekly-menus/$weeklyMenuId',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdSuprimentosNewRoute =
  ProtectedModulesKitchenKitchenIdSuprimentosNewRouteImport.update({
    id: '/suprimentos/new',
    path: '/suprimentos/new',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute =
  ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRouteImport.update({
    id: '/suprimentos/$draftId',
    path: '/suprimentos/$draftId',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdRecipesNewRoute =
  ProtectedModulesKitchenKitchenIdRecipesNewRouteImport.update({
    id: '/recipes/new',
    path: '/recipes/new',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdEventsNewRoute =
  ProtectedModulesKitchenKitchenIdEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdEventsEventIdRoute =
  ProtectedModulesKitchenKitchenIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesGlobalRecipesRecipeIdVersionsRoute =
  ProtectedModulesGlobalRecipesRecipeIdVersionsRouteImport.update({
    id: '/global/recipes/$recipeId/versions',
    path: '/global/recipes/$recipeId/versions',
    getParentRoute: () => ProtectedModulesRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute =
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => ProtectedModulesKitchenKitchenIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute =
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute =
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () =>
      ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute,
  } as any)
const ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute =
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRouteImport.update({
    id: '/fork',
    path: '/fork',
    getParentRoute: () =>
      ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/hub': typeof ProtectedHubRoute
  '/changelog': typeof PublicChangelogRoute
  '/tutorial': typeof PublicTutorialRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/analytics': typeof ProtectedModulesAnalyticsRouteRouteWithChildren
  '/kitchen-production/$kitchenId': typeof ProtectedModulesKitchenProductionKitchenIdRouteRouteWithChildren
  '/kitchen/$kitchenId': typeof ProtectedModulesKitchenKitchenIdRouteRouteWithChildren
  '/local-analytics/$unitId': typeof ProtectedModulesLocalAnalyticsUnitIdRouteRouteWithChildren
  '/messhall/$messHallId': typeof ProtectedModulesMesshallMessHallIdRouteRouteWithChildren
  '/unit/$unitId': typeof ProtectedModulesUnitUnitIdRouteRouteWithChildren
  '/analytics/chat': typeof ProtectedModulesAnalyticsChatRoute
  '/analytics/global': typeof ProtectedModulesAnalyticsGlobalRoute
  '/diner/forecast': typeof ProtectedModulesDinerForecastRoute
  '/diner/mcp-keys': typeof ProtectedModulesDinerMcpKeysRoute
  '/diner/menu': typeof ProtectedModulesDinerMenuRoute
  '/diner/profile': typeof ProtectedModulesDinerProfileRoute
  '/diner/qr-code': typeof ProtectedModulesDinerQrCodeRoute
  '/diner/self-check-in': typeof ProtectedModulesDinerSelfCheckInRoute
  '/global/chat': typeof ProtectedModulesGlobalChatRoute
  '/global/compras-sync': typeof ProtectedModulesGlobalComprasSyncRoute
  '/global/evaluation': typeof ProtectedModulesGlobalEvaluationRoute
  '/global/permissions': typeof ProtectedModulesGlobalPermissionsRoute
  '/global/places-manager': typeof ProtectedModulesGlobalPlacesManagerRoute
  '/global/policy': typeof ProtectedModulesGlobalPolicyRoute
  '/analytics/': typeof ProtectedModulesAnalyticsIndexRoute
  '/diner/': typeof ProtectedModulesDinerIndexRoute
  '/global/': typeof ProtectedModulesGlobalIndexRoute
  '/kitchen-production/': typeof ProtectedModulesKitchenProductionIndexRoute
  '/kitchen/': typeof ProtectedModulesKitchenIndexRoute
  '/local-analytics/': typeof ProtectedModulesLocalAnalyticsIndexRoute
  '/messhall/': typeof ProtectedModulesMesshallIndexRoute
  '/unit/': typeof ProtectedModulesUnitIndexRoute
  '/global/ingredients/$ingredientId': typeof ProtectedModulesGlobalIngredientsIngredientIdRoute
  '/global/recipes/new': typeof ProtectedModulesGlobalRecipesNewRoute
  '/global/weekly-plans/$planId': typeof ProtectedModulesGlobalWeeklyPlansPlanIdRoute
  '/global/weekly-plans/new': typeof ProtectedModulesGlobalWeeklyPlansNewRoute
  '/kitchen/$kitchenId/chat': typeof ProtectedModulesKitchenKitchenIdChatRoute
  '/kitchen/$kitchenId/planning': typeof ProtectedModulesKitchenKitchenIdPlanningRoute
  '/kitchen/$kitchenId/qr-code': typeof ProtectedModulesKitchenKitchenIdQrCodeRoute
  '/kitchen/$kitchenId/settings': typeof ProtectedModulesKitchenKitchenIdSettingsRoute
  '/local-analytics/$unitId/dashboard': typeof ProtectedModulesLocalAnalyticsUnitIdDashboardRoute
  '/local-analytics/$unitId/indicators': typeof ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute
  '/unit/$unitId/chat': typeof ProtectedModulesUnitUnitIdChatRoute
  '/unit/$unitId/dashboard': typeof ProtectedModulesUnitUnitIdDashboardRoute
  '/unit/$unitId/procurement': typeof ProtectedModulesUnitUnitIdProcurementRouteWithChildren
  '/unit/$unitId/settings': typeof ProtectedModulesUnitUnitIdSettingsRoute
  '/global/ingredients/': typeof ProtectedModulesGlobalIngredientsIndexRoute
  '/global/recipes/': typeof ProtectedModulesGlobalRecipesIndexRoute
  '/global/weekly-plans/': typeof ProtectedModulesGlobalWeeklyPlansIndexRoute
  '/kitchen-production/$kitchenId/': typeof ProtectedModulesKitchenProductionKitchenIdIndexRoute
  '/kitchen/$kitchenId/': typeof ProtectedModulesKitchenKitchenIdIndexRoute
  '/messhall/$messHallId/': typeof ProtectedModulesMesshallMessHallIdIndexRoute
  '/unit/$unitId/': typeof ProtectedModulesUnitUnitIdIndexRoute
  '/kitchen/$kitchenId/recipes/$recipeId': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteWithChildren
  '/global/recipes/$recipeId/versions': typeof ProtectedModulesGlobalRecipesRecipeIdVersionsRoute
  '/kitchen/$kitchenId/events/$eventId': typeof ProtectedModulesKitchenKitchenIdEventsEventIdRoute
  '/kitchen/$kitchenId/events/new': typeof ProtectedModulesKitchenKitchenIdEventsNewRoute
  '/kitchen/$kitchenId/recipes/new': typeof ProtectedModulesKitchenKitchenIdRecipesNewRoute
  '/kitchen/$kitchenId/suprimentos/$draftId': typeof ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute
  '/kitchen/$kitchenId/suprimentos/new': typeof ProtectedModulesKitchenKitchenIdSuprimentosNewRoute
  '/kitchen/$kitchenId/weekly-menus/$weeklyMenuId': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute
  '/kitchen/$kitchenId/weekly-menus/new': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute
  '/unit/$unitId/procurement/$ataId': typeof ProtectedModulesUnitUnitIdProcurementAtaIdRoute
  '/unit/$unitId/procurement/new': typeof ProtectedModulesUnitUnitIdProcurementNewRoute
  '/global/recipes/$recipeId/': typeof ProtectedModulesGlobalRecipesRecipeIdIndexRoute
  '/kitchen/$kitchenId/events/': typeof ProtectedModulesKitchenKitchenIdEventsIndexRoute
  '/kitchen/$kitchenId/recipes/': typeof ProtectedModulesKitchenKitchenIdRecipesIndexRoute
  '/kitchen/$kitchenId/suprimentos/': typeof ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute
  '/kitchen/$kitchenId/weekly-menus/': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute
  '/unit/$unitId/procurement/': typeof ProtectedModulesUnitUnitIdProcurementIndexRoute
  '/kitchen/$kitchenId/recipes/$recipeId/fork': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute
  '/kitchen/$kitchenId/recipes/$recipeId/versions': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute
  '/kitchen/$kitchenId/recipes/$recipeId/': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/health': typeof HealthRoute
  '/hub': typeof ProtectedHubRoute
  '/changelog': typeof PublicChangelogRoute
  '/tutorial': typeof PublicTutorialRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/local-analytics/$unitId': typeof ProtectedModulesLocalAnalyticsUnitIdRouteRouteWithChildren
  '/analytics/chat': typeof ProtectedModulesAnalyticsChatRoute
  '/analytics/global': typeof ProtectedModulesAnalyticsGlobalRoute
  '/diner/forecast': typeof ProtectedModulesDinerForecastRoute
  '/diner/mcp-keys': typeof ProtectedModulesDinerMcpKeysRoute
  '/diner/menu': typeof ProtectedModulesDinerMenuRoute
  '/diner/profile': typeof ProtectedModulesDinerProfileRoute
  '/diner/qr-code': typeof ProtectedModulesDinerQrCodeRoute
  '/diner/self-check-in': typeof ProtectedModulesDinerSelfCheckInRoute
  '/global/chat': typeof ProtectedModulesGlobalChatRoute
  '/global/compras-sync': typeof ProtectedModulesGlobalComprasSyncRoute
  '/global/evaluation': typeof ProtectedModulesGlobalEvaluationRoute
  '/global/permissions': typeof ProtectedModulesGlobalPermissionsRoute
  '/global/places-manager': typeof ProtectedModulesGlobalPlacesManagerRoute
  '/global/policy': typeof ProtectedModulesGlobalPolicyRoute
  '/analytics': typeof ProtectedModulesAnalyticsIndexRoute
  '/diner': typeof ProtectedModulesDinerIndexRoute
  '/global': typeof ProtectedModulesGlobalIndexRoute
  '/kitchen-production': typeof ProtectedModulesKitchenProductionIndexRoute
  '/kitchen': typeof ProtectedModulesKitchenIndexRoute
  '/local-analytics': typeof ProtectedModulesLocalAnalyticsIndexRoute
  '/messhall': typeof ProtectedModulesMesshallIndexRoute
  '/unit': typeof ProtectedModulesUnitIndexRoute
  '/global/ingredients/$ingredientId': typeof ProtectedModulesGlobalIngredientsIngredientIdRoute
  '/global/recipes/new': typeof ProtectedModulesGlobalRecipesNewRoute
  '/global/weekly-plans/$planId': typeof ProtectedModulesGlobalWeeklyPlansPlanIdRoute
  '/global/weekly-plans/new': typeof ProtectedModulesGlobalWeeklyPlansNewRoute
  '/kitchen/$kitchenId/chat': typeof ProtectedModulesKitchenKitchenIdChatRoute
  '/kitchen/$kitchenId/planning': typeof ProtectedModulesKitchenKitchenIdPlanningRoute
  '/kitchen/$kitchenId/qr-code': typeof ProtectedModulesKitchenKitchenIdQrCodeRoute
  '/kitchen/$kitchenId/settings': typeof ProtectedModulesKitchenKitchenIdSettingsRoute
  '/local-analytics/$unitId/dashboard': typeof ProtectedModulesLocalAnalyticsUnitIdDashboardRoute
  '/local-analytics/$unitId/indicators': typeof ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute
  '/unit/$unitId/chat': typeof ProtectedModulesUnitUnitIdChatRoute
  '/unit/$unitId/dashboard': typeof ProtectedModulesUnitUnitIdDashboardRoute
  '/unit/$unitId/settings': typeof ProtectedModulesUnitUnitIdSettingsRoute
  '/global/ingredients': typeof ProtectedModulesGlobalIngredientsIndexRoute
  '/global/recipes': typeof ProtectedModulesGlobalRecipesIndexRoute
  '/global/weekly-plans': typeof ProtectedModulesGlobalWeeklyPlansIndexRoute
  '/kitchen-production/$kitchenId': typeof ProtectedModulesKitchenProductionKitchenIdIndexRoute
  '/kitchen/$kitchenId': typeof ProtectedModulesKitchenKitchenIdIndexRoute
  '/messhall/$messHallId': typeof ProtectedModulesMesshallMessHallIdIndexRoute
  '/unit/$unitId': typeof ProtectedModulesUnitUnitIdIndexRoute
  '/global/recipes/$recipeId/versions': typeof ProtectedModulesGlobalRecipesRecipeIdVersionsRoute
  '/kitchen/$kitchenId/events/$eventId': typeof ProtectedModulesKitchenKitchenIdEventsEventIdRoute
  '/kitchen/$kitchenId/events/new': typeof ProtectedModulesKitchenKitchenIdEventsNewRoute
  '/kitchen/$kitchenId/recipes/new': typeof ProtectedModulesKitchenKitchenIdRecipesNewRoute
  '/kitchen/$kitchenId/suprimentos/$draftId': typeof ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute
  '/kitchen/$kitchenId/suprimentos/new': typeof ProtectedModulesKitchenKitchenIdSuprimentosNewRoute
  '/kitchen/$kitchenId/weekly-menus/$weeklyMenuId': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute
  '/kitchen/$kitchenId/weekly-menus/new': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute
  '/unit/$unitId/procurement/$ataId': typeof ProtectedModulesUnitUnitIdProcurementAtaIdRoute
  '/unit/$unitId/procurement/new': typeof ProtectedModulesUnitUnitIdProcurementNewRoute
  '/global/recipes/$recipeId': typeof ProtectedModulesGlobalRecipesRecipeIdIndexRoute
  '/kitchen/$kitchenId/events': typeof ProtectedModulesKitchenKitchenIdEventsIndexRoute
  '/kitchen/$kitchenId/recipes': typeof ProtectedModulesKitchenKitchenIdRecipesIndexRoute
  '/kitchen/$kitchenId/suprimentos': typeof ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute
  '/kitchen/$kitchenId/weekly-menus': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute
  '/unit/$unitId/procurement': typeof ProtectedModulesUnitUnitIdProcurementIndexRoute
  '/kitchen/$kitchenId/recipes/$recipeId/fork': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute
  '/kitchen/$kitchenId/recipes/$recipeId/versions': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute
  '/kitchen/$kitchenId/recipes/$recipeId': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/_protected/_modules': typeof ProtectedModulesRouteRouteWithChildren
  '/_protected/hub': typeof ProtectedHubRoute
  '/_public/changelog': typeof PublicChangelogRoute
  '/_public/tutorial': typeof PublicTutorialRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_public/': typeof PublicIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/_modules/analytics': typeof ProtectedModulesAnalyticsRouteRouteWithChildren
  '/_protected/_modules/kitchen-production/$kitchenId': typeof ProtectedModulesKitchenProductionKitchenIdRouteRouteWithChildren
  '/_protected/_modules/kitchen/$kitchenId': typeof ProtectedModulesKitchenKitchenIdRouteRouteWithChildren
  '/_protected/_modules/local-analytics/$unitId': typeof ProtectedModulesLocalAnalyticsUnitIdRouteRouteWithChildren
  '/_protected/_modules/messhall/$messHallId': typeof ProtectedModulesMesshallMessHallIdRouteRouteWithChildren
  '/_protected/_modules/unit/$unitId': typeof ProtectedModulesUnitUnitIdRouteRouteWithChildren
  '/_protected/_modules/analytics/chat': typeof ProtectedModulesAnalyticsChatRoute
  '/_protected/_modules/analytics/global': typeof ProtectedModulesAnalyticsGlobalRoute
  '/_protected/_modules/diner/forecast': typeof ProtectedModulesDinerForecastRoute
  '/_protected/_modules/diner/mcp-keys': typeof ProtectedModulesDinerMcpKeysRoute
  '/_protected/_modules/diner/menu': typeof ProtectedModulesDinerMenuRoute
  '/_protected/_modules/diner/profile': typeof ProtectedModulesDinerProfileRoute
  '/_protected/_modules/diner/qr-code': typeof ProtectedModulesDinerQrCodeRoute
  '/_protected/_modules/diner/self-check-in': typeof ProtectedModulesDinerSelfCheckInRoute
  '/_protected/_modules/global/chat': typeof ProtectedModulesGlobalChatRoute
  '/_protected/_modules/global/compras-sync': typeof ProtectedModulesGlobalComprasSyncRoute
  '/_protected/_modules/global/evaluation': typeof ProtectedModulesGlobalEvaluationRoute
  '/_protected/_modules/global/permissions': typeof ProtectedModulesGlobalPermissionsRoute
  '/_protected/_modules/global/places-manager': typeof ProtectedModulesGlobalPlacesManagerRoute
  '/_protected/_modules/global/policy': typeof ProtectedModulesGlobalPolicyRoute
  '/_protected/_modules/analytics/': typeof ProtectedModulesAnalyticsIndexRoute
  '/_protected/_modules/diner/': typeof ProtectedModulesDinerIndexRoute
  '/_protected/_modules/global/': typeof ProtectedModulesGlobalIndexRoute
  '/_protected/_modules/kitchen-production/': typeof ProtectedModulesKitchenProductionIndexRoute
  '/_protected/_modules/kitchen/': typeof ProtectedModulesKitchenIndexRoute
  '/_protected/_modules/local-analytics/': typeof ProtectedModulesLocalAnalyticsIndexRoute
  '/_protected/_modules/messhall/': typeof ProtectedModulesMesshallIndexRoute
  '/_protected/_modules/unit/': typeof ProtectedModulesUnitIndexRoute
  '/_protected/_modules/global/ingredients/$ingredientId': typeof ProtectedModulesGlobalIngredientsIngredientIdRoute
  '/_protected/_modules/global/recipes/new': typeof ProtectedModulesGlobalRecipesNewRoute
  '/_protected/_modules/global/weekly-plans/$planId': typeof ProtectedModulesGlobalWeeklyPlansPlanIdRoute
  '/_protected/_modules/global/weekly-plans/new': typeof ProtectedModulesGlobalWeeklyPlansNewRoute
  '/_protected/_modules/kitchen/$kitchenId/chat': typeof ProtectedModulesKitchenKitchenIdChatRoute
  '/_protected/_modules/kitchen/$kitchenId/planning': typeof ProtectedModulesKitchenKitchenIdPlanningRoute
  '/_protected/_modules/kitchen/$kitchenId/qr-code': typeof ProtectedModulesKitchenKitchenIdQrCodeRoute
  '/_protected/_modules/kitchen/$kitchenId/settings': typeof ProtectedModulesKitchenKitchenIdSettingsRoute
  '/_protected/_modules/local-analytics/$unitId/dashboard': typeof ProtectedModulesLocalAnalyticsUnitIdDashboardRoute
  '/_protected/_modules/local-analytics/$unitId/indicators': typeof ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute
  '/_protected/_modules/unit/$unitId/chat': typeof ProtectedModulesUnitUnitIdChatRoute
  '/_protected/_modules/unit/$unitId/dashboard': typeof ProtectedModulesUnitUnitIdDashboardRoute
  '/_protected/_modules/unit/$unitId/procurement': typeof ProtectedModulesUnitUnitIdProcurementRouteWithChildren
  '/_protected/_modules/unit/$unitId/settings': typeof ProtectedModulesUnitUnitIdSettingsRoute
  '/_protected/_modules/global/ingredients/': typeof ProtectedModulesGlobalIngredientsIndexRoute
  '/_protected/_modules/global/recipes/': typeof ProtectedModulesGlobalRecipesIndexRoute
  '/_protected/_modules/global/weekly-plans/': typeof ProtectedModulesGlobalWeeklyPlansIndexRoute
  '/_protected/_modules/kitchen-production/$kitchenId/': typeof ProtectedModulesKitchenProductionKitchenIdIndexRoute
  '/_protected/_modules/kitchen/$kitchenId/': typeof ProtectedModulesKitchenKitchenIdIndexRoute
  '/_protected/_modules/messhall/$messHallId/': typeof ProtectedModulesMesshallMessHallIdIndexRoute
  '/_protected/_modules/unit/$unitId/': typeof ProtectedModulesUnitUnitIdIndexRoute
  '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteWithChildren
  '/_protected/_modules/global/recipes/$recipeId/versions': typeof ProtectedModulesGlobalRecipesRecipeIdVersionsRoute
  '/_protected/_modules/kitchen/$kitchenId/events/$eventId': typeof ProtectedModulesKitchenKitchenIdEventsEventIdRoute
  '/_protected/_modules/kitchen/$kitchenId/events/new': typeof ProtectedModulesKitchenKitchenIdEventsNewRoute
  '/_protected/_modules/kitchen/$kitchenId/recipes/new': typeof ProtectedModulesKitchenKitchenIdRecipesNewRoute
  '/_protected/_modules/kitchen/$kitchenId/suprimentos/$draftId': typeof ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute
  '/_protected/_modules/kitchen/$kitchenId/suprimentos/new': typeof ProtectedModulesKitchenKitchenIdSuprimentosNewRoute
  '/_protected/_modules/kitchen/$kitchenId/weekly-menus/$weeklyMenuId': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute
  '/_protected/_modules/kitchen/$kitchenId/weekly-menus/new': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute
  '/_protected/_modules/unit/$unitId/procurement/$ataId': typeof ProtectedModulesUnitUnitIdProcurementAtaIdRoute
  '/_protected/_modules/unit/$unitId/procurement/new': typeof ProtectedModulesUnitUnitIdProcurementNewRoute
  '/_protected/_modules/global/recipes/$recipeId/': typeof ProtectedModulesGlobalRecipesRecipeIdIndexRoute
  '/_protected/_modules/kitchen/$kitchenId/events/': typeof ProtectedModulesKitchenKitchenIdEventsIndexRoute
  '/_protected/_modules/kitchen/$kitchenId/recipes/': typeof ProtectedModulesKitchenKitchenIdRecipesIndexRoute
  '/_protected/_modules/kitchen/$kitchenId/suprimentos/': typeof ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute
  '/_protected/_modules/kitchen/$kitchenId/weekly-menus/': typeof ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute
  '/_protected/_modules/unit/$unitId/procurement/': typeof ProtectedModulesUnitUnitIdProcurementIndexRoute
  '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/fork': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute
  '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/versions': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute
  '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/': typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/health'
    | '/hub'
    | '/changelog'
    | '/tutorial'
    | '/auth/reset-password'
    | '/auth/'
    | '/analytics'
    | '/kitchen-production/$kitchenId'
    | '/kitchen/$kitchenId'
    | '/local-analytics/$unitId'
    | '/messhall/$messHallId'
    | '/unit/$unitId'
    | '/analytics/chat'
    | '/analytics/global'
    | '/diner/forecast'
    | '/diner/mcp-keys'
    | '/diner/menu'
    | '/diner/profile'
    | '/diner/qr-code'
    | '/diner/self-check-in'
    | '/global/chat'
    | '/global/compras-sync'
    | '/global/evaluation'
    | '/global/permissions'
    | '/global/places-manager'
    | '/global/policy'
    | '/analytics/'
    | '/diner/'
    | '/global/'
    | '/kitchen-production/'
    | '/kitchen/'
    | '/local-analytics/'
    | '/messhall/'
    | '/unit/'
    | '/global/ingredients/$ingredientId'
    | '/global/recipes/new'
    | '/global/weekly-plans/$planId'
    | '/global/weekly-plans/new'
    | '/kitchen/$kitchenId/chat'
    | '/kitchen/$kitchenId/planning'
    | '/kitchen/$kitchenId/qr-code'
    | '/kitchen/$kitchenId/settings'
    | '/local-analytics/$unitId/dashboard'
    | '/local-analytics/$unitId/indicators'
    | '/unit/$unitId/chat'
    | '/unit/$unitId/dashboard'
    | '/unit/$unitId/procurement'
    | '/unit/$unitId/settings'
    | '/global/ingredients/'
    | '/global/recipes/'
    | '/global/weekly-plans/'
    | '/kitchen-production/$kitchenId/'
    | '/kitchen/$kitchenId/'
    | '/messhall/$messHallId/'
    | '/unit/$unitId/'
    | '/kitchen/$kitchenId/recipes/$recipeId'
    | '/global/recipes/$recipeId/versions'
    | '/kitchen/$kitchenId/events/$eventId'
    | '/kitchen/$kitchenId/events/new'
    | '/kitchen/$kitchenId/recipes/new'
    | '/kitchen/$kitchenId/suprimentos/$draftId'
    | '/kitchen/$kitchenId/suprimentos/new'
    | '/kitchen/$kitchenId/weekly-menus/$weeklyMenuId'
    | '/kitchen/$kitchenId/weekly-menus/new'
    | '/unit/$unitId/procurement/$ataId'
    | '/unit/$unitId/procurement/new'
    | '/global/recipes/$recipeId/'
    | '/kitchen/$kitchenId/events/'
    | '/kitchen/$kitchenId/recipes/'
    | '/kitchen/$kitchenId/suprimentos/'
    | '/kitchen/$kitchenId/weekly-menus/'
    | '/unit/$unitId/procurement/'
    | '/kitchen/$kitchenId/recipes/$recipeId/fork'
    | '/kitchen/$kitchenId/recipes/$recipeId/versions'
    | '/kitchen/$kitchenId/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/hub'
    | '/changelog'
    | '/tutorial'
    | '/auth/reset-password'
    | '/auth'
    | '/local-analytics/$unitId'
    | '/analytics/chat'
    | '/analytics/global'
    | '/diner/forecast'
    | '/diner/mcp-keys'
    | '/diner/menu'
    | '/diner/profile'
    | '/diner/qr-code'
    | '/diner/self-check-in'
    | '/global/chat'
    | '/global/compras-sync'
    | '/global/evaluation'
    | '/global/permissions'
    | '/global/places-manager'
    | '/global/policy'
    | '/analytics'
    | '/diner'
    | '/global'
    | '/kitchen-production'
    | '/kitchen'
    | '/local-analytics'
    | '/messhall'
    | '/unit'
    | '/global/ingredients/$ingredientId'
    | '/global/recipes/new'
    | '/global/weekly-plans/$planId'
    | '/global/weekly-plans/new'
    | '/kitchen/$kitchenId/chat'
    | '/kitchen/$kitchenId/planning'
    | '/kitchen/$kitchenId/qr-code'
    | '/kitchen/$kitchenId/settings'
    | '/local-analytics/$unitId/dashboard'
    | '/local-analytics/$unitId/indicators'
    | '/unit/$unitId/chat'
    | '/unit/$unitId/dashboard'
    | '/unit/$unitId/settings'
    | '/global/ingredients'
    | '/global/recipes'
    | '/global/weekly-plans'
    | '/kitchen-production/$kitchenId'
    | '/kitchen/$kitchenId'
    | '/messhall/$messHallId'
    | '/unit/$unitId'
    | '/global/recipes/$recipeId/versions'
    | '/kitchen/$kitchenId/events/$eventId'
    | '/kitchen/$kitchenId/events/new'
    | '/kitchen/$kitchenId/recipes/new'
    | '/kitchen/$kitchenId/suprimentos/$draftId'
    | '/kitchen/$kitchenId/suprimentos/new'
    | '/kitchen/$kitchenId/weekly-menus/$weeklyMenuId'
    | '/kitchen/$kitchenId/weekly-menus/new'
    | '/unit/$unitId/procurement/$ataId'
    | '/unit/$unitId/procurement/new'
    | '/global/recipes/$recipeId'
    | '/kitchen/$kitchenId/events'
    | '/kitchen/$kitchenId/recipes'
    | '/kitchen/$kitchenId/suprimentos'
    | '/kitchen/$kitchenId/weekly-menus'
    | '/unit/$unitId/procurement'
    | '/kitchen/$kitchenId/recipes/$recipeId/fork'
    | '/kitchen/$kitchenId/recipes/$recipeId/versions'
    | '/kitchen/$kitchenId/recipes/$recipeId'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/auth'
    | '/health'
    | '/_protected/_modules'
    | '/_protected/hub'
    | '/_public/changelog'
    | '/_public/tutorial'
    | '/auth/reset-password'
    | '/_public/'
    | '/auth/'
    | '/_protected/_modules/analytics'
    | '/_protected/_modules/kitchen-production/$kitchenId'
    | '/_protected/_modules/kitchen/$kitchenId'
    | '/_protected/_modules/local-analytics/$unitId'
    | '/_protected/_modules/messhall/$messHallId'
    | '/_protected/_modules/unit/$unitId'
    | '/_protected/_modules/analytics/chat'
    | '/_protected/_modules/analytics/global'
    | '/_protected/_modules/diner/forecast'
    | '/_protected/_modules/diner/mcp-keys'
    | '/_protected/_modules/diner/menu'
    | '/_protected/_modules/diner/profile'
    | '/_protected/_modules/diner/qr-code'
    | '/_protected/_modules/diner/self-check-in'
    | '/_protected/_modules/global/chat'
    | '/_protected/_modules/global/compras-sync'
    | '/_protected/_modules/global/evaluation'
    | '/_protected/_modules/global/permissions'
    | '/_protected/_modules/global/places-manager'
    | '/_protected/_modules/global/policy'
    | '/_protected/_modules/analytics/'
    | '/_protected/_modules/diner/'
    | '/_protected/_modules/global/'
    | '/_protected/_modules/kitchen-production/'
    | '/_protected/_modules/kitchen/'
    | '/_protected/_modules/local-analytics/'
    | '/_protected/_modules/messhall/'
    | '/_protected/_modules/unit/'
    | '/_protected/_modules/global/ingredients/$ingredientId'
    | '/_protected/_modules/global/recipes/new'
    | '/_protected/_modules/global/weekly-plans/$planId'
    | '/_protected/_modules/global/weekly-plans/new'
    | '/_protected/_modules/kitchen/$kitchenId/chat'
    | '/_protected/_modules/kitchen/$kitchenId/planning'
    | '/_protected/_modules/kitchen/$kitchenId/qr-code'
    | '/_protected/_modules/kitchen/$kitchenId/settings'
    | '/_protected/_modules/local-analytics/$unitId/dashboard'
    | '/_protected/_modules/local-analytics/$unitId/indicators'
    | '/_protected/_modules/unit/$unitId/chat'
    | '/_protected/_modules/unit/$unitId/dashboard'
    | '/_protected/_modules/unit/$unitId/procurement'
    | '/_protected/_modules/unit/$unitId/settings'
    | '/_protected/_modules/global/ingredients/'
    | '/_protected/_modules/global/recipes/'
    | '/_protected/_modules/global/weekly-plans/'
    | '/_protected/_modules/kitchen-production/$kitchenId/'
    | '/_protected/_modules/kitchen/$kitchenId/'
    | '/_protected/_modules/messhall/$messHallId/'
    | '/_protected/_modules/unit/$unitId/'
    | '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId'
    | '/_protected/_modules/global/recipes/$recipeId/versions'
    | '/_protected/_modules/kitchen/$kitchenId/events/$eventId'
    | '/_protected/_modules/kitchen/$kitchenId/events/new'
    | '/_protected/_modules/kitchen/$kitchenId/recipes/new'
    | '/_protected/_modules/kitchen/$kitchenId/suprimentos/$draftId'
    | '/_protected/_modules/kitchen/$kitchenId/suprimentos/new'
    | '/_protected/_modules/kitchen/$kitchenId/weekly-menus/$weeklyMenuId'
    | '/_protected/_modules/kitchen/$kitchenId/weekly-menus/new'
    | '/_protected/_modules/unit/$unitId/procurement/$ataId'
    | '/_protected/_modules/unit/$unitId/procurement/new'
    | '/_protected/_modules/global/recipes/$recipeId/'
    | '/_protected/_modules/kitchen/$kitchenId/events/'
    | '/_protected/_modules/kitchen/$kitchenId/recipes/'
    | '/_protected/_modules/kitchen/$kitchenId/suprimentos/'
    | '/_protected/_modules/kitchen/$kitchenId/weekly-menus/'
    | '/_protected/_modules/unit/$unitId/procurement/'
    | '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/fork'
    | '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/versions'
    | '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/tutorial': {
      id: '/_public/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof PublicTutorialRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/changelog': {
      id: '/_public/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof PublicChangelogRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/hub': {
      id: '/_protected/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof ProtectedHubRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_modules': {
      id: '/_protected/_modules'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedModulesRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_modules/analytics': {
      id: '/_protected/_modules/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedModulesAnalyticsRouteRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/unit/': {
      id: '/_protected/_modules/unit/'
      path: '/unit'
      fullPath: '/unit/'
      preLoaderRoute: typeof ProtectedModulesUnitIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/messhall/': {
      id: '/_protected/_modules/messhall/'
      path: '/messhall'
      fullPath: '/messhall/'
      preLoaderRoute: typeof ProtectedModulesMesshallIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/local-analytics/': {
      id: '/_protected/_modules/local-analytics/'
      path: '/local-analytics'
      fullPath: '/local-analytics/'
      preLoaderRoute: typeof ProtectedModulesLocalAnalyticsIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/kitchen/': {
      id: '/_protected/_modules/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof ProtectedModulesKitchenIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/kitchen-production/': {
      id: '/_protected/_modules/kitchen-production/'
      path: '/kitchen-production'
      fullPath: '/kitchen-production/'
      preLoaderRoute: typeof ProtectedModulesKitchenProductionIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/': {
      id: '/_protected/_modules/global/'
      path: '/global'
      fullPath: '/global/'
      preLoaderRoute: typeof ProtectedModulesGlobalIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/diner/': {
      id: '/_protected/_modules/diner/'
      path: '/diner'
      fullPath: '/diner/'
      preLoaderRoute: typeof ProtectedModulesDinerIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/analytics/': {
      id: '/_protected/_modules/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof ProtectedModulesAnalyticsIndexRouteImport
      parentRoute: typeof ProtectedModulesAnalyticsRouteRoute
    }
    '/_protected/_modules/global/policy': {
      id: '/_protected/_modules/global/policy'
      path: '/global/policy'
      fullPath: '/global/policy'
      preLoaderRoute: typeof ProtectedModulesGlobalPolicyRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/places-manager': {
      id: '/_protected/_modules/global/places-manager'
      path: '/global/places-manager'
      fullPath: '/global/places-manager'
      preLoaderRoute: typeof ProtectedModulesGlobalPlacesManagerRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/permissions': {
      id: '/_protected/_modules/global/permissions'
      path: '/global/permissions'
      fullPath: '/global/permissions'
      preLoaderRoute: typeof ProtectedModulesGlobalPermissionsRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/evaluation': {
      id: '/_protected/_modules/global/evaluation'
      path: '/global/evaluation'
      fullPath: '/global/evaluation'
      preLoaderRoute: typeof ProtectedModulesGlobalEvaluationRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/compras-sync': {
      id: '/_protected/_modules/global/compras-sync'
      path: '/global/compras-sync'
      fullPath: '/global/compras-sync'
      preLoaderRoute: typeof ProtectedModulesGlobalComprasSyncRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/chat': {
      id: '/_protected/_modules/global/chat'
      path: '/global/chat'
      fullPath: '/global/chat'
      preLoaderRoute: typeof ProtectedModulesGlobalChatRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/diner/self-check-in': {
      id: '/_protected/_modules/diner/self-check-in'
      path: '/diner/self-check-in'
      fullPath: '/diner/self-check-in'
      preLoaderRoute: typeof ProtectedModulesDinerSelfCheckInRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/diner/qr-code': {
      id: '/_protected/_modules/diner/qr-code'
      path: '/diner/qr-code'
      fullPath: '/diner/qr-code'
      preLoaderRoute: typeof ProtectedModulesDinerQrCodeRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/diner/profile': {
      id: '/_protected/_modules/diner/profile'
      path: '/diner/profile'
      fullPath: '/diner/profile'
      preLoaderRoute: typeof ProtectedModulesDinerProfileRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/diner/menu': {
      id: '/_protected/_modules/diner/menu'
      path: '/diner/menu'
      fullPath: '/diner/menu'
      preLoaderRoute: typeof ProtectedModulesDinerMenuRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/diner/mcp-keys': {
      id: '/_protected/_modules/diner/mcp-keys'
      path: '/diner/mcp-keys'
      fullPath: '/diner/mcp-keys'
      preLoaderRoute: typeof ProtectedModulesDinerMcpKeysRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/diner/forecast': {
      id: '/_protected/_modules/diner/forecast'
      path: '/diner/forecast'
      fullPath: '/diner/forecast'
      preLoaderRoute: typeof ProtectedModulesDinerForecastRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/analytics/global': {
      id: '/_protected/_modules/analytics/global'
      path: '/global'
      fullPath: '/analytics/global'
      preLoaderRoute: typeof ProtectedModulesAnalyticsGlobalRouteImport
      parentRoute: typeof ProtectedModulesAnalyticsRouteRoute
    }
    '/_protected/_modules/analytics/chat': {
      id: '/_protected/_modules/analytics/chat'
      path: '/chat'
      fullPath: '/analytics/chat'
      preLoaderRoute: typeof ProtectedModulesAnalyticsChatRouteImport
      parentRoute: typeof ProtectedModulesAnalyticsRouteRoute
    }
    '/_protected/_modules/unit/$unitId': {
      id: '/_protected/_modules/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/unit/$unitId'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdRouteRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/messhall/$messHallId': {
      id: '/_protected/_modules/messhall/$messHallId'
      path: '/messhall/$messHallId'
      fullPath: '/messhall/$messHallId'
      preLoaderRoute: typeof ProtectedModulesMesshallMessHallIdRouteRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/local-analytics/$unitId': {
      id: '/_protected/_modules/local-analytics/$unitId'
      path: '/local-analytics/$unitId'
      fullPath: '/local-analytics/$unitId'
      preLoaderRoute: typeof ProtectedModulesLocalAnalyticsUnitIdRouteRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId': {
      id: '/_protected/_modules/kitchen/$kitchenId'
      path: '/kitchen/$kitchenId'
      fullPath: '/kitchen/$kitchenId'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdRouteRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/kitchen-production/$kitchenId': {
      id: '/_protected/_modules/kitchen-production/$kitchenId'
      path: '/kitchen-production/$kitchenId'
      fullPath: '/kitchen-production/$kitchenId'
      preLoaderRoute: typeof ProtectedModulesKitchenProductionKitchenIdRouteRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/unit/$unitId/': {
      id: '/_protected/_modules/unit/$unitId/'
      path: '/'
      fullPath: '/unit/$unitId/'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdIndexRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdRouteRoute
    }
    '/_protected/_modules/messhall/$messHallId/': {
      id: '/_protected/_modules/messhall/$messHallId/'
      path: '/'
      fullPath: '/messhall/$messHallId/'
      preLoaderRoute: typeof ProtectedModulesMesshallMessHallIdIndexRouteImport
      parentRoute: typeof ProtectedModulesMesshallMessHallIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/': {
      id: '/_protected/_modules/kitchen/$kitchenId/'
      path: '/'
      fullPath: '/kitchen/$kitchenId/'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdIndexRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen-production/$kitchenId/': {
      id: '/_protected/_modules/kitchen-production/$kitchenId/'
      path: '/'
      fullPath: '/kitchen-production/$kitchenId/'
      preLoaderRoute: typeof ProtectedModulesKitchenProductionKitchenIdIndexRouteImport
      parentRoute: typeof ProtectedModulesKitchenProductionKitchenIdRouteRoute
    }
    '/_protected/_modules/global/weekly-plans/': {
      id: '/_protected/_modules/global/weekly-plans/'
      path: '/global/weekly-plans'
      fullPath: '/global/weekly-plans/'
      preLoaderRoute: typeof ProtectedModulesGlobalWeeklyPlansIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/recipes/': {
      id: '/_protected/_modules/global/recipes/'
      path: '/global/recipes'
      fullPath: '/global/recipes/'
      preLoaderRoute: typeof ProtectedModulesGlobalRecipesIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/ingredients/': {
      id: '/_protected/_modules/global/ingredients/'
      path: '/global/ingredients'
      fullPath: '/global/ingredients/'
      preLoaderRoute: typeof ProtectedModulesGlobalIngredientsIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/unit/$unitId/settings': {
      id: '/_protected/_modules/unit/$unitId/settings'
      path: '/settings'
      fullPath: '/unit/$unitId/settings'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdSettingsRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdRouteRoute
    }
    '/_protected/_modules/unit/$unitId/procurement': {
      id: '/_protected/_modules/unit/$unitId/procurement'
      path: '/procurement'
      fullPath: '/unit/$unitId/procurement'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdProcurementRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdRouteRoute
    }
    '/_protected/_modules/unit/$unitId/dashboard': {
      id: '/_protected/_modules/unit/$unitId/dashboard'
      path: '/dashboard'
      fullPath: '/unit/$unitId/dashboard'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdDashboardRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdRouteRoute
    }
    '/_protected/_modules/unit/$unitId/chat': {
      id: '/_protected/_modules/unit/$unitId/chat'
      path: '/chat'
      fullPath: '/unit/$unitId/chat'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdChatRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdRouteRoute
    }
    '/_protected/_modules/local-analytics/$unitId/indicators': {
      id: '/_protected/_modules/local-analytics/$unitId/indicators'
      path: '/indicators'
      fullPath: '/local-analytics/$unitId/indicators'
      preLoaderRoute: typeof ProtectedModulesLocalAnalyticsUnitIdIndicatorsRouteImport
      parentRoute: typeof ProtectedModulesLocalAnalyticsUnitIdRouteRoute
    }
    '/_protected/_modules/local-analytics/$unitId/dashboard': {
      id: '/_protected/_modules/local-analytics/$unitId/dashboard'
      path: '/dashboard'
      fullPath: '/local-analytics/$unitId/dashboard'
      preLoaderRoute: typeof ProtectedModulesLocalAnalyticsUnitIdDashboardRouteImport
      parentRoute: typeof ProtectedModulesLocalAnalyticsUnitIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/settings': {
      id: '/_protected/_modules/kitchen/$kitchenId/settings'
      path: '/settings'
      fullPath: '/kitchen/$kitchenId/settings'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdSettingsRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/qr-code': {
      id: '/_protected/_modules/kitchen/$kitchenId/qr-code'
      path: '/qr-code'
      fullPath: '/kitchen/$kitchenId/qr-code'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdQrCodeRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/planning': {
      id: '/_protected/_modules/kitchen/$kitchenId/planning'
      path: '/planning'
      fullPath: '/kitchen/$kitchenId/planning'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdPlanningRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/chat': {
      id: '/_protected/_modules/kitchen/$kitchenId/chat'
      path: '/chat'
      fullPath: '/kitchen/$kitchenId/chat'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdChatRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/global/weekly-plans/new': {
      id: '/_protected/_modules/global/weekly-plans/new'
      path: '/global/weekly-plans/new'
      fullPath: '/global/weekly-plans/new'
      preLoaderRoute: typeof ProtectedModulesGlobalWeeklyPlansNewRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/weekly-plans/$planId': {
      id: '/_protected/_modules/global/weekly-plans/$planId'
      path: '/global/weekly-plans/$planId'
      fullPath: '/global/weekly-plans/$planId'
      preLoaderRoute: typeof ProtectedModulesGlobalWeeklyPlansPlanIdRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/recipes/new': {
      id: '/_protected/_modules/global/recipes/new'
      path: '/global/recipes/new'
      fullPath: '/global/recipes/new'
      preLoaderRoute: typeof ProtectedModulesGlobalRecipesNewRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/global/ingredients/$ingredientId': {
      id: '/_protected/_modules/global/ingredients/$ingredientId'
      path: '/global/ingredients/$ingredientId'
      fullPath: '/global/ingredients/$ingredientId'
      preLoaderRoute: typeof ProtectedModulesGlobalIngredientsIngredientIdRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/unit/$unitId/procurement/': {
      id: '/_protected/_modules/unit/$unitId/procurement/'
      path: '/'
      fullPath: '/unit/$unitId/procurement/'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdProcurementIndexRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdProcurementRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/weekly-menus/': {
      id: '/_protected/_modules/kitchen/$kitchenId/weekly-menus/'
      path: '/weekly-menus'
      fullPath: '/kitchen/$kitchenId/weekly-menus/'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/suprimentos/': {
      id: '/_protected/_modules/kitchen/$kitchenId/suprimentos/'
      path: '/suprimentos'
      fullPath: '/kitchen/$kitchenId/suprimentos/'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdSuprimentosIndexRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/recipes/': {
      id: '/_protected/_modules/kitchen/$kitchenId/recipes/'
      path: '/recipes'
      fullPath: '/kitchen/$kitchenId/recipes/'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdRecipesIndexRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/events/': {
      id: '/_protected/_modules/kitchen/$kitchenId/events/'
      path: '/events'
      fullPath: '/kitchen/$kitchenId/events/'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdEventsIndexRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/global/recipes/$recipeId/': {
      id: '/_protected/_modules/global/recipes/$recipeId/'
      path: '/global/recipes/$recipeId'
      fullPath: '/global/recipes/$recipeId/'
      preLoaderRoute: typeof ProtectedModulesGlobalRecipesRecipeIdIndexRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/unit/$unitId/procurement/new': {
      id: '/_protected/_modules/unit/$unitId/procurement/new'
      path: '/new'
      fullPath: '/unit/$unitId/procurement/new'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdProcurementNewRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdProcurementRoute
    }
    '/_protected/_modules/unit/$unitId/procurement/$ataId': {
      id: '/_protected/_modules/unit/$unitId/procurement/$ataId'
      path: '/$ataId'
      fullPath: '/unit/$unitId/procurement/$ataId'
      preLoaderRoute: typeof ProtectedModulesUnitUnitIdProcurementAtaIdRouteImport
      parentRoute: typeof ProtectedModulesUnitUnitIdProcurementRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/weekly-menus/new': {
      id: '/_protected/_modules/kitchen/$kitchenId/weekly-menus/new'
      path: '/weekly-menus/new'
      fullPath: '/kitchen/$kitchenId/weekly-menus/new'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdWeeklyMenusNewRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/weekly-menus/$weeklyMenuId': {
      id: '/_protected/_modules/kitchen/$kitchenId/weekly-menus/$weeklyMenuId'
      path: '/weekly-menus/$weeklyMenuId'
      fullPath: '/kitchen/$kitchenId/weekly-menus/$weeklyMenuId'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/suprimentos/new': {
      id: '/_protected/_modules/kitchen/$kitchenId/suprimentos/new'
      path: '/suprimentos/new'
      fullPath: '/kitchen/$kitchenId/suprimentos/new'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdSuprimentosNewRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/suprimentos/$draftId': {
      id: '/_protected/_modules/kitchen/$kitchenId/suprimentos/$draftId'
      path: '/suprimentos/$draftId'
      fullPath: '/kitchen/$kitchenId/suprimentos/$draftId'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/recipes/new': {
      id: '/_protected/_modules/kitchen/$kitchenId/recipes/new'
      path: '/recipes/new'
      fullPath: '/kitchen/$kitchenId/recipes/new'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdRecipesNewRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/events/new': {
      id: '/_protected/_modules/kitchen/$kitchenId/events/new'
      path: '/events/new'
      fullPath: '/kitchen/$kitchenId/events/new'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdEventsNewRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/events/$eventId': {
      id: '/_protected/_modules/kitchen/$kitchenId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/kitchen/$kitchenId/events/$eventId'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdEventsEventIdRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/global/recipes/$recipeId/versions': {
      id: '/_protected/_modules/global/recipes/$recipeId/versions'
      path: '/global/recipes/$recipeId/versions'
      fullPath: '/global/recipes/$recipeId/versions'
      preLoaderRoute: typeof ProtectedModulesGlobalRecipesRecipeIdVersionsRouteImport
      parentRoute: typeof ProtectedModulesRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId': {
      id: '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/kitchen/$kitchenId/recipes/$recipeId'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/': {
      id: '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/'
      path: '/'
      fullPath: '/kitchen/$kitchenId/recipes/$recipeId/'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/versions': {
      id: '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/versions'
      path: '/versions'
      fullPath: '/kitchen/$kitchenId/recipes/$recipeId/versions'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute
    }
    '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/fork': {
      id: '/_protected/_modules/kitchen/$kitchenId/recipes/$recipeId/fork'
      path: '/fork'
      fullPath: '/kitchen/$kitchenId/recipes/$recipeId/fork'
      preLoaderRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRouteImport
      parentRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute
    }
  }
}

interface ProtectedModulesAnalyticsRouteRouteChildren {
  ProtectedModulesAnalyticsChatRoute: typeof ProtectedModulesAnalyticsChatRoute
  ProtectedModulesAnalyticsGlobalRoute: typeof ProtectedModulesAnalyticsGlobalRoute
  ProtectedModulesAnalyticsIndexRoute: typeof ProtectedModulesAnalyticsIndexRoute
}

const ProtectedModulesAnalyticsRouteRouteChildren: ProtectedModulesAnalyticsRouteRouteChildren =
  {
    ProtectedModulesAnalyticsChatRoute: ProtectedModulesAnalyticsChatRoute,
    ProtectedModulesAnalyticsGlobalRoute: ProtectedModulesAnalyticsGlobalRoute,
    ProtectedModulesAnalyticsIndexRoute: ProtectedModulesAnalyticsIndexRoute,
  }

const ProtectedModulesAnalyticsRouteRouteWithChildren =
  ProtectedModulesAnalyticsRouteRoute._addFileChildren(
    ProtectedModulesAnalyticsRouteRouteChildren,
  )

interface ProtectedModulesKitchenProductionKitchenIdRouteRouteChildren {
  ProtectedModulesKitchenProductionKitchenIdIndexRoute: typeof ProtectedModulesKitchenProductionKitchenIdIndexRoute
}

const ProtectedModulesKitchenProductionKitchenIdRouteRouteChildren: ProtectedModulesKitchenProductionKitchenIdRouteRouteChildren =
  {
    ProtectedModulesKitchenProductionKitchenIdIndexRoute:
      ProtectedModulesKitchenProductionKitchenIdIndexRoute,
  }

const ProtectedModulesKitchenProductionKitchenIdRouteRouteWithChildren =
  ProtectedModulesKitchenProductionKitchenIdRouteRoute._addFileChildren(
    ProtectedModulesKitchenProductionKitchenIdRouteRouteChildren,
  )

interface ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteChildren {
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute
}

const ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteChildren: ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteChildren =
  {
    ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute:
      ProtectedModulesKitchenKitchenIdRecipesRecipeIdForkRoute,
    ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute:
      ProtectedModulesKitchenKitchenIdRecipesRecipeIdVersionsRoute,
    ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute:
      ProtectedModulesKitchenKitchenIdRecipesRecipeIdIndexRoute,
  }

const ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteWithChildren =
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute._addFileChildren(
    ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteChildren,
  )

interface ProtectedModulesKitchenKitchenIdRouteRouteChildren {
  ProtectedModulesKitchenKitchenIdChatRoute: typeof ProtectedModulesKitchenKitchenIdChatRoute
  ProtectedModulesKitchenKitchenIdPlanningRoute: typeof ProtectedModulesKitchenKitchenIdPlanningRoute
  ProtectedModulesKitchenKitchenIdQrCodeRoute: typeof ProtectedModulesKitchenKitchenIdQrCodeRoute
  ProtectedModulesKitchenKitchenIdSettingsRoute: typeof ProtectedModulesKitchenKitchenIdSettingsRoute
  ProtectedModulesKitchenKitchenIdIndexRoute: typeof ProtectedModulesKitchenKitchenIdIndexRoute
  ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute: typeof ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteWithChildren
  ProtectedModulesKitchenKitchenIdEventsEventIdRoute: typeof ProtectedModulesKitchenKitchenIdEventsEventIdRoute
  ProtectedModulesKitchenKitchenIdEventsNewRoute: typeof ProtectedModulesKitchenKitchenIdEventsNewRoute
  ProtectedModulesKitchenKitchenIdRecipesNewRoute: typeof ProtectedModulesKitchenKitchenIdRecipesNewRoute
  ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute: typeof ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute
  ProtectedModulesKitchenKitchenIdSuprimentosNewRoute: typeof ProtectedModulesKitchenKitchenIdSuprimentosNewRoute
  ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute: typeof ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute
  ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute: typeof ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute
  ProtectedModulesKitchenKitchenIdEventsIndexRoute: typeof ProtectedModulesKitchenKitchenIdEventsIndexRoute
  ProtectedModulesKitchenKitchenIdRecipesIndexRoute: typeof ProtectedModulesKitchenKitchenIdRecipesIndexRoute
  ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute: typeof ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute
  ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute: typeof ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute
}

const ProtectedModulesKitchenKitchenIdRouteRouteChildren: ProtectedModulesKitchenKitchenIdRouteRouteChildren =
  {
    ProtectedModulesKitchenKitchenIdChatRoute:
      ProtectedModulesKitchenKitchenIdChatRoute,
    ProtectedModulesKitchenKitchenIdPlanningRoute:
      ProtectedModulesKitchenKitchenIdPlanningRoute,
    ProtectedModulesKitchenKitchenIdQrCodeRoute:
      ProtectedModulesKitchenKitchenIdQrCodeRoute,
    ProtectedModulesKitchenKitchenIdSettingsRoute:
      ProtectedModulesKitchenKitchenIdSettingsRoute,
    ProtectedModulesKitchenKitchenIdIndexRoute:
      ProtectedModulesKitchenKitchenIdIndexRoute,
    ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRoute:
      ProtectedModulesKitchenKitchenIdRecipesRecipeIdRouteRouteWithChildren,
    ProtectedModulesKitchenKitchenIdEventsEventIdRoute:
      ProtectedModulesKitchenKitchenIdEventsEventIdRoute,
    ProtectedModulesKitchenKitchenIdEventsNewRoute:
      ProtectedModulesKitchenKitchenIdEventsNewRoute,
    ProtectedModulesKitchenKitchenIdRecipesNewRoute:
      ProtectedModulesKitchenKitchenIdRecipesNewRoute,
    ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute:
      ProtectedModulesKitchenKitchenIdSuprimentosDraftIdRoute,
    ProtectedModulesKitchenKitchenIdSuprimentosNewRoute:
      ProtectedModulesKitchenKitchenIdSuprimentosNewRoute,
    ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute:
      ProtectedModulesKitchenKitchenIdWeeklyMenusWeeklyMenuIdRoute,
    ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute:
      ProtectedModulesKitchenKitchenIdWeeklyMenusNewRoute,
    ProtectedModulesKitchenKitchenIdEventsIndexRoute:
      ProtectedModulesKitchenKitchenIdEventsIndexRoute,
    ProtectedModulesKitchenKitchenIdRecipesIndexRoute:
      ProtectedModulesKitchenKitchenIdRecipesIndexRoute,
    ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute:
      ProtectedModulesKitchenKitchenIdSuprimentosIndexRoute,
    ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute:
      ProtectedModulesKitchenKitchenIdWeeklyMenusIndexRoute,
  }

const ProtectedModulesKitchenKitchenIdRouteRouteWithChildren =
  ProtectedModulesKitchenKitchenIdRouteRoute._addFileChildren(
    ProtectedModulesKitchenKitchenIdRouteRouteChildren,
  )

interface ProtectedModulesLocalAnalyticsUnitIdRouteRouteChildren {
  ProtectedModulesLocalAnalyticsUnitIdDashboardRoute: typeof ProtectedModulesLocalAnalyticsUnitIdDashboardRoute
  ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute: typeof ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute
}

const ProtectedModulesLocalAnalyticsUnitIdRouteRouteChildren: ProtectedModulesLocalAnalyticsUnitIdRouteRouteChildren =
  {
    ProtectedModulesLocalAnalyticsUnitIdDashboardRoute:
      ProtectedModulesLocalAnalyticsUnitIdDashboardRoute,
    ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute:
      ProtectedModulesLocalAnalyticsUnitIdIndicatorsRoute,
  }

const ProtectedModulesLocalAnalyticsUnitIdRouteRouteWithChildren =
  ProtectedModulesLocalAnalyticsUnitIdRouteRoute._addFileChildren(
    ProtectedModulesLocalAnalyticsUnitIdRouteRouteChildren,
  )

interface ProtectedModulesMesshallMessHallIdRouteRouteChildren {
  ProtectedModulesMesshallMessHallIdIndexRoute: typeof ProtectedModulesMesshallMessHallIdIndexRoute
}

const ProtectedModulesMesshallMessHallIdRouteRouteChildren: ProtectedModulesMesshallMessHallIdRouteRouteChildren =
  {
    ProtectedModulesMesshallMessHallIdIndexRoute:
      ProtectedModulesMesshallMessHallIdIndexRoute,
  }

const ProtectedModulesMesshallMessHallIdRouteRouteWithChildren =
  ProtectedModulesMesshallMessHallIdRouteRoute._addFileChildren(
    ProtectedModulesMesshallMessHallIdRouteRouteChildren,
  )

interface ProtectedModulesUnitUnitIdProcurementRouteChildren {
  ProtectedModulesUnitUnitIdProcurementAtaIdRoute: typeof ProtectedModulesUnitUnitIdProcurementAtaIdRoute
  ProtectedModulesUnitUnitIdProcurementNewRoute: typeof ProtectedModulesUnitUnitIdProcurementNewRoute
  ProtectedModulesUnitUnitIdProcurementIndexRoute: typeof ProtectedModulesUnitUnitIdProcurementIndexRoute
}

const ProtectedModulesUnitUnitIdProcurementRouteChildren: ProtectedModulesUnitUnitIdProcurementRouteChildren =
  {
    ProtectedModulesUnitUnitIdProcurementAtaIdRoute:
      ProtectedModulesUnitUnitIdProcurementAtaIdRoute,
    ProtectedModulesUnitUnitIdProcurementNewRoute:
      ProtectedModulesUnitUnitIdProcurementNewRoute,
    ProtectedModulesUnitUnitIdProcurementIndexRoute:
      ProtectedModulesUnitUnitIdProcurementIndexRoute,
  }

const ProtectedModulesUnitUnitIdProcurementRouteWithChildren =
  ProtectedModulesUnitUnitIdProcurementRoute._addFileChildren(
    ProtectedModulesUnitUnitIdProcurementRouteChildren,
  )

interface ProtectedModulesUnitUnitIdRouteRouteChildren {
  ProtectedModulesUnitUnitIdChatRoute: typeof ProtectedModulesUnitUnitIdChatRoute
  ProtectedModulesUnitUnitIdDashboardRoute: typeof ProtectedModulesUnitUnitIdDashboardRoute
  ProtectedModulesUnitUnitIdProcurementRoute: typeof ProtectedModulesUnitUnitIdProcurementRouteWithChildren
  ProtectedModulesUnitUnitIdSettingsRoute: typeof ProtectedModulesUnitUnitIdSettingsRoute
  ProtectedModulesUnitUnitIdIndexRoute: typeof ProtectedModulesUnitUnitIdIndexRoute
}

const ProtectedModulesUnitUnitIdRouteRouteChildren: ProtectedModulesUnitUnitIdRouteRouteChildren =
  {
    ProtectedModulesUnitUnitIdChatRoute: ProtectedModulesUnitUnitIdChatRoute,
    ProtectedModulesUnitUnitIdDashboardRoute:
      ProtectedModulesUnitUnitIdDashboardRoute,
    ProtectedModulesUnitUnitIdProcurementRoute:
      ProtectedModulesUnitUnitIdProcurementRouteWithChildren,
    ProtectedModulesUnitUnitIdSettingsRoute:
      ProtectedModulesUnitUnitIdSettingsRoute,
    ProtectedModulesUnitUnitIdIndexRoute: ProtectedModulesUnitUnitIdIndexRoute,
  }

const ProtectedModulesUnitUnitIdRouteRouteWithChildren =
  ProtectedModulesUnitUnitIdRouteRoute._addFileChildren(
    ProtectedModulesUnitUnitIdRouteRouteChildren,
  )

interface ProtectedModulesRouteRouteChildren {
  ProtectedModulesAnalyticsRouteRoute: typeof ProtectedModulesAnalyticsRouteRouteWithChildren
  ProtectedModulesKitchenProductionKitchenIdRouteRoute: typeof ProtectedModulesKitchenProductionKitchenIdRouteRouteWithChildren
  ProtectedModulesKitchenKitchenIdRouteRoute: typeof ProtectedModulesKitchenKitchenIdRouteRouteWithChildren
  ProtectedModulesLocalAnalyticsUnitIdRouteRoute: typeof ProtectedModulesLocalAnalyticsUnitIdRouteRouteWithChildren
  ProtectedModulesMesshallMessHallIdRouteRoute: typeof ProtectedModulesMesshallMessHallIdRouteRouteWithChildren
  ProtectedModulesUnitUnitIdRouteRoute: typeof ProtectedModulesUnitUnitIdRouteRouteWithChildren
  ProtectedModulesDinerForecastRoute: typeof ProtectedModulesDinerForecastRoute
  ProtectedModulesDinerMcpKeysRoute: typeof ProtectedModulesDinerMcpKeysRoute
  ProtectedModulesDinerMenuRoute: typeof ProtectedModulesDinerMenuRoute
  ProtectedModulesDinerProfileRoute: typeof ProtectedModulesDinerProfileRoute
  ProtectedModulesDinerQrCodeRoute: typeof ProtectedModulesDinerQrCodeRoute
  ProtectedModulesDinerSelfCheckInRoute: typeof ProtectedModulesDinerSelfCheckInRoute
  ProtectedModulesGlobalChatRoute: typeof ProtectedModulesGlobalChatRoute
  ProtectedModulesGlobalComprasSyncRoute: typeof ProtectedModulesGlobalComprasSyncRoute
  ProtectedModulesGlobalEvaluationRoute: typeof ProtectedModulesGlobalEvaluationRoute
  ProtectedModulesGlobalPermissionsRoute: typeof ProtectedModulesGlobalPermissionsRoute
  ProtectedModulesGlobalPlacesManagerRoute: typeof ProtectedModulesGlobalPlacesManagerRoute
  ProtectedModulesGlobalPolicyRoute: typeof ProtectedModulesGlobalPolicyRoute
  ProtectedModulesDinerIndexRoute: typeof ProtectedModulesDinerIndexRoute
  ProtectedModulesGlobalIndexRoute: typeof ProtectedModulesGlobalIndexRoute
  ProtectedModulesKitchenProductionIndexRoute: typeof ProtectedModulesKitchenProductionIndexRoute
  ProtectedModulesKitchenIndexRoute: typeof ProtectedModulesKitchenIndexRoute
  ProtectedModulesLocalAnalyticsIndexRoute: typeof ProtectedModulesLocalAnalyticsIndexRoute
  ProtectedModulesMesshallIndexRoute: typeof ProtectedModulesMesshallIndexRoute
  ProtectedModulesUnitIndexRoute: typeof ProtectedModulesUnitIndexRoute
  ProtectedModulesGlobalIngredientsIngredientIdRoute: typeof ProtectedModulesGlobalIngredientsIngredientIdRoute
  ProtectedModulesGlobalRecipesNewRoute: typeof ProtectedModulesGlobalRecipesNewRoute
  ProtectedModulesGlobalWeeklyPlansPlanIdRoute: typeof ProtectedModulesGlobalWeeklyPlansPlanIdRoute
  ProtectedModulesGlobalWeeklyPlansNewRoute: typeof ProtectedModulesGlobalWeeklyPlansNewRoute
  ProtectedModulesGlobalIngredientsIndexRoute: typeof ProtectedModulesGlobalIngredientsIndexRoute
  ProtectedModulesGlobalRecipesIndexRoute: typeof ProtectedModulesGlobalRecipesIndexRoute
  ProtectedModulesGlobalWeeklyPlansIndexRoute: typeof ProtectedModulesGlobalWeeklyPlansIndexRoute
  ProtectedModulesGlobalRecipesRecipeIdVersionsRoute: typeof ProtectedModulesGlobalRecipesRecipeIdVersionsRoute
  ProtectedModulesGlobalRecipesRecipeIdIndexRoute: typeof ProtectedModulesGlobalRecipesRecipeIdIndexRoute
}

const ProtectedModulesRouteRouteChildren: ProtectedModulesRouteRouteChildren = {
  ProtectedModulesAnalyticsRouteRoute:
    ProtectedModulesAnalyticsRouteRouteWithChildren,
  ProtectedModulesKitchenProductionKitchenIdRouteRoute:
    ProtectedModulesKitchenProductionKitchenIdRouteRouteWithChildren,
  ProtectedModulesKitchenKitchenIdRouteRoute:
    ProtectedModulesKitchenKitchenIdRouteRouteWithChildren,
  ProtectedModulesLocalAnalyticsUnitIdRouteRoute:
    ProtectedModulesLocalAnalyticsUnitIdRouteRouteWithChildren,
  ProtectedModulesMesshallMessHallIdRouteRoute:
    ProtectedModulesMesshallMessHallIdRouteRouteWithChildren,
  ProtectedModulesUnitUnitIdRouteRoute:
    ProtectedModulesUnitUnitIdRouteRouteWithChildren,
  ProtectedModulesDinerForecastRoute: ProtectedModulesDinerForecastRoute,
  ProtectedModulesDinerMcpKeysRoute: ProtectedModulesDinerMcpKeysRoute,
  ProtectedModulesDinerMenuRoute: ProtectedModulesDinerMenuRoute,
  ProtectedModulesDinerProfileRoute: ProtectedModulesDinerProfileRoute,
  ProtectedModulesDinerQrCodeRoute: ProtectedModulesDinerQrCodeRoute,
  ProtectedModulesDinerSelfCheckInRoute: ProtectedModulesDinerSelfCheckInRoute,
  ProtectedModulesGlobalChatRoute: ProtectedModulesGlobalChatRoute,
  ProtectedModulesGlobalComprasSyncRoute:
    ProtectedModulesGlobalComprasSyncRoute,
  ProtectedModulesGlobalEvaluationRoute: ProtectedModulesGlobalEvaluationRoute,
  ProtectedModulesGlobalPermissionsRoute:
    ProtectedModulesGlobalPermissionsRoute,
  ProtectedModulesGlobalPlacesManagerRoute:
    ProtectedModulesGlobalPlacesManagerRoute,
  ProtectedModulesGlobalPolicyRoute: ProtectedModulesGlobalPolicyRoute,
  ProtectedModulesDinerIndexRoute: ProtectedModulesDinerIndexRoute,
  ProtectedModulesGlobalIndexRoute: ProtectedModulesGlobalIndexRoute,
  ProtectedModulesKitchenProductionIndexRoute:
    ProtectedModulesKitchenProductionIndexRoute,
  ProtectedModulesKitchenIndexRoute: ProtectedModulesKitchenIndexRoute,
  ProtectedModulesLocalAnalyticsIndexRoute:
    ProtectedModulesLocalAnalyticsIndexRoute,
  ProtectedModulesMesshallIndexRoute: ProtectedModulesMesshallIndexRoute,
  ProtectedModulesUnitIndexRoute: ProtectedModulesUnitIndexRoute,
  ProtectedModulesGlobalIngredientsIngredientIdRoute:
    ProtectedModulesGlobalIngredientsIngredientIdRoute,
  ProtectedModulesGlobalRecipesNewRoute: ProtectedModulesGlobalRecipesNewRoute,
  ProtectedModulesGlobalWeeklyPlansPlanIdRoute:
    ProtectedModulesGlobalWeeklyPlansPlanIdRoute,
  ProtectedModulesGlobalWeeklyPlansNewRoute:
    ProtectedModulesGlobalWeeklyPlansNewRoute,
  ProtectedModulesGlobalIngredientsIndexRoute:
    ProtectedModulesGlobalIngredientsIndexRoute,
  ProtectedModulesGlobalRecipesIndexRoute:
    ProtectedModulesGlobalRecipesIndexRoute,
  ProtectedModulesGlobalWeeklyPlansIndexRoute:
    ProtectedModulesGlobalWeeklyPlansIndexRoute,
  ProtectedModulesGlobalRecipesRecipeIdVersionsRoute:
    ProtectedModulesGlobalRecipesRecipeIdVersionsRoute,
  ProtectedModulesGlobalRecipesRecipeIdIndexRoute:
    ProtectedModulesGlobalRecipesRecipeIdIndexRoute,
}

const ProtectedModulesRouteRouteWithChildren =
  ProtectedModulesRouteRoute._addFileChildren(
    ProtectedModulesRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedModulesRouteRoute: typeof ProtectedModulesRouteRouteWithChildren
  ProtectedHubRoute: typeof ProtectedHubRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedModulesRouteRoute: ProtectedModulesRouteRouteWithChildren,
  ProtectedHubRoute: ProtectedHubRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicChangelogRoute: typeof PublicChangelogRoute
  PublicTutorialRoute: typeof PublicTutorialRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicChangelogRoute: PublicChangelogRoute,
  PublicTutorialRoute: PublicTutorialRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
