/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as PublicTutorialRouteImport } from './routes/_public/tutorial'
import { Route as PublicChangelogRouteImport } from './routes/_public/changelog'
import { Route as ProtectedSelfCheckInRouteImport } from './routes/_protected/selfCheckIn'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPresenceRouteImport } from './routes/_protected/presence'
import { Route as ProtectedForecastRouteImport } from './routes/_protected/forecast'
import { Route as ProtectedSuperAdminIndexRouteImport } from './routes/_protected/superAdmin/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedSuperAdminIngredientsRouteImport } from './routes/_protected/superAdmin/ingredients'
import { Route as ProtectedAdminProcurementRouteImport } from './routes/_protected/admin/procurement'
import { Route as ProtectedAdminPlanningRouteImport } from './routes/_protected/admin/planning'
import { Route as ProtectedAdminRecipesIndexRouteImport } from './routes/_protected/admin/recipes/index'
import { Route as ProtectedAdminRecipesNewRouteImport } from './routes/_protected/admin/recipes/new'
import { Route as ProtectedAdminRecipesRecipeIdRouteImport } from './routes/_protected/admin/recipes/$recipeId'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicTutorialRoute = PublicTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicChangelogRoute = PublicChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedSelfCheckInRoute = ProtectedSelfCheckInRouteImport.update({
  id: '/selfCheckIn',
  path: '/selfCheckIn',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPresenceRoute = ProtectedPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedForecastRoute = ProtectedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSuperAdminIndexRoute =
  ProtectedSuperAdminIndexRouteImport.update({
    id: '/superAdmin/',
    path: '/superAdmin/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSuperAdminIngredientsRoute =
  ProtectedSuperAdminIngredientsRouteImport.update({
    id: '/superAdmin/ingredients',
    path: '/superAdmin/ingredients',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminProcurementRoute =
  ProtectedAdminProcurementRouteImport.update({
    id: '/admin/procurement',
    path: '/admin/procurement',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminPlanningRoute = ProtectedAdminPlanningRouteImport.update({
  id: '/admin/planning',
  path: '/admin/planning',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRecipesIndexRoute =
  ProtectedAdminRecipesIndexRouteImport.update({
    id: '/admin/recipes/',
    path: '/admin/recipes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminRecipesNewRoute =
  ProtectedAdminRecipesNewRouteImport.update({
    id: '/admin/recipes/new',
    path: '/admin/recipes/new',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminRecipesRecipeIdRoute =
  ProtectedAdminRecipesRecipeIdRouteImport.update({
    id: '/admin/recipes/$recipeId',
    path: '/admin/recipes/$recipeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/forecast': typeof ProtectedForecastRoute
  '/presence': typeof ProtectedPresenceRoute
  '/profile': typeof ProtectedProfileRoute
  '/selfCheckIn': typeof ProtectedSelfCheckInRoute
  '/changelog': typeof PublicChangelogRoute
  '/tutorial': typeof PublicTutorialRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/planning': typeof ProtectedAdminPlanningRoute
  '/admin/procurement': typeof ProtectedAdminProcurementRoute
  '/superAdmin/ingredients': typeof ProtectedSuperAdminIngredientsRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/superAdmin/': typeof ProtectedSuperAdminIndexRoute
  '/admin/recipes/$recipeId': typeof ProtectedAdminRecipesRecipeIdRoute
  '/admin/recipes/new': typeof ProtectedAdminRecipesNewRoute
  '/admin/recipes/': typeof ProtectedAdminRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/health': typeof HealthRoute
  '/forecast': typeof ProtectedForecastRoute
  '/presence': typeof ProtectedPresenceRoute
  '/profile': typeof ProtectedProfileRoute
  '/selfCheckIn': typeof ProtectedSelfCheckInRoute
  '/changelog': typeof PublicChangelogRoute
  '/tutorial': typeof PublicTutorialRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/admin/planning': typeof ProtectedAdminPlanningRoute
  '/admin/procurement': typeof ProtectedAdminProcurementRoute
  '/superAdmin/ingredients': typeof ProtectedSuperAdminIngredientsRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/superAdmin': typeof ProtectedSuperAdminIndexRoute
  '/admin/recipes/$recipeId': typeof ProtectedAdminRecipesRecipeIdRoute
  '/admin/recipes/new': typeof ProtectedAdminRecipesNewRoute
  '/admin/recipes': typeof ProtectedAdminRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/_protected/forecast': typeof ProtectedForecastRoute
  '/_protected/presence': typeof ProtectedPresenceRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/selfCheckIn': typeof ProtectedSelfCheckInRoute
  '/_public/changelog': typeof PublicChangelogRoute
  '/_public/tutorial': typeof PublicTutorialRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_public/': typeof PublicIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/admin/planning': typeof ProtectedAdminPlanningRoute
  '/_protected/admin/procurement': typeof ProtectedAdminProcurementRoute
  '/_protected/superAdmin/ingredients': typeof ProtectedSuperAdminIngredientsRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/superAdmin/': typeof ProtectedSuperAdminIndexRoute
  '/_protected/admin/recipes/$recipeId': typeof ProtectedAdminRecipesRecipeIdRoute
  '/_protected/admin/recipes/new': typeof ProtectedAdminRecipesNewRoute
  '/_protected/admin/recipes/': typeof ProtectedAdminRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/health'
    | '/forecast'
    | '/presence'
    | '/profile'
    | '/selfCheckIn'
    | '/changelog'
    | '/tutorial'
    | '/auth/reset-password'
    | '/auth/'
    | '/admin/planning'
    | '/admin/procurement'
    | '/superAdmin/ingredients'
    | '/admin/'
    | '/superAdmin/'
    | '/admin/recipes/$recipeId'
    | '/admin/recipes/new'
    | '/admin/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/forecast'
    | '/presence'
    | '/profile'
    | '/selfCheckIn'
    | '/changelog'
    | '/tutorial'
    | '/auth/reset-password'
    | '/auth'
    | '/admin/planning'
    | '/admin/procurement'
    | '/superAdmin/ingredients'
    | '/admin'
    | '/superAdmin'
    | '/admin/recipes/$recipeId'
    | '/admin/recipes/new'
    | '/admin/recipes'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/auth'
    | '/health'
    | '/_protected/forecast'
    | '/_protected/presence'
    | '/_protected/profile'
    | '/_protected/selfCheckIn'
    | '/_public/changelog'
    | '/_public/tutorial'
    | '/auth/reset-password'
    | '/_public/'
    | '/auth/'
    | '/_protected/admin/planning'
    | '/_protected/admin/procurement'
    | '/_protected/superAdmin/ingredients'
    | '/_protected/admin/'
    | '/_protected/superAdmin/'
    | '/_protected/admin/recipes/$recipeId'
    | '/_protected/admin/recipes/new'
    | '/_protected/admin/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/tutorial': {
      id: '/_public/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof PublicTutorialRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/changelog': {
      id: '/_public/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof PublicChangelogRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/selfCheckIn': {
      id: '/_protected/selfCheckIn'
      path: '/selfCheckIn'
      fullPath: '/selfCheckIn'
      preLoaderRoute: typeof ProtectedSelfCheckInRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/presence': {
      id: '/_protected/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof ProtectedPresenceRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/forecast': {
      id: '/_protected/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ProtectedForecastRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/superAdmin/': {
      id: '/_protected/superAdmin/'
      path: '/superAdmin'
      fullPath: '/superAdmin/'
      preLoaderRoute: typeof ProtectedSuperAdminIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/superAdmin/ingredients': {
      id: '/_protected/superAdmin/ingredients'
      path: '/superAdmin/ingredients'
      fullPath: '/superAdmin/ingredients'
      preLoaderRoute: typeof ProtectedSuperAdminIngredientsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/procurement': {
      id: '/_protected/admin/procurement'
      path: '/admin/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof ProtectedAdminProcurementRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/planning': {
      id: '/_protected/admin/planning'
      path: '/admin/planning'
      fullPath: '/admin/planning'
      preLoaderRoute: typeof ProtectedAdminPlanningRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/recipes/': {
      id: '/_protected/admin/recipes/'
      path: '/admin/recipes'
      fullPath: '/admin/recipes/'
      preLoaderRoute: typeof ProtectedAdminRecipesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/recipes/new': {
      id: '/_protected/admin/recipes/new'
      path: '/admin/recipes/new'
      fullPath: '/admin/recipes/new'
      preLoaderRoute: typeof ProtectedAdminRecipesNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/recipes/$recipeId': {
      id: '/_protected/admin/recipes/$recipeId'
      path: '/admin/recipes/$recipeId'
      fullPath: '/admin/recipes/$recipeId'
      preLoaderRoute: typeof ProtectedAdminRecipesRecipeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedForecastRoute: typeof ProtectedForecastRoute
  ProtectedPresenceRoute: typeof ProtectedPresenceRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSelfCheckInRoute: typeof ProtectedSelfCheckInRoute
  ProtectedAdminPlanningRoute: typeof ProtectedAdminPlanningRoute
  ProtectedAdminProcurementRoute: typeof ProtectedAdminProcurementRoute
  ProtectedSuperAdminIngredientsRoute: typeof ProtectedSuperAdminIngredientsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedSuperAdminIndexRoute: typeof ProtectedSuperAdminIndexRoute
  ProtectedAdminRecipesRecipeIdRoute: typeof ProtectedAdminRecipesRecipeIdRoute
  ProtectedAdminRecipesNewRoute: typeof ProtectedAdminRecipesNewRoute
  ProtectedAdminRecipesIndexRoute: typeof ProtectedAdminRecipesIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedForecastRoute: ProtectedForecastRoute,
  ProtectedPresenceRoute: ProtectedPresenceRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSelfCheckInRoute: ProtectedSelfCheckInRoute,
  ProtectedAdminPlanningRoute: ProtectedAdminPlanningRoute,
  ProtectedAdminProcurementRoute: ProtectedAdminProcurementRoute,
  ProtectedSuperAdminIngredientsRoute: ProtectedSuperAdminIngredientsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedSuperAdminIndexRoute: ProtectedSuperAdminIndexRoute,
  ProtectedAdminRecipesRecipeIdRoute: ProtectedAdminRecipesRecipeIdRoute,
  ProtectedAdminRecipesNewRoute: ProtectedAdminRecipesNewRoute,
  ProtectedAdminRecipesIndexRoute: ProtectedAdminRecipesIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicChangelogRoute: typeof PublicChangelogRoute
  PublicTutorialRoute: typeof PublicTutorialRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicChangelogRoute: PublicChangelogRoute,
  PublicTutorialRoute: PublicTutorialRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
