/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicPoliticaDeCookiesRouteImport } from './routes/_public/politica-de-cookies'
import { Route as PublicPoliticaDePrivacidadeRouteImport } from './routes/_public/politica-de-privacidade'
import { Route as PublicTermosDeUsoRouteImport } from './routes/_public/termos-de-uso'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPermissoesRouteImport } from './routes/admin/permissoes'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known.agent-skills.index[.]json'
import { Route as PublicUniformesIndexRouteImport } from './routes/_public/uniformes/index'
import { Route as AdminItensIndexRouteImport } from './routes/admin/itens/index'
import { Route as AdminPecasIndexRouteImport } from './routes/admin/pecas/index'
import { Route as AdminUniformesUniformIdRouteImport } from './routes/admin/uniformes/$uniformId'
import { Route as DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport } from './routes/[.]well-known.agent-skills.$skill.SKILL[.]md'
import { Route as PublicUniformesUniformIdIndexRouteImport } from './routes/_public/uniformes/$uniformId/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPoliticaDeCookiesRoute = PublicPoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPoliticaDePrivacidadeRoute =
  PublicPoliticaDePrivacidadeRouteImport.update({
    id: '/politica-de-privacidade',
    path: '/politica-de-privacidade',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicTermosDeUsoRoute = PublicTermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPermissoesRoute = AdminPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicUniformesIndexRoute = PublicUniformesIndexRouteImport.update({
  id: '/uniformes/',
  path: '/uniformes/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminItensIndexRoute = AdminItensIndexRouteImport.update({
  id: '/itens/',
  path: '/itens/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPecasIndexRoute = AdminPecasIndexRouteImport.update({
  id: '/pecas/',
  path: '/pecas/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUniformesUniformIdRoute = AdminUniformesUniformIdRouteImport.update({
  id: '/uniformes/$uniformId',
  path: '/uniformes/$uniformId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DotwellKnownAgentSkillsSkillSKILLDotmdRoute =
  DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport.update({
    id: '/.well-known/agent-skills/$skill/SKILL.md',
    path: '/.well-known/agent-skills/$skill/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicUniformesUniformIdIndexRoute =
  PublicUniformesUniformIdIndexRouteImport.update({
    id: '/uniformes/$uniformId/',
    path: '/uniformes/$uniformId/',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/politica-de-cookies': typeof PublicPoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof PublicTermosDeUsoRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/admin/uniformes/$uniformId': typeof AdminUniformesUniformIdRoute
  '/uniformes/': typeof PublicUniformesIndexRoute
  '/admin/itens/': typeof AdminItensIndexRoute
  '/admin/pecas/': typeof AdminPecasIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/uniformes/$uniformId/': typeof PublicUniformesUniformIdIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/politica-de-cookies': typeof PublicPoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof PublicTermosDeUsoRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/admin/uniformes/$uniformId': typeof AdminUniformesUniformIdRoute
  '/uniformes': typeof PublicUniformesIndexRoute
  '/admin/itens': typeof AdminItensIndexRoute
  '/admin/pecas': typeof AdminPecasIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/uniformes/$uniformId': typeof PublicUniformesUniformIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/politica-de-cookies': typeof PublicPoliticaDeCookiesRoute
  '/_public/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/_public/termos-de-uso': typeof PublicTermosDeUsoRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/admin/uniformes/$uniformId': typeof AdminUniformesUniformIdRoute
  '/_public/uniformes/': typeof PublicUniformesIndexRoute
  '/admin/itens/': typeof AdminItensIndexRoute
  '/admin/pecas/': typeof AdminPecasIndexRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/_public/uniformes/$uniformId/': typeof PublicUniformesUniformIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/health'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/permissoes'
    | '/admin/'
    | '/auth/'
    | '/.well-known/agent-skills/index.json'
    | '/admin/uniformes/$uniformId'
    | '/uniformes/'
    | '/admin/itens/'
    | '/admin/pecas/'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/uniformes/$uniformId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/permissoes'
    | '/'
    | '/admin'
    | '/auth'
    | '/.well-known/agent-skills/index.json'
    | '/admin/uniformes/$uniformId'
    | '/uniformes'
    | '/admin/itens'
    | '/admin/pecas'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/uniformes/$uniformId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/health'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/_public/politica-de-cookies'
    | '/_public/politica-de-privacidade'
    | '/_public/termos-de-uso'
    | '/admin/permissoes'
    | '/_public/'
    | '/admin/'
    | '/auth/'
    | '/.well-known/agent-skills/index.json'
    | '/admin/uniformes/$uniformId'
    | '/_public/uniformes/'
    | '/admin/itens/'
    | '/admin/pecas/'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/_public/uniformes/$uniformId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/politica-de-cookies': {
      id: '/_public/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PublicPoliticaDeCookiesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/politica-de-privacidade': {
      id: '/_public/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PublicPoliticaDePrivacidadeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/termos-de-uso': {
      id: '/_public/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof PublicTermosDeUsoRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/permissoes': {
      id: '/admin/permissoes'
      path: '/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AdminPermissoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/uniformes/': {
      id: '/_public/uniformes/'
      path: '/uniformes'
      fullPath: '/uniformes/'
      preLoaderRoute: typeof PublicUniformesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/itens/': {
      id: '/admin/itens/'
      path: '/itens'
      fullPath: '/admin/itens/'
      preLoaderRoute: typeof AdminItensIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pecas/': {
      id: '/admin/pecas/'
      path: '/pecas'
      fullPath: '/admin/pecas/'
      preLoaderRoute: typeof AdminPecasIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/uniformes/$uniformId': {
      id: '/admin/uniformes/$uniformId'
      path: '/uniformes/$uniformId'
      fullPath: '/admin/uniformes/$uniformId'
      preLoaderRoute: typeof AdminUniformesUniformIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/.well-known/agent-skills/$skill/SKILL.md': {
      id: '/.well-known/agent-skills/$skill/SKILL.md'
      path: '/.well-known/agent-skills/$skill/SKILL.md'
      fullPath: '/.well-known/agent-skills/$skill/SKILL.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/uniformes/$uniformId/': {
      id: '/_public/uniformes/$uniformId/'
      path: '/uniformes/$uniformId'
      fullPath: '/uniformes/$uniformId/'
      preLoaderRoute: typeof PublicUniformesUniformIdIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicPoliticaDeCookiesRoute: typeof PublicPoliticaDeCookiesRoute
  PublicPoliticaDePrivacidadeRoute: typeof PublicPoliticaDePrivacidadeRoute
  PublicTermosDeUsoRoute: typeof PublicTermosDeUsoRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicUniformesIndexRoute: typeof PublicUniformesIndexRoute
  PublicUniformesUniformIdIndexRoute: typeof PublicUniformesUniformIdIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicPoliticaDeCookiesRoute: PublicPoliticaDeCookiesRoute,
  PublicPoliticaDePrivacidadeRoute: PublicPoliticaDePrivacidadeRoute,
  PublicTermosDeUsoRoute: PublicTermosDeUsoRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicUniformesIndexRoute: PublicUniformesIndexRoute,
  PublicUniformesUniformIdIndexRoute: PublicUniformesUniformIdIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminPermissoesRoute: typeof AdminPermissoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUniformesUniformIdRoute: typeof AdminUniformesUniformIdRoute
  AdminItensIndexRoute: typeof AdminItensIndexRoute
  AdminPecasIndexRoute: typeof AdminPecasIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPermissoesRoute: AdminPermissoesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUniformesUniformIdRoute: AdminUniformesUniformIdRoute,
  AdminItensIndexRoute: AdminItensIndexRoute,
  AdminPecasIndexRoute: AdminPecasIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute:
    DotwellKnownAgentSkillsSkillSKILLDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
