/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminPecasIndexRouteImport } from './routes/admin/pecas/index'
import { Route as AdminItensIndexRouteImport } from './routes/admin/itens/index'
import { Route as PublicUniformesIndexRouteImport } from './routes/_public/uniformes/index'
import { Route as AdminUniformesUniformIdRouteImport } from './routes/admin/uniformes/$uniformId'
import { Route as PublicUniformesUniformIdIndexRouteImport } from './routes/_public/uniformes/$uniformId/index'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminPecasIndexRoute = AdminPecasIndexRouteImport.update({
  id: '/pecas/',
  path: '/pecas/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminItensIndexRoute = AdminItensIndexRouteImport.update({
  id: '/itens/',
  path: '/itens/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicUniformesIndexRoute = PublicUniformesIndexRouteImport.update({
  id: '/uniformes/',
  path: '/uniformes/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminUniformesUniformIdRoute = AdminUniformesUniformIdRouteImport.update({
  id: '/uniformes/$uniformId',
  path: '/uniformes/$uniformId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicUniformesUniformIdIndexRoute =
  PublicUniformesUniformIdIndexRouteImport.update({
    id: '/uniformes/$uniformId/',
    path: '/uniformes/$uniformId/',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/uniformes/$uniformId': typeof AdminUniformesUniformIdRoute
  '/uniformes/': typeof PublicUniformesIndexRoute
  '/admin/itens/': typeof AdminItensIndexRoute
  '/admin/pecas/': typeof AdminPecasIndexRoute
  '/uniformes/$uniformId/': typeof PublicUniformesUniformIdIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/uniformes/$uniformId': typeof AdminUniformesUniformIdRoute
  '/uniformes': typeof PublicUniformesIndexRoute
  '/admin/itens': typeof AdminItensIndexRoute
  '/admin/pecas': typeof AdminPecasIndexRoute
  '/uniformes/$uniformId': typeof PublicUniformesUniformIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/uniformes/$uniformId': typeof AdminUniformesUniformIdRoute
  '/_public/uniformes/': typeof PublicUniformesIndexRoute
  '/admin/itens/': typeof AdminItensIndexRoute
  '/admin/pecas/': typeof AdminPecasIndexRoute
  '/_public/uniformes/$uniformId/': typeof PublicUniformesUniformIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/health'
    | '/admin/'
    | '/auth/'
    | '/admin/uniformes/$uniformId'
    | '/uniformes/'
    | '/admin/itens/'
    | '/admin/pecas/'
    | '/uniformes/$uniformId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/uniformes/$uniformId'
    | '/uniformes'
    | '/admin/itens'
    | '/admin/pecas'
    | '/uniformes/$uniformId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/health'
    | '/_public/'
    | '/admin/'
    | '/auth/'
    | '/admin/uniformes/$uniformId'
    | '/_public/uniformes/'
    | '/admin/itens/'
    | '/admin/pecas/'
    | '/_public/uniformes/$uniformId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/pecas/': {
      id: '/admin/pecas/'
      path: '/pecas'
      fullPath: '/admin/pecas/'
      preLoaderRoute: typeof AdminPecasIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/itens/': {
      id: '/admin/itens/'
      path: '/itens'
      fullPath: '/admin/itens/'
      preLoaderRoute: typeof AdminItensIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/uniformes/': {
      id: '/_public/uniformes/'
      path: '/uniformes'
      fullPath: '/uniformes/'
      preLoaderRoute: typeof PublicUniformesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/uniformes/$uniformId': {
      id: '/admin/uniformes/$uniformId'
      path: '/uniformes/$uniformId'
      fullPath: '/admin/uniformes/$uniformId'
      preLoaderRoute: typeof AdminUniformesUniformIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/uniformes/$uniformId/': {
      id: '/_public/uniformes/$uniformId/'
      path: '/uniformes/$uniformId'
      fullPath: '/uniformes/$uniformId/'
      preLoaderRoute: typeof PublicUniformesUniformIdIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicUniformesIndexRoute: typeof PublicUniformesIndexRoute
  PublicUniformesUniformIdIndexRoute: typeof PublicUniformesUniformIdIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicUniformesIndexRoute: PublicUniformesIndexRoute,
  PublicUniformesUniformIdIndexRoute: PublicUniformesUniformIdIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUniformesUniformIdRoute: typeof AdminUniformesUniformIdRoute
  AdminItensIndexRoute: typeof AdminItensIndexRoute
  AdminPecasIndexRoute: typeof AdminPecasIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUniformesUniformIdRoute: AdminUniformesUniformIdRoute,
  AdminItensIndexRoute: AdminItensIndexRoute,
  AdminPecasIndexRoute: AdminPecasIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
